### PR TITLE
Allows every race to be bogmaster

### PR DESCRIPTION
**Pull request by Takoros**
## About The Pull Request

It modifies the races able to be bogmasters, simply.

## Why It's Good For The Game

It would allow for more diversity inside of the bog guard ranks, allow some different mindsets too, and, it would allow players of shunned race to be bogmaster, when there is none, which is annoying, since you cant recruit as a simple bog guard (and also have to break into armory if you need something in there)

### CODE REVIEW

**Comment by Lhars** [comment]
Not even the bogmaster description respects the bogmaster - It makes sense that shunned races should be able to play it. Plus, due to the key situation and the general lack of interest in boggies, opening it up seems ideal.

**Comment by Hmeister-real** [comment]
this is good

**Comment by Kepteyn** [comment]
Keeps the filthy kobolds away from the city, so what if one is the bogmaster? The king doesn't need to see the ugly little gremlin.

**Comment by Jackofashepard** [comment]
The Bog Master is still a leadership role that interacts with the royalty sometimes. And to be frank i really dont want the immensely ERP prone races as bog masters, its already bad enough with lupians

**Comment by Takoros** [comment]
I mean, you guys complain about shunned races to ERP, but when they dont, want to invest themselves and play characters with a real evolution and not horny, you spit on their face.

Restricting them to such littles roles is maybe part of the reason a lot of them acts like this. And its not fair for the players of shunned races that wants to invest themselves like everyone else.

**Comment by DelineFortune** [comment]
No one is playing -job- so lets allow shunned race to play -job-

Epic logic

**Comment by Gr33d-y** [comment]
> The Bog Master is still a leadership role that interacts with the royalty sometimes. And to be frank i really dont want the immensely ERP prone races as bog masters, its already bad enough with lupians

Yeah it would be really weird if they were a drow or some other demonspawn.

**Comment by Takoros** [comment]
> No one/small amount of players is playing -job- so lets allow shunned races to play -job-
> 
> Epic logic



> > The Bog Master is still a leadership role that interacts with the royalty sometimes. And to be frank i really dont want the immensely ERP prone races as bog masters, its already bad enough with lupians
> 
> Yeah it would be really weird if they were a drow or some other demonspawn.

Pretty sure both of your talk wouldnt be the same, if humens or any mainstream race would be the shunned races.

**Comment by Gr33d-y** [comment]
> > No one/small amount of players is playing -job- so lets allow shunned races to play -job-
> > Epic logic
> 
> > > The Bog Master is still a leadership role that interacts with the royalty sometimes. And to be frank i really dont want the immensely ERP prone races as bog masters, its already bad enough with lupians
> > 
> > 
> > Yeah it would be really weird if they were a drow or some other demonspawn.
> 
> Pretty sure both of your talk wouldnt be the same, if humens or any mainstream race would be the shunned races.

I would remove humens from the game as a whole if I could tbh.

**Comment by Takoros** [comment]
What i meant by that, is that you wouldnt have the same speech if your favorite race was bannished from playing a lot of roles, without any sort of compensation, and got punished in comparison to another player, just because you like the race.

**Comment by Gr33d-y** [comment]
> What i meant by that, is that you wouldnt have the same speech if your favorite race was bannished from playing a lot of roles, without any sort of compensation, and got punished in comparison to another player, just because you like the race.

Well, there's a different between most races, and a race made to be looked down upon. When I played kobold I was upset they were not looked down on even more and stopped playing them after I was not really getting that shunned race experience. I'm looking for atmosphere and a setting, not just to play any species in any role.

**Comment by DeerJesus** [comment]
> The Bog Master is still a leadership role that interacts with the royalty sometimes. And to be frank i really dont want the immensely ERP prone races as bog masters, its already bad enough with lupians

Dog I see more humen/halfkin erp than I do any other race

**Comment by SixplyDev** [comment]
Bog Master being a shunned race is a horribly stunted way of thinking. He is someone the court has to see regularly, he's someone that's the public face of the Bog Guard, he's someone that's meant to be the best of the bogmen. Shunned races in leadership roles only opens the floodgates to watering down the shunned races job list. You don't appoint an idiot to be king of the idiots, you appoint someone you can tolerate so you don't have to directly deal with the idiots. Shunned races should be mechanically shunned more, including keeping them out of leadedship roles like this.

**Comment by radarseas** [comment]
they might be the top idiot, but they were still respected enough as the top idiot to be put in _charge by the balliff/captain/king_. It makes sense anyone shunned would have been cast away from _such an important even if forgetable commoner position_.

Afterall, _would you want a filthy zizo worshipping drow/demonspawn_ or some _graggarite caveman orc_ to be your **master** of your bog lands?

keep the shunning, such a position of leadership is one still **granted**, not **taken nor owed**.

**Comment by Jaaackx** [comment]
> they might be the top idiot, but they were still respected enough as the top idiot to be put in _charge by the balliff/captain/king_. It makes sense anyone shunned would have been cast away from _such an important even if forgetable commoner position_.
> 
> Afterall, _would you want a filthy zizo worshipping drow/demonspawn_ or some _graggarite caveman orc_ to be your **master** of your bog lands?
> 
> keep the shunning, such a position of leadership is one still **granted**, not **taken nor owed**.

The description of the Bog Master role literally says they're the most 'experienced idiot to volunteer for the Bog Guard'. 

Bog roles are shunned on their own, they don't get much respect IC. Not really an issue having them be a band of less popular races who aren't wanted in the Town but serve the job of guarding the Bog.

**Comment by SixplyDev** [comment]
> > they might be the top idiot, but they were still respected enough as the top idiot to be put in _charge by the balliff/captain/king_. It makes sense anyone shunned would have been cast away from _such an important even if forgetable commoner position_.
> > Afterall, _would you want a filthy zizo worshipping drow/demonspawn_ or some _graggarite caveman orc_ to be your **master** of your bog lands?
> > keep the shunning, such a position of leadership is one still **granted**, not **taken nor owed**.
> 
> The description of the Bog Master role literally says they're the most 'experienced idiot to volunteer for the Bog Guard'.
> 
> Bog roles are shunned on their own, they don't get much respect IC. Not really an issue having them be a band of less popular races who aren't wanted in the Town but serve the job of guarding the Bog.

This doesn't mean that shunned races should be allowed to hold a senior leadership position like this one especially when it's so important to the defense of the town. While they may be looked down upon, the Bog Master would still be a senior leadership role that the Court wouldn't hand down to a shunned race. This is assuming the Court is insulated and extremely racist being noble and all. Shunned races should NOT inhabit senior leadership positions and should be shunned mechanically as well as IC.

Trying to make Bog Master a shunned race is only inviting more issues from those who play the role and makes 0 actual contributions to it. How is one expected to be able to reasonably lead their garrison if they're completely shunned by everyone else? Keeping the current restrictions in place for Bog Master are fine as they make sense for the expectations required of the role.

**Comment by KKLZ4** [comment]
Half-orc Bog Master would have 5 STR, 4 CON, 2 PER, -2 INT, 3 END, -2 SPD

**Comment by Cyprex** [comment]
You know what, let's do this. If this ends up being excessive wrt to stats we can nerf the job stat bonuses or revert this

**Comment by SixplyDev** [comment]
Why the actual fuck was this merged? Absolutely 0 positives would come of this, kobolds aren't taken seriously to begin with so why would they be taken seriously as Bog Master? In addition to this, horcs would just be the biggest fraggers alive with the stats that being Bog Master would give them. Shunned races need to be more mechanically shunned, not opening up more leadership roles for them like this,

**Pull request merged**
