### PR TITLE
Banditry options PR; ported from Azure

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request
Requested PR to give bandits options for loadouts and adds bandit as a round start job. This is a port  requested by code bounty.
This PR Aims to provide 5 options, and eventually a sixth for bandit 'loadouts'.

Brigand: A strength based role for using a battleaxe/cudgel, or flail and shield. heavy Penalties in INT

Foresworn: a more generalist bandit, leaned towards sword and shield, or spears. Less stats then brigand, but lacking INT penalty.

Hedgeknight: The same hedgeknight as prior. Only 1 can be picked, and it has a 25% chance to roll. Notably: Slower then prior, however has high riding skill. Find yourself a steed, disgraced nobleman.

Knave: Double dagger loadout- the same giant speed buff as the knife bandit option from prior. Alternatively, you have the bow-sword loadout. Less speedy then daggers, but extra strength for faster bow draws. Can not wear medium armor.

Sawbones: Cleaver bandit. Good with knives, starts with a backpack of surgical tools and high medical skill. Broken limbs? Never fear, the sawbones will patch you up.

Currently disabled pending spell rework and may be thrown out entirely, but present in this PR: Rogue mages. Worse adventurer mages, basically.
Bandit is also now a selectable job that you can pick roundstart, rather then having to roll for it as an antag. Migrant waves for bandits still exist.
Azure PR:
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/352/files

## Why It's Good For The Game
Bandits now aren't given a randomized playstyle at round start, and can pick their weapon of choice.
Being able to have bandits join midround without a migrant wave could be fairly useful if the rounds gotten slower, to be honest.

### CODE REVIEW

**Comment by radarseas** [comment]
scalemail idol reward should probably be slapdash short-term replaced with a _haulbergon_ so most of these classes can actually use it until someone reworks the idol's rewards to be more of a shop system _for favor like a recent PR there is doing_. its a medium armor type and you can't sprint in it.

unless I'm missing something, some of these classes lack athletics skill, just like the original PR by accident. _I'm not seeing brigand with any athletics skill?_ Only hedge knight.


personal ask but uhh, any chance of leaving `combat_bandit2.ogg` for hedge knights and sawbones? I prefer bandits having their unique own combat musics over a massive inconstancy miss-mash of a unique tune for almost every class.

**Comment by RadiantFlash7** [comment]
> scalemail idol reward should probably be slapdash short-term replaced with a _haulbergon_ so most of these classes can actually use it until someone reworks the idol's rewards to be more of a shop system _for favor like a recent PR there is doing_. its a medium armor type and you can't sprint in it as 3 of these classes.
> 
> 
> 
> unless I'm missing something, some of these classes lack `athletics` skill, just like the original PR by accident. _I'm not seeing brigand with any athletics skill?_ Only hedge knight.
> 
> 
> 
> 
> 
> personal ask but uhh, any chance of leaving `combat_bandit2.ogg` for hedge knights and sawbones? I prefer bandits having their unique own combat musics over a massive inconstancy miss-mash of re-using other theme musics.

All of the bandit types, aside from knave and sawbones, have medium armor I believe. Though I could probably add it to sawbones with no issues tbh.
Missing Athletics is a bit of an oversight. I'll slap it in there when I make an adjustment a bit later today. I will note however, that swimming is intentionally absent. It's a bit silly for bandits to be good at swimming, and completely bypass the gate by swimming up riber.

**Comment by hugmeorelse** [comment]
> dont merge this till its been converted for here, this was made/balanced with HRP roleplay ever sword swing in mind;
> 
> just the FIRST one. and already a fucking flail and steel battle axe +4 str
> 
> lets not give a frag-played-class a grenade launcher shall we?

Good point. They would have better weapons than adventurers or bog guard if you think about it. 


> As for the music, I'll probably leave that up to the person who asked me to make the pr port. I'm not particularly fussed about keeping or changing it myself.

I don't really care either ways. If @radarseas likes it and they play bandit, I feel like it's good to listen to the folks that play the role.

**Comment by RadiantFlash7** [comment]
> dont merge this till its been converted for here, this was made/balanced with HRP roleplay ever sword swing in mind; 
> 
> 
> 
> just the FIRST one. and already a fucking flail and steel battle axe +4 str
> 
> 
> 
> lets not give a frag-played-class a grenade launcher shall we?

Two things. One: the +4 to strength is already existing in our current bandits. All bandits natively have a +3 to strength. Depending on the loadout they randomly roll, they can get an extra +1. Its the exact same stats. Plus, it's not that out of line with other heavy combat classes such as keepsman. And bandits should have high strength in general to allow for grapple/wrestling easier to take people alive.

Secondly, the grenade launcher is a crossbow, in the code, to be clear. And that isn't even in this pr. I removed the crossbow from a class, and left so they poacher had a bow and arrow instead.

**Comment by Marrone321** [comment]
hey just a few questions!

code/modules/antagonists/roguetown/villain/bandit.dm
39	ADD_TRAIT(H, TRAIT_MEDIUMARMOR, TRAIT_GENERIC)

what exactly is this doing, does it remove medium armor proficiency from bandit?

//

You didnt mention in your PR description that it would make Bandits jobbable as opposed to just round-start/migrant wave. 

I think we're open minded to this, but a little more transparency on the initial PR description can go a long way!

With that said, does it work _exactly_ as the original PR describes or is it different? For reference below:

> Additionally, bandits now become a latejoinable job role when it's a proper bandit round - if the server rolls for bandits and none are chosen roundstart, players can join later through the latejoin menu. Latejoin slots are capped at what the bandit cap normally is. Bandit migrant waves also still exist and functional normally.

///

and finally, this last question

code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm

20 mask = /obj/item/clothing/mask/rogue/facemask/steel //idk if this makes it so they cant cast but i want all of the bandits to have the same mask

My question is, can you please test this? If its not tested, then that means players test it, and that means they're gonna ahelp when if it doesnt work. So we want to avoid that, find a solution before it gets to that point.

///

Appreciate all the work you put into it so far, definitely not opposed to bandits having options for their loadouts, we just gotta make sure that its a side-grade not an upgrade to whats currently here, and seems like these options would add a lot of flavor to the game and give people opportunities to try different levels/types of antagonism as opposed to what we got right now.

**Comment by RadiantFlash7** [comment]
> hey just a few questions!
> 
> code/modules/antagonists/roguetown/villain/bandit.dm 39 ADD_TRAIT(H, TRAIT_MEDIUMARMOR, TRAIT_GENERIC)
> 
> what exactly is this doing, does it remove medium armor proficiency from bandit?
> 
> //
> 
> You didnt mention in your PR description that it would make Bandits jobbable as opposed to just round-start/migrant wave.
> 
> I think we're open minded to this, but a little more transparency on the initial PR description can go a long way!
> 
> With that said, does it work _exactly_ as the original PR describes or is it different? For reference below:
> 
> > Additionally, bandits now become a latejoinable job role when it's a proper bandit round - if the server rolls for bandits and none are chosen roundstart, players can join later through the latejoin menu. Latejoin slots are capped at what the bandit cap normally is. Bandit migrant waves also still exist and functional normally.
> 
> ///
> 
> and finally, this last question
> 
> code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
> 
> 20 mask = /obj/item/clothing/mask/rogue/facemask/steel //idk if this makes it so they cant cast but i want all of the bandits to have the same mask
> 
> My question is, can you please test this? If its not tested, then that means players test it, and that means they're gonna ahelp when if it doesnt work. So we want to avoid that, find a solution before it gets to that point.
> 
> ///
> 
> Appreciate all the work you put into it so far, definitely not opposed to bandits having options for their loadouts, we just gotta make sure that its a side-grade not an upgrade to whats currently here, and seems like these options would add a lot of flavor to the game and give people opportunities to try different levels/types of antagonism as opposed to what we got right now.



> hey just a few questions!
> 
> code/modules/antagonists/roguetown/villain/bandit.dm 39 ADD_TRAIT(H, TRAIT_MEDIUMARMOR, TRAIT_GENERIC)
> 
> what exactly is this doing, does it remove medium armor proficiency from bandit?
> 
> //
> 
> You didnt mention in your PR description that it would make Bandits jobbable as opposed to just round-start/migrant wave.
> 
> I think we're open minded to this, but a little more transparency on the initial PR description can go a long way!
> 
> With that said, does it work _exactly_ as the original PR describes or is it different? For reference below:
> 
> > Additionally, bandits now become a latejoinable job role when it's a proper bandit round - if the server rolls for bandits and none are chosen roundstart, players can join later through the latejoin menu. Latejoin slots are capped at what the bandit cap normally is. Bandit migrant waves also still exist and functional normally.
> 
> ///
> 
> and finally, this last question
> 
> code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
> 
> 20 mask = /obj/item/clothing/mask/rogue/facemask/steel //idk if this makes it so they cant cast but i want all of the bandits to have the same mask
> 
> My question is, can you please test this? If its not tested, then that means players test it, and that means they're gonna ahelp when if it doesnt work. So we want to avoid that, find a solution before it gets to that point.
> 
> ///
> 
> Appreciate all the work you put into it so far, definitely not opposed to bandits having options for their loadouts, we just gotta make sure that its a side-grade not an upgrade to whats currently here, and seems like these options would add a lot of flavor to the game and give people opportunities to try different levels/types of antagonism as opposed to what we got right now.

To clarify, Removal of the medium armor trait on villian/bandit, is to apply it directly on the archtype loadouts. This is because the knave was given dodge expert and not medium armor, which makes some sense, beacuse if your main weapon is knives and you have highspeed, you'll want to be dodging. The only issue with this, is that bandit rewards still provide scalemail, which is medium armor, so the knave alone out of all classes can't wear that. But thats not really a major things, a lot of bandits tend to leave aside some rewards they don't want in the first place.

As for what the PR Is compared to the port from Azure. It's more or less the exact same functionally, Only it's loadout and stats have been changed to be in line with current bandits after I had talked over them with xyel. I should have included the fact that bandit was a round start job you could pick in the PR description. Thats my bad.

Mages can wear masks I'm fairly sure, that comment was leftover from azure specifically. I can check however. Also, as my PR description states, Bandit mage isn't enabled. Specifically, I left the file unchecked so that it could be further adjusted and worked on as a potential bandit archetype once spell reworks are finished. Because currently, most of the spells mages get need reworking to be useful. Something I'm actually working on in a seperate PR. Xyel expressed concern in having bandit mages be playable in the current state, so they're ported over, but disabled and unable to be played pending. It provides a good framework for later.

**Comment by radarseas** [comment]
> 20 mask = /obj/item/clothing/mask/rogue/facemask/steel //idk if this makes it so they cant cast but i want all of the bandits to have the same mask
> 
> My question is, can you please test this? If its not tested, then that means players test it, and that means they're gonna ahelp when if it doesnt work. So we want to avoid that, find a solution before it gets to that point.

the only thing that stops mages classing is **anything that mutes**, so mouth slot items like cloth.

Steel masks, hell even fullplate, knight helmet over steel mask bervor is _a-okay for casting._

**Comment by Nakalon** [comment]
IMO the idea of roundstart bandits could work but it would require incredible good faith form the part of the player base...
I always believe in the player base and that are hopefully however!

**Comment by Nakalon** [comment]
> you should not believe in the playerbase from a good faith perspective.

While I understand why you think this way I like to keep a positive outlook!

Even from the negative perspective that we can't trust players we can always punish them if they dont have good faith!

Imagine this:
Test merge
Players behave, they get the cookies
Players missbehave, they don't get to enjoy the cookies

Then there's no reason for anyone to say something was taken from them. They not only didn't have it but also broke the toy on the first day!

**Comment by RadiantFlash7** [comment]
Looking at the

> IMO the idea of roundstart bandits could work but it would require incredible good faith form the part of the player base... I always believe in the player base and that are hopefully however!

coding things in the expectation they won't be abused is bad coding proctice in fairness. I kind of agree with mori in that regard.

THAT SAID- We recently had rounds with over 10 bandits on round start. Which- I can honestly say is /way/ too many. Theres not nearly enough loot available from people and the town to even satisfy that many bandits. I'm thinking of dropping max bandits to 7 round start.

**Comment by RadiantFlash7** [comment]
> Im also not a fan of bandits as a selectable job. Keep them as a rollable minor antag for now

Whats wrong with bandits being a selectable job? Wouldn't it be better to allow them to be latejoinable if people weren't present at the round start?

**Comment by RadiantFlash7** [comment]
> > > Im also not a fan of bandits as a selectable job. Keep them as a rollable minor antag for now
> > 
> > 
> > Whats wrong with bandits being a selectable job? Wouldn't it be better to allow them to be latejoinable if people weren't present at the round start?
> 
> They are an antag. They also get latejoins through migrant waves if im not mistaken.

They /are/ an antagonist force for the round, but it's reliant on people having readied up round start. We /can/ get migrant bandit waves, but they're not very common, and that would require people to sit around and wait for waves, reducing players on the server actually playing. IMO, having it be a job that you can ready up for on round start AND have latejoin as without needing a rare migrant wave would be ideal, especially since theres plenty of times where only 2-3 players actually roll for bandit, and they potentially get killed 30 minutes into the round, leaving several jobs like bog guard with a lacking adversary.

**Comment by RadiantFlash7** [comment]
> > > > > Im also not a fan of bandits as a selectable job. Keep them as a rollable minor antag for now
> > > > 
> > > > 
> > > > Whats wrong with bandits being a selectable job? Wouldn't it be better to allow them to be latejoinable if people weren't present at the round start?
> > > 
> > > 
> > > They are an antag. They also get latejoins through migrant waves if im not mistaken.
> > 
> > 
> > They /are/ an antagonist force for the round, but it's reliant on people having readied up round start. We /can/ get migrant bandit waves, but they're not very common, and that would require people to sit around and wait for waves, reducing players on the server actually playing. IMO, having it be a job that you can ready up for on round start and havethe option latejoin for a select amount of slots without needing a rare migrant wave would be ideal, especially since theres plenty of times where only 2-3 players actually roll for bandit.
> > Nevermind that they can get killed 30 minutes into the round, leaving several jobs like bog guard with a lacking adversary.
> 
> We would have the same issue we have with adventurers.

How exactly? We can already have over 10 bandits round start if people enable bandit to play it.
At present, this PR would reduce the maximum bandit amount to 7 round start, and would let folks join in as bandits. And while some adventurers do antagonistic things like the wandering murderhobos they are, proper antagonists being a garunteed joinable isn't a bad thing.

**Comment by radarseas** [comment]
bandits already roll 100% of the time, I know they're an antag but they're guarrenteed anyway. It just means more consistant showup.


I think 10 slots as a job is completely fine honestly, I'd lower it based on pop though with a bandit to each 10 pop at a minimal of 2. _most bandits will die to the most random of shit including maneaters, anyway long before they meet a person or die rushing the bridge._

**Comment by RadiantFlash7** [comment]
> fix conflicts on this and I will throw a TM on it

I was holding off on the conflict resolution because I already adjusted this for the lupian merc being merged. I can do so, though I should see about making the job scaling, perhaps.

**Comment by RadiantFlash7** [comment]
> fine with this being tmed as long as it follows the new scaling #1265

Unless I'm foolish. This shooould be setting the bandit job total positions to number of players /8
	if(num_players() >= 8)
		// 1 bandit per 8 players, 0 if less than 8, no maximum
		num_bandits = round(num_players() / 8)
		var/datum/job/bandit_job = SSjob.GetJob("Bandit")
		bandit_job.total_positions = num_bandits
		bandit_job.spawn_positions = num_bandits
		banditgoal += (num_bandits * rand(200,400))

**Comment by RadiantFlash7** [comment]
> Double antag for bandits is intended?
> 
> aka bandit-ww roundstart.

Directly intended, not necessarily. However there has been several times in the server where werevolves had matthios as their patron and worked with bandits. 

It is however kinda iffy gameplay wise, and i'm already looking into making it so bandits can't also be werevolves

**Comment by RadiantFlash7** [comment]
Bandits can no longer be vampires or werevolves. 😸

**Comment by HissyNays** [comment]
Holy shit, 4 strength for regular brigand? Don't you feel like thats way too much? 3 was already a lot but 4?!
Thats nevermind the fact everyone gets 2-3 strength if not 4.
Bloody bodybuilders of Mathios.

**Comment by HissyNays** [comment]
So I learned this is basicly content from another server so it's balanced for around there.
This clarifies why those stats are so wild. This is a good PR but it really needs rebalancing, you gotta account for the fact that bandits can group up and steamroll through each guard type separately. You also have to understand that guard is often spread out all over the map rather than moving in pairs/together and there is another even more significant factor, there is always less guards than bandits.
Basicly, why try and come up with smart plans, do the whole guerilla warfare meme or be sneaky when you can just group up and steamroll through whole town and park ontop of duke to say hi to entire town from his throne.

**Comment by RadiantFlash7** [comment]
> Holy shit, 4 strength for regular brigand? Don't you feel like thats way too much? 3 was already a lot but 4?! Thats nevermind the fact everyone gets 2-3 strength if not 4. Bloody bodybuilders of Mathios.

Prior to this PR, bandits got 3 strength by default. 4, if they rolled for the flail loadout. This is the exact same as prior.

**Comment by katsukai** [comment]
> > Holy shit, 4 strength for regular brigand? Don't you feel like thats way too much? 3 was already a lot but 4?! Thats nevermind the fact everyone gets 2-3 strength if not 4. Bloody bodybuilders of Mathios.
> 
> Prior to this PR, bandits got 3 strength by default. 4, if they rolled for the flail loadout. This is the exact same as prior.

Think should be lowered to 3. I hope this gets merged so I can do overhaul with wrestling balance.

**Pull request merged**
