### PR TITLE
Curse system: Divine curses

### PR DESCRIPTION
**Pull request by Gyrandola**
## Curses

The curse system allows players to be victim to curses and to have their curse lifted by admins. This PR should also provide a decent foundation for other contributors to add their own curses if they so desire.

## Roadmap

- Curses **✓**
- Admin Cursing & Curse lifting  **✓**

## Special curses

| Name | Description |
| ------------- | ------------- |
| Atheism &nbsp; | I cannot stand any mention of the divine, and I refuse to believe either the gods or miracles are real. |

## Divine curses

| Name | Description |
| ----------------- | ----------------- |
| Astrata  | I am forsaken by the Sun. Healing miracles have no effect on me.  |
| Noc  | Magical knowledge is now beyond my grasp.  |
| Ravox   | Violence disgusts me. I cannot bring myself to wield any kind of weapon.  |
| Necra | Necra has claimed my soul. No one will bring me back from the dead.  |
| Xylix | Fortune is no longer on my side. |
| Pestra | I feel sick to my stomach, and my skin is slowly starting to rot. |
| Eora| I am unable to show and receive any kind of affection or love, whether carnal or platonic. |
| Zizo| I can no longer distinguish reality from delusion. |
| Graggar| I am engulfed by unspeakable rage. I cannot stop myself from harming others. When that's not an option, my rage is directed inward. |
| Matthios &nbsp;| I hate the sight of wealth, and I cannot have anything to do with mammons. |
| Baotha | I'm in a constant state of arousal, and I cannot control my urges. |

Feedback and suggestions are appreciated.

### CODE REVIEW

**Comment by Hmeister-real** [comment]
Some ideas
Astrata could forbid you from touching sunlight or stop miracles from working on you.
Dendor could make beasts prioritise you over others, and increase chances of attacks from beasts. 
Abyssor could make you unable to swim entirely, and make rain water scold you
Malum could make it impossible to mine, mason, smith, craft and carpent
Psydon could make you have a mega fortune debuff

**Comment by CalamaBanana** [comment]
Dendor could just be some sort of madness tied to civilisation. Randomly bite people around you if you are in an area with stone walls / stone floors, for example

**Comment by DeerJesus** [comment]
Players shouldn’t be able to curse other players… That’s a little strong.

**Comment by Hmeister-real** [comment]
> Players shouldn’t be able to curse other players… That’s a little strong.

I think its for the Priest and maybe Acolytes/clerics with strong faith

**Comment by DeerJesus** [comment]
> > Players shouldn’t be able to curse other players… That’s a little strong.
> 
> I think its for the Priest and maybe Acolytes/clerics with strong faith

It’s an unlimited range spell unblockable spell that just fucks you over until the person decides to fix you - rendering you COMPLETELY unable to defend yourself if you’re a mage/cleric/vampire  and they cast Noc curse - and acolytes/clerics ar a already a little too battlemage-happy. It should be like… Priest but cost all your devotion, or admin ONLY, since the admins are the gods.

**Comment by DeerJesus** [comment]
> The idea is to let players curse as well, it's not supposed to be easy and it wont be. As for curse lifting, the idea is for the priest to be able to lift almost if not all curses.

It better be rrrreaaally hard then.

**Comment by Juubo** [comment]
Can certain classes start with curses? Bums having a Matthios curse would make a lot of sense why they can't pick themselves up.

Certain curses applying after a bad omen would also be interesting.

**Comment by CalamaBanana** [comment]
For Dendor, you could add that spooky invisible monster LW had. Dendor is madness.

If cursed by Dendor, have the player chased by an invisible slowly moving giant angry tree that only the cursed one can see and will skeletonize them if it touches them. Everyone will think them mad as they keep running away from it, just as Dendor wills it.

**Comment by SixplyDev** [comment]
Being cursed by Psydon could add like uhhh idk make you spout some shit about how Psydon is the true God and the church is blasphemous randomly and out of your control yk?

**Pull request merged**
