### PR TITLE
Mirror Description

### PR DESCRIPTION
**Pull request by dotCatshark**
## About The Pull Request

Changes mirror to have a fun little "It's me!" description when examined. Also a test PR because I have barely any idea how to use GitHub or program. Learning is fun!

## Why It's Good For The Game

Self explanatory.

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Not grim dark enough

**Comment by Hmeister-real** [comment]
This PR completely fucks the entire codebase and deletes all the sprites and also gave me a 1000 terrabite zipbomb. Gitbanning you for life

**Comment by dotCatshark** [comment]
> Not grim dark enough

More like grim shart

**Comment by Azlier** [comment]
Not nearly lore accurate enough. Needs to include a 'There's nothing there' for vampires and a 'It's not me' for maniacs, etc etc.

**Comment by TheFenix323** [comment]
> Not nearly lore accurate enough. Needs to include a 'There's nothing there' for vampires and a 'It's not me' for maniacs, etc etc.

This ^

**Comment by dotCatshark** [comment]
I might be able to shove an if statement in there that does this. Will try something.

**Comment by dotCatshark** [comment]
Alright so it may be that doing that is simply impossible as it stands with byond, or at the very least I am nowhere near experienced enough for that.

**Pull request merged**
