### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request

Removes tree walls around the map, placed a bunch of single trees instead of deleted ones
Replaced bones at south-west bog mine with proper ones, that can be passed
Fixes double closet at hand's room
Fixed torches inside walls where i managed to find them
Added lights to admin test area
Fixed drawer at 3rd fancy inn room
Moved shylock near smiths to be between peddlers
Made merchant's goldface look less out of place
Tweaked some standing fires at inn bath to be passable
Standartized stone keep walls on 1st floor
Deleted this 
image

## Why It's Good For The Game
Stupid tree walls is no good

### CODE REVIEW

**Comment by Cyprex** [comment]
I like the treewalls, but the rest of this PR is good. They make the areas they're in hard to navigate, and really incentivize you to get out your axe.

**Comment by CalamaBanana** [comment]
Tree walls are important to break up the openness of the bog at least a little. They are important for juking as well, the bog should not be just neatly trimmed city park. To be honest, there should be even more tree walls, to turn the bog into a proper maze.

**Comment by Red-Honk** [comment]
Tree walls should stay, interesting combat situations happen when one party gets cornered there or uses the place to hide, or even makes an omega tree house, it's quite amusing really.

And when it comes to the rest, well, why not.

**Comment by Cyprex** [comment]
Good changes, but don't change the trees!

**Comment by Heheniy** [comment]
There will still be stupid tree walls because of random tree spawn

**Review by Jaaackx — CHANGES_REQUESTED** [review]
Not a fan of the 'tree wall' removal, everything else here is good.

**Comment by Heheniy** [comment]
artificial bullshit like this was removed
image



there still will be random tree walls as trees have random spawn

**Comment by Cyprex** [comment]
Tree maze is good

**Pull request closed without merging**
