### PR TITLE
Cutting Stump is no longer Ass

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

Now chopping a stump works the same way as chopping a lot:

image

## Why It's Good For The Game

As of now cutting a stump only delays the player for no real gain, which lead to a lot of stumps everywhere.
Players would rather have to push the cart with them and climb on top of the stump to store the logs in their cart and do this for every tree than to actually remove the stump.
Since players liked this woodcutting mechanic, I decided to expand it to stumps to solve the problems highlighted above.

### CODE REVIEW

**Comment by 2PlainGhoul** [comment]
Yeah, I never had this issue before -- this seems like a non-problem

**Comment by Nakalon** [comment]
> Yeah, I never had this issue before -- this seems like a non-problem

oh... kay?

**Comment by Hmeister-real** [comment]
yeah this isn't really an issue, stumps are just part of cutting a tree

**Comment by Gyrandola** [comment]
Stumps are supposed to be not worth removing. Theyre stumps.

**Comment by Nakalon** [comment]
> Stumps are supposed to be not worth removing. Theyre stumps.

Stumps cause you to have to climb on top of them to get the logs into the cart, every single time, and if you decide to remove them you get 1 stick and one small log, now you have to fish for that stick because you don't want it occupying space in your cart.

This takes away the stick element, makes it so you can just put everything in your cart at once and doesn't give you much more than it already did, except for the small chance of the small log it would otherwise spawn become an essence of lumber instead

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
