### PR TITLE
Expands Examine

### PR DESCRIPTION
**Pull request by GuppyLaxx**
Examine now takes into account where exactly you're looking at on people, and also if you're looking at something on you, your hands, or inside your bags.

Removes automatically facing whatever you examine aswell.

dreamseeker_bktkHX5ZLc
dreamseeker_VucVFH8F79

### CODE REVIEW

**Comment by Coolgat3** [comment]
omg i can be a fucking pervert and stare at people's ass hell yeah

**Comment by hugmeorelse** [comment]
What if you make it a perception check? :^) To see where they're looking at directly?

**Comment by Hmeister-real** [comment]
DO NOT REMOVE FACING WHAT YOU EXAMINE, PLEASE. I use it all the time to look in a certain direction, or to turn around and look at someone in one motion

**Comment by radarseas** [comment]
Leave turning as you examine, its a suble but **EXTREMELY** _useful que for you've caught someone's eye_ and they're trying to check if _something is off with you_. It can absolutely change the game despite how subtle it is. In fact it can be enough to give you that early que to move faster/hide away and not get ganged on.

**Comment by Ragnuv** [comment]
> Leave turning as you examine, its a suble but **EXTREMELY** _useful que for you've caught someone's eye_ and they're trying to check if _something is off with you_. It can absolutely change the game despite how subtle it is. In fact it can be enough to give you that early que to move faster/hide away and not get ganged on.

THIS, definitively this, something that would also be interesting, and also add a use for the perception stat which is borderline useless as of now, would be determining rather you turn or not on examining something depending on your perception stat (above 10, you don't turn, and below 10 you turn)

**Comment by HissyNays** [comment]
Ehhh not a fan of examine not making you turn towards thing you examine. You can now even examine some one behind you without turning. It ends up feeling like game is glitched and thus makes the game less immersive.

**Comment by EzekyalLegit** [comment]
Guys you can turn to face a direction by just holding CTRL and hitting any WASD direction

**Comment by Cyprex** [comment]
Is this good to merge?

**Pull request merged**
