### PR TITLE
Siege antag gamemode

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

The basics for a siege gamemode with an invading baron and his army, very WIP so don't yell at me too hard

# WHAT'S NEEDED BEFORE IT'S READY

give the baron the title of baron, and his soldiers the title of barons soldier

possibly siphon players from adven & pilgrim to make sure the baron has a good number of troops

~~probably the baron and his hand need custom sprites, maybe also a way to color his troops~~

when the baron sits on the throne and makes an announcement it should provide the "win" for the baron and his men just like peasantrebel

a way for the baron to send one announcement before leaving camp, stopping soldiers leaving the camp before the baron has made that announcement

~~the barons hand defined in the siege.dm file, I couldn't get it to compile if I added it to 15 and tried to do the same force load pick, not sure why maybe someone with more experience can help with that~~

probably more that i am missing, screenshots below of what IS done so far

Screenshot 2024-08-27 150559

Screenshot 2024-08-27 143330

Screenshot 2024-08-27 143403

Screenshot 2024-08-27 144939

Screenshot 2024-08-27 144946

Screenshot 2024-08-27 145213

Screenshot 2024-08-27 145328

## Why It's Good For The Game

Everyone has been asking for this, i just was very lazy and didn't sit down to try making it, i am still very new to this so if there are glaring mistakes in this PR please comment and let me know so i can fix

### CODE REVIEW

**Comment by LeShprotina** [comment]
BASED AS FUCK

LET'S FUUUUCKING GOOOOOOOOOOOOOO!!!
(I really want some sieges)

**Comment by CalamaBanana** [comment]
>possibly siphon players from adven & pilgrim to make sure the baron has a good number of troops

Change all migrant waves to be troops for the baron. LW had a system where their siege leader could pay for specific wave types. As in, melee infantry, ranged infantry, rifle infantry or support troops.

**Comment by zakanater19** [comment]
> > possibly siphon players from adven & pilgrim to make sure the baron has a good number of troops
> 
> Change all migrant waves to be troops for the baron. LW had a system where their siege leader could pay for specific wave types. As in, melee infantry, ranged infantry, rifle infantry or support troops.

Could be nice, but really i want to keep it simple till it's ready for play, then i guess we can get wild with it  xD

**Comment by zakanater19** [comment]
> Also, a small smithy for the camp so people have something to do before it is time to leave

Yeah i probably will, also a reminder if anyone can help with the coding problems listed in the PR please dm me on post it here

**Comment by zakanater19** [comment]
Shitty placeholder baron cloak
Screenshot 2024-08-27 212106

**Comment by zakanater19** [comment]
ok hand spawns next in line after baron and then soliders like it should
Screenshot 2024-08-27 223922

**Comment by CalamaBanana** [comment]
Thing I'd add to the to-do list:
- a banner that the hand has to carry. Can't be an army without a flag.
- brainstorming a way to push most of the town to resist and not just stand by idly or even side with the invaders. Maybe secondary objectives like blowing up the farm, shop and brothel? Invader army getting better reinforcements the more damage they do to the town? Or perhaps make them the great heathen army, invading for the glory of Graggar, Baotha and Zizo? (Not Matthios, he has his bandits without a lord)
- a unique helmet style so they are easily recognized by everyone else. With good enough stats that they won't resmelt it into the usual flavor of the month helmet
- hud icon for troops

**Comment by Heheniy** [comment]
> * unique helmet style so they are easily recognized by everyone else

are colorable tabards a joke for you?

**Comment by zakanater19** [comment]
> Thing I'd add to the to-do list:
> 
>     * a banner that the hand has to carry. Can't be an army without a flag.
> 
>     * brainstorming a way to push most of the town to resist and not just stand by idly or even side with the invaders. Maybe secondary objectives like blowing up the farm, shop and brothel? Invader army getting better reinforcements the more damage they do to the town? Or perhaps make them the great heathen army, invading for the glory of Graggar, Baotha and Zizo? (Not Matthios, he has his bandits without a lord)
> 
>     * a unique helmet style so they are easily recognized by everyone else. With good enough stats that they won't resmelt it into the usual flavor of the month helmet
> 
>     * hud icon for troops

banner maybe, i was thinking all of the barons men would have distinct color uniforms anyway

yeah im not entirely sure the direction yet, probably best to leave it up to the baron player how he wants to go about it, could do RP could just kill everything

yes for the last two im still trying to figure out how to give them the tag that shows they are with the baron in big letters, i THINK it works already but i have not tested it with the two accounts to make sure

**Comment by zakanater19** [comment]
> No way it's back

it's actually extreme CBT

**Comment by zakanater19** [comment]
Going to work on this and then PR it when it's in a more complete state

**Pull request closed without merging**
