### PR TITLE
lowers adventurer cap to 10

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
WOE BE UPON ADVENTURER MAINS GO BACK TO THE WANDERER QUEUE

## Why It's Good For The Game
image
someone on discord asked for it

### CODE REVIEW

**Comment by Keazra** [comment]
Based.

**Comment by kokokokokokokokokokokokokokoko** [comment]
I'm angry. I'm going to kill you.
With rocks.
Big rocks.

**Comment by Keazra** [comment]
My reasoning it's good for the game: towner roles go woefully unused because everyone wants to be a badass. drip feed the addiction of adventurers and force them to shake up their choices at least a little bit.

**Comment by SayonaraEcho** [comment]
> My reasoning it's good for the game: towner roles go woefully unused because everyone wants to be a badass. drip feed the addiction of adventurers and force them to shake up their choices at least a little bit.

Sorry to be the bearer of bad news but it's possible to join this role via migration. I've always join as adventurer via migration if there's no slot for it. Better to delete adventurers and piligrims, only for migration keep.

**Comment by kokokokokokokokokokokokokokoko** [comment]
> My reasoning it's good for the game: towner roles go woefully unused because everyone wants to be a badass. drip feed the addiction of adventurers and force them to shake up their choices at least a little bit.

The problem is that forcing players into a role that, as you say, is BARELY used will not fix anything, people will not be happy and those who already played adventurer will just wait for the migration.
there's no real incentive to play Towner besides; oh woah i can huh make cheese and that's it.

**Comment by Keazra** [comment]
> > My reasoning it's good for the game: towner roles go woefully unused because everyone wants to be a badass. drip feed the addiction of adventurers and force them to shake up their choices at least a little bit.
> 
> Sorry to be the bearer of bad news but it's possible to join this role via migration. I've always join as adventurer via migration if there's no slot for it. Better to delete adventurers and piligrims, only for migration keep.

Yeah I know I want people to be forced to migrate. As is people don’t have to migrate if there are fewer than twenty adventurers. :) Maybe people will wait for it, or maybe they’ll opt to play a pilgrim or something if they decide they don’t want to wait!

**Comment by radarseas** [comment]
I main adventurer, but this is for the better.

Too many people pick it to be able to do combat and immedately fuck off to play as non-combat roles until antags do anything interesting and then wipe them.

I would adjust it to scale a slot up 1 to every 10 pop as soon as the lobby timer runs, else we'll still get whoops, all mages and clerics on basically no-pop.

**Comment by Red-Honk** [comment]
We already lowered it from 40 to 20, we aren't halfing it again, I am sorry, but it's hard enough to be an adventurer to begin with.

**Comment by katsukai** [comment]
Feel like this change will make people complain and eventually stop playing in ratwood

**Comment by Jaaackx** [comment]
good change but Towner needs improving at the same time, it's unnecessarily garbage

Need to discourage adventurer play and encourage Town roles more

**Comment by NikolayByondPlayer** [comment]
Making adventurer class more rare for pilgrims would be better - but this is also good
Maybe even making if 5 would be better. Now we have PVPkeep with everyone having proficiency in every weapon possible.

**Comment by Keazra** [comment]
> good change but Towner needs improving at the same time, it's unnecessarily garbage
> 
> Need to discourage adventurer play and encourage Town roles more

I saw a commit that improves tower roles a lot!

**Pull request merged**
