### PR TITLE
[BALANCE] Reduces garrison powercreep. Gives knights polearms.

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

A [port](https://github.com/Blackstone-SS13/BLACKSTONE/pull/1066) of my failed attempt to reduce the huge garrison powercreep Blackstone has. Plus a few modifications.

<h1>Changes</h1>

<h3>Captain of the Guard:</h3>

- Gear
   - Helmet: Pigface --> Visored Sallet
- Skills
   - Polearms: Legendary --> Master
   - Swords: Legendary --> Master

<h3>Man At Arms:</h3>

- Gear
   - Gloves: Plate --> Chain gloves
   - Boots: Plate --> Leather

<h3>Bog Master:</h3>

- Skills
   - Swords: Legendary --> Expert
   - Axemaces: Legendary --> Expert
- Stats
   - Strength: 4 --> 3

<h3>Knight</h3>

- Gear
   - Weapon: Polemace / Lucerne  (Bastard sword moved to sidearm)

### CODE REVIEW

**Comment by K4rlox** [comment]
knights should get a sword not a mace...

**Comment by Gyrandola** [comment]
> knights should get a sword not a mace...

Despite Hollywood portrayal, a knight's main weapon was usually a polearm, as it could more easily kill an equally armored opponent.

main-qimg-1b44414422d3147be2c1bb27a863e14c

I'll however, still give them a sword they can use as sidearm, so you're happy.

**Comment by Coolgat3** [comment]
The garrison is supposed to be hard to beat by stupid journeyman bandits. You are lowering the skills of the only 2 jobs that get legendary swordsmanship, idk for what reason. They get it to be able to train. The captain gets a pigface because he's supposed to be stronger than the bog master. You made the bog master weaker than a knight which makes 0 sense considering hierarchy wise the Bog Master and Captain of the Guard are equals.

**Comment by DeerJesus** [comment]
This seems like a bad idea. There are a LOT of antags and they can still absolutely DEMOLISH our current guard at very high rates.

**Comment by PTFOperations** [comment]
Hell, vamps can very easily overwhelm the keep.

**Comment by zeratino** [comment]
This is a good idea. I think that there is way too much going into the Guard's favor, right now.

**Comment by Gyrandola** [comment]
> Hell, vamps can very easily overwhelm the keep.

That's because the counter to vamps is not brute force, but miracles that literally explode them / set them on fire. An organized church can handle the vampires.

**Pull request merged**
