### PR TITLE
Lowers extended to 30%, bandits to 100%

### PR DESCRIPTION
**Pull request by Useroth**

### CODE REVIEW

**Comment by wow50000** [comment]
No description provided.

**Comment by SixplyDev** [comment]
I think that bandit populations should be scaled off bogman population. I don't want to say 1:2 but maybe 1:1.5 or something similar. It's stupid when there's like 10 bandits vs a single bogman. Other than that, I like this PR, it should spice up the round.

**Comment by radarseas** [comment]
> I think that bandit populations should be scaled off bogman population. I don't want to say 1:2 but maybe 1:1.5 or something similar. It's stupid when there's like 10 bandits vs a single bogman. Other than that, I like this PR, it should spice up the round.

remember that the watch, masters at arms, the knights, the king, all of the mercenaries and every single adventurer is incentivised by either job expectations, the 80 headhunting bounty or just the sheer scale of noticable crimes bandits will be commiting.

often its adventurers that fend off bandits that try to overrun the gate, or at least hold long enough for the keep to send reinforcements, especally with a cleric present or two.

**Comment by SixplyDev** [comment]
> > I think that bandit populations should be scaled off bogman population. I don't want to say 1:2 but maybe 1:1.5 or something similar. It's stupid when there's like 10 bandits vs a single bogman. Other than that, I like this PR, it should spice up the round.
> 
> remember that the watch, masters at arms, the knights, the king, all of the mercenaries and every single adventurer is incentivised by either job expectations, the 80 headhunting bounty or just the sheer scale of noticable crimes bandits will be commiting.
> 
> often its adventurers that fend off bandits that try to overrun the gate, or at least hold long enough for the keep to send reinforcements, especally with a cleric present or two.

I really don't see a lot of that anymore and even then it's only usually if there's massive bandit populations. We still need to keep in mind that a lot of times the bog has nobody or just a handful of people against sometimes massive numbers. I feel like some kind of change should be made so that bandits can't steamroll the 1-2 bogmen roundstart

**Pull request merged**
