### PR TITLE
Prosthetic fix 2

### PR DESCRIPTION
**Pull request by OrangeDecay**
Sorry, my bad.

### CODE REVIEW

**Comment by OrangeDecay** [comment]
Don't merge yet

**Comment by OrangeDecay** [comment]
That should address every complaint so far.

**Comment by Gremillion** [comment]
I saw in the first fix that it says female prosthetics, though I have this issue with my male characters also. Are they both fixed in this one?
(Thank you btw, this has been driving me insane)

**Comment by OrangeDecay** [comment]
> I saw in the first fix that it says female prosthetics, though I have this issue with my male characters also. Are they both fixed in this one? (Thank you btw, this has been driving me insane)

Should fix that

**Comment by CalamaBanana** [comment]
> That should address every complaint so far.

image

Have a new one, forgive me.
Does not show the sprite from the side.

**Comment by OrangeDecay** [comment]
> > That should address every complaint so far.
> 
> image
> 
> Have a new one, forgive me. Does not show the sprite from the side.
> 
> As comparison, how her good arm looks, so you know it is not the dress: image

Huh, both are being rendered using the same code. I assume icons are missing something again.

**Pull request merged**
