### PR TITLE
Blindness Flaw

### PR DESCRIPTION
**Pull request by Multigamer99**
## About The Pull Request

Wow the game is terribly difficult to play with no visuals but kinda fun IMO.

Lets you be blind at round start. AFAIK, this cannot be cured by getting eyes put into you.

Changelog:
- Adds a new "Blind" flaw that permanently blinds the character for that round.

## Why It's Good For The Game

It lets you roleplay a blind person without having to manually gouge your eyes out every round, and since there's potentially interesting stories in that, why not have it as a feature? Plus, it is still possible to play while blind, as you can still me and say, and you can use your mouse to navigate "by touch", so to speak.

### CODE REVIEW

**Comment by Multigamer99** [comment]
Also, might be a decent idea to do it like other ss13 servers where you CAN see around yourself, but I think this is a bit funnier.

**Comment by Multigamer99** [comment]
That's a good point. I'll sit down and do flaw blocks later. At the store at the moment.

**Comment by Multigamer99** [comment]
That should have fixed the conflict.

Now jobs reset whenever you change your flaw, and most jobs are banned if you are blind.

**Comment by Multigamer99** [comment]
I originally did it like this for readability but that's a good point. I'll get that up in a moment.

**Comment by Multigamer99** [comment]
alright, i think that'll do it

**Comment by Multigamer99** [comment]
lemme know if i fucked it there

**Comment by CalamaBanana** [comment]
Please do exclude this one from the "random flaws" if it is not already. This one is just not a flaw, it is round crippling.

**Comment by Multigamer99** [comment]
Yeah, sure. I can do that.

**Comment by Multigamer99** [comment]
Fixed the merge issues.

**Pull request closed without merging**
