### PR TITLE
Marriage for everyone

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request

Now same gender marriage is real

Last name will be assigned from first person who bit an apple

## Why It's Good For The Game

Gay marriage wooo

### CODE REVIEW

**Comment by LeShprotina** [comment]
Baotha's slave PR

**CLOSE THIS PR IMMEDIATELY**

**Comment by ZybZybov** [comment]
Sounds gay to me

**Comment by zakanater19** [comment]
this playerbase bro..

**Comment by Elli-Skala** [comment]
People are down voting this pr but if this should be allowed or not 100% should be a IC issue and not predicted by code which is adminbussed in half the time anyways

**Comment by Shuzukiama** [comment]
Excessive tolerance has gone too far. Remove this PR

**Comment by Kepteyn** [comment]
This doesn't stop you, as the priest, saying no to gay marriage IC. But given that gay relationships are widely treated with indifference in-game, it's entirely reasonable to allow marriage too.

**Comment by wow50000** [comment]
eora is homophobic :)

**Comment by Kepteyn** [comment]
> eora is homophobic :)

The one trick Eora doesn't want you to know about (it's sucking dick)

**Comment by Useroth** [comment]
I think we won't be doing this one for time being

**Pull request closed without merging**
