### PR TITLE
Templar Improvements

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

Improves Templar loadout. Switches Gambeson and Hauberk for Hauberk and Half-Plate. Improves Templar helmet visibility (I think).

Gives them slightly better mace training and slightly better wrestling for non-lethal approach.

## Why It's Good For The Game

It's a 3 slot role meant to be the elite protectors of the Church and Priestess. Can't really do that if your equipment's mediocre at round start and you can't see 90% of the Church with your awful helmet on.

Makes them ever so slightly more intimidating to deal with. This role _should be strong_ given they're competing with 10 in the King's Guard regularly.

### CODE REVIEW

**Comment by Teragenic** [comment]
Solid no on the improving visibility part. That's a genuine skill issue. If you do that, Guards/Powergamers are gonna ask for these helmets or ask for their own helmets to be buffed in the same way.

Please show it also compiling.

The second part of the code is fine and understandable.

**Comment by Jaaackx** [comment]
I can see the helmet change being too much and can remove that if needed.

I do think the other changes make sense, though. Most Templar will go to the Smithy very quickly and just get better armour anyway, so it wouldn't change anything in terms of their strength. Mostly convenience so they don't need to leave their singular posting for 30 mins for Smithy queue.

And I think the skill changes are pretty necessary, just for the sake of RP. It blows being basically stuck using a sword at all times and regularly struggling with wrestling. More fun to non-lethally detain people.

**Comment by Altangy** [comment]
As a templar, I've gone entire rounds and survived church purges with out upgrading my gear. It's good enough, and the bucket vision is your trade off for using it.

**Comment by Jaaackx** [comment]
> As a templar, I've gone entire rounds and survived church purges with out upgrading my gear. It's good enough, and the bucket vision is your trade off for using it.

They are the sole combat focused role of the Church. If we're _really_ being fair, they'd have equipment comparable to the Knights. I don't really think half-plate and a hauberk is a big ask in comparison.

**Comment by Jaaackx** [comment]
Closing this and I'll redo a PR with the helmet change gone.

**Pull request closed without merging**
