### PR TITLE
Removes churn spell

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request

Removes churn spell from game (left it commented out if someone one day would decide to rebalance all spells (haha)).

## Why It's Good For The Game
This spell is one of the most cancerous mechanics of the game.
No matter how well prepared you are, how good is your equipment or starts are, how much effort did you put into everything you achieved - if you are undead- even naked, limbless, the most retarded necra templar/acolyte/whatever can nuke you with a single click of a button, that has 0 charge time, CD only of a few seconds and costs 20 devotion (literally nothing).

https://cdn.discordapp.com/attachments/1240810707877101598/1300957762368438303/unknown_2024.10.29-18.57.mp4?ex=67236395&is=67221215&hm=809631433ed0e192c0aa50c163026d0cda135ca65c49f2116a714601e2b542b7&

https://cdn.discordapp.com/attachments/1240810707877101598/1300957928605356032/unknown_2024.10.29-18.57_1.mp4?ex=672363bc&is=6722123c&hm=e64330141020afb7fc07fb761c3c568dad70ef244245628bd223580487f436fa&

### CODE REVIEW

**Comment by Nakalon** [comment]
Don't comment out code by the love of god, just remove it if you're removing it.

If you actually want to balance it, then do so and don't remove it.

**Comment by Xaytan** [comment]
Counterpoint: The undermaiden rebukes.

**Comment by Nakalon** [comment]
Gyran is working on the Lich still and has said this can't be removed.

So I'm pulling out one of the nuke keys and voting for a no go. 🔑

Unless you're inclined to find a different approach?

**Comment by SayonaraEcho** [comment]
> while removing it wouldn't be a bad idea, I'm sure we can do better like making it only target a single person, or something like azure did, else this removes the whole "putting the dead to rest" gimmic necrans are supposed to have that seperates them from any magical random.
> 
> I will however say every paladin getting a "full powered version" of the same spell doesn't help neither, if anything it should be something exclusive to cleric/morticians as compensation for being magically inferior to every single other patron. Especally that every second adventurer is a paladin these days.
> 
> for example, this PR: https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/709 does a good job at keeping it without decimating the use of it.

Yeah, how about to port from Azure Peak remake of churn undead? I think it's better than undead explosion with one button.

**Pull request closed without merging**
