### PR TITLE
Armor sleeping 2: Electric Boogalo

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request

If you are in crit you now can 'fall asleep' even wearing armor

## Why It's Good For The Game
No more this while fucking DYING
image

### CODE REVIEW

**Comment by Hmeister-real** [comment]
bad, just don't wear metal armor

**Comment by ikrarkjr** [comment]
Add sleep paralysis

**Comment by radarseas** [comment]
blessed PR.

**Comment by Keazra** [comment]
I’ve grown to grudge how lethal Ratwood has become almost in large part due to the sleeping in armour changes so I highly approve of this change. Restorative comas, yes yes yes.

**Pull request merged**
