### PR TITLE
BIG BOOBS update

### PR DESCRIPTION
**Pull request by usernameasterisk**
## About The Pull Request

add: BIG BOOBS

## Why It's Good For The Game

Funny BIG BOOBS. You can gain BIG BOOBS by setting your breasts size "enormous" in your character panel. BIG BOOBS can distract anyone with GIANT ASS text on examine (even bigger than "BANDIT!" warning (yes, even when clothed). In exchange, getting up from the floor takes twice as long, you can't wear armor (all items are in the "armor" slot, the chainmail shirt will still work) and shoot with a bow.

image

More funny features with these BIG BOOBS may come. For example, I was planning to add a stat change (+3 CON, -2 END, -1 SPD), but couldn't figure out how to do it correctly.

**UPDATE:** now robes, gambesons, chainmail and leather can hold BIG BOOBS. So you can wear any light armor without any problem. Still, females with BIG BOOBS are locked from wearing some medium armor and all heavy armor.

### CODE REVIEW

**Comment by usernameasterisk** [comment]
Jakksergal disliked BIG BOOBS PR I'm in tears right now. :sob::sob::sob::sob::sob::sob::sob::sob:

**Comment by Gr33d-y** [comment]
If it removes all items from being worn in the armor slot would it not prevent you from wearing most dresses or did you just disable the armors?

**Comment by usernameasterisk** [comment]
> Weird fetish PR

Fun fact: this PR does not add "enormous" breasts size. It is already in game, but without any funny mechanical traits.

**Comment by usernameasterisk** [comment]
> If it removes all items from being worn in the armor slot would it not prevent you from wearing most dresses or did you just disable the armors?

Most of the dresses, as far as I know, can be worn in ITEM_SLOT_SHIRT. But not robes. I probably should fit these BIG BOOBS into robes somehow.

**Comment by usernameasterisk** [comment]
Major BIG BOOBS buff. Now robes, gambesons, chainmail and leather can hold BIG BOOBS. So you can wear any light armor without any problem. Still, females with BIG BOOBS are locked from wearing some medium armor and all heavy armor.

**Comment by Gr33d-y** [comment]
I mean I'm fine with adding unique interactions with people having massive breasts or genitals. The only thing I think is weird is the examine stuff and the fact that they are called "THEM" As if their breasts are these unnameable horrors. Feels a bit weird. As they said through, these breasts are already in the game and while it's cool and we should let people have them, there prolly should be some downsides to doing so. It would make playing with them feel like someone is dedicated to the bit instead of just maxing out all sliders. Just imo tho.

**Comment by usernameasterisk** [comment]
> > > Weird fetish PR
> > 
> > 
> > Fun fact: this PR does not add "enormous" breasts size. It is already in game, but without any funny mechanical traits. By the way, you liked addition of actual dildos in game, but you don't like BIG BOOBS. Something is wrong with you.
> 
> dildos are a reasonable addition. Characters with hyper-inflated breasts that make them unable to be anything but a fetish erp bait are not.

bro can't you read? "enormous" breasts size is ALREADY in game, you ALREADY can choose it, but you do cope about addition of laughable mechanics for them. meanwhile also supporting addition of actual fucking sex toys in the game, holy shit.

**Comment by usernameasterisk** [comment]
> I mean I'm fine with adding unique interactions with people having massive breasts or genitals. The only thing I think is weird is the examine stuff and the fact that they are called "THEM" As if their breasts are these unnameable horrors. Feels a bit weird. As they said through, these breasts are already in the game and while it's cool and we should let people have them, there prolly should be some downsides to doing so. It would make playing with them feel like someone is dedicated to the bit instead of just maxing out all sliders. Just imo tho.

they are called THEM because this is funny as fuck

**Comment by usernameasterisk** [comment]
> > > > > Weird fetish PR
> > > > 
> > > > 
> > > > Fun fact: this PR does not add "enormous" breasts size. It is already in game, but without any funny mechanical traits. By the way, you liked addition of actual dildos in game, but you don't like BIG BOOBS. Something is wrong with you.
> > > 
> > > 
> > > dildos are a reasonable addition. Characters with hyper-inflated breasts that make them unable to be anything but a fetish erp bait are not.
> > 
> > 
> > bro can't you read? "enormous" breasts size is ALREADY in game, you ALREADY can choose it, but you do cope about addition of laughable mechanics for them. meanwhile also supporting addition of actual fucking sex toys in the game, holy shit.
> 
> 341627206-a1db95dc-52ea-4ffd-80f3-73535ce7ea8b
> 
> Yeah, and it's already bad enough. You're the one who also wants to make sure whoever has those boobs is bound to be a walking fetish.

Yeah, playing with fetish-sized boobs debuff-free while ignoring all anatomy logic is totally better than actually struggle because of their size with no real advantages besides BIG BOOBS. Is that what you are trying to prove?

**Comment by Nep993** [comment]
Why is this a necessary addition besides just screwing with people who wanna have large breasts exactly? You've not provided a single rational explanation as to why you wanna add this aside from some vague vendetta against people that like having big breasts.

**Comment by Useroth** [comment]
Amusing PR but please...

**Comment by usernameasterisk** [comment]
IT'S SO OVER

**Comment by coffeecoffeecoffee** [comment]
Please reopen this. This is what I play for and it's very tastefully done for what it is, plus it's immersive to have huge chests actually prevent you from doing certain tasks like drawing a bow. This adds realism, ironically.

**Comment by EaglePhntm** [comment]
this is the best pr i ever seen, i could maybe use this in dreamkeep since its closed here, as a temporary curse or debuff of sorts, since its funny.

**Pull request closed without merging**
