### PR TITLE
Update soilson.dm

### PR DESCRIPTION
**Pull request by KKLZ4**
Soilson buff. Gives them Novice Cooking, Novice Sewing, removes Bows. General stat buffing, apart from PER which was nuked.

## About The Pull Request

Soilson was given Novice in Cooking and Sewing, their Bows skill was removed. Polearms and Knives were buffed from Novice to Apprentice. Stats were overall buffed, PER was nerfed as a concession.

## Why It's Good For The Game

Soilson as a role is currently in an awful state. An Adventurer with 11 INT can out-farm and out-produce soilsons by the sheer fact that Farming as a skill is currently meaningless, and because 11 INT means that you'll have infinitely more uses for anything you can farm, while Soilsons, with their -2 INT, quite literally can't do shit without a long, painful grind.

### CODE REVIEW

**Comment by Useroth** [comment]
why the +3 strength and +3 endurance?

**Comment by X404ErrorX** [comment]
why +3 str lol, time to male half orc soilson with XVI strength

**Comment by KKLZ4** [comment]
> why +3 str lol, time to male half orc soilson with XVI strength

Not as bad as Knight getting +4 STR, full plate armor, and master and expert in like 6 different weapon categories, lol.

**Comment by Teragenic** [comment]
They do not need the extra weapon skill, strength, and endurance. This is just power creep. I get the Intelligence, but I don't see why you are buffing everything else to be onpar/better than most actual combat classes.

**Comment by KKLZ4** [comment]
> They do not need the extra weapon skill, strength, and endurance. This is just power creep. I get the Intelligence, but I don't see why you are buffing everything else to be onpar/better than most actual combat classes.

They're not on par, though. 

They lack roundstart equipment. Farmers have no roundstart armor, and the best armor we can theoretically craft is leather, hide, and gambesons. Farmers don't get any special armor training to use Maille or Plate, etc. The best weapon farmers have at roundstart is an Iron Axe, which they do not get the combat skill to use so they literally cannot hit anyone with it who activates their parry. Threshers are still coded as Maces, despite technically working with the same principle as flails, so again cannot be used in combat so long as the opponent has parry active.  The the only weapons they actually can use at roundstart are sickles, and the butcher's Hunting Knife, if the Butcher doesn't spawn in/have it stolen by randoms who rush his house for a free knife.

Soilers spawn with almost no money, and their income only comes after performing their actual work, while Guards are /meant/ to be routinely paid by the Steward for doing literally nothing other than being alive, letting them steadily accrue armor and weapons without any actual effort.

Arguably most importantly in the way of balancing, soft-power in the form of implicit role trust. Tell me, if you're a guardsman or a do-gooder, and you see a farmer beating the shit out of a bog-guard, are you really going to stand there and go "ERM!!! MISTER FARMER,,,, DID THE BOG GUARD DESERVE THIS... OR R U A FRAGGER.....???" Or are you immediately going to sprint to the guard's rescue/get other guards to rescue him without stopping to question or even trying to pick the farmer's side?

Also, in terms of stat balance, Soilers are 2 INT, 1 STR, and 1 END better than a Bog Guard, and equal to in every other stat, except for Perception, where they're 4 points worse than a Bog Guard, along with being out-skilled in every combat skill, and once again, not having access to roundstart arms and armor, implicit role trust, and functionally-free money.

**Comment by KKLZ4** [comment]
This PR essentially brings soilers up to par with how they are on Stonekeep, and just about everyone who no-lifed soiler on there agrees that they are in a significantly better state on Stonekeep than they are here.

In the farm's current state, there is literally no reason to play soiler when you can spawn in as an Adventurer, have higher stats, better combat skills, and be able to out-farm and out-craft every single soiler, and on top of that, then go an engage in combat or whatever else you desire.

It's so bad right now that I've consistently seen people just rush the farm as Adventurers and muscle out the actual soilers so they can spend the entire round farming instead of spawning in as a Soilson, because there's _literally no reason to even bother playing the role._ If you want a good farming experience, play _anything other than soilson._

**Pull request closed without merging**
