### PR TITLE
ABP&F - Antag Mass touchup PR.

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Antags weak to certain dumb things.
Coder man fix.

## Why It's Good For The Game
Vlord dying to lesser miracle & verewolf dying to caltrops was so unfunny.

Also fixes Volfs taking damage slowdown from painstunning.

Also gives VLord some redeeming traits & makes them harder to instakill via High STR builds (like flail to the head instacritting and killing)

KEY NOTE: This should still allow VLord to be decapitated/instakilled via destroying their heart, or scoring a heart critical.

MORE DETAILED CHANGELOG:
-Adds Miracle Immunity, a trait that makes lesser/greater miracle still LOOK like it functions on a target, but doesn't actually heal (and has a chance to tell the miracle user that healing you is unusually tiring)
-VL now has miracle immunity, and will not directly alert miracle users (though on a 5% chance they can see it takes more stamina to "heal" them)
-VL has lost CRITICAL WEAKNESS due to balancing concerns - Temp re-enabled while I work on a better system for killing them.
-VL has gained the FAKE WEAKNESS (TRAIT_DECEIVING_MEEKNESS) trait (so they cannot be easily questioned while disguised as to why they look like a werewolf in terms of strength)
-VL has gained PAINSTUN immunity, as they were already immune to pain (but not the stuns from broken/dislocated legs)
-WW has gained TRAIT_PIERCERESIST (which does not affect our combat system), preventing blade embeds (fixing the qdelete issue where species transforms deletes all items in your limbs), and stopping glass shards from stunning
-WW has gained PAINSTUN resist, but can still take pain! (No more crits stunning WW in place for 5-10 seconds anymore, they'll still fall over if legcritted, but should be more survivable now!)
-WW has gained an extra 15 base armor (for once their main armor fails). Subjetc to change.

### CODE REVIEW

**Comment by DeerJesus** [comment]
VL is already rrrreaaaally powerful- miracles don’t actually do that much damage to a full power VL then slow them down… Have you ever PLAYED against a VL that had been slurping on a bloodbag doing no rp for 1 hour straight? It’s fucking annoying

**Comment by Stagrawl** [comment]
This is going to lead to truly the most abysmal dogshit, but hey, pressure to make vampires social I guess.

**Comment by ApplePlastic** [comment]
so today I removed the 20 speed/str/legendary sword skill antag's one and only weakness

**Comment by DeerJesus** [comment]
C8CC1BD4-5899-4E31-AD8D-FDA08AAB5A7C

**Comment by Teragenic** [comment]
After interacting with two VLs post TM, I have to agree with the sentiment. At the moment the only Counter to the VL is the Inquisitors Silver dagger, which is countered by the overtuned Vampire Lord Stats.

I feel like miracles itself should be reworked.

And the "Bane Bug" fixed instead of making a new PR to power rise the VL

**Comment by coffeecoffeecoffee** [comment]
Vampire lords under this change have been able to slaughter their way through the entire town with relative impunity.

**Comment by wgtjunior743** [comment]
> > Vampire lords under this change have been able to slaughter their way through the entire town with relative impunity.
> 
> This is more of a symptom with how their stats scale & powers than an inherent problem with their design (Though there is many). I'll just put the weakness back on for VL. (even though they were doin' this before, and as said before, only dying to one-shot flail hits)
> 
> WW is keeping their anti-embed though, and its intentional silver does nothing to a T4 vamp lord due to shartzeth code.

It was not zeth who made any of the silver dagger or psycross effects, it was me spending hours on how to even do something in this mess code he created,  the psycross effect was working on blackstone, i always tested the stuff i coded.
The game has the original "funny effects" on these items but they were not working, i went and made these additions based on the silver dagger description.
Atleast my plan was that eventually silver would be buyable from imports or a very rare ore, but i won't be coding for a game with ERP.

**Comment by DeerJesus** [comment]
Just redo vampires to be closer to fulp bloodsuckers with only a limited amount spawning in town already, and then nonvampiric thralls. This "vampire lord" bullshit where the antagonist depends on one player who is half of the time extremely incompetent and dies instantly and the other half of the time the most robust motherfucksr you've ever seen, isn't working.

**Comment by Stagrawl** [comment]
> > > Vampire lords under this change have been able to slaughter their way through the entire town with relative impunity.
> > 
> > 
> > This is more of a symptom with how their stats scale & powers than an inherent problem with their design (Though there is many). I'll just put the weakness back on for VL. (even though they were doin' this before, and as said before, only dying to one-shot flail hits)
> > WW is keeping their anti-embed though, and its intentional silver does nothing to a T4 vamp lord due to shartzeth code.
> 
> It was not zeth who made any of the silver dagger or psycross effects, it was me spending hours on how to even do something in this mess code he created, the psycross effect was working on blackstone, i always tested the stuff i coded. The game had the original "funny effects" on these items but they were not working, i went and made these additions based on the silver dagger description. Atleast my plan was that eventually silver would be buyable from imports or a very rare ore, but i won't be coding for a game with ERP.
> 
> [Blackstone-SS13/BLACKSTONE#1155](https://github.com/Blackstone-SS13/BLACKSTONE/pull/1155)

aren’t you the guy who literally broke all of these?

**Comment by Stagrawl** [comment]
At one point silver used to actually stun. Bro took functioning code, made it nonfunctional and then declares he’s quitting from a project literally fucking no one invited him to?

The fuck?

**Comment by radarseas** [comment]
VL suffers bigger issues that probably need addressing more, namely its not worth thralling. They really, _really_ don't need buffing into maniac but better.

1: lesser vamps only get like, 800 vitae, it _drains 1 per second,_ you have if I estimated right 12 minutes to drink blood or get comatised by even the slightest bleeding. this is without disguise on top. This, does not help vampires that actually bother to RP, since you're on a very tight timer, against people that can pile up very fast to a kidnapping.

2: you're just tenfold stronger than your vampire spawn, you basically can't die if you keep your armor intact, regenerate off injuries and bat away. Especally with a polearm since you have very high speed stats, let alone strength.

3: disguises currently still have the telltale white eyes, which just means you get miracled even disguised, or just randomly miracled at all, which stops stealth vamps really, working. Especally when it just straight stunburns you through disguises, compared to churn undead which can be resisted.

4: vamp lord at full power doesn't subscribe to churn undead, your thralls do, by just doing it yourself you eliminate most of the church's counters for fighting actual non-lord vamps and deny them the gear off of vamps to arm on.

5: oh yeah, vamplord doesn't subscribe to the sun, anyway on full power. Your lesser vamps will just evaporate if they get miracled in the sun, you just regenerate the stun off in seconds.

**Comment by wgtjunior743** [comment]
> > > It was not zeth who made any of the silver dagger or psycross effects, it was me spending hours on how to even do something in this mess code he created, the psycross effect was working on blackstone, i always tested the stuff i coded. The game had the original "funny effects" on these items but they were not working, i went and made these additions based on the silver dagger description. Atleast my plan was that eventually silver would be buyable from imports or a very rare ore, but i won't be coding for a game with ERP.
> > > [Blackstone-SS13/BLACKSTONE#1155](https://github.com/Blackstone-SS13/BLACKSTONE/pull/1155)
> > 
> > 
> > aren’t you the guy who literally broke all of these?
> 
> ditto on this.
> 
> In this PR I had to fix several bugs that should have been fixed months ago on Blackstone, but ( as an example), there were several bugs left in because your coders forgot to add another subpath, for example, or even just doing proper typechecking, such as the silver issue, where all psycrosses were being counted as silver, even wooden ones, because you forgot to add another subpath to the /silver ending (I just moved it to /silver/I and it fixed the bug), so it was no longer treating all psycrosses as silver, which turned out to break Vampyres even more, because balancing an instant sleep spell around a very rare material that costs like 300 mammons from the Merchant is a terrible idea. Same with pierce-immune on verewolves. These are issues that should have been immediately smoothed out, you coming into here and instead of contributing actual useful information (past the fact it was not Zeth at fault); and instead flexing about how you coded basically nonfunctional content.
> 
> Thanks!
> 
> If you want more examples as a sidenote,
> 
> All powders can currently be crafted into dough, which is why salt tends to get eaten by the recipe (due to the way the subpath is checked). A lot of weapons have duplicate/lesser recipes but the exact same stats. E.G Lucerne is made out of one iron bar and a log, eagles beak is steel, they have the exact same stats but the Lucerne has MORE blade integrity (and intents). A majority of our crafting system is entirely fucked due to brainrotted changes made by Blackstone. A majority of our skills, and stats need debloating because of Blackstone. A majority of antags were only made more problematic to balance DUE to Blackstone, which is why PR's like this even exist.
> 
> Anyway, I can guarantee a majority of your content was not extensively tested. My PR got unmerged because a fraggoid got ahold of VL and immediately killed the entire server, which is possible without it, so it was decided that until a full rework is done, yeah no we'd rather VLord either die immediately to a miracle, or yknow, kill everything under their existing powers (thus giving us more impetus to rework them), but otherwise, everything in here worked perfectly fine and as intended.
> 
> You coming in here, to a project you have not contributed to (past legacy code which is now being removed and reworked), then going "Weelll I waaas going to do X but you're an ERP server" is in no way conducive.
> 
> Have a nice day.

Alright ,if blackstone was so broken and bad, why was the ENTIRE code base merged without any "balance" or questions about it , as such half of the top 10 contributors are from blackstone, the maint team did not picked the ones you could call "non broken" but literally control c + control v the code and ofcourse fixed some merging issues.
No idea about the subpath issue but i coded for blackstone but as i said before, in that game the silver psycross and the silver dagger was working i literally have a version on my pc that i can show the logs,
It is no way flexing, i don't even knew my code was being used in the ERP server and went to dig abit, i found about people not crediting my work, mixing my feelings with the ERP server, it truly made me abit mad.
The instant sleep is part of the vampire kit and besides the vamp lord or unless the vamp t4, it is hard to pull of as thrall but well, the PR was not about nerfing vamps but giving more tools to the inquisitor  or people who got some of his items.

**Comment by wgtjunior743** [comment]
> > > > Vampire lords under this change have been able to slaughter their way through the entire town with relative impunity.
> > > 
> > > 
> > > This is more of a symptom with how their stats scale & powers than an inherent problem with their design (Though there is many). I'll just put the weakness back on for VL. (even though they were doin' this before, and as said before, only dying to one-shot flail hits)
> > > WW is keeping their anti-embed though, and its intentional silver does nothing to a T4 vamp lord due to shartzeth code.
> > 
> > 
> > It was not zeth who made any of the silver dagger or psycross effects, it was me spending hours on how to even do something in this mess code he created, the psycross effect was working on blackstone, i always tested the stuff i coded. The game had the original "funny effects" on these items but they were not working, i went and made these additions based on the silver dagger description. Atleast my plan was that eventually silver would be buyable from imports or a very rare ore, but i won't be coding for a game with ERP.
> > [Blackstone-SS13/BLACKSTONE#1155](https://github.com/Blackstone-SS13/BLACKSTONE/pull/1155)
> 
> aren’t you the guy who literally broke all of these?

Since the first version of blackstone i got my hands of, the previous silver dagger or psycross interactions called the function "funny_attack_effects" that was not working, so i changed and made  use of two actually working functions to equip and interact with a mob and do actually funny effects.

**Pull request closed without merging**
