### PR TITLE
Alchemists of lvl 2 can see what reagents are in a container, and removes duplicate alchemist skill/other unused dupe skills

### PR DESCRIPTION
**Pull request by Slorbin**
image

lvl 2 alchemists can determine whats in a container

we also had a duplicate second alchemist skill (craft/alchemist) that did nothing compared to our regular alchemist skill (misc/alchemist) and some unfortunate roles had it

also removes the completely unused skills bombmaking and medicinecrafting (both were rolled into alchemy) and clothesmaking (rolled into sewing and weaving)

edit: also made it so alchemists of lvl 2 could see more detailed amounts (up to 1 decimal place) of what's in a container (since oz is units x 3 and it might be nice to know exactly how much you have for alchemy later)
image

### CODE REVIEW

**Comment by Stagrawl** [comment]
Always wanted to implement alchemy having this. Good job.

**Comment by DeerJesus** [comment]
fixed the merge conflicts :) should be working again

**Comment by DeerJesus** [comment]
> Should just be a part of the human's `/can_see_reagents()` proc. Also add an .Adjacent check, so the alchemist has to be next to the beaker

alright done

**Comment by TheFenix323** [comment]
The barber surgeon changes whould be reverting #424

**Comment by DeerJesus** [comment]
> The barber surgeon changes whould be reverting #424

No, there was a merge conflict and I fixed it. The barber surgeon changes are still there.

**Comment by DeerJesus** [comment]
> The barber surgeon changes whould be reverting #424

Wait yes it does. The git hook didn't do it very well. I'll fix that in a moment.

**Comment by DeerJesus** [comment]
> The barber surgeon changes whould be reverting #424

Revert undone

**Pull request merged**
