### PR TITLE
Milking and Saiga Fixes

### LINKED ISSUE #812: [BUG] Saiga kids become aggressive and untamed when growing into adult saiga
When saiga kids grow up, they have the behavior of wild saigas, but without the possibility of taming, since they immediately become aggressive.

Thus, it is impossible to breed saigas as mounts, but only for slaughter.

### PR DESCRIPTION
**Pull request by TheFenix323**
## About The Pull Request
Milking always worked in an odd manner, you needed to break away from the progress bar to milk the animal, now you need to wait for the progress bar to finish.
This also fixes Saigas breeding spawning aggressive Saigas instead of tamed ones

## Why It's Good For The Game
Fixes milking and Butchers getting killed by Saigas.
fixes #812

### CODE REVIEW

**Comment by MefAnneFeminene** [comment]
Milking.... 🤤

**Comment by Cyprex** [comment]
Rather than merge this I've isntead just rewritte thant smol proc. I'll PR it in like 8 hours or so.

**Comment by TheFenix323** [comment]
> Rather than merge this I've isntead just rewritte thant smol proc. I'll PR it in like 8 hours or so.

Need me to change anything from the PR?

**Comment by Cyprex** [comment]
Closing in favor of #964

**Comment by JohnnyJohnJohnson** [comment]
user was milked for this post

**Pull request closed without merging**
