### PR TITLE
Town and basin fixes and tweks

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request

Fixed all inside-wall objects i managed to find
Fixed, at least most, wall candles
River at west and south sewer side is now sewer again
Seamstress house gets same treatment as other houses- no full barrel of water and stove
Various tents and shaks lost their 'indoor' area and get the one from their surrounding
Double and treeple trees fixed where found
Town roofs gets roof area
Area north-east to the church gets proper outdoors area
Added shylock near smith and merchant
Merchant's goldface better positioned
No more place to grow crops at tavers- go ask farmers, idiot
Floor at tavern now looks better
Moved trees away from farm fields
Farm house now starts unlocked
Replaced manequiens at smithery for better spacing
Moved purity from outside baths- inside
Added well near small farmhouse west of town

### CODE REVIEW

**Comment by Nakalon** [comment]
Whats up with this?
image

Plus. The "seamster house" Isn't a house. I didn't make it in the image of random houses. I made it in the image of the smithery.
Which you can see has an Oven and a water barrel. (Together with a mug and crackers which I now notice are gone and aren't mentioned anywhere. I can only assume Mori forgot to replace them in #1202 with new food.)

If anything I think all houses SHOULD have this instead of making it the other way around.

Plus, why even remove the oven since most houses get a hearth?

**Comment by NikolayByondPlayer** [comment]
"River at west and south sewer side is now sewer again" 
But why? Making people be careful at that place is fun, no? 

"Floor at tavern now looks better" 
Tavern was made to be shittier with these floors because of Rockhill being a reck of a place 

Also let's keep some places darker and not put the lights in the shady alley behind the inn? We need some dark places for people to hide too.

Also you didn't write all changes in this PR I can see more in the map, can you adress all the changes in the future? By both writing about them and attaching screenshots.

**Comment by Heheniy** [comment]
one side of the river is literally a death sentance
image

it looks shittier not because of mossy tiles but because how mixed up all of tiles are
image

**Comment by Heheniy** [comment]
something fucked up again, temporar draft

**Comment by Heheniy** [comment]
guuuuh shit is fucked, will redo tomorrow

**Pull request closed without merging**
