### PR TITLE
Adds the Glaive as a New Polearm

### PR DESCRIPTION
**Pull request by Mortiz999**
## About The Pull Request

By unpopular demand, I'm back to <s>fuck up the meta again</s> bring more weapon variety.
Introducing the glaive: A light and nimble weapon for the humble polearm user.
It can't do much against armor, as it uses the sword's anti-armor stats, but it can swing far faster than any other polearm.
-Compared to the halberd, its almost entirely worse, but cheaper, and faster to swing.
-Compared to the billhook, it shares its defense and cost to smith, but is far far worse at fighting armor and stabbing.
As always, I would love to hear feedback on how to improve this.
Images attached below:
Screenshot_63
Screenshot_64

## Why It's Good For The Game

More polearm variety is always fun, and this creates a (slightly) lighter-weight weapon for those who can only barely use a spear. There was also a lack of an 'anti-unarmored' weapon in the polearm category, which this fixes. (A similar 'anti-unarmored' weapon would be the saber for swords.)

(Feel free to just delete this PR if it won't fit the server, I threw this together last night without thinking too hard.)

### CODE REVIEW

**Comment by pilotmans** [comment]
millions of mobs will die by my master glaivsmenship, may this be added to grenzlehoft spawn pool?

**Comment by john-pawson** [comment]
If you're trying to make it a light-weight or fast version of a polearm maybe give it the swift property? (aka `wbalance = 1`) I think it'd probably fit. Either way great PR my guy.

**Comment by Mortiz999** [comment]
1) I'll see if it fits in another PR, adding it to grenzles would be fun but outside this PR's scope.
2) I'll do a test on if swift over-tunes it, it already out-speeds every other polearm by swinging at the default sword speed.

**Comment by john-pawson** [comment]
> 2. I'll do a test on if swift over-tunes it, it already out-speeds every other polearm by swinging at the default sword speed.

But... all polearm attacks swing at the default speed... (Excluding the halberd cut and the eaglebeak smash)

**Comment by Mortiz999** [comment]
> > 2. I'll do a test on if swift over-tunes it, it already out-speeds every other polearm by swinging at the default sword speed.
> 
> But... all polearm attacks swing at the default speed... (Excluding the halberd cut and the eaglebeak smash)

1) You are very correct on that, the difference is that the glaive uses the sword cut instead of the halberd one.
2) Adding swift makes it a bit strong at foot sniping, making it just a saber that can hit feet. I do like disrupting the meta, but this would make unarmored feet a death sentence.

**Comment by Red-Honk** [comment]
I think you'll have to recode it once more because of this PR: https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1021.

**Comment by john-pawson** [comment]
> I think you'll have to recode it once more because of this PR: #1021.

The PR https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1021 only changes a few comments on the polearms file, it should be fine unless for some unexplained reason a merge conflict shows up. In which case it should be easy to fix.

**Comment by Mortiz999** [comment]
> > I think you'll have to recode it once more because of this PR: #1021.
> 
> The PR #1021 only changes a few comments on the polearms file, it should be fine unless for some unexplained reason a merge conflict shows up. In which case it should be easy to fix.

Checked in on the PR, the glaive seems to be unaffected, outside of using the new attack descriptors that were used.

**Comment by Cyprex** [comment]
DMI conflicts

**Comment by Mortiz999** [comment]
> DMI conflicts

I'm going to close and rework the pr on an updated branch, I'll put a new PR up soon.

**Pull request closed without merging**
