### PR TITLE
Removes the stunmace

### PR DESCRIPTION
**Pull request by Dedwolf**
## About The Pull Request

No this isn't a salt PR.
I've had a friend use the stunmace on me as a funny prank and I'm absolutely blown away with how long it takes you out of the fight. It's enough time that they can stow the mace and take out a hammer and just beat you to death. 

Fixes: https://github.com/Rotwood-Vale/Ratwood-Keep/issues/249

## Why It's Good For The Game

The stunmace does not add anything interesting to the game. Its entire gimmick is being a single click win button, I cannot find any reason for its existence.

### CODE REVIEW

**Comment by DeerJesus** [comment]
yeah we don't really NEED stunbatongs on the server - the master's rod is DEVASTATING as is

**Comment by CVSthePharmacy** [comment]
Mr president we need to close this pr, it's a nerf to players and a buff to the keep and antag. All antags except  revs and bandits have stun resist, they don't get taken out of the fight with them. Players can simply grab you to make you drop the stunmace if you hit them, as the charge transfers. The stunmace is ALREADY locked behind the secret tab which ONLY the merchant can buy, and apart from that you STILL need 300 mammon. The stunmace is only seen on average once every 7 rounds, I did the math. Once again, close this salt PR. -Armas.

**Comment by githubuser4141** [comment]
Just make it not work against armour, and NERF how much it does?

**Comment by CVSthePharmacy** [comment]
> Just make it not work against armour, and NERF how much it does?

me when the electric shock is blocked by metal??????????????????

**Comment by sirelgate** [comment]
Would you prefer to be beaten to death by a guard with a steel mace?

**Pull request closed without merging**
