### PR TITLE
fixes the description and restores purge to what it was

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
see title

## Why It's Good For The Game
Mori couldnt fix his own shit

### CODE REVIEW

**Comment by Nakalon** [comment]
Wanna see test evidence

**Comment by Gyrandola** [comment]
> Wanna see test evidence

this

**Comment by wow50000** [comment]
image
evidence it works however the target didnt need to be buckled to a bed, just near one
so yeah this spell is still hyper abuseable

**Comment by Nakalon** [comment]
> image evidence it works however the target didnt need to be buckled to a bed, just near one so yeah this spell is still hyper abuseable one of you might want to test that though but from what I can tell the code is running on current code

Silly man! The test was not for the code we have NOW, it was for the one you are PRing!!

**Comment by Gyrandola** [comment]
This PR is unclear to me. Reopen it with a clear description of what you are doing and WHY.

**Pull request closed without merging**
