### PR TITLE
Immense PSYDON BLESSINGS upon rockhill

### PR DESCRIPTION
**Pull request by Jackofashepard**
## About The Pull Request

Racism is back baby.
Lupe, vulf, moth and dracons are now tolerated. Only the purest in PSYDONS image remain in respected
Verminkin and kobolds are VERY SHUNNED. Both are rats at heart
RACISM level upped for bog master and nobles
CROWN purified as well
PSYDONS MERCY upon the half kins for they are at least half psydonian glory

## Why It's Good For The Game

Racism is slipping in rockhill. Reintroduces racism to many species!

### CODE REVIEW

**Comment by Jackofashepard** [comment]
PSYDON BLESS THIS HOLY PR

**Comment by Jackofashepard** [comment]
INQUISITOR. INSERT MORE POSITIONS FOR PURIFICATION HERE

**Comment by SixplyDev** [comment]
Holy fucking based. Yes PLEASE, the game is heavily lacking in the IC racism department and this should fix that thank fuck

**Comment by Hmeister-real** [comment]
This is actually so fucking based, as a Contributor who made the Zybantines and other popular PR's i approve of this 👍

**Comment by wow50000** [comment]
I will miss kobold churchling

**Comment by SixplyDev** [comment]
I don't understand why a single soul is disliking this. Frankly, I would like to hear from the community as to why they think that this is a bad PR. I think we're long overdue to add in more mechanical racism to fix some of the issues this server has with people bringing 21st century morals to be the paragons of acceptance and tolerance.

**Comment by K4rlox** [comment]
i doubt this PR will be merged unless the devs pull a TG maintainer move and merge a conterversial PR for the following reasons
1. this is a furry server
2. theres already a lot of furry royalty characters, this would make them unable to play their characters at all anymore
3. this PR could cause a lot of players to quit the server due to no longer being able to play characters they poured their hearts into

**Comment by SixplyDev** [comment]
> i doubt this PR will be merged unless the devs pull a TG maintainer move and merge a conterversial PR for the following reasons
> 
> 1. this is a furry server
> 2. theres already a lot of furry royalty characters, this would make them unable to play their characters at all anymore
> 3. this PR could cause a lot of players to quit the server due to no longer being able to play characters they poured their hearts into

People poured their heart into shunned characters but that doesn't make them any less shunned. I'm sorry but if you're unable to adapt your character to fit role restrictions, that's a player issue and not a mechanical one. We cannot accommodate and coddle everyone's preferences for how they want their characters to be. Something needs to be done regarding the lack of xenophobia and racism IC and I think this PR is a step in the right direction to address it.

**Comment by Coolgat3** [comment]
Personally if your furry hate disguised as "This should be good lore" gets merged I'm just leaving to hearthstone like many others will.

**Comment by SixplyDev** [comment]
For those who are confused and don't read the code, I'll leave this here. This is a basic overview of what the PR does (and makes it clearer) 

The PR does a few things:
- King is now forced to be a respected race
- Queen Consort is now forced to be a respected race
- Prince/Princess is now forced to be a respected race
- **Pilgrim** Noble is now forced to be a respected race
- Bog Master is now forced to be a tolerated or respected races
- Lupians, vulpkians, moths, and drakians are moved from respected to tolerated
- Half-kin are moved from tolerated to respected
- Respected races are solidified as humen, elf, dwarf, aasimar, and half-kin
- Kobold & Verminfolk moved to very shunned

**Comment by Coolgat3** [comment]
> For those who are confused and don't read the code, I'll leave this here. This is a basic overview of what the PR does (and makes it clearer)
> 
> The PR does a few things:
> 
> * King is now forced to be a respected race
> * Queen Consort is now forced to be a respected race
> * Prince/Princess is now forced to be a respected race
> * **Pilgrim** Noble is now forced to be a respected race
> * Bog Master is now forced to be a tolerated or respected races
> * Lupians, vulpkians, moths, and drakians are moved from respected to tolerated
> * Half-kin are moved from tolerated to respected
> * Respected races are solidified as humen, elf, dwarf, aasimar, and half-kin
> * Kobold & Verminfolk moved to very shunned

TL:DR
King, Queen, Prince, Pilgrim Nobles are locked to human-faced species only.

**Comment by K4rlox** [comment]
> > i doubt this PR will be merged unless the devs pull a TG maintainer move and merge a conterversial PR for the following reasons
> > 
> > 1. this is a furry server
> > 2. theres already a lot of furry royalty characters, this would make them unable to play their characters at all anymore
> > 3. this PR could cause a lot of players to quit the server due to no longer being able to play characters they poured their hearts into
> 
> People poured their heart into shunned characters but that doesn't make them any less shunned. I'm sorry but if you're unable to adapt your character to fit role restrictions, that's a player issue and not a mechanical one. We cannot accommodate and coddle everyone's preferences for how they want their characters to be. Something needs to be done regarding the lack of xenophobia and racism IC and I think this PR is a step in the right direction to address it.

1rm62num5wwc1

**Comment by Hmeister-real** [comment]
> Personally if your furry hate disguised as "This should be good lore" gets merged I'm just leaving to hearthstone like many others will.

i AM a furry, and i completely approve of this PR! Hooray for realism and higher RP standards!

**Comment by MefAnneFeminene** [comment]
Why is it the consensus that the **FURRY** server must have the **FURRIES** lower than humans?

I propose the opposite, removing non-furry races from being Respected.

**Comment by Coolgat3** [comment]
> Why is it the consensus that the **FURRY** server must have the **FURRIES** lower than humans?
> 
> I propose the opposite, removing non-furry races from being Respected.

Yeah in fact why don't we just do that. We will have racism, isn't that what this PR is about? To add more racism for the good of the server? This is an amazing suggestion.
In all honesty it's as dumbfuck as this PR and we all know this is just a good example for why this should never get merged. It could go both ways.

On another hand if the royal family being similiar to eachother is so important, why not make a rotation where the game informs people which species the royal family is going to be this round and people have to bend to it. It would be much better than whatever this joke of a PR is, because it wouldnt permamently cross out players of one species.

**Comment by Grisiuem** [comment]
This might help making the royal family appear to be more immersive. But I fail to understand how it will do anything to affect the level of racism in game. There has always been a lack of racism even against the worst shunned species like Drows or H-Orcs. You think preventing the one or two people who happens to play bogmaster or a Pilgrim noble as one of those species will somehow makes it better?  The lack of racism is  definitely more of a player issue and not a mechanical one. This PR will probably give more power to a few who wants to be racist as keep players, but leave most of the things unchanged. 

Also lore-wise, a part of this doesn’t makes sense, unless it’s established that none of the above-mentioned furry species has their own kingdoms/nations, are all following different religions, or are all living under human-like species’ occupation….They can absolutely just be nobilities.

**Comment by Alanii** [comment]
This PR will need more work. 

It would be better to soften the blow by just using and creating a new define for respected races. 

Then go from there. People will defend their furry races and the like to the death, regardless of this server having them or not.

It would make more sense for you to simply create this new define and tie to all kingdom nobility (let the pilgrim noble be disgusting creatures).

The lore is still and probably will never actually pop up. So we can't really dictate respected races in such a manner at this time. There is far too much confusion as to what a respected race is and what a tolerated race is, due to how the define for "respected races up" includes tolerated races.

It would be better to make this PR more of a simple
- Add define for respected_races only
- Added define for noble races

This way players can cry about how their race was originally only tolerated all along instead of respected.

**Comment by NikolayByondPlayer** [comment]
Good stuff

**Comment by Jackofashepard** [comment]
So while i did have a massive laugh reading all this i want to do some clarification.
In terms of restricting races this PR actually does very little. We used the TOLERATED UP race classification pretty much everywhere. The only races and roles that will be massively impacted here is the crown. There will basically not be any more furry/scaly/whatever crown people, all other roles are unaffected (aside from foreign nobles of course for consistency). 

The only other thing to look for is kobolds and vermin will definitely lost a few roles and of course bog master will now be back to its respected state.

PYSDON BLESS

**Comment by Useroth** [comment]
No more of these PRs until we start getting content for the other end of the tolerance spectrum that is only available to shunned races and the like.

**Comment by Hmeister-real** [comment]
this is bullshit. the RP quality is going down the drain and this would have made it so much better.

**Comment by Coolgat3** [comment]
> this is bullshit. the RP quality is going down the drain and this would have made it so much better.

leave server pls

**Comment by SixplyDev** [comment]
Genuine bullshit that this was closed. Something needs to be done about the fact that nobody shuns any shunned races anymore. Ratwood doesn't feel like a medieval fantasy world, it feels like medieval 2024 larp with the amount of tolerance and acceptance of everyone going on.

**Comment by Useroth** [comment]
Shunned races shouldn't have less content, they should have different content fitting their shunning, crimes, heresy and the like. We've got a slum district in the works and some plans for content in that direction. All you people can think of "yeah if we limit race X and Y from some content RP will improve so much" which is just shallow thinking.

**Comment by zakanater19** [comment]
lel

**Comment by SixplyDev** [comment]
> Shunned races shouldn't have less content, they should have different content fitting their shunning, crimes, heresy and the like. We've got a slum district in the works and some plans for content in that direction. All you people can think of "yeah if we limit race X and Y from some content RP will improve so much" which is just shallow thinking.

Something still needs to be done about the general environment of the game. Shunned races don't feel shunned in the slightest, the game very much feels like people injected 21st century morality into it.

**Pull request closed without merging**
