### PR TITLE
Prevents mantrap cheese

### PR DESCRIPTION
**Pull request by Dedwolf**
## About The Pull Request

~~Tunes down the mantrap stun duration to 2 seconds, down from 8 seconds.~~ Reset back to 8 second stun.
Prevents players putting armed mantraps inside bags and sacks. 

## Why It's Good For The Game

It should be armed prior to being deployed, prevents players carrying them around and throwing them at people or combat dropping them.

### CODE REVIEW

**Comment by Hmeister-real** [comment]
> ## About The Pull Request
> Tunes down the mantrap stun duration to 2 seconds, down from 8 seconds. Prevents players putting armed mantraps inside bags and sacks.
> 
> ## Why It's Good For The Game
> It should be armed prior to being deployed, prevents players carrying them around and throwing them at people or combat dropping them.

this makes them completely useless, you are having a MANtrap (made to catch HUMENS) clamp around your leg, digging into the flesh and fracturing the bone, 2 SECONDS is fucking RETARDED

**Comment by Heheniy** [comment]
> digging into the flesh and fracturing the bone

broken bone != 8 second standing still not being able to move even your arms

**Comment by Hmeister-real** [comment]
> > digging into the flesh and fracturing the bone
> 
> broken bone != 8 second standing still not being able to move even your arms

yes, you are fucking yelling and screaming in gutteral pain. Do you KNOW how painful it is to have your bones shatter and metal mantrap pins digging into your leg?

**Comment by radarseas** [comment]
leave the 8 second long stun, its nessessary, if anything, buff it to 12 seconds, you can literally disarm it with a rock by left-clicking it. Only lower it to 8 if they have leg armor.

if anything yes, remove the backpack and drop it technique but don't clown the thing into uselessness, its a trap, that's the whole point of it existing. make it worth using at least.

**Comment by RadiantFlash7** [comment]
I kind of agree with the others. Leave the stun. The weight class is fine enough of a change- though gigantic might be a bit salt pr-rd xD
Those things shouldn't be bagable when active.

That said- This does /not/ actually fix the issue. You set a weight class to a predefined version of the mantrap. You need to define it's weight class after a player arms it, and after its disarmed. Otherwise, roundstart mapped mantraps will be giant, but crafted ones will be tiny still.

**Comment by Hmeister-real** [comment]
> Okay stun time reset back to 8 seconds but FULL ON WARNING 8 seconds is enough to pull your helmet/neck armor off and just straight up kill you.

that was your reasoning for changing it? what?

**Comment by DelineFortune** [comment]
Another one PR that takes away tricky-not fair way to fight

**Comment by RadiantFlash7** [comment]
> Okay stun time reset back to 8 seconds but FULL ON WARNING 8 seconds is enough to pull your helmet/neck armor off and just straight up kill you.

This still doesn't fix the problem. You set the class to a premade one that starts on the map. People can make mantraps and put them armed in their bag still. You need to add lines of code at the arming section and disarmed section of the mantrap that changes it's size as well.

**Comment by RadiantFlash7** [comment]
> > > Okay stun time reset back to 8 seconds but FULL ON WARNING 8 seconds is enough to pull your helmet/neck armor off and just straight up kill you.
> > 
> > 
> > This still doesn't fix the problem. You set the class to a premade one that starts on the map. People can make mantraps and put them armed in their bag still. You need to add lines of code at the arming section and disarmed section of the mantrap that changes it's size as well.
> 
> i think this can be closed and he can make a proper fix for it.

Theres no point in closing this. it's the exact same thing, but 2 lines of code in differant parts of the same file.

**Pull request closed without merging**
