### PR TITLE
Remove all but one Purity machines, located in a crackden. Dramatically increases drug prices.

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Title.

image

## Why It's Good For The Game

Cheap, safe and readily available drugs are ruining the economy.
Drug machines in the keep, the town and the bog have turned Rockhill in the most progressive city in the continent.
NOURISH especially has rendered most foodmaking useless.

### CODE REVIEW

**Comment by Nakalon** [comment]
I love this I want this yes.

**Comment by 2PlainGhoul** [comment]
What a retarded fucking change

**Comment by Kepteyn** [comment]
NOURISH should probably just be removed, being as it exists to completely bypass the need to farm or engage in that economy, though this helps with it.

**Comment by Nakalon** [comment]
> What a dumb change

Literally the opinion of whoever abuses drugs to get stats

**Comment by 2PlainGhoul** [comment]
> > What a dumb change
> 
> Literally the opinion of whoever abuses drugs to get stats

I used them to buy smokes so my guy could actually be a smoker lol -- I havent even tried all the new stuff yet

**Comment by 2PlainGhoul** [comment]
Okay the PURITY is moved by why is there still a shylock?

**Comment by Nakalon** [comment]
> > > What a dumb change
> > 
> > 
> > Literally the opinion of whoever abuses drugs to get stats
> 
> I used them to buy smokes so my guy could actually be a smoker lol -- I havent even tried all the new stuff yet

The answer here would be to have another way of making zigs. Separate hard drugs from stuff like cigarets

**Comment by Keazra** [comment]
The box of zigs should be sold by the merchant, otherwise this is a neat change.

**Comment by DorfGuy1** [comment]
> > > > What a dumb change
> > > 
> > > 
> > > Literally the opinion of whoever abuses drugs to get stats
> > 
> > 
> > I used them to buy smokes so my guy could actually be a smoker lol -- I havent even tried all the new stuff yet
> 
> The answer here would be to have another way of making zigs. Separate hard drugs from stuff like cigarets

you can make cigs? 
Also just have a drug dealer role replace this all and get rid of Nourish. Solution done.

**Review by Nakalon — APPROVED** [review]

**Comment by Cleric2145** [comment]
I like it, except also one in the depths of the bath house. Like maybe in the sewer room. That way it steers people either towards sketchy isolation antag-town, or towards one of the most neglected yet atmospherically cool town buildings.

**Pull request merged**
