### PR TITLE
Garrison + Keep Role Tweaks

### PR DESCRIPTION
**Pull request by Stagrawl**
Removes Knights + Squires, toned down Garrison Numbers.

### CODE REVIEW

**Comment by Stagrawl** [comment]
> removes knights "Let's just give this a try honestly"
> removes squires "Could be made into something else later"
> No description, misleading commits, completely unrelated title. Come on Sembia fucking hell, do you not see the issue here?

People who need to review this are capable of doing so.

**Comment by Jaaackx** [comment]
Hiding the changes you're trying to make because you know they're going to be insanely unpopular is a massively shit move, and the PR should be closed.

**Comment by Hmeister-real** [comment]
Im personally for the knight removal, not so much the squire one, but im wholey against the presentation and think the PR should be closed because its a dick move just not explaining and trying to conceal changes. This is an open source codebase, other peoples opinions and ideas are super fucking important and the fact you are misleading people who aren't code smart is just you being a massive prick so you don't need to argue your points

**Comment by Stagrawl** [comment]
Fine. I’m not doing the arguing shit, although obviously you’re all free to argue away.

**Comment by Stagrawl** [comment]
Closed in favour of rolebans, garrison still needs adjusting but whatever. Slop for another time.

**Pull request closed without merging**
