### PR TITLE
Deep caves expand

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Expandes deep caves and removes some forgotten cave area in the middle of deep caves
image

### CODE REVIEW

**Comment by zakanater19** [comment]
is the forgotten cave area middle left Z1? cause that's supposed to be a way up into the underground lake area, it's why i left it in

**Comment by Nakalon** [comment]
> is the forgotten cave area middle left Z1? cause that's supposed to be a way up into the underground lake area, it's why i left it in 

I'm not at all surprised the author failed to understand why something in the map was the way it was...

**Comment by Heheniy** [comment]
here are areas of z1 on z2
image
there is no template or logic that that leftover area follows so i see no reason to keep it

**Comment by zakanater19** [comment]
this is the gap thing i was talking about, you can see the dark green tiles are air leading down/up into the z1 cavern

Screenshot 2024-10-29 174435

**Comment by Heheniy** [comment]
cant see it anywhere else, thats the reason
image

**Comment by zakanater19** [comment]
The others are not guaranteed to be clear, but that area is since it's the only one past the bog, but yeah should be big enough not to be closed off

**Comment by Heheniy** [comment]
it is 30% for a turf to be a wall, none of the holls can be fully walled 
image

**Comment by Nakalon** [comment]
This would be much easier if the "Why it's good for the game" wasn't empty and the only argument for this change wasn't "But everything should be the same everywhere".

**Pull request closed without merging**
