### PR TITLE
Removes random auto spitting

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Random auto spitting of item you are holding in mouth removed
It is fucking annoying when you WANT to hold something in your mouth but game just goes nuh-uh, spit

### CODE REVIEW

**Comment by Hmeister-real** [comment]
> ## About The Pull Request
> Random auto spitting of item you are holding in mouth removed It is fucking annoying when you WANT to hold something in your mouth but game just goes nuh-uh, spit
> 
> ## Why It's Good For The Game

It's there so you don't get a free slot to hold stuff, and you can't just carry a knife in your mouth 24/7

**Comment by Hmeister-real** [comment]
Also rather than removing it, give items that you feel shouldn't drop out of your mouth the same function as the cloth gag, and give reasoning for each. Would make the PR seem less like cope

**Comment by Squird5** [comment]
> Also rather than removing it, give items that you feel shouldn't drop out of your mouth the same function as the cloth gag, and give reasoning for each. Would make the PR seem less like cope

They already do. If you have an item in your mouth, you can not talk. That's how the cloth gag works to begin with. If you have a fiber bundle in your mouth, you can't cast spells because your mouth is obstructed. The pipe and cigs I think are the exception to that.

**Comment by Hmeister-real** [comment]
> > Also rather than removing it, give items that you feel shouldn't drop out of your mouth the same function as the cloth gag, and give reasoning for each. Would make the PR seem less like cope
> 
> They already do. If you have an item in your mouth, you can not talk. That's how the cloth gag works to begin with. If you have a fiber bundle in your mouth, you can't cast spells because your mouth is obstructed. The pipe and cigs I think are the exception to that.

i meant as in, don't drop out of your mouth. I know everything gags you aside from smokes, but i meant that the creator of this PR should make certain items stay inside the mouth with reason rather than completely removing the function

**Comment by Useroth** [comment]
It's intentional so that it's not a free slot, like mentioned in one of the comments above.
However, if you want, you could give it a minimal time before you start rolling for autospit, ie. 30-60 sec or so, so that you can use it in a pinch during work but not to carry stuff around reliably.

**Comment by Koteshkin** [comment]
How do you remove a roach then? It seems to dont have a sprite in mouth and you cant really get it out unless spit automaticly.

**Pull request closed without merging**
