### PR TITLE
Bank Revert

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

An overcomplication of an already delicate system that created a lot of bugs and weird economic phenomena.

### CODE REVIEW

**Comment by Nakalon** [comment]
What about #1210?
I think this is only one part of the system which was introduced in that PR.

**Comment by Gyrandola** [comment]
> What about #1210? I think this is only one part of the system which was introduced in that PR.

that has also been reverted, see second commit. I know its weird the diff is minimal.

**Comment by Nakalon** [comment]
> > What about #1210? I think this is only one part of the system which was introduced in that PR.
> 
> that has also been reverted, see second commit. I know its weird the diff is minimal. You can check manually.

Yessss fantastic!
This was causing a lot of trouble!

**Comment by Heheniy** [comment]
> lot of bugs and weird economic phenomena.

can you elaborate?

**Pull request merged**
