### PR TITLE
Female Rulers of Heartfelt, Male noble consorts of heartfelt

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request
Renames Lady of heartfelt to Noble Consort of heartfelt.
Renames Lord of heartfelt to Ruler of heartfelt.
gives both slightly seperate clothing based on their sex

## Why It's Good For The Game
Heartfelt is apparently a barony, a relatively tiny location, compared the large duchy. Locking it's ruler to a baron/lord of heartfelt instead of a baroness/lady, and similarly, preventing the lady of heartfelt from being male is pretty lame. I want to be able to have a male consort as a baroness, Or even as a baron, damn you.

### CODE REVIEW

**Comment by Gyrandola** [comment]
I understand the gender thing, but the new titles are extraordinarily generic and banal.

**Comment by Nakalon** [comment]
I have no feelings towards this

**Comment by 2PlainGhoul** [comment]
> I understand the sex thing, but the new titles are extraordinarily generic and banal.
You mean like everything you come out with?

**Comment by Nakalon** [comment]
> > I understand the sex thing, but the new titles are extraordinarily generic and banal.
> > You mean like everything you come out with?

Thats really uncessarry

**Comment by RadiantFlash7** [comment]
> I understand the sex thing, but the new titles are extraordinarily generic and banal.

It was the easiest way to support the differant sexes being pickable. Plus, theres no real good name to give whoevers married to the lord/ruler of heartfelt. If it's not always garunteed to be female, lady doesn't work.

**Comment by Hmeister-real** [comment]
> > I understand the sex thing, but the new titles are extraordinarily generic and banal.
> 
> It was the easiest way to support the differant sexes being pickable. Plus, theres no real good name to give whoevers married to the lord/ruler of heartfelt. If it's not always garunteed to be female, lady doesn't work. If you've got a suggestion on a better name, I'm happy to hear it.

why does it have to support different sexes? There is absolutely 0 reason for it other than "equality" which is a stupid argument for this server and this
> I want to be able to have a male consort as a baroness, Or even as a baron, damn you.
Is not it

**Comment by RadiantFlash7** [comment]
> > > I understand the sex thing, but the new titles are extraordinarily generic and banal.
> > 
> > 
> > It was the easiest way to support the differant sexes being pickable. Plus, theres no real good name to give whoevers married to the lord/ruler of heartfelt. If it's not always garunteed to be female, lady doesn't work. If you've got a suggestion on a better name, I'm happy to hear it.
> 
> why does it have to support different sexes? There is absolutely 0 reason for it other than "equality" which is a stupid argument for this server and this
> 
> > I want to be able to have a male consort as a baroness, Or even as a baron, damn you.
> 
> Is not it

Because why shouldn't it? It's not an 'equality' reason. There was plenty of times in history a baroness was in charge of a barony. Its litterally one of the lowest 'land-zoning' lands in feudalism. It's so players can be a baroness. or vice versa with their consort.  What are you losing with allowing it? The title of lord? Lord isn't even really an accurate title for a barony in the first place, it's rather grand.

**Comment by BlueMemesauce** [comment]
that is true but it's not really worth the cost of them having a stupid name

also I think this means they can be gay now which is historically inaccurate

**Comment by RadiantFlash7** [comment]
> that is true but it's not really worth the cost of them having a stupid name
> 
> also I think this means they can be gay now which is historically inaccurate

Noble Consort isn't really that stupid, considering- thats what people are. Flat out 'ruler' isn't a great title, I'll grand you that. I'm looking at adjusting it to be baron/baroness depending on sex atm. Should be doable with a bit more coding. 

It does mean they could be gay, but the church of ten currently allows gay marriage. More or less a nonissue there.

**Comment by Gyrandola** [comment]
Closing this for the sole reason you can get two women or two men which is funny

**Pull request closed without merging**
