### PR TITLE
Court Mage can no longer be Zizoid

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
I actually missed that and merged it, I only wanted adventurer mages to get this

### CODE REVIEW

**Comment by DeerJesus** [comment]
Why shouldn't a court mage be zizoid?

**Comment by Elli-Skala** [comment]
Why It's Good For The Game

**Comment by Gr33d-y** [comment]
> Why shouldn't a court mage be zizoid?

A lot of trusted roles in the keep can't be inhumen, it only makes sense the court mage can't be inhumen as well. Knights can't be, the phys can't be, the captain can't be. This was the outlier.

**Comment by radarseas** [comment]
court mage is working off the king's paycheck for their research... its one of the few roles which does make sense, to be a zizolite power hungry megalomaniac that worships a god that wholeheartly approves of power over reason. Especally with the entire court to hide behind this and their funding.

I don't think we should be axing potental RP fronts that make sense and bring interesting conflict into the court, especally ones that have some mechanical backing to base more RP off of, like the inquisitor.

**Comment by Useroth** [comment]
I think this should stay unless people are massive shitters

**Pull request closed without merging**
