### PR TITLE
Soilson Farm, Butcher, and Village Elder Remap & Rebalance.

### PR DESCRIPTION
**Pull request by KKLZ4**
## About The Pull Request

This PR is a general remapping and minor touch-up/slight buffing of the Soilsons, Butcher, and Village Elder.

In terms of mapping, the three buildings have now been turned into a miniature village, which has taken the place of the Bog Church. The Bog Church has now been moved over to where the Farm originally was and was given some flowers and a well; hopefully, this will make people utilize it more instead of being a forgotten ERP den in the corner of the map. This new 'village' area, now has three seperate bad omen spawnpoints. Two within the village, and one just outside it on the bridge; which should encourage the players to invest their hard-earned mammons in self-defense equipment or mercenaries to deal with the inevitable goblin portals.

The mini village features three brand-new buildings, which have been improved and touched upon. The soilsons now get proper key-locked doors, tables outside, lose their 3 axes and gain 3 pitchforks instead, and the building is made just a tiny bit nicer and larger. The soilsons also get a proper oven and hearth, along with a mini-cellar for storing/hiding their goods in. The Butcher's building no longer gets an underground dungeon, but instead is now a two-story barn, with their loft bedroom hanging above the cows. The hunting knife has been removed as a map spawn in the building, and the animals pens are now properly separated, so the saigas should no longer murder all the butcher's animals when they inevitably get janky and aggro. The Village Elder's house has been touched up, and some minor issues have been fixed, such as the Elder's mini-armory now spawning with an actual quiver for the bow he's always had, along with getting a peasant warflail--- That, hilariously, most peasant roles can't use to due to the absurd STR requirement. The Elder also gains a miniature, publicly-viewable prison cell and rope to serve as a temporary holding cell. No longer will the soilsons have to bury people alive, or just straight up resort to full-killing people because there's nowhere to put them! This new village also gets proper lever and winch-operated gates! Both the soilsons and the butcher get a Peddler outside the village that they can stock up with goods for sale to the public!

Soilsons now spawn with keys on their belts, and go from +0 to +2 END, which should compensate for how horrifically stamina-intensive farming has become with the rework done a little bit ago. They also now have Novice Reading, which will allow them to use their new Peddler. Soilsons have gone from Apprentice to Novice in Bows, and Novice to Apprentice in Polearms. Soilsons also went from 0 Athletics to Expert Athletics. This should help further bridge the gap between druids & soilsons, and also help deal with the cripplingly-high stamina drain of the new farming system.

Butcher now spawns with a hunting knife on his belt to compensate for the loss of his map-spawn hunting life. He is also brought up from +1 to +2 STR, making him the only person in the village capable of (semi-consistently) using the Elder's peasant warflail (provided their race/gender doesn't give them a - to STR). Butcher now also spawns with Apprentice in Whips/Flails, since that will allow him to make active use of leather whips he can craft, along with the peasant warflail. Butchers went from 0 Athletics to Expert Athletics. The role desperately needs buffs in general.

The Village Elder now spawns with 1 level in Fishing to use the fishing rod his house now spawns with. No other changes.

As a minor note, I've organized the skill lists for each of the roles. They're properly organized as Combat > Craft > Labor > Misc. This pleases my eyes.

## Why It's Good For The Game

The farm/butchery in its current state is just an absolute mess of abysmal dogshit. It's too exposed, undefended (Despite, supposedly, having 11 slots dedicated to protecting it who gather around a building literally 5 tiles next to it, the Bog Garrison typically do not protect the farm), and has tons of bizarre mapping issues, like how the butcher's saigas routinely slaughter the goats at the slightest provocation, or how the cowpen is just a bitch to get inside of sometimes. Many rounds, I spend a good 30-40 minutes at roundstart dedicated to just trying to secure the farm so it isn't immediately robbed of all its tools by iron-hungry adventurers. Imagine if the Weaponsmith/Armor/Mason had to build their entire shop at roundstart 'lest people sprint in and just start taking shit. It's such an absolutely miserable experience. Soilson and Butcher both as a role is unfortunately dwarfed by the uber-powerful Druid role, who can basically out-farm them with ease and on top of that get powerful combat and support spells, with neither Soilson nor Butcher getting anything to compensate. Now, they have slightly higher base stats and a few extra skills to compensate for the Druid's magical abilities. In my opinion- soilsons and butchers are still a LONG way behind Druids and will likely need more buffs, but they've atleast closed the gap a TINY amount.

The Village Elder technically isn't *bad*, but by its design being so far from the farm in the current map, a lot of Elders might not immediately realize that they're actually the ones in charge of the farm, and because there's no defined 'village area', it's hard for them to really exercise any sort of authority since there's no strictly-defined 'village' for them to be the Elder of, that the bogguard can't immediately sprint in and go "shut the fuck up old man" unless someone means to claim that the Elder is actually in charge of the entire Bog-town area, which- good luck enforcing that in code!

In my opinion, this also gives the Peasant Rebel antag a potential base of operations. Somewhere where they can potentially organize and stage an uprising from, given that it's (somewhat self-sufficient) and not within immediate earshot of our 40 fucking guard slots.

Farm layer1
farm layer2
farm layer3

### CODE REVIEW

**Comment by KKLZ4** [comment]
During this remap, I was considering moving the Veteran out of the Manor and reflavoring him as a 'retired career soldier' whose been given a little tract hut and tract of land in the village to retire in. He'd functionally serve as the village's single dedicated guard alongside the Village Elder who can kinda do guard stuff (even if his stats are CRIPPLINGLY BAD) and would potentially also be able to teach the peasants how to fight in the event they need to defend themselves given the Veteran actually has high enough combat skills to train the peasants up with. Unfortunately, despite asking around, I didn't receive any opinions or thoughts on this sort of change, and did not go through with it.

If shuffling the Veteran out of the manor (woo one less uber-powerful combat role dedicated solely to the manor and running out to validhunt!!!) interests you, please let me know so I can actually go forwards with it!

**Comment by Keazra** [comment]
What is the.. maze building in the lower left of the last image supposed to be?

**Comment by KKLZ4** [comment]
> What is the.. maze building in the lower left of the last image supposed to be?

Just a dark, musty attic. It's something I really liked in Stonekeep's farmhouse that I felt like would be nice to take a crack at. It'd also give the area just a tiny bit more z-level variety.

**Comment by Kepteyn** [comment]
It looks nice! The Attic maze is a fun idea, but it looks too barren in that screenshot. Maybe add some cobwebs, rats, and a couple chest of miscellaneous items that might reasonably be in the attic of a farmhouse (spades, old rags and shirts, a couple buckets, a loose copper or two, that sort of thing) to give it a bit of life?

**Comment by Frienderanian** [comment]
No goats for the Butcher? Where will he get fur? :( I'd almost somehow put the buildings even closer together if possible! Could you maybe include making the butchers Skin crafting skill higher too? It's so strange, he's the role that primarily interacts with hides and furs yet doesn't seem that good at it? Lol I hope this will encourage people to have fun village roleplays and be a tight knit community like Bog players are!

**Comment by EzekyalLegit** [comment]
It seems to me the village is way too far from traffic, like maybe it should be moved north next to the bog garrison? Being way down in that corner is a bit of a "nobody hears you scream" scenario. The mercs coming from the bog likely will never visit there to be hired too.

**Comment by EzekyalLegit** [comment]
> Can you throw some garlic and onion and plump helmet mushroom seeds somewhere in the soilson's building thanks

if so I think these should be added to the stockpile, seeing as usually soilsons don't even grow the westleach and oats they start with since neither is on the stockpile and anything not bolted down gets stolen.

**Comment by KKLZ4** [comment]
> No goats for the Butcher? Where will he get fur? :( I'd almost somehow put the buildings even closer together if possible! Could you maybe include making the butchers Skin crafting skill higher too? It's so strange, he's the role that primarily interacts with hides and furs yet doesn't seem that good at it? Lol I hope this will encourage people to have fun village roleplays and be a tight knit community like Bog players are!

The Butcher does actually get goats! They're in the little animal pen on the east side of the butcher's barn. As for Skincrafting, normally, I'd agree with you- but every single skincraft recipe has a difficulty of 0, meaning you only need Novice Skincrafting or 11+ Int and no Skincrafting to make every single recipe.

If I were to buff the butcher's skincraft level, I'd also have to add varying difficulties to the skincrafting recipes... But frankly, the problem we have right now is that basically only 3-4 items are consistent sellers. The Whip, Satchel/Backpack, and Saddle. Nobody ever buys leather armor apart from the soilsons, and even then- it requires significantly more effort, time to produce, and resource cost for all the hide you need for a full set of leather armor compared to a full set of mid-tier chainmail armor, while providing objectively worse protection. Leather armor just in general REALLY sucks especially considering how many combat roles have plate or even chainmail training.

My only real idea for improving leather armor would be to make chainmail/low-tier iron give players a slight speed penalty, high-tier iron/low-tier steel a moderate speed penalty, and steel full plate would give a big speed penalty in order to differentiate leather armor beyond solely "You can sleep in it."

**Comment by KKLZ4** [comment]
> It seems to me the village is way too far from traffic, like maybe it should be moved north next to the bog garrison? Being way down in that corner is a bit of a "nobody hears you scream" scenario. The mercs coming from the bog likely will never visit there to be hired too.

The thing is, this is already an issue, and the farmhouse's walls in the current map are like 5 tiles away from the bog gate. Guards and mercenaries do not come to defend the place, because the pay is dogshit and only comes in an hour when the farm's finally up and running. Guarding the farm is boring as sin since you'll really only have to fight maybe one or two people, and the rest of your round is literally standing doing nothing because you have no farming/crafting/sewing/carpentry skill to be of use. Yeah, you might have to fight off the manor if the manor tries something stupid like attacking the farm, but by that point you're basically just dead.

The other issue we have (Or rather, the Inn has) is that once people find out the soilsons are giving away free/cheap food and drink, the Inn suddenly has no customers apart from people sitting at the bar trying to get ERP. The Farm should be people's /last/ choice for sustenance, because there are 3 different places whose entire objective is to give out/sell food. The Inn, the Manor Kitchen, and the Church. The problem with the soilsons is because they're in such a high-traffic area that nearly 50% of the server passes by currently, nothing's stopping random whoevers from stopping by and going "SOILSONS I WANT FUUUD" and then buying it for dirt cheap instead of first trying to patronize the Inn, Church, or Manor Kitchen.

**Comment by KKLZ4** [comment]
Latest commits fix a some direction errors on a few railings, along with a map error where a duplicate southern boggate spawned in the boggate stable walls. Also, the invisible table in the tavern has now been made visible.

**Comment by challade** [comment]
Wow, soilsons really did get a garrison fort to occupy. I really don't like the lever gate on the left though, that one seems to powergamey and unnecessary, similar to the meta strategy that was building palisades within the first 5 minutes of the game because soilysons didn't like asking the bog for help. 
I'm gonna keep it real, keeping soilsons away from everything seems a bit... boring. Part of the fun from a non soilson is harassing the peasantry, I understand that there have to be limitations, however that limitation was the bog guards, and that they fail is not everyone else's fault but the fault of lack of communication. You don't hide the keep away even further because the men at arms suck, that's a roleplay issue. 

My suggestion would be to keep these buildings but in the place they already were, next to the river, and between town and the gate, they are nice buildings, but it's really on boggies to guard it, not for mappers to encapsulate themselves.

**Comment by KKLZ4** [comment]
> Wow, soilsons really did get a garrison fort to occupy. I really don't like the lever gate on the left though, that one seems to powergamey and unnecessary, similar to the meta strategy that was building palisades within the first 5 minutes of the game because soilysons didn't like asking the bog for help. I'm gonna keep it real, keeping soilsons away from everything seems a bit... boring. Part of the fun from a non soilson is harassing the peasantry, I understand that there have to be limitations, however that limitation was the bog guards, and that they fail is not everyone else's fault but the fault of lack of communication. You don't hide the keep away even further because the men at arms suck, that's a roleplay issue.
> 
> My suggestion would be to keep these buildings but in the place they already were, next to the river, and between town and the gate, they are nice buildings, but it's really on boggies to guard it, not for mappers to encapsulate themselves.

Once again, it's not a roleplay issue, it's a "Guarding the farm fucking sucks because there's nothing to do except fight off the 1, maybe 2 shitstirrers that actually do come to the farm that the soilsons can't handle in an entire round and the roleplay is minimal because there's too much mechanics happening for the soilsons to offer you lots of interesting roleplay."

I had this exact discussion on Stonekeep. You can't convince people to guard the farm for 3 hours because there's literally nothing to do as a combat role in the farm for a huge majority of those 3 hours when you compare it to... Guarding the manor (There's almost always someone bumming around for roleplay or some dumb gimmick to get involved in) or joining the bogguard to go validhunt antags (combat fun!!!) The bog gate was 5 tiles away from the farm, and STILL it was a nightmare to actually get a bog guard to sit down and guard the farm for more than maybe 15-20 minutes before they fucked off out of sheer boredom.

**Comment by CalamaBanana** [comment]
Some thoughts:
- The farming area needs to be closer to that gate. Right now, if the gate is closed, there is no way for outsiders to be heard inside, considering the field is where the soilsons most likely linger. You can't even see if someone is working the farm from the outside. This should be changed. By all hate for visitors, they should still be able to interact with those inside.

- The butcher needs some privacy somewhere, at least in his bedroom His entire place can be looked into from the outside.

- There is a stray hermes in the middle of the trees. Was that intentional? 
image

Overall, I like the hacienda vibe it gives off, though.

**Comment by DorfGuy1** [comment]
> Wow, soilsons really did get a garrison fort to occupy. I really don't like the lever gate on the left though, that one seems to powergamey and unnecessary, similar to the meta strategy that was building palisades within the first 5 minutes of the game because soilysons didn't like asking the bog for help. I'm gonna keep it real, keeping soilsons away from everything seems a bit... boring. Part of the fun from a non soilson is harassing the peasantry, I understand that there have to be limitations, however that limitation was the bog guards, and that they fail is not everyone else's fault but the fault of lack of communication. You don't hide the keep away even further because the men at arms suck, that's a roleplay issue.
> 
> My suggestion would be to keep these buildings but in the place they already were, next to the river, and between town and the gate, they are nice buildings, but it's really on boggies to guard it, not for mappers to encapsulate themselves.

palasades a meta strat? Because of boggys? Nah, it's cause of people stealing stuff. 
Anyway, the whole thing about it being so far away is totally valid. I wish we could just...move it back to where it was.

**Comment by DorfGuy1** [comment]
Maybe move it back to where it used to be, and add a bog tavern like that one PR did.

**Comment by Genevesh** [comment]
I get the farm needs protection, but I think the stuff they can make themselves, aka fences and lockable doors is JUST fine enough; What I mean is a fucking LEVER GATE is an overkill, it's like they get a whole ass fortress to themselves that's arguably defended just as well as the keep.

I'd tone it down a little bit; They already have a narrow bridge, just close it off with some fences and doors, you don't need to go out of your way to make the farm a future base for every antag possible.

**Comment by Useroth** [comment]
We can make some changes in following PRs

**Pull request merged**
