### PR TITLE
Lets Vampyres FUCK

### PR DESCRIPTION
**Pull request by Kevak**
## About The Pull Request

This lets vampires fuck, orgasm, be erect, and so on. It's shrimply that shrimple.

## Why It's Good For The Game

Kitty wants hot vampire sex while being nibbled on. Also vampires operate on blood and dicks are inflated by blood. I see no reason they could not simply will their blood to a specific location in their body and thus inflate their dicks if they are somehow able to use their blood to mend their wounds. 

Note for vampires: You do still need to gather blood, the timer does not cease just because thee be fuckin. Take care to not run dry of vitae whilst fucking people. It's on your hides if you fuck yourselves dry.

## Proof Of Testing

Screenshot 2024-11-30 203401

### CODE REVIEW

**Comment by Kevak** [comment]
> not unless they cum ash

They are full of blood. Not full of ash. I could maybe make them cum blood tho.

**Comment by Hmeister-real** [comment]
One of becoming a vamps most impactful flaws is being limp dicked. If you want hot vamp sex, you can have hot vamp sex but the vamp will simply just not cum, likewise with female vamps, but it's still possible

**Comment by Gyrandola** [comment]
universally unacclaimed change.

#NeverGoon

**Comment by Kevak** [comment]
Had to try eheh

**Pull request closed without merging**
