### PR TITLE
you can now aggressively grab and bite the head off a seelie through the same method in the previous pr

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

#1793 same as this but decap instead of gib

## Why It's Good For The Game

still want the graggarite bite seelie interaction but a gib proved a little too harsh

### CODE REVIEW

**Comment by DeerJesus** [comment]
not sure how to turn this into a draft, i meant to open it as a draft as a reminder to work on it later

**Comment by TheFenix323** [comment]
> not sure how to turn this into a draft, i meant to open it as a draft as a reminder to work on it later. whatever ill just finish it and test it now

image

**Comment by DeerJesus** [comment]
image
 mm hehe tasty

**Review by Gyrandola — APPROVED** [review]

**Comment by Uweinee** [comment]
Cool another vore pr in disguise.

**Comment by SociableStream** [comment]
What the actual fuck?

**Pull request merged**
