### PR TITLE
Change the health potions recipe 

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

Beforehand it was designed to be do-able with the blackstone fishing rework, however on Ratwood, the clownfish is simply unobtainable. New one is, 1 bottle, 1 ash, 1 berry, 1 mince, 1 leech

## Why It's Good For The Game

unobtainable recipe edging you is bad

only the HIGHEST quality video i could make

[alchemy test.webm](https://github.com/user-attachments/assets/17f62b2a-f389-4ff6-bd2d-fe74e283d41f)

### CODE REVIEW

**Comment by Colfer1** [comment]
> "the clownfish is simply unobtainable."

I've gotten it before by fishing in clear waters. Is it some special kind of clownfish? Because they are obtainable. Unless I just rolled really high on like a 0.0003% spawn rate.

**Comment by Hmeister-real** [comment]
> > "the clownfish is simply unobtainable."
> 
> I've gotten it before by fishing in clear waters. Is it some special kind of clownfish? Because they are obtainable. Unless I just rolled really high on like a 0.0003% spawn rate.

Here, or on blackstone?? In the code it isnt obtainable

**Comment by Colfer1** [comment]
> Here, or on blackstone?? In the code it isnt obtainable

I collected it here. It is obtainable here, I am 100% certain of it. Fishing in clear river water gives you clown fish, this is certain to me.

**Comment by Hmeister-real** [comment]
> > Here, or on blackstone?? In the code it isnt obtainable
> 
> I collected it here. It is obtainable here, I am 100% certain of it. Fishing in clear river water gives you clown fish, this is certain to me.

what bait??? in the bait code the baits only catch carp, eels and Anglers?? maybe its in the turf code...

**Comment by Hmeister-real** [comment]
Either way clownfish is far too rare to be acceptible to use for a /SINGLE/ health potion

**Comment by Hmeister-real** [comment]
Clownfish is so rare, and so obscure to get, that ti's just not worth peoples time. Whats the point of grinding for a grub, then grinding for a clownfish, simply relying on shit RNG to get a single health potion when you could just chop lumber, stockpile lumber, and then buy a health potion significantly faster and more time efficiently? This allows people to invest in the ingredients, and then get rewarded for getting the ingredients since they are all able to be gathered sustainably by getting health potions. I simply dont agree with the idea of though that a fish, that is reliant on two extremely difficult RNG rolls to even get, is fair to be an ingredient used for a potion so easily obtainable by other means. When things like strength potions get added, the clownfish would be great to reuse for a significantly stronger and rarer potion, not a potion that you can literally just buy.

**Comment by Hmeister-real** [comment]
> Dont base off changes off of issues that are to be addressed

what??? I made the original Chemistry PR with the intention of it being merged alongside the fishing reword, which it ISN'T here on Ratwood. So its ltierally, and outdated recipe that i put off fixing for a while...
https://github.com/Blackstone-SS13/BLACKSTONE/pull/1310

**Comment by Hmeister-real** [comment]
>Make clownfish easier to get

It's the rarest fish for a reason, that makes it pointless. We already have a rare fish, the Angler fish. The clownfish is meant to be the end all be all of Fishing, not just another rare fish, especially since the potion isn't nearly as rare

**Comment by Hmeister-real** [comment]
> > > Make clownfish easier to get
> > 
> > 
> > It's the rarest fish for a reason, that makes it pointless. We already have a rare fish, the Angler fish. The clownfish is meant to be the end all be all of Fishing, not just another rare fish, especially since the potion isn't nearly as rare
> 
> If it's supposed to be the end of be all then why was it supposed to be common in the new fishing. I dont understand the intent

no, new fishing made it bareable but hard to get, old fishing makes it ~impossible~. 0.0005 chance or something with the chance for maggot+fishing. It's stupid to make it THAT hard to get, i can't repeat myself more.

**Comment by Hmeister-real** [comment]
> So what's wrong with making it more bareable to get instead, just like I suggested?

because it's meant to be a very very rare fish, supposed to be a show piece and used for a much more rare potion than health.

**Comment by Hmeister-real** [comment]
Any chance this can be TM'ed to see how it goes?
I just want to see if it gets abused at all, or if it works as intended. If there start being massive free health potion stands or something il think of a harder recipe, but for now all complaints thrown at this recipe are theory or just saying that the current one is "fine" when it isn't

**Comment by Stagrawl** [comment]
My kinda overall opinion on this is that it's just updating a placeholder, much more effort on this is pointless as this ultimately isn't what the alchemy system should be. It either needs to be something merged fast that's just good enough for now, or it should just be left.

**Pull request merged**
