### PR TITLE
Particle Weather System & Food smells

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Ports:
- https://github.com/Vanderlin-Tales-Of-Wine/Vanderlin/pull/18.
- https://github.com/Vanderlin-Tales-Of-Wine/Vanderlin/pull/20.
- https://github.com/Vanderlin-Tales-Of-Wine/Vanderlin/pull/21.

The weather types include:
- Rain
- Rainstorm
- Snow
- Snowstorm

Testing proof:

https://github.com/user-attachments/assets/bd7108c4-4d0a-4d06-9760-c8e5fa76f685

## Why It's Good For The Game

Functioning weather after a long time.
Food smells make use of the pollutant system that was only used for perfumes.

### CODE REVIEW

**Comment by dwasint** [comment]
note you can disable the transform matrix on snow and I would recommend that so the snow looks larger.

**Comment by RadiantFlash7** [comment]
> note you can disable the transform matrix on snow and I would recommend that so the snow looks larger.

Hey, Thanks for coding this, even on another server! It looks amazing and I adore how it works!

**Comment by Gyrandola** [comment]
> note you can disable the transform matrix on snow and I would recommend that so the snow looks larger.

Will try

**Comment by dwasint** [comment]
> Can we add a toggle for this? I fear like it's another one of those cases where certain setups shit themselves while rendering this
> 
> Also you mfs better add snow tile overlay if we are getting snow and satisfying crunchy snow walking sounds

its actually quite light on the client since its just 1 particle emitter

**Review by Nakalon — APPROVED** [review]
This is so cute

**Pull request merged**
