### PR TITLE
Grenzelhoft's new look and changes

### PR DESCRIPTION
**Pull request by SarmentiCampbell**
## About The Pull Request
Bring grenzelhoft drips from the codebase Openkeep to make them more unique
Along with that, replaced lit torches with torches on their belt due to runtime and gave grenzel merc key because it is dumb only desert riders get them

The sprites were made by Cre, so Credit to them because it look actually amazing!
https://github.com/Darkrp-community/OpenKeep

also i wasn't able to fix that nanotrasen and syndicate svg issue, it keep appearing frequently?

## Why It's Good For The Game
image

Drip is always appreciated.

### CODE REVIEW

**Comment by zeratino** [comment]
the person who made this is "cre." on discord :)

**Comment by coffeecoffeecoffee** [comment]
Having now played with this please allow me to say
WOOOOOOOOOO YEAHHHHHH THAT'SWHATWE'RETALKINGABOUT. It is SO much better and really defines the Grenzelhoft as a culture!
It does appear though that both items are recolored at the same time by right-clicking the body, which can be a little confusing figuring out the first time, instead of being able to color the hat and shirt differently, which would be pretty cool. landsknecht COLORS

**Comment by glitchbow** [comment]
Holy fuck yes please, these are gorgeous. I no longer have to keep failing at making/buying a fancy hat, I already start with a really great one. Thank you, Cre! I love added fashion so much.

**Comment by coffeecoffeecoffee** [comment]
Some of the colors are pretty muddy and ugly compared to the very nice white, red, and blue. A "light blue" would be nice, and yellow needs to be much brighter I think.

**Pull request merged**
