### PR TITLE
Pestra Paladin/Templar fix

### LINKED ISSUE #1215: [BUG] Pestran paladins are too good
Pestran paladins have access to T3 miracles instead of T1

They have: 
churn undead (based spell for all templars and paladins)
Miracle
Reattach limb
Cure rot

Instead of:
churn undead
diagnosis 
lesser miracle

## Steps to Reproduce:

Adventurer -> paladin -> combat master

No idea about another class or templar

### PR DESCRIPTION
**Pull request by TheFenix323**
## About The Pull Request
Fixes #1215 using the fix #1206 made for Clerics/Acolytes but for Paladins/Templars.
(And yes it was tested on Local)

## Why It's Good For The Game
Fixes a bug.

### CODE REVIEW

**Comment by Nakalon** [comment]
I'm all for the fix but would like the opinion of someone who plays the class regarding your balance change... I wouldn't know myself how this would impact players

**Comment by Nakalon** [comment]
> better miracle shouldnt be swapped. if you go pestra you deserve something for taking a med focused pantheon

Agreed! Exactly what I was thinking but didn't have the knowledge to put into words!

**Comment by TheFenix323** [comment]
> better miracle shouldnt be swapped. if you go pestra you deserve soemthing for taking a med focused pantheon

Asked Zirok about it and said to switch them, I'm fine with either way.

**Comment by TheFenix323** [comment]
> better miracle shouldnt be swapped. if you go pestra you deserve soemthing for taking a med focused pantheon

Reverted

**Comment by Nakalon** [comment]
> > better miracle shouldnt be swapped. if you go pestra you deserve soemthing for taking a med focused pantheon
> 
> Asked Zirok about it and he said to switch them, I'm fine with either way.

I think what Zirok was standing for was removing either lesser miracle or miracle. Not have both

**Comment by TheFenix323** [comment]
> > > better miracle shouldnt be swapped. if you go pestra you deserve soemthing for taking a med focused pantheon
> > 
> > 
> > Asked Zirok about it and he said to switch them, I'm fine with either way.
> 
> I think what Zirok was standing for was removing either lesser miracle or miracle. Not have both

Yes, swapping them would cause the Paladin to not have both

**Pull request merged**
