### PR TITLE
Give bandits t2 love potion reward

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
Gives bandits the love potion once they sacrifice 200 mammons worth of loot to mattheos

## Why It's Good For The Game
Right now bandits have no way of actually managing prisoners properly or securing loyalty and due to the larger pop count, the prison isn't enough for everyone to get a prisoner. With how far into the code its put, this shouldnt really have an effect until late into the round though so I am not opposed to putting it earlier.

### CODE REVIEW

**Comment by Drayco84** [comment]
As somebody who wishes to get love potion'd or made into a willing and devoted slave, I'd like to see this unlocked earlier. Maybe even have a few lying around in the prison at game start.

**Comment by MickDick1** [comment]
For this to have impact it does need to come sooner. I agree. It's a neat idea in lieu of other more thematically appropriate methods.

Matthios IS a wish granter and who wouldn't want a willing pet? Bit Baothan thematically but this could shake things up.

**Comment by wow50000** [comment]
gonna move it to 2 because thats when they get their moondust

**Comment by Jul-Jul** [comment]
Well until something better comes along to handle slaves/captives, this does seem the next best thing.

**Comment by Elli-Skala** [comment]
Now to become a bandit main

**Comment by Alanii** [comment]
Just know the love potion has no real mechanics outside of hearts. So players may interpret the love hearts to be "love" or just infaturation.

Worse case, they will ignore it and try to be very mean about the ordeal.

**Comment by Drayco84** [comment]
Also need to add more chains and sack hoods to the prisoner cell to make taking captives through mundane ways easier.

**Comment by n3tis** [comment]
> Also need to add more chains and sack hoods to the prisoner cell to make taking captives through mundane ways easier.

you don't need sack hoods you can just make and use regular sacks
chains can be substituted for ropes
and if you really need 'em, make 'em bruh!

**Comment by Useroth** [comment]
As said: 

> Well until something better comes along to handle slaves/captives, this does seem the next best thing.

**Pull request merged**
