### PR TITLE
Add Vulp hair, ears and snout

### PR DESCRIPTION
**Pull request by SuhEugene**
## About The Pull Request

Port of this: https://github.com/Fluffy-Frontier/FluffySTG/pull/3184

## Why It's Good For The Game

Adds variety of sprite accessories for Vulps.
More customization options is good.

### CODE REVIEW

**Comment by SuhEugene** [comment]
Are you okay with me making everything I added unique to the Vulpkians?

**Comment by HelskiWoof** [comment]
Yeah, make it only for vulpkians sounds more correct

**Comment by SuhEugene** [comment]
No, sadly, this hairs fit humanoids very badly, so... Vulpkians only it is...

**Comment by HelskiWoof** [comment]
soo, this PR is ready to be tested and merged, someone is want to do this? :D

**Comment by HelskiWoof** [comment]
love ya! 😻

**Comment by HelskiWoof** [comment]
> > soo, this PR is ready to be tested and merged, someone is want to do this? :D
> 
> Yeah, apologies

love ya! 😻

**Pull request merged**
