### PR TITLE
Gunpowder guns by GISELA

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

- [x] Add guns used in #1518 
  - Arquebus 
image
  - Handgonne
image
  - Pistol
image
  - Ramrod (It comes with every new gun, right click to retrieve it)
image
  - Gunpowder flask
image
- [x] Gives guns and relative firearm skills to specific roles.
- [ ] Integrate gunmaking into the artificer, allowing him to craft ammo, gunpowder and guns.

### CODE REVIEW

**Comment by ThatReformedEngineer** [comment]
Funnily enough, you can get sulfur already by grinding torches, charcoal exists as a reagent you can make with ash and salt, so all that would be needed for gunpowder is some form of saltpetre creation. Though good luck using historical methods since they usually tend to involve very distasteful substances. Could always use the mineral refinement route with artificers or alchemists?

**Comment by Gyrandola** [comment]
> Funnily enough, you can get sulfur already by grinding torches, charcoal exists as a reagent you can make with ash and salt, so all that would be needed for gunpowder is some form of saltpetre creation. Though good luck using historical methods since they usually tend to involve very distasteful substances. Could always use the mineral refinement route with artificers or alchemists?
> 
> Oh and you could also add rotten cackleberries for an extra source of sulfur if that is desired.

Distasteful substances?

**Comment by Vultchurr** [comment]
They mean piss, I believe. Urine was a component in medieval gunpowder recipes (or so google tells me anyways)

**Comment by Gyrandola** [comment]
> They mean piss, I believe. Urine was a component in medieval gunpowder recipes (or so google tells me anyways)

at long last.. piss reagent

**Comment by Vultchurr** [comment]
We're getting the rifle /and/ jarate update in one merge!

**Comment by Gyrandola** [comment]
> Literally taken from Helmsguard without any proper credit here or in announcements, only a name in event pr that was closed seemingly. That's disturbing. Don't be splurt devs, man just saying.

I already credited gisela back when guns were first tested here. Crawl back to dreamkeep little man

**Comment by EaglePhntm** [comment]
> > Literally taken from Helmsguard without any proper credit here or in announcements, only a name in event pr that was closed seemingly. That's disturbing. Don't be splurt devs, man just saying.
> 
> I already credited gisela (in the PR I purposefully linked too) back when guns were first tested here. Crawl back to dreamkeep little man

"I already quoted in the little obscure pr thats now irrelevant to anything." Is all I am hearing. Dreamkeep is also, you guessed it. Irrelevant, not just that Dreamkeep also properly credited and was permitted by Gisela to have that. Shame on you.

**Comment by Feralape** [comment]
the lack of genuineness is appalling, you even went as far as removing me from the staff team over me asking to be credited. Choke on the guns, you thieves. - Gisela

**Comment by RyszardParys** [comment]
Swag, lets hope this doesn't become a meta like with the runelock.

**Comment by Hmeister-real** [comment]
> > > Literally taken from Helmsguard without any proper credit here or in announcements, only a name in event pr that was closed seemingly. That's disturbing. Don't be splurt devs, man just saying.
> > 
> > 
> > I already credited gisela (in the PR I purposefully linked too) back when guns were first tested here. Crawl back to dreamkeep little man
> 
> "I already quoted in the little obscure pr thats now irrelevant to anything." Is all I am hearing. Dreamkeep is also, you guessed it. Irrelevant, not just that Dreamkeep also properly credited and was permitted by Gisela to have that.

Roguetowns roots are set in ingenuine stealing and using Lifewebs assets + sounds, so this isn't really a surprise. It's a free, open codebase :P

**Comment by Gyrandola** [comment]
> the lack of genuineness is appalling, you even went as far as removing me from the staff team over me asking to be credited. Choke on the guns, you thieves. - Gisela

You have a grand total of 2 rounds played on our server.

**Comment by Gyrandola** [comment]
And before you call anyone a thief, go read the open source license your entire repository is based on. 

BTA, make sure to make it public again if you ever host it on a server, or you would be violating the most important clause of AGPL.

**Comment by EaglePhntm** [comment]
> And before you call anyone a thief, go read the open source license your entire repository is based on. 
> 
> BTW, make sure to make it public again if you ever host it on a server, or you would be violating the most important clause of AGPL.

I dont own helmsgusrd but literally enigma was closed source until stolen, the same code you are using, i dunno what you are talkin about but damn, excuses to fool yourself to sleep better as if you aren't stealing someone's work and announcing it as if its your own while initially putting a lil name to a previous event pr and calling it a day.

Same as what splurt did with venus 'oh look what i found on the ground the way home' *imports everything from venus station shamelessly*

**Comment by EaglePhntm** [comment]
> > > > Literally taken from Helmsguard without any proper credit here or in announcements, only a name in event pr that was closed seemingly. That's disturbing. Don't be splurt devs, man just saying.
> > > 
> > > 
> > > I already credited gisela (in the PR I purposefully linked too) back when guns were first tested here. Crawl back to dreamkeep little man
> > 
> > "I already quoted in the little obscure pr thats now irrelevant to anything." Is all I am hearing. Dreamkeep is also, you guessed it. Irrelevant, not just that Dreamkeep also properly credited and was permitted by Gisela to have that.
> 
> Roguetowns roots are set in ingenuine stealing and using Lifewebs assets + sounds, so this isn't really a surprise. Stuff like this happens with a free, open codebase, AP and Hearthstone stole from Ratwood countless of times, and Dreamkeep is literally just Hearthstone rebranded :P

Dreamkeep is irrelevant, Gisela owns Helmsguard, a server she has been working on nearly on her own and they stole her ENTIRE helmsguard modular folder and she was only starting off making her server and was basically unplayable yet, this is just VILE.

**Comment by Feralape** [comment]
> > the lack of genuineness is appalling, you even went as far as removing me from the staff team over me asking to be credited. Choke on the guns, you thieves. - Gisela
> 
> You have a grand total of 2 rounds played on our server. Perhaps you should have put more, or any effort at all into this community.

So, because i don't play on Rat as much you stole my work, and now, my entire modular folder in your hand, and kick me out straight after I asked for proper credits, and now threatening me as well?  this is just being petty and absolutely scummy. Shame on you, I made an absolute mistake trusting you and this community.

**Comment by RyszardParys** [comment]
Damn, much cope in the chat...
Mfw the codebase is public and anyone can use or code whatever they want...
"C-Credit me! Waahhh! Thief!"
Ok little bro, hardly anyone cares who coded this shi, at the end of the day, people just play the game and either enjoy the dumb fucking guns PR or not.
It's not a big deal.

**Comment by EaglePhntm** [comment]
> Damn, much cope in the chat... Mfw the codebase is public and anyone can use or code whatever they want... "C-Credit me! Waahhh! Thief!" Ok little bro, hardly anyone cares who coded this shi, at the end of the day, people just play the game and either enjoy the dumb fucking guns PR or not. It's not a big deal. PLUS you ARE credited in the title, so why the hell is this continuing?

she was not even credited in the title until i brought it up.

**Comment by Gyrandola** [comment]
> > And before you call anyone a thief, go read the open source license your entire repository is based on. 
> > 
> > BTW, make sure to make it public again if you ever host it on a server, or you would be violating the most important clause of AGPL.
> 
> I dont own helmsgusrd but literally enigma/roguetown was closed source until stolen, the same code you are using, i dunno what you are talkin about but damn, excuses to fool yourself to sleep better as if you aren't stealing someone's work and announcing it as if its your own while initially putting a lil name to a previous event pr and calling it a day.
> 
> Same as what splurt did with venus 'oh look what i found on the ground the way home' *imports everything from venus station shamelessly*
> 
> Good strategy to violate upcoming servers and their work though not gonna lie, helmsguard was barely being built and you already stick your dirty hands in it.

Let me lecture you on the fact roguetown being closed source was illegal since it used TG as a base. AGPL requires all publicly hosted software to be open source.

Other than that. Ive got nothing more to say to you. I dont care about your false claims and your deluded vision of the world.

**Comment by Feralape** [comment]
> > > And before you call anyone a thief, go read the open source license your entire repository is based on.
> > > BTW, make sure to make it public again if you ever host it on a server, or you would be violating the most important clause of AGPL.
> > 
> > 
> > I dont own helmsgusrd but literally enigma/roguetown was closed source until stolen, the same code you are using, i dunno what you are talkin about but damn, excuses to fool yourself to sleep better as if you aren't stealing someone's work and announcing it as if its your own while initially putting a lil name to a previous event pr and calling it a day.
> > Same as what splurt did with venus 'oh look what i found on the ground the way home' _imports everything from venus station shamelessly_
> > Good strategy to violate upcoming servers and their work though not gonna lie, helmsguard was barely being built and you already stick your dirty hands in it.
> 
> Let me lecture you on the fact roguetown being closed source was illegal since it used TG as a base. AGPL requires all publicly hosted software to be open source.
> 
> I didnt make these rules, I play by them. If gisela wanted to avoid stuff being ported before the server would open, they should have privated the repo. I also never announced anything as my own.
> 
> Other than that. Ive got nothing more to say to you. I dont care about your false claims and your deluded vision of the world.

fucked up, dude, i trusted you, real fucked up

**Pull request merged**
