### PR TITLE
Contribution Guidelines File

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

This is a file with some Contribution Guidelines worked on by me an Zirok!

Here's a copy of them:

## Contribution Guidelines

These guidelines serve to safeguard our codebase, improve workflow and facilitate the job of Maintainers.
Following them is important to make sure your work makes it into the game swiftly but also, that our server is in the best shape it could possibly be in!

## Contributor Guidelines

1 - PRs must follow the these standards:
- All Changes must be properly documented in the PR body.

- **Test evidence MUST be included.**
*This does not apply to very small changes like changing a stat from 1 to 2.
In the case your PR doesn't affect something which can be clearly seen in game, the minimum required is for you to show us it compiles.*

- The "Why is this good for the game" section should reflect how the PR will positively affect the server as a whole.
*"This was stupid and I don't agree with it" and similar things are, of course, not acceptable.*

- We recommend you make a changelog of all changes you have made, summarized.
*This is to make the work of the lovely Elianore easier. She deserves it.*

2 - Do not comment out code. If you're removing it, remove it completely.

3 - Do not include slurs in your code, comments included.

4 - Try to be civil while discussing PRs.
*We are all here working for the same goal and because we love what we do, remember that!*

5 - You are encouraged to seek out and engage with player feedback on your PRs.
*Sometimes other people have ideas we didn't think of, being open to this can be the pathway to many abilities some consider to be unnatural...*

## Maintainer Guidelines

1 - Maintainers may not merge their own PRs save for reverts or fixes to game breaking bugs.
*This also includes PRs where the maintainer was heavily involved in developing, even if not their own.*

2 - Maintainer decisions on game direction are absolute.
*If something on a PR is not up to a Maintainers standards and the author is unwilling to comply the PR should be closed.*

3 - PRs should be taken as they are and as if no follow up PRs were to be made.
*Maintainers may in theory assume the Author of any given PR will fall off the face of the earth directly after merge.*

4 - In order to Merge a map changing PR the approval of a Maptainer is necessary (if they are available).

## Why It's Good For The Game

This is very important to improve the standards of contribution in our lovely server as we all work our hardest to make it into the best it could ever be!

### CODE REVIEW

**Comment by Gyrandola** [comment]
> 3 - PRs must be at least 24 hours hold to be merged.
> This does not apply for important fixes or reverts.

Im not fine with this. If a change has been approved by a maintainer then it should be merged. I dont have time to waste.

**Comment by Nakalon** [comment]
> > 3 - PRs must be at least 24 hours hold to be merged.
> > This does not apply for important fixes or reverts.
> 
> Im not fine with this. If a change has been approved by a maintainer then it should be merged. I dont have time to waste.

Updated to reflect your wishes!

**Comment by Nakalon** [comment]
> im not fine with 24 hour wait either

That was already changed silly

**Comment by Nakalon** [comment]
> and I absolutely WILL merge my own PR's. revert exists im not gonna fight people over it staying but im not waiting for a butt pat and a handshake.

We have enough maintainers now for that not to be necessary Mori.

Let other people look at your stuff.
Its better to nip bugs in the bud than have them get merged in and then reverted.

A second new pair of eyes is very much necessary in cases where we're so tired we don't see things straight anymore!

**Pull request merged**
