### PR TITLE
Adds Mouth-to-Mouth to combat oxyloss.

### PR DESCRIPTION
**Pull request by CalamaBanana**
## About The Pull Request

- Adds a Mouth-to-Mouth "surgery" to combat the oxyloss most commonly caused by bleeding out.

Works like this:
- Target mouth on a person on the floor with touch intent on weak. If they have oxy-damage, you will start breathing air into their lungs. It repeats on success, if you fail, you need to click again. So you really need to be paying attention to it.

I tinkered with the numbers a little, with 0 medicine skill you have a ~40% to ~60% failure chance each time, barely enough to keep people in the round until real help arrives. If you have a needle and water available right as they pass out, you might get lucky and save them all by yourself. The chance is low, but it is there. If not, better start shouting for people to bring those things while you struggle against the oxyloss.

## Why It's Good For The Game

It is frustrating as hell to stitch someone up completely, just for them to expire when the last wound was stitched. This PR adds a way to delay the inevitable, and as long as the survivors are able to stitch wounds and bring water, people can be kept in the round more easily.

- Passing out from bloodloss is no longer a death sentence, if care can be provided in time.
- Keeps people in the round. At least people that have friends.
- Antags will have a slightly easier time to stay in the round if their comrades win the fight, and they can sometimes capture people that would just have died a stupid death before.
- Vampires accidentally critting when biting won't mean certain death for their victim anymore, if the vampire cares enough to provide aid.

### CODE REVIEW

**Comment by Teragenic** [comment]
Help intent? So grabbing their mouth then selecting help intent?

**Comment by CalamaBanana** [comment]
> Help intent? So grabbing their mouth then selecting help intent?
No, simply click them with help intent active. Or wait, ingame it is called touch. I can see the confusion. The code calls it help still.

**Comment by Koteshkin** [comment]
How mouth-to-mouth should help if you have no damn blood to transfer that oxygen.

**Comment by Teragenic** [comment]
> How mouth-to-mouth should help if you have no damn blood to transfer that oxygen.

This is a moment where gameplay > Realism

**Comment by CalamaBanana** [comment]
> How mouth-to-mouth should help if you have no damn blood to transfer that oxygen.

Ask my magic bed that heals all my wounds in my sleep.

**Comment by ddsaw** [comment]
Should vamps be able to CPR people? They have no stam and I assume they do not breathe.
We are focused on immersion after all..

**Comment by CalamaBanana** [comment]
> Should vamps be able to CPR people? They have no stam and I assume they do not breathe. We are focused on immersion after all..

They do not need to breathe. They still have lungs and muscles to move air.

**Comment by githubuser4141** [comment]
> How mouth-to-mouth should help if you have no damn blood to transfer that oxygen.

This is the same PR that makes stabbing people with a water needle instantly heal all their blood. Or the game that allows you to recover 3 L of lost blood by eating some oats or drinking swamp water.

**Pull request merged**
