### PR TITLE
Empowers towners

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
Buffs almost all towners across the board to have a +6 stat point bonus or a special gimmick.
Buffs guard roles to encourage more people to play guard with the added responsibilities of working for the duke
Buffs warrior because warrior is objectively worse than every adventurer role and merc.

Extensive list of changes

Warrior:
Removed RNG, buffed con to keep it a step above paladin in martial prowess, gave it guns due to multiskilled but no way to get a gun outside of being provided with one.

Blacksmith:
buffed melee capabilities, should be able to hold their own but not as good as a dedicated combat class, needed this buff because forge clerics are advancing on their territory. Still has no armour proficiencies or multi skill in combat

Carpenter:
Gave them the option for more weapon spread due to them using a wide spread of tools and lack of work generally. Can double as a worse warrior in times where no repairs are needed.

Cheesemaker:
Removed unneeded stats, buffed wrestling unarmed and knives to keep it in line with the other classes.

Drunkard:
Re statted the role to be a decent criminal and a discount rogue, may nerf if people don't like it or if it is too strong

Fisher: 
Gives fishermen knives and polearms due to skill in gutting fish and fishing rods, Illogical but what can you do ? Also buffed stats to keep in line with

Hunter:
Buffed ranged capabilities and stats to keep in line with changes, also gives polearm skill so they can spear hunt if they really wanted to.

Minstrel:
Buffed music skill to be better than bard, buffed knife and sword skill to keep in line with changes as well as buffing endurance so they can keep "performing" for longer.

Noble:
Given nobles a rapier for basic self defence as well as a staff for bog traversal, Buffed sword, knives, polearms and bows to keep in line with buffs while keeping stats low.

Peasant:
General all round buffs to keep them in line with other towner roles, gave stronger wrestling and unarmed because farming involves hauling a lot of heavy things around and it's hard work.

Legendary smith:
Buffed skill gaps and gave them an empty pouch.

Woodcutter:
Buffed unarmed and wrestling to journeyman, buffed athletics to cut trees for longer.

Watchmen:
Gave them firearm skill to adapt to advancing technology as well as guaranteed maces 4 and stats outclassing warrior in exchange for a different skill set.

Men at arms:
Gave them firearms 4 due to their elite status above watchmen and other common rabble. Buffed their stats alongside watchmen.

Soilson:
Buffed to keep in line with towner farmer, should have slightly better skills to encourage playing soilson and to fight off any undesirables who dare harm the soilfort.

## Why It's Good For The Game
Towners have been getting bullied by these jobless foreigner bums for too long, it's time they took action and learned how to fight back.

### CODE REVIEW

**Comment by wow50000** [comment]
> I think it is better to nerf adventurers then to make towners too robust

nerfing adventurers runs into the issue of adventurers being useless, which... at that point just straight up remove them.

**Comment by Xaytan** [comment]
> > > I think it is better to nerf adventurers then to make towners too robust
> > 
> > 
> > Nerfing adventurers runs into the issue of adventurers being useless, which... at that point just straight up remove them. This also runs into the issue of mercs needing nerfs because those are also an issue.
> 
> I just don't think that all roles and classes should be combat ready - it's an inflation of combat skill that kind of makes it a standart thing and nudges everyone into pvps and main character syndrome.

I'm going to hard disagree.

Having a sizable section of the playerbase be relegated to RPG NPCs who can be murdered with little difficulty or consequence by adventurers, mercenaries and bandits does far more to push main character syndrome than letting those people fight back.

I think some of these are a little much in terms of stat increases, but keep in mind most of these roles don't start with armor and don't have armor proficiencies. The ability to wear medium armor without losing your ability to sprint out of a bad situation is by itself an enormous advantage.

The game is more fun and more interesting when the peasant militia can arm up and protect their homes, and when people have to consider that the person they're attacking is another player and not free loot. Hell, some of these changes are just undoing nerfs that happened within the last few months.

**Comment by NikolayByondPlayer** [comment]
> > > > I think it is better to nerf adventurers then to make towners too robust
> > > 
> > > 
> > > Nerfing adventurers runs into the issue of adventurers being useless, which... at that point just straight up remove them. This also runs into the issue of mercs needing nerfs because those are also an issue.
> > 
> > 
> > I just don't think that all roles and classes should be combat ready - it's an inflation of combat skill that kind of makes it a standart thing and nudges everyone into pvps and main character syndrome.
> 
> I'm going to hard disagree.
> 
> Having a sizable section of the playerbase be relegated to RPG NPCs who can be murdered with little difficulty or consequence by adventurers, mercenaries and bandits does far more to push main character syndrome than letting those people fight back.
> 
> I think some of these are a little much in terms of stat increases, but keep in mind most of these roles don't start with armor and don't have armor proficiencies. The ability to wear medium armor without losing your ability to sprint out of a bad situation is by itself an enormous advantage.
> 
> The game is more fun and more interesting when the peasant militia can arm up and protect their homes, and when people have to consider that the person they're attacking is another player and not free loot. Hell, some of these changes are just undoing nerfs that happened within the last few months.
> 
> Rank 3 in their main tool is just one step higher than the role could train on their own with a dummy, and is where most of the manual labourer classes should sit. Their stats, armor proficiencies and other weapon skills should all be ill suited to combat.

They can still arm up if they unite

**Comment by Gyrandola** [comment]
I'm #teamtowner but this is not the way

**Comment by JohnnyJohnJohnson** [comment]
Man, seeing Hunters and Fishermen get polearms would've been awesome...

**Pull request closed without merging**
