### PR TITLE
Armor reforged and boiled

### PR DESCRIPTION
**Pull request by Red-Honk**
Armor reforged and boiled.

## About The Pull Request

[Hats/helmets]:

Fixes the helmets FOV issue not presenting itself proper.

[Masks]:
updated desc on the steel and iron hound masks.
"A mask of steel, made for those who have snouts, which protects the eyes, nose and muzzle while also obscuring the face."

"An iron mask, made for those who have snouts, protecting the eyes, nose and muzzle while obscuring the face."

[Neck]:
The cloth/leather coif has been given 125 integrity and giving it stab crit prevention with a description.
desc = "A coif made either of leather or cloth that is comfortable enough to sleep in that protects the head, ears and neck, while providing no protection from arrows and bolts and sadly enough too, soft to prevent chops from decapitating."

The iron chain coif has been given a description.
desc = "An iron chain coif, composed of interlinked metal rings, that barely absorb impacts from arrows that protects the head, ears and neck, and is sadly too uncomfortable to sleep in."

The steel chain coif has been given a description.
desc = "A steel chain coif, composed of interlinked metal rings, that barely absorb impacts from arrows that protects the head, ears and neck, and is sadly too uncomfortable to sleep in."

The bervor was renamed into the bevor for accuracy's sake, no doubt a typo has lost its ability to protect the ears, because it shouldn't have them protected to begin with, that's what the sallet is for, also has been given an updated description.
desc = "A steel bevor that protects the lower part of the head, that being the neck, mouth and nose."

[Chest]:

Gambeson updated description.
desc = "A large padded defense jacket designed to be cheap, resewable and worn as its own armor or go beneath armor that protects the torso, arms and legs."

Chainmallie updated description.
desc = "A iron chain vest composed of interwoven metal rings, that absorb arrow impacts decently enough while being also comfortable enough to sleep in covering just the torso."

Haubergeon updated description.
desc = "A steel maille also known as the little coat of mail, composed of interwoven metal rings that absorb arrow impacts decently enough while being also comfortable enough to sleep in covering the torso and arms."

Hauberk.
"A longer steel maille also known as coat of mail, composed of interwoven metal rings that absorb arrow impacts decently enough while being also comfortable enough to sleep in covering the torso, arms and legs."

[Pants]:

Labour/work trousers have been given 100 integrity and have inherited the cloth/leather coifs armor values of:
"blunt" = 33, "slash" = 12, "stab" = 22, without stab crit prevention.

Leather/mourning trousers have been given 130 integrity and have inherited the values/cost of a chest leather armor:
"blunt" = 50, "slash" = 25, "stab" = 40, "bullet" = 10, with an added bonus of stab crit prevention

Iron chain chassues updated description and had their integrity lowered from 200 to 175. (Because iron)
desc = "Iron chain leggings, composed of interlinked metal rings, that absorb arrow impacts decently enough."

Steel chain chassues updated description.
desc = "Steel chain leggings, composed of interlinked metal rings, that absorb arrow impacts decently enough."

Scalemail updated description.
desc = "Steel metal scales interwoven intricately to form flexible protection that ends up covering the torso and legs."

Plated leggings updated description.
desc = "Plated armor to protect the legs, especially against arrows."

[Note]:

The basic chest leather armor does not have stab crit prevention, either stud it or make it out of hide for that, also the boots have not been touched either.

## Why It's Good For The Game

Descriptions are good for readability's sake acting like a mini-tutor, variety is neat to have allowing even lower tier leather armor such as trousers and coif to have some kind of purpose, instead of being, I stab your leg, got a lucky crit, now "you are already dead", type of deal, this should encourage folk to fight and require less time waiting on the smithy or the like for a fullset of armor now that leather has a purpose besides being mostly cosmetic when characters go for leg stabs.

### CODE REVIEW

**Comment by Nakalon** [comment]
All descriptions should be handled with this degree of care! Bravo!

**Comment by john-pawson** [comment]
Also, since you're already changing the armor stats, would it be possible to give the leather trousers slightly more protection or let them keep their integrity? I don't know why the cloth trousers and the leather trousers use the same stat block, but maybe giving the leather trousers a slight buff make them a viable option for armor, since they're leather and way harder to make compared to the cloth ones.

**Comment by Nakalon** [comment]
Hey friend!

image

This is why its not passing!

**Comment by Red-Honk** [comment]
> Also, since you're already changing the armor stats, would it be possible to give the leather trousers slightly more protection or let them keep their integrity? I don't know why the cloth trousers and the leather trousers use the same stat block, but maybe giving the leather trousers a slight buff makes them a viable option for armor, since they're leather and way harder to make compared to the cloth ones.

The worker trousers are also made out of leather, the clothed pants to my knowledge lack any protection whatsoever, and you are supposed to mix those leather pants with a gambeson and trust me when I say, that the leather pants ain't all that bad, but I suppose I could give them the same protection as a leather/clothed coif.

**Comment by john-pawson** [comment]
> The worker trousers are also made out of leather, the clothed pants to my knowledge lack any protection whatsoever, and you are supposed to mix those leather pants with a gambeson and trust me when I say, that the leather pants ain't all that bad, but I suppose I could give them the same protection as a leather/clothed coif.

Nope, worker trousers are made out of 2 cloth, 1 fiber, and need 1 sewing skill to craft.
And also, the leather pants can be pierced by every single stab attack. Including the one with the lowest armor penetration so far (sword stab at 20 armorpen) and any axe cut, not even chop, cut also goes through the armor (10 armor pen).

**Comment by john-pawson** [comment]
> The worker trousers are also made out of leather, the clothed pants to my knowledge lack any protection whatsoever, and you are supposed to mix those leather pants with a gambeson and trust me when I say, that the leather pants ain't all that bad, but I suppose I could give them the same protection as a leather/clothed coif.
> 
Nope, worker trousers are made out of 2 cloth, 1 fiber, and need 1 sewing skill to craft. And also, the leather pants can be pierced by every single stab attack. Including the one with the lowest armor penetration so far (sword stab at 20 armorpen) and any axe cut, not even chop, cut also goes through the armor (10 armor pen).

Edit: I meant buff the *leather trousers* not the work ones, since those are already cheap and easiest to get.

**Comment by Red-Honk** [comment]
> > The worker trousers are also made out of leather, the clothed pants to my knowledge lack any protection whatsoever, and you are supposed to mix those leather pants with a gambeson and trust me when I say, that the leather pants ain't all that bad, but I suppose I could give them the same protection as a leather/clothed coif.
> 
> Nope, worker trousers are made out of 2 cloth, 1 fiber, and need 1 sewing skill to craft. And also, the leather pants can be pierced by every single stab attack. Including the one with the lowest armor penetration so far (sword stab at 20 armorpen) and any axe cut, not even chop, cut also goes through the armor (10 armor pen).
> 
> Edit: After seeing the commit i'd like to clarify, i meant the _leather trousers_ not the work trousers, since those are the ones actually made out of leather.

In other words, you wish for me to buff up the leather armor, so it can at least withstand something?; Alright, let's discuss this over discord: _redth

**Comment by Red-Honk** [comment]
> Hey friend!
> 
> image
> 
> This is why its not passing!

Worked like a charm, appreciated it.

**Comment by Red-Honk** [comment]
> > The worker trousers are also made out of leather, the clothed pants to my knowledge lack any protection whatsoever, and you are supposed to mix those leather pants with a gambeson and trust me when I say, that the leather pants ain't all that bad, but I suppose I could give them the same protection as a leather/clothed coif.
> 
> Nope, worker trousers are made out of 2 cloth, 1 fiber, and need 1 sewing skill to craft. And also, the leather pants can be pierced by every single stab attack. Including the one with the lowest armor penetration so far (sword stab at 20 armorpen) and any axe cut, not even chop, cut also goes through the armor (10 armor pen).
> 
> Edit: After seeing the commit i'd like to clarify, i meant the _leather trousers_ not the work trousers, since those are the ones actually made out of leather.

I mean, I would give them something close if not the same as chest leather but like, they're so cheap to produce, one hide, novice skill with a sewing needle at a drying rack, I can either give them a slight buff of their own, or, up the price to two hide and buff them a tad more proper.

**Comment by john-pawson** [comment]
> I mean, I would give them something close if not the same as chest leather but like, they're so cheap to produce, one hide, novice skill with a sewing needle at a drying rack, I can either give them a slight buff of their own, or, up the price to two hide and buff them a tad more proper.

Second option would probably be better, to at least have something inbetween "Chain leggings" and "slightly thick cloth pants" (Yeah i know ignoring gambesons and padded dresses, but those are way harder to get and mainly used for whole body prot)

**Comment by Red-Honk** [comment]
> > I mean, I would give them something close if not the same as chest leather but like, they're so cheap to produce, one hide, novice skill with a sewing needle at a drying rack, I can either give them a slight buff of their own, or, up the price to two hide and buff them a tad more proper.
> 
> Second option would probably be better, to at least have something inbetween "Chain leggings" and "slightly thick cloth pants" (Yeah i know ignoring gambesons and padded dresses, but those are way harder to get and mainly used for whole body prot)
> 
> PD: Unrelated to the PR, but i responded to that question on the ear crit PR, just in case you haven't read it

I read that eye/ear PR https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1066, and I got a headache, are you telling me, that my theory of the armor that can fully absorb x damage type getting damaged was false all along?; And in fact it's actually bugged so it takes the damage?; Well, I'll be, probably should make a new rule that goes with how I thought it worked, or maybe not, note to self: The gambeson will gimp you if plated, by that logic, spear stabs should stab through plated armor.

**Pull request merged**
