### PR TITLE
Update rockhill.dmm

### PR DESCRIPTION
**Pull request by PTFOperations**
## About The Pull Request

Moves entire court to throne room, and moves the goblin keep further to the edge of the map, added skeletons in the tunnel network under bog.

## Why It's Good For The Game

QoL, increased difficulty, and allows the King to see his subjects.

### CODE REVIEW

**Comment by DeerJesus** [comment]
Why did you remove the door in the secret space?

**Comment by PTFOperations** [comment]
> Why did you remove the door in the secret space in Rockhill Keep?

Which door is that?

**Comment by PTFOperations** [comment]
Fixed

**Comment by PTFOperations** [comment]
The conflicts were already fixed.

**Pull request closed without merging**
