### PR TITLE
Maxes PQ at 30, allows giving self PQ when debugging

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

PQ is very overabbundant, and smaller PQ dumps do literally nothing since the PQ currently is balanced in a really dumb way. Now when you lose PQ, it ACTUALLY matters. I vouch for a full PQ reset with this, but if not people with more than 30 should be set back to 30 PQ

## Why It's Good For The Game

overinflation in PQ, PQ's only use if you have lots of it is avoiding punishment for rape  (-4 PQ). Also lets admins debugging to give themselves PQ, and remove it

image

image

### CODE REVIEW

**Comment by john-pawson** [comment]
> overinflation in PQ, PQ's only use if you have lots of it is avoiding punishment for rape (-4 PQ). Also lets admins debugging to give themselves PQ, and remove it

PQ isn't like triumphs??? It's just the amount of people that have said "Yeah i like him/had fun with him/helped me around" I don't see any problem with "overinflation" since it's not any kind of currency. And if it was used to just avoid punishment for rape it doesn't make much sense?? It'd mean to play a bunch of rounds as a nice guy just to go on a raping streak of 5 rounds and back to being a nice guy, to wich point you're probably going to get in trouble with admins.

But i do agree with the PQ for debugging, since it's a pain in the ass to set otherwise, and it's probably not going to get abused since everything gets logged.

**Comment by DeerJesus** [comment]
PQ is a **LIMITED** resource. You cannot cap it. There is a **FINITE** number of players who play the server and after a certain point getting pq is  fucking atrociously hard

**Comment by john-pawson** [comment]
> PQ is a **LIMITED** resource. You cannot cap it. There is a **FINITE** number of players who play the server and after a certain point getting pq is fucking atrociously hard

First, PQ is not a resource.

Second, if it's becoming a problem to have PQ because of the lack of new players (Wich is already insane) why would you cap it?

Third, WHY WOULD YOU WANT SO MUCH PQ??????? If it's a problem because you ran out of people commending you, you either haven't talked to anyone else other than the same people, or already got the majority of the server commending you, in wich case you do NOT NEED MORE PQ.

**Comment by Elli-Skala** [comment]
> PQ is a **LIMITED** resource. You cannot cap it. There is a **FINITE** number of players who play the server and after a certain point getting pq is fucking atrociously hard

Just for note there is already a cap (of 100)

**Pull request closed without merging**
