### PR TITLE
Moved soilery to a different place

### PR DESCRIPTION
**Pull request by NikolayByondPlayer**
## About The Pull Request

Moved soilery, remade buildings, added peddler, added some shop.
Was asked to do it by Desdemona.
Needs testing, gonna finish it in the morning .
image
image
image

## Why It's Good For The Game

More interaction with town

### CODE REVIEW

**Comment by Nakalon** [comment]
I love you

**Comment by wow50000** [comment]
could you put the rape prison in the basement and give the butcher his own rape basement ?

**Comment by NikolayByondPlayer** [comment]
Ready for merge, merge first please
image

**Comment by Heheniy** [comment]
get trees away from fields

**Comment by Heheniy** [comment]
just MOVE them

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
