### PR TITLE
Dumb nobles getting captured

### PR DESCRIPTION
**Pull request by Rayforx**
## About The Pull Request
Adds a special trait that makes Heirs and Hands captured at round start.

Regarding gameplay, A noble gets stripped with only their keys and pouch and put in the bandit camp. Only the Heir, Hand and Courtier can be this special so it only has a HUGE gameplay negative to the loop.

Video of the current code

https://github.com/user-attachments/assets/5d586f6f-dde1-4452-8ddd-f521eb868aed

## Why It's Good For The Game
It's pretty funny. And it could open up for some roleplay at roundstart.

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
Good shit, also is map dif broken?

**Comment by Heheniy** [comment]
but what if there is no bandits

**Comment by Rayforx** [comment]
> but what if there is no bandits

Then, they must wait for bandits to spawn. A minimum of four bandits are always able to join.

**Comment by Gyrandola** [comment]
Shouldnt the keep be aware someone has been kidnapped / is missing?
Else they will assume nobody rolled the role in the first place

**Comment by Rayforx** [comment]
It was a funny idea, but we probably have to scratch it for now.

**Pull request closed without merging**
