### PR TITLE
you can now eat seelie whole.

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

You can now eat seelies whole. Only works on seelie.

Thanks, and have fun.
image

Proof that it works. I hesitate to share more.

Seelies and the seeleater both have to have the option enabled, so no avoiding defiance. If you want it so people can frag seelies with this, let me know.
## Why It's Good For The Game

they're small you should be able to eat them. it's more immersive

Someone needs to do graggar's work!
most code from https://github.com/CausticCove/Caustic-Cove-Main/pull/45

we-do-a-little-trolling-aot

### CODE REVIEW

**Comment by AranyaPTH** [comment]
Is-... Is this Vore in my Ratwood?!

**Comment by DeerJesus** [comment]
Instead of having a separate "accursed" tab I should intersperse the actions through the menus.

**Comment by Gyrandola** [comment]
Ratwood spearheading innovation as always

**Comment by Gyrandola** [comment]
Id be down only because its something a graggarite could realistically do with a seelie.

Anyways @Useroth decides

**Comment by Gyrandola** [comment]
Additionally, Im only in favor of vore thats strictly non sexual. I want body horror, not a fetish.

**Comment by Gyrandola** [comment]
I think whoever is behind this PR does not want the good of this server

**Pull request closed without merging**
