### PR TITLE
Book Blessing buff

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

Makes it so blessing someone with the holy book as a Priest removes the Death Weakened effect, meaning it gets rid of the -2 to all stats + no revives. Book Blessings only work on living people, so you can't just infinitely revive anyone. 

## WARNING
My Localhosting is fucked, it doesn't let me test this PR or even load up my localhost on my main, so this isn't tested. however comparing it to stuff like the sleep code, it should function as intended
```
if(has_status_effect(/datum/status_effect/debuff/sleepytime))
	remove_status_effect(/datum/status_effect/debuff/sleepytime)
	// this is how sleep is done, exactly the same way as this PR does it
```

## Why It's Good For The Game

Gives Priests a massive boost in power that they seriously need, without it being combat orientated. Now people are more inclined to roleplay with a Priest to get what they want since only they can perform book blessings, giving them physicial, social and political leverage, that cannot be avoided through mindless fragging or threats

### CODE REVIEW

**Comment by Alanii** [comment]
I would wait for admins to start policing people with bad role play.

This is just going to have people start acting like more fools by demanding to be blessed or create a "copy and paste" obligatory "oh holy one please bless me" type memes.

**Comment by Jaaackx** [comment]
Could see an argument for this if blessing had a CD or limit how many can be used in a round.

If not then this is literally just going to be a standard part of every revival routine and further cements the Church healbot vibe.

Hate this anyway, death should have permanent consequence.

**Comment by radarseas** [comment]
personally, I'd only remove the debuff but keep the limited lives and limit it to maybe a person a day, counter that builds up so having your debuff removed is entirely a choice the priest has to make beyond just _meh, do it anyway_ to not be hated while not forcing them to have to do it either.

this just means priest'll have more authority over those that owe the church then. Else this is an insanely fucking powerful church buff and a **_HUGE_** antag nerf, since only towners would have infinite revives.

**Comment by Useroth** [comment]
It needs to come at a significant cost.

**Comment by Hmeister-real** [comment]
i don't have much free time, if somebody wants to make it just add the stats back temporarily but not the let you revive, il do it at some point

**Comment by Hmeister-real** [comment]
> if ya still alive get back to me otherwise gonna have to close it for now. it needs an update from upstream by this point anyway.

yeah im around.

**Comment by Hmeister-real** [comment]
> I dont have the time myself to do anything besides function tweaks to PRs so if you wanna fix conflicts and get it ready for merge yourself I can merge/rebalance before hand but, we really dont have coders or anyone to do anything besides their own personal projects as it stands.

i have no clue why it's failing, all the code is correct

**Pull request merged**
