### PR TITLE
Sprites By Kino

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
Adds a bunch of sprites to the "to add" folder, made by @Kino1208. To be used in the future.

Tiles:
image

Lamppost:
image

Lantern:
image

### CODE REVIEW

**Comment by Kino1208** [comment]
Hey that's me

**Comment by Genevesh** [comment]
> Hey that's me

They look awesome, nice work!

**Comment by Gyrandola** [comment]
Cool sprites but adding them without an intended use is bad

**Comment by Kepteyn** [comment]
> Cool sprites but adding them without an intended use is bad

Our mappers would certainly find use out of it. Prettier maps is a good thing, I reckon.

**Comment by Gyrandola** [comment]
the day has come

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
