### PR TITLE
Removes MAA latejoins, but allows women to be MAA.

### PR DESCRIPTION
**Pull request by Useroth**

### CODE REVIEW

**Comment by zakanater19** [comment]
I normally never see more than 2 MAA readied up at roundstart, might be a timezone problem but how they filter in when people don't get the role they wanted or from people who just like to pick unfilled roles whatever.. i don't think this is a good change because it also changes the power balance

**Comment by coffeecoffeecoffee** [comment]
Why would one remove latejoins from a role that very rarely gets enough people in it in the first place? Why Is It Good For The Game:tm:
Incredibly based to un-genderlock this one though.

**Comment by Wildwestmars** [comment]
Agreed on the latejoin removal being too much for such a underselected job. Easy enough for MAA to say "Oh, I returned from the Crusades." and people just shrug and go "Fair enough. Uh, King is Dead, Everything is Fucked. Kill the Jester."

**Comment by DeerJesus** [comment]
Why remove MAA latejoins...? That's kinda weird.

**Comment by DorfGuy1** [comment]
I swear that I could not ready up for roundstart MAA, but it might just be me.

**Comment by burdwatcher** [comment]
Not a fan of garrison late joins in general, more arms after round start would be better spent recruited into a scrappy militia by the king and captain instead of just casually popping off the train to take part in whatever side of the conflict they just observed.

**Comment by coffeecoffeecoffee** [comment]
> Not a fan of garrison late joins in general, more arms after round start would be better spent recruited into a scrappy militia by the king and captain instead of just casually popping off the train to take part in whatever side of the conflict they just observed.

There is not Observe option or mode, remember., and this is not for people being promoted or titled by the King but people joining as MAA from the lobby when the game has started.

**Comment by zakanater19** [comment]
Please please please close this and just make a new PR with the female MAAs, removing MAA latejoin really fucks the keeps balance

**Pull request closed without merging**
