### PR TITLE
Church Changes 2 Electric Boogaloo + Confessor / High Templar

### LINKED ISSUE #743: [REQUEST] Inquisitor assistants (totally not practicals)
In the code there's a unused role that's called the "confessor" and it's obliusly some idea that did not get finished, apparently the idea was giving this role the ability to do miracles and do some sort of invocation of psydon.
(code/modules/spells/roguetown/confessor.dm) 

honestly just remove the spells and maybe the objective of "extract 5 confessions and send them to kingsfield" (that could be a good gimmick for the confessor and inquisitior) put two slots and you've got a new cool class to help the inquisitor instead of having the inquisitor alone vs the world.

pretty obvious that whoever was making a inquisition was inspired by lfwb or the first law (probably lfwb)

### PR DESCRIPTION
**Pull request by Jaaackx**
**About The Pull Request**

Fucked up my last PR, map couldn't merge. Fixed here. Old PR with discussion:
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/767
Added Astrata statues and re-added some Psycrosses in addition to all below.
Raised Confessor to 2 slots upon request.

Code:

- (re)Added Confessor using existing code. 2 slots, support to Inquisitor. Inquisitor needs friends. Basic skills and equipment, forced Psydon worship. Shepherd role renamed to Confessor throughout code.
- Altered Inquisitor description to make it clear that they're hired by the Priest(ess) rather than the Keep. No confusion needed. Raised Inquisitor PQ requirement to 8 to align with Priest.
- Addition of High Templar (name open to suggestion) role. 1 slot. Plate armour, grand mace and a fancy helmet, more weapons skill, ability to hire new Templars. Someone to keep them wrangled. Comparable to a Knight but just a bit worse overall stats/skills wise.
- Added said fancy helm to code.
- Removal of 1 Templar slot to account for High Templar. Limited to 2 now.
- Removal of Churchling miracles.
- Gives Priest graveyard keys.
- I want to mess about with Acolyte / potentially a lead Medical role, but there's a PR up messing with anastasis and I want to see what happens there first.

Map:

Slightly shrunk the space of the Chapel, Kitchen and dining area. General aesthetic changes. Removal of the psycrosses at the altar.
Moved healing off to a small clinic on the side, moved Acolyte quarters upstairs and shrunk (in place of Inquisitor quarters).
Moved the equipment room around. Added a small, Priest-locked armoury with a very limited supply of haubergeon, gambeson, steel swords and a mace.
Added a tunnel connecting the Church to the Crypt underneath.
Moved the Inquisitor down a level. Proper torture basement with cells, Inquisitor's quarters, Confessor dorm. Small tunnel to the river.
Made the Priest quarters a little bigger. Added an actual bedroom and bath away from the 'office'.
Z2:
image

Z3:
image

Z4:
image

Z5:
image

**Why It's Good For The Game**

- Confessor -Inquisitor needs friends to help. Make it a bit more of a social role. Arguably role bloat and up for debate.
- High Templar - Sorely needed. Priest is too busy to continually wrangle the Templar to do their jobs, and this just adds another leadership position to the Church. Arguably role bloat and up for debate.
- Inquisitor - Falling in as part of the Church hierarchy makes sense. No interesting conflict comes from them being a Keep hire, most act as part of the Church anyway. Just the sneakier, nastier part of the Church without any more easy 'oh I don't hire them, I can't stop them torturing you' excuses.
- Churchling - Pushes Churchling into the support cooking/cleaning role rather than just being Aco-lite.
- Map changes - Sanity, increased vibes and atmosphere. Sex bath for the Priest. Church needed some form of armoury for ages.

Resolves #743.

### CODE REVIEW

**Comment by Jaaackx** [comment]
ok no more retarded commits it's sorted

**Comment by Teragenic** [comment]
Looking closer at the map I see that the workflow of the dining area and the rest of the place in the Church lacks basic QOL for people working here.  The dining area is too small and too cramp for actual group level RP, a single table would be better.

The healing ward is too hard to get to from the front and it will be an issue for people roleplaying in the front.  There's no more side passages for easy movement.

The removal of the cross in the front makes it awkward for Marriages. I would prefer also if the pictures had better descriptions of each room. Have you tested it in game? Especially the new healing ward part. It seems like the lighting won't be enough. The healing ward being also /TWO/ (ONE TILE) entrance will cause problems for acolytes who want to get people into the area or drag supplies in. No washbin either for washing clothes or bandages. 

Theres also no cups for actually using the barrel that's stored in the healing ward.

Many small things make my OCD go brr
image

**Comment by Teragenic** [comment]
image
I also wish to add that this is a horrible office to actually RP in due to the size and it's hard to manuever around. I'd make the bedroom moved one to the right.

**Comment by Teragenic** [comment]
Additions suggested: Wooden staves for those who need it to walk. Armory needs to probably be made started empty or almost barren, while I understand armory good it also doesn't really make sense because Templars start with their own arms and armor. 

It should probably be spare shields/gambesons, knives, and tabards. If you really want arms and armor, it should be genuinely thought through of 'Why would this Temple be having an active armory that the Crown will not take or the Cardinal/Saints/Pope allow to have?' 

Having full maces and swords, the swords especially doesn't make much sense. Axes, shovels, and etc may make more sense. They have other uses.

**Comment by Alanii** [comment]
Suggestions;
Rephrase Inqusitor to being assigned to the church, not hired by the Priest. The inqusitor should be part of the church organization as a whole. This way the priest can stand in their way, but the inqusitor is not beholden to the priest entirely. Especially if you get some dumb priest who goes and fucks a werewolf.

Additionally stop adding baths to everything you weirdos. The priest isn't a bath wench.

I'm also still on the fence about a "high templar" due to the way players play. There really is no reason to have a "high templar" when you generally only have 3 templar. It logically makes no sense.

Maybe in the future when the church is expanded upon more, you could change the priest to a bishop and have a grandmaster or something.

**Comment by Jaaackx** [comment]
> Suggestions;
> Rephrase Inqusitor to being assigned to the church, not hired by the Priest. The inqusitor should be part of the church organization as a whole. This way the priest can stand in their way, but the inqusitor is not beholden to the priest entirely. Especially if you get some dumb priest who goes and fucks a werewolf.
> 
> Additionally stop adding baths to everything you weirdos. The priest isn't a bath wench.
> 
> I'm also still on the fence about a "high templar" due to the way players play. There really is no reason to have a "high templar" when you generally only have 3 templar. It logically makes no sense.
> 
> Maybe in the future when the church is expanded upon more, you could change the priest to a bishop and have a grandmaster or something.
> 
> 

High Templar makes sense just because it's another authority figure in the Church. Someone else to lead whilst the Priest is away, someone else to leave information with, etc. I don't think role numbers matter really.

I like the Inquisitor suggestion and I'll reword to that.

Sex bath remains.

**Comment by Jaaackx** [comment]
> Additions suggested: Wooden staves for those who need it to walk, and washbin.. Armory needs to probably be made started empty or almost barren, while I understand armory good it also doesn't really make sense because Templars start with their own arms and armor. 
> 
> It should probably be spare shields/gambesons, knives, and tabards. If you really want arms and armor, it should be genuinely thought through of 'Why would this Temple be having an active armory that the Crown will not take or the Cardinal/Saints/Pope allow to have?' 
> 
> Having full maces and swords, the swords especially doesn't make much sense. Axes, shovels, and etc may make more sense. They have other uses. 

Armoury was half the point of the PR. I think you're nitpicking, it's QOL and isn't really hard to justify IC. It's a convenience so Templar aren't always screwed by 20 minutes of Smithy line every time their armour gets damaged, like every other Guard group gets.

As for the stuff above, I'll make a small change to the dining room and Priest office to improve the space slightly. Cross was already added as said in the PR. Leaving everything else as is.

**Comment by Teragenic** [comment]
> > Additions suggested: Wooden staves for those who need it to walk, and washbin.. Armory needs to probably be made started empty or almost barren, while I understand armory good it also doesn't really make sense because Templars start with their own arms and armor.
> > It should probably be spare shields/gambesons, knives, and tabards. If you really want arms and armor, it should be genuinely thought through of 'Why would this Temple be having an active armory that the Crown will not take or the Cardinal/Saints/Pope allow to have?'
> > Having full maces and swords, the swords especially doesn't make much sense. Axes, shovels, and etc may make more sense. They have other uses.
> 
> Armoury was half the point of the PR. I think you're nitpicking, it's QOL and isn't really hard to justify IC. It's a convenience so Templar aren't always screwed by 20 minutes of Smithy line every time their armour gets damaged, like every other Guard group gets.
> 
> As for the stuff above, I'll make a small change to the dining room and Priest office to improve the space slightly. Cross was already added as said in the PR. Leaving everything else as is.

The healing room definitely needs a better design or an improved entrance. Side passages on the sides of the benches to allow for movement is also recommended. 

Also, they still have to get their armor repaired at the Smithy line. Nothing you add stops that.

**Comment by ThinkArbies** [comment]
One minor nitpick. Templar slots are 4, not 3 currently unless I am sorely mistaken. But even so, I don't feel there's any particular need to limit their slots to make way for the High Templar. The church is already shafted as is in terms of manpower or being able to stand against armed resistance, so there's no harm in giving them one extra guard who still is worse than a knight.

**Comment by Menpbel** [comment]
It would be nice if we get this before or when the cultist pr get's launched. Inquisitor buddies and a dungeon is nice.

**Comment by Maromar15910** [comment]
I don't think removing churchling miracles would be a very popular decision. Nerf their devotion gain if you must, but it makes a role that already has little appeal have less appeal if you neuter it.

**Comment by SixplyDev** [comment]
I agree with the above statements regarding the inquisitor. Their flavor text should reflect more that they are hosted by the church due to an incredibly fragile "alliance" to combat a mutual enemy. It should also reflect that they are from a much higher authority outside of Rockhill and not necessarily entirely beholden to the whims and wishes of the Church. Something that could reinforce this is perhaps the inquisitor spawning with a "Writ of Authority" or something similar like that which is effectively this nice and fancy document that **orders** the church and all citizens to help them in the course of their duties (this obviously is not expected to be played as "help me or die!" but would encourage inquisitors to use some of their "authority" to get what they want). The Keep could also start with a letter roundstart that says effectively the same thing, that an inquisitor has been sent due to X reason (it can be a randomized goal, inquisitor would also need to be aware of it if it is). Really, I hope to see inquisitor seen less as a part of the church and more of a foreigner from a higher authority. This could lead to interesting RP regarding their foreign status as well as Church x Inquisitor arguments regarding how they conduct their duties and such.

**Pull request closed without merging**
