### PR TITLE
[Port] Keyrings and bags from Hearthstone

### PR DESCRIPTION
**Pull request by Vladmar11**
Port https://github.com/Tree445/Hearthstone/pull/506

Keyring rework. They now have an inventory interface, sound when dropping, putting on and putting in a key (which also has a sound when dropping).
Added the ability to inspect keyrings on the ground.
Keyrings can quickly collect all the keys from a tile.
Satchels have also been given the ability to quickly collect items from a tile(but not backpacks) by clicking on it, and along with keyrings, quickly drop items to the floor.
image

### CODE REVIEW

**Review by Gyrandola — APPROVED** [review]

**Comment by Purpleturtle3** [comment]
Steward's keys no longer work on the nervemaster

**Comment by ophaq** [comment]
FINALLY. No more dropping all of my keys as tavern keeper to just get to the fucking one to unlock my kitchen door.

**Comment by Gyrandola** [comment]
> Steward's keys no longer work on the nervemaster

fix ASAP!!!

**Comment by Vladmar11** [comment]
> > Steward's keys no longer work on the nervemaster
> 
> fix ASAP!!!

I won't be home for another eight hours. I'll check it out when I get. No idea why it's broken yet.

**Comment by Vladmar11** [comment]
> > Steward's keys no longer work on the nervemaster
> 
> fix ASAP!!!

Lol. Checked it out myself - it works.

**Pull request merged**
