### PR TITLE
Keep Bath, Sparring Room & Greenhouse

### PR DESCRIPTION
**Pull request by ProbablyCarl**
## About The Pull Request
Adds in a bathing area for the royalty.
Moves the Physician's garden into a rather large greenhouse. Shifts around quite a bit of things.
Expands the upper floor of the Keep, accordingly, with the above.
## Why It's Good For The Game
I 'unno. It's fairly subjective, but it was requested all the same.

### CODE REVIEW

**Comment by Nakalon** [comment]
bro I gotta ask @NikolayByondPlayer I never set foot in the fucking keep

**Comment by Gyrandola** [comment]
Waiting on Nikolay to weigh in.

**Comment by NikolayByondPlayer** [comment]
> Waiting on Nikolay to weigh in.

Good stuff, finally dirty nobles will clean themselves

**Review by Gyrandola — APPROVED** [review]

**Comment by Kregle** [comment]
As a physician main, this is a joy.

**Pull request merged**
