### PR TITLE
Crafting refined with basic price re-adjustments.

### PR DESCRIPTION
**Pull request by Red-Honk**
## About The Pull Request

[Items]:

[In-crafting name changes]
Renamed: sewing needle to the thorn sewing needle.
Renamed: bag to sack.

[Item-changes]:
wooden sword recipe now requires: 1 small wood log and 2 fibers in-exchange for giving 3 training wooden swords instead of the original 2.
Wood pipe requires 1 stick instead of a whole small wood log to be carved.

[Item-Addition]:
Added a new recipe called paper parchments (x8) that costs: 30 water, small wood log, requiring a drying rack (which is made with 3 sticks) and a hunting knife acting like a catalyst to be produced.

[Leather]:

[In-crafting name changes]
Renamed: cloth gloves into cloth fingerless gloves.
Renamed: heavy leather gloves into hide gloves.
Renamed: leather pants into leather trousers.
Upping the leather trousers price due to the last PR buffing their values up to their leather armor counterpart + stab crit prevention.

[Adjusting the prices]: 
13 per hide, 15 per fur, 1 per fiber, 2 per cloth, 2 per stone. Fluff -> (Holy attire is exempt and as such shall not gain a price, because those holy cloths are in fact priceless)
Drum to 5.

[Item cost changes]:
Sack hood craft cost from 3 cloth to 2. (Why was it that expensive to begin with?)
Tabard/surcoats/jupons reduced from 3 cloth and 1 fiber to 2 cloth and 1 fiber.

[Item craft result differ]:
Making a satchel now makes 2 instead of 1, using the logic that you need 1 and a half leather to make a satchel, and as such making 2.

Structure.
[Structure cost changes]:
Reducing the railings cost from 1 small log to 2 sticks. (Finally, you can erect several in a row, and not wonder how a chest is the same price while clearly being bigger)
the palisade small log now refunds a stick when build. (It will also spawn a stick where the palisade to be scooped in a pile and sharpened for more defenses, no more net negative because someone wanted to focus on speed instead of sharpening two sticks)
The chest now requires a small log and a stick to be made. (Think of it as hinges)
wooden coffin now renamed to wooden coffin/casket.

## Why It's Good For The Game

Readability, cost making more sense in turn making folk make them more often, things that use to have no value whatsoever can now be sold or put in the vault to vary it up, making those that can make such items searched for employment which will boost roleplay while also giving a sense of purpose as a result.

### CODE REVIEW

**Comment by katsukai** [comment]
Find the final naming choice of
name = "wooden coffin/casket" and 	name = "sack/bag" Kinda odd. Just choose either.

**Comment by Nakalon** [comment]
> Find the final naming choice of name = "wooden coffin/casket" and name = "sack/bag" Kinda odd. Just choose either.

Yeah if the item resulting is a sack make it be a sack!

Standardize names so we don-t get big differences everywhere!

**Comment by Hmeister-real** [comment]
>Wood pipe requires 1 stick instead of a whole small wood log to be carved.

this will destroy the econonmy. Pipes are already one of the best ways to earn money quick giving like, 15 per pipe

**Comment by Hmeister-real** [comment]
>Added a new recipe called paper parchments (x8) that costs: 30 water, small wood log, requiring a drying rack (which is made with 3 sticks) and a hunting knife acting like a catalyst to be produced.

this is.. already a thing? https://github.com/Rotwood-Vale/Ratwood-Keep/blob/033166f008c179520d7edf67c309debb86a5690a/code/modules/roguetown/roguecrafting/items.dm#L445

**Comment by Hmeister-real** [comment]
>the palisade small log now refunds a stick when build.

the log palisade sacrifices that stick for the efficiency of not having to sharpen 2 stakes, this is just stupid

**Comment by Red-Honk** [comment]
> Find the final naming choice of name = "wooden coffin/casket" and name = "sack/bag" Kinda odd. Just choose either.

Different languages use different words, this shall make it easier for both.

**Pull request merged**
