### PR TITLE
Accents 1.7th Edition

### PR DESCRIPTION
**Pull request by Squird5**
## About The Pull Request

A little more accent variety among races to make them less homogeneous ((I hated 100% of elves being Russian)). Also tried to make the formatting more consistent between the JSONs.

Also removed the majority of the non-English words from most lists (Except German), making them more oriented around the sounds they make than simply tossing in foreign words.

## Why It's Good For The Game

More variety in speech patterns is always good. Also, all elves speaking demi-Russian would throw me completely out of character every time I saw "Privyet" or "Da" and I would stop thinking of my own character and instead of my friend's Pathfinder character.

## REFERENCE GUIDE

Accents are now broken into four parts: **Full**, **Start**, **End**, and **Syllable**.

**Full** replaces only entire key words with their counterpart. Any additional characters will prevent it from triggering.
`"watch": "look"` will only apply to "**Watch**", changing it to "**Look**", but variants like "**Watch**ed" or "**Watch**es" will **not** change

**Start** will replace words that start with the key word, regardless of the following characters.
`"watch": "look"` will end up allowing **Watch**ing and **Watch**ed to convert to **Look**ing and **Look**ed

**End** is the opposite of Start. It will apply to characters only at the end of a word. Useful for consistently dropping a letter at the end that would be messy if applied as a Syllable.
`"ing": "en'"` will end up allowing Watch**ing** and Slapp**ing** to convert to Watch**en'** and Slapp**en'**

**Syllable** will apply to any instance of the characters in the text, so use it carefully.
`"a": "aye"` would end up being painful, changing "H**a**ve **a** nice d**a**y" to "H**aye**ve **aye** nice d**aye**y"

### Notes
**Do not** use escape characters for things like apostrophes. `\'` It will work in some cases, but not all, resulting in demihuman accents working fine while the exact same accent list on Humans doesn't.

The **order of your replacers matters**. While having them in alphabetical order might look nice, it can result in unwanted outcomes. If a "c" becomes a "k", and a "k" becomes "kh", words like "Change" turn into "Khhange".

**Always test your work.**

## Change List

* REGEX fixed to allow for different types of replacers, while working reliably and multiple times in a line of text.
* Reformatted Universal without changes
* Reformatted German without changes, adding the new regex fields
* Reformatted Anglish without changes, adding the new regex fields
* Reformatted Middlespeak without changes, adding the new regex fields
* Reformatted Dwarf without changes, adding the new regex fields
* Reformatted Proper without changes, adding the new regex fields
* Changed French, removing most of the full word replacements
* Changed Russian, removing the full word replacements and tweaking some of the quirks
* Readded Spanish
* Changed Italian, removing the vast majority of full words
* Added Welsh, for boondock Elves
* Added Norf, for Londoner Orks, built from heavily modified Dwarf
* Added Inzectoid, for Moths
* Added Tabaxi, based on the Russian accent
* Added Hissy, for lizard things
* Added Lizzerman, for the Sisseans, a hissy-like Brazilian derived accent with Caribbean Spanish quirks

* Additional accents for Humens (and Demi-Humans)
-- Otava use Italian
-- Etrusca use Spanish
-- Ebon use Middlespeak
* Additional accents for Elves; Russian baseline removed
-- Dandelion Creek & Walnut Woods use Welsh
-- Azuregrove & Timberborn use Russian
-- Almondvalle use Anglish
* Additional accents for Drow; French baseline removed
-- Commorah use Anglish
-- Sshanntynlan & Tafravma use French
-- Yuethindrynn use Russian
* Additional Accents for Half Elves
-- Timber-Gronn use Russian
-- Etruscan-Dandelion use Welsh
-- Ebonborn use Middlespeak
* Dwarf is unchanged
* Aasimar is unchanged
* Additional Accents for Half Orcs, maintaining Middlespeak baseline
-- Splitjaw & Blackhammer use Norf
* Additional accents for Tieflings
-- Castillian use Spanish
-- Succubus use Proper
-- Incubus use Middlespeak
* Large Anthromorphs use Anglish as baseline
* Dracon and Kobold use Hissy as baseline
* Sisseans use Lizzerman as baseline
* Fluvians use Inzectoid as baseline
* Tabaxi use Tabaxi as baseline
* Vulpkanin use Proper as baseline

* Italian
Ratwood_Italian

* Spanish
Ratwood_Spanish

* Welsh
Ratwood_Welsh

* Russian
Ratwood_Russian

* French
Ratwood_French

* Norf
Ratwood_Norf

* Hissy
Ratwood_Hissy

* Lizzerman
Ratwood_Lizzerman

* Inzectoid
Ratwood_Inzectoid

* Tabaxi
Ratwood_Tabaxi

### CODE REVIEW

**Comment by Squird5** [comment]
This **_does_** kind of undo #236, but in a way that is likely passable. Rather than just throwing around Spanish words, it's more hissing Ss and rolling Rs.

**Comment by MefAnneFeminene** [comment]
Could you also add that Half-Kins get the accent that they are ancestral to?

So a Grenzelhoft Half-Kin gets a German Accent, like all Grenzelhofts?

**Comment by DorfGuy1** [comment]
> Could you also add that Half-Kins get the accent that they are ancestral to?
> 
> So a Grenzelhoft Half-Kin gets a German Accent, like all Grenzelhofts?

I support this. Qualifications: None. I'm a player that knows how to read shitty byond code and thats it.

**Comment by Squird5** [comment]
I have been off and on trying to add a method to pull a list of accents per race, then select them on the character creation screen, but I don't know enough of any of this to quite pull that off.

Suggestions on how to make that work would be appreciated, otherwise I will just fall back on accents being tied back to skintone.

**Comment by Squird5** [comment]
> Could you also add that Half-Kins get the accent that they are ancestral to?
> 
> So a Grenzelhoft Half-Kin gets a German Accent, like all Grenzelhofts?

This was added in Mod 1, a day before you asked

**Comment by Squird5** [comment]
Went ahead and commented out the changes trying to add in the accent selection system and reenabled the skin_tone based accent system that was already in place, with the expansions and tweaks I added.

**Comment by Squird5** [comment]
> The diffs are weird here, merge upstream/main into this

Nuked the local repo, used commit history to remake it. Should have that fuckery fixed now.

**Comment by CalamaBanana** [comment]
Not the biggest fan of watering down racial identity even more, but please do keep the Russian elf accent on a pale skin at least as well. Timberborn is a very dark skin tone nearly no one uses. 99% of current elf chars are pale, and most of them are used to speaking the Russian accent by now. Please do add it to the Azuregrove skintone as well at least.

**Comment by Squird5** [comment]
Reformatted to adhere to the new Regex rules as per #546

Tested on local, now fully working.

**Comment by Squird5** [comment]
Added change list, pictures, reference guide
Removed the kh from Russian and Tabaxi

**Pull request closed without merging**
