### PR TITLE
Added bog armory keys to boggurds

### PR DESCRIPTION
**Pull request by Jackofashepard**
Title says it all

### CODE REVIEW

**Comment by Cyprex** [comment]
Can be merged in 21h

**Comment by Keazra** [comment]
There should be, like, one key somewhere roundstart for the bogguards to grab in the event of no bogmaster.

**Comment by SayonaraEcho** [comment]
>  It's a massive treasure trove of equipment for literally anyone who wants it and giving a key to every single bogman is a bad idea because of this. It'd also be easy to ambush a single person and get keys to the whole armory and everything in it. It doesn't make sense to make an exception for the bogmen when every other armory is locked behind the garrison captain's keys. I don't think this would be helpful to the Bog Guard and I think it would simply cause more issues with the well-stocked armory they already have.

Do you know that if there's no bog master then bog guards can just easily break the armoury's door in roundstart? There's no point for it. It just takes a little more time to get the gear than just opening the damn door in one second. 
If you're talking about bandits or thieves, they can get into the barracks without keys with ease too, because no one is in them, since the bog guards are sitting on the gate at all times. Bandits usually break a reinforced window on the third floor and climb inside and then go down into the basement to the armoury.

**Comment by Cyprex** [comment]
If this ends up being problematic we'll just revert it.

**Pull request merged**
