### PR TITLE
Shunned races, job eligiblity & Sellswords

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Moves Drows and Tieflings to shunned
Opens a lot of jobs for shunned races: Weaponsmith, Armorsmith, Churchling, Mortician, Dungeoneer, **The Hand**
Orcs were moved to an even worse category than shunned as they are having troubles to fit with society, which mostly has what used to be previously in shunned, but including the Dungeoneer

Adds a new job, called the Sellsword, which is a common, unaligned Mercenary for every species
Grenzel and Desert mercenaries now have much stricter, and selective races:
Desert: Tiefling, Tabaxi, Sissean, Human, Wildkin, Halfkin
Greznel: Lupian, Vulpkian, Fluvian, Dwarf, Drakian, Human, Wildkin, Halfkin

Also gives Dungeoneer 1 medicine skill so he can make incisions with the tools he has lol

Sellsword drip:
UW4HdXXzhm

### CODE REVIEW

**Comment by Elli-Skala** [comment]
I think it may be good to give the shunned races Acolyte aswell so they have a option for higher miricals without adventuers reining king(they still do) but still keep them restricted from templars and priests (because by the ten we need more pestias)

**Comment by Hmeister-real** [comment]
> I think it may be good to give the shunned races Acolyte aswell so they have a option for higher miricals without adventuers reining king(they still do) but still keep them restricted from templars and priests (because by the ten we need more pestias)

thats why clerics exist in adventurer, Acolytes should be respected members of society, thats why Churchlings open because they are less so

**Comment by Alanii** [comment]
Oh no, a vermin/kobold hand

**Comment by pilotmans** [comment]
Why are Axians excluded from the larger Mercenary Guilds?

**Comment by pilotmans** [comment]
> > Why are Axians excluded from the larger Mercenary Guilds?
> 
> They don't like the desert, nor would they fit with Grenzelhofts due to their nature

Why not Grenzlehofts?

**Comment by pilotmans** [comment]
Sellsword of any type seems to go against being settled in any way, after all it is a form of contractor, is it not?

**Comment by pilotmans** [comment]
Fair enough, still a shame to lose the plume, either way does seem like a good improvement on what we had before.

**Comment by Mogurk** [comment]
orks never did anything wrong

**Comment by DeerJesus** [comment]
If you're going to let shunned races be hands, can you also let shunned races be court mages? For the #drow in the chat...

**Comment by DeerJesus** [comment]
> > If you're going to let shunned races be hands, can you also let shunned races be court mages? For the #drow in the chat...
> 
> The Hand has a solid lore justification for why most races could be it. The Court mage, as much as Drows Mages is a staple, not so much. I can see apprentices when I roll out a new system I have planned

What's the lore justification for the hand? They're a noble..?

**Comment by DeerJesus** [comment]
> > > > If you're going to let shunned races be hands, can you also let shunned races be court mages? For the #drow in the chat...
> > > 
> > > 
> > > The Hand has a solid lore justification for why most races could be it. The Court mage, as much as Drows Mages is a staple, not so much. I can see apprentices when I roll out a new system I have planned
> > 
> > 
> > What's the lore justification for the hand? They're a noble..?
> 
> The Hand is the King's best friend, his advisor and spymaster. The Nobility status in the world is granted by Astrata, so it's not something you can only get from birth

Actually yeah I can see the justification. However, the court mage is literally just a hired mage for the court, according to our lore. The king would probably accept it if they had coin.

**Pull request merged**
