### PR TITLE
[Testmerge] Scon2

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
The moggening

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Why is it good for the game

**Comment by pismorizzo** [comment]
Can we stop with the meme PR descriptions beings used to to stop all documentation or explanation of what a PR actually does. 
Purposefully and lazily attempting to hide what a PR does helps nobody

**Comment by IgneGame** [comment]
> Can we stop with the meme PR descriptions beings used to to stop all documentation or explanation of what a PR actually does. Purposefully and lazily attempting to hide what a PR does helps nobody

Tbh, if you look at what there changing.. I don't blame them for not wanting to right it down. I wouldn't either.

**Comment by Useroth** [comment]
> Can we stop with the meme PR descriptions beings used to to stop all documentation or explanation of what a PR actually does. Purposefully and lazily attempting to hide what a PR does helps nobody

Everyone who is actually reviewing it knows what the PR is. I don't see the issue.

**Pull request merged**
