### PR TITLE
Lots of new clothing ported from azure

### PR DESCRIPTION
**Pull request by john-pawson**
## About The Pull Request

As a request of this guy: 
image

Ports some of the clothing from azure keep. These are all the PRs i've managed to find that are related to the clothes: 
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/534
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/916
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/810
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/commit/c24b288d2e2e29e5ff98974f6ab676b862ea20e6

Please tell me if i missed a PR and where to find them, since the guy that asked me to port the things didn't exactly have the PRs from when the icons were added, and this was all i could find.

Anyways, here's a list of all the clothing added, where to find it, and how it looks like:
(Note: All of the silk clothing don't have dwarf sprites, check out the first PR to know why. Would be useful for someone else to make sprites for them on the future though, if we want the short ones to be able to wear them)

All the clothes were added into new files for modularity, in case anyone decides to disable them for whatever reason.
---------**Silk clothing**---------
Silk robes (2 cloth, 3 silk, expert to craft)
image

Silk pants (1 cloth, 3 silk, expert to craft)
image

Silk cloak (1 cloth, 3 silk, expert to craft)
image

Silk gloves (1 cloth, 1 silk, novice to craft)
image

---------**Leather coats**----------
Leather coat (4 cured hides, 1 fur, 1 fiber, expert to craft)
Protection: Blunt protection: 50, Slash protection: 25, Stab protection: 40.
image

Heavy leather coat (4 fur, 1 cured hide, 1 fiber, master to craft)
Blunt protection: 70, Slash protection: 40, Stab protection: 50.
image

(There is an unused detail sprite on the coats, if anyone would like adding the red part being colorable, i did not touch this since this was used as the royal colors for uniforms for the marshals and this PR adds them as common but expensive clothing)

Edit: Hey, ignore this part. Ended up adding it myself. Check out my comment on the PR.
---------**Steward clothing**----------
Steward's tunic (Uncraftable, can be found on the steward's room)
image

Steward's dress (Same as tunic)
image

--------**Rag clothing**----------
Rag mask (1 cloth, no skill)
image

Hand wrappings (1 cloth, no skill)
image

--------**Pestran masks**-----------
Pestra mask (Only pestran acolytes get them)
image

Court physician mask (On his backpack)
image

## Why It's Good For The Game

Adds a bunch of new clothing from azure! Hopefully it'll diversify the amount of clothing we can see used on the server, it also gives some of the roles like the steward or the court physician some variants/different looks without removing or changing any of the existing clothing they already have.

### CODE REVIEW

**Comment by john-pawson** [comment]
Added the customizable part of the leather coats. So ignore the comment i put on them before:
image
Right click them to change the color

**Comment by RadiantFlash7** [comment]
YO I was just thinking about how I wished there was some fancy pants options. All we really had were tights.

**Review by Gyrandola — APPROVED** [review]

**Comment by Gremillion** [comment]
the pestran mask only works if you port the rest of the outfit it's made specifically for. i assume it's the same for the court physician mask also?

image

**Comment by john-pawson** [comment]
> the pestran mask only works if you port the rest of the outfit it's made specifically for. i assume it's the same for the court physician mask also?
> 
> image

Well like i said on the PR, this was all i got sent to add and i don't know where to get the rest of the outfit or where the other PRs are, i didn't even get told what the masks were from. So i decided to give it to pestrans since it fits and they had the necran outfit for some reason. Feel free to send me the PR with the rest of the outfit and i'll see if i can do something later.

**Comment by Gremillion** [comment]
> > the pestran mask only works if you port the rest of the outfit it's made specifically for. i assume it's the same for the court physician mask also?
> > image
> 
> Well like i said on the PR, this was all i got sent to add and i don't know where to get the rest of the outfit or where the other PRs are, i didn't even get told what the masks were from. So i decided to give it to pestrans since it fits and they had the necran outfit for some reason. Feel free to send me the PR with the rest of the outfit and i'll see if i can do something later.

i don't know either, i didnt ask for it. i just wanted to let you know because now my pestran looks BALD and stupid

**Pull request merged**
