### PR TITLE
Recruitment spells icons 

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

- Ports https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/676
379531068-6a6a46fd-ee77-4978-b6d0-b696fea73ac7
379531102-b8dbe132-dd21-42f9-b2a5-89b070751abd

I do look forward to Sinner's stuff.

## Why It's Good For The Game

> Easier to tell which recruitment is for what!
> Monarch's are based on wax seals, priest continues the motif of metal sigils.

### CODE REVIEW

**Comment by Gyrandola** [comment]
> sinner is remaking all of these which is why there are conflicts.

fixed conflicts, giving priority to sinner's sprites where conflicting.

**Comment by Nakalon** [comment]
Going on with this RN?

**Comment by Gyrandola** [comment]
> Going on with this RN?

Its ready

**Review by Nakalon — APPROVED** [review]
epic!

**Pull request merged**
