### PR TITLE
Adds the bog tavern back

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Adds the old bog tavern back into the map, slightly moves the stockpile and shylock position like 10 tiles around, and moves druids spawns a bit south but other than that just fills the empty space left of the bog garrison building

## Why It's Good For The Game

it's comfy

Up close z3
Screenshot 2024-07-18 045629

z3
Screenshot 2024-07-18 045635

z4
Screenshot 2024-07-18 045641

z5
Screenshot 2024-07-18 045646

### CODE REVIEW

**Comment by Alanii** [comment]
I suggest making it less well off. Replace the "lordly doors" with basic doors and the fancier beds with less fancy beds.

Also you may have to add actual roles for this.

**Comment by Teragenic** [comment]
I feel like people will just break in and metarush this for loot since it's out of the way. People already do it with the normal inn.

**Comment by zakanater19** [comment]
> I feel like people will just break in and metarush this for loot since it's out of the way. People already do it with the normal inn.

Yeah.. but without it the bog village just feels barebones and shit

**Comment by DorfGuy1** [comment]
No loot, just vibes and RP. Otherwise it'll be a meta target for sweatheads.

**Comment by zakanater19** [comment]
> No loot, just vibes and RP. Otherwise it'll be a meta target for sweatheads.

i mean the "loot" is just butter and crackers, maybe the barrel of ale

**Comment by zakanater19** [comment]
conflicts, can always reopen later

**Pull request closed without merging**
