### PR TITLE
Update soilson.dm

### PR DESCRIPTION
**Pull request by lalaria1**
I think farmer should be a stronger role, physically, because they eat very well and do a lot of exercise and physical activity.

## Why It's Good For The Game
Soilsons are too weak in the game, they get bullied by everyone and that doesn't make sense. They go to the local inn and practice brawling and fighting every week, eat healthy and do lots of work out in the farm.

A lot of people are very skeptical of my changes and have been vocally against them, so I think it'd be useful to highlight what farmers lack:

Spawns without armor.
No armor training.
Very low weapon skills. (no parrying)
No dodge-expert (no dodging)

These are some of the reasons why I gave them so much end and con, so they can soak punishment since they have no armor or ability to avoid it. I hope that explains my reasoning a bit.

### CODE REVIEW

**Comment by Mannybrado** [comment]
so true brother so true

**Comment by MefAnneFeminene** [comment]
I don't think I need to tell you how dumb it would be for a Farmer to have better hand-to-hand fighting than Monks. To preface, this gives them MASTER fist AND wrestling.

**Comment by wow50000** [comment]
strength four holy fuck.

**Comment by lalaria1** [comment]
> I don't think I need to tell you how dumb it would be for a Farmer to have better hand-to-hand fighting than Monks. To preface, this gives them MASTER fist AND wrestling.

This is my first PR and time editing the code. I could lower the number. Do you have any suggestions on what number you think would be good?

**Comment by X404ErrorX** [comment]
constitution 6 and str 4? thats not a fucking LOT

**Comment by MefAnneFeminene** [comment]
Someone has got to close this PR.

**Comment by Maromar15910** [comment]
Apprentice fist and apprentice wrestling would be good with a +2 str and con MAYBE 3 con. But more is a bit much.

**Comment by Rayforx** [comment]
CIVILIZEDBARBARIAN gives your hands a 15-plus damage modifier on fist damage, plus all the strength.
Strength 4 is the same strength as a knight, which is one of the strongest in the game.
Constitution 6 is just plain stupid, the highest constitution anyone gets in the game is 4.
Endurance 4 I really should not say anything at this point.

Make sure to write all of this info in your PR, people should not NEED to look at the code to understand what is happening.

Instead of giving them dumb stats, then buff their polearm to 2, give them a few leather armor pieces and some spears, and call it a day.
They are not a combat class, if they need help then hire people, or talk with the bog guard, etc

**Comment by Cyprex** [comment]
No. These stat adjustments are way excessive, going beyond what even knights get. You can buff them a little, but this is simply too much.

**Pull request closed without merging**
