### PR TITLE
Nerfs warhammers

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
changes warhammer pick to be stab instead of pick

## Why It's Good For The Game
https://discord.com/channels/1240735983276654733/1240810578029576292/1313959686793461990
requested on discord

### CODE REVIEW

**Comment by john-pawson** [comment]
Alright i definitely think there are better ways to nerf this than making it stab intent. You've basically completely removed pick intent from any weapons on the entire game.
And before you mention pickaxes, they don't have any kind of armor penetration.

Maybe just nerf the pick intent crit chance itself or give certain plate armors pick resistance instead of removing the BLASS altogether? I agree it needs a nerf but this simply makes it so the intent itself will probably never be used.

**Comment by wow50000** [comment]
I don't really care either way, someone asked me to make this.

**Comment by john-pawson** [comment]
> I don't really care either way, someone asked me to make this.

Ok then. To whoever asked for this:

Go read the first comment i made.

**Comment by Heheniy** [comment]
when did 'someone asked on discord' became valid argument?

**Comment by Gyrandola** [comment]
i need to ban balance prs

**Pull request closed without merging**
