### PR TITLE
Removes Bandit Love Potion, replaces it with 2 Firebombs

### PR DESCRIPTION
**Pull request by GuppyLaxx**
What it says on the title.

The love potions were a f***ing mistake.

### CODE REVIEW

**Comment by EzekyalLegit** [comment]
I think the interaction between bandit and love potion WAS interesting. I wonder if it could be changed so its 10% chance a love potion and 90% a firebomb.

**Comment by EzekyalLegit** [comment]
One example of the value of love potion for bandits was how it could simulate stockholm syndrome in a captive worker. Usually captives often betray the camp with a reckless abandon, losing their life to lash out at the bandits. With this potion the captive slave was able to be given a firm reason to obey the camp and actually play along, Instead of trying to behead sleeping bandits or sneaking out to lead the keeps army into the camp.

The bandits just DONT have the manpower to corral slaves properly so this potion was a nice IC workaround.

**Comment by radarseas** [comment]
why not push them up with the matthios dragonscale necklace reward instead? they DO lead to interesting gameplay but it was far too early.

Maybe put firebombs at T3... I think bandits luring the keep's army out and just absolutely critting all of them by spamming firebombs is urm... a little bit of a balance issue for something you can do early into the round.

**Comment by kepesk1** [comment]
this guy makes some of the goofiest PRs

**Comment by wow50000** [comment]
I understand why you are removing them but dont replace them with fire bombs lmao

**Comment by Takoros** [comment]
love potion are cool, dont remove that

**Comment by DorfGuy1** [comment]
And he merged it anyway.

**Pull request merged**
