### PR TITLE
Remove skeleton organs

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Title.

## Why It's Good For The Game

1. It makes no sense.
2. The Gock economic crash.

### CODE REVIEW

**Comment by Heheniy** [comment]
they are not starting to die immediately?

**Comment by Gyrandola** [comment]
> they are not starting to die immediately?

didnt seem to. Maybe I should have tested it longer

**Comment by Nakalon** [comment]
I'd use this as an alternative to the organs rotting instantly. Could that be done instead?

**Comment by Gyrandola** [comment]
> I'd use this as an alternative to the organs rotting instantly. Could that be done instead?

what exactly?

**Comment by Nakalon** [comment]
> > I'd use this as an alternative to the organs rotting instantly. Could that be done instead?
> 
> what exactly?

Wait I'm stupid. If it's a skeleton the organs got eaten away!!!!

**Comment by Nakalon** [comment]
Did you test this? Everything works normal?

**Comment by Gyrandola** [comment]
> Did you test this? Everything works normal?

I tested npcs and direct control of npcs and I wasnt exactly dying.

**Comment by Nakalon** [comment]
> > Did you test this? Everything works normal?
> 
> I tested npcs and direct control of npcs and I wasnt exactly dying.

thank god I don't want you to die

**Review by Nakalon — APPROVED** [review]

**Pull request merged**
