### PR TITLE
nukes grappling into the earth

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

image

grappling is now so much harder

basically #856 which i closed because guppy's seemed promising, but i am now taking that back as guppy's didn't do jack shit to nerf this.

but like 3x more of a nerf
## Why It's Good For The Game

sick of legitimately every person using grapple fu in our swords and guns fantasy combat system. three nerfs and nothing worked.

What is the point of all these swords and cool weapons if grappling is just. Always better. Getting pinned means you are OVER.

it has gotten to the point where **every** class gets wrestling skill because that is how you 'counter wrestling'. atrocious really

The 'but our non-lethal takedown!' argument is moot - All city watch members get a stunmace that can do the same thing, and is far more balanced than every single man, woman and child having an effective batong in the palm of their hands

### CODE REVIEW

**Comment by DelineFortune** [comment]
So no non lethal takedowns and we are supposed to stop people stabbing their necks?

**Comment by DeerJesus** [comment]
> So no non lethal takedowns and we are supposed to stop people stabbing their necks?

you ever heard of chains?

**Comment by DelineFortune** [comment]
How are we supposed to stop aggressive 100500 combat roles as maa, templar or knight then? Those roles have no stunmaces. But we have spear/sword to cut their leg off.

Also there is no watchmen on low pop, only 1-2 knights, 1 templar and 1-2 vanguards. What are we supposed to do again bandits/adventurers/mercs? Stop them with lethal force?

**Comment by DeerJesus** [comment]
> How are we supposed to stop aggressive 100500 combat roles as maa, templar or knight then? Those roles have no stunmaces. But we have spear/sword to cut their legs off.
> 
> Also there is no watchmen on low pop, only 1-2 knights, 1 templar and 1-2 vanguards. What are we supposed to do again bandits/adventurers/mercs? Stop them with lethal force?

if bandits are coming for you at low pop? Yes! You should probably do something lethal to them! Same with the other aggressive 100500 combat roles! This isn't fucking ss13 where the antag needs to spend 5 minutes in the brig after being read his lawyer rights

**Comment by RadiantFlash7** [comment]
This is a pure salt PR to be frank.
Grabbing since the start of the server has been reworked and then nerfed repeatedly.
Wallthrowing doesn't exist. Grabbing and dragging to a wallis hard now,
Pinning someone is difficult If a role has journeyman wrestling, pinning that person will be difficult unless you have master wrestling.
Not to mention grabbing is already parriable, and dodgeable.

**Comment by Gyrandola** [comment]
This PR got ratiod

**Pull request closed without merging**
