### PR TITLE
Nerfs Dendor as a patron and changes kneestinger spell

### PR DESCRIPTION
**Pull request by GuppyLaxx**
This PR removes dendor's kneestinger immunity and the conjure kneestingers spell

Instead, dendorites get a trait that lets them walk through weepvines easier, and the spell is replaced with one that makes a wall of weepvines infront of them in a 3x1 row.

Also, this PR adds the evil tree into the spawning pool of the bog

### CODE REVIEW

**Comment by CalamaBanana** [comment]
This is not the way to go about this. The kneestinger spell should just be changed to be less combat-castable with either a long warmup where one needs to remain standing still or growth time for the seedlings on the ground. Lighting your Dendorite commune with kneestingers is great, using them in your defenses is great. (Not like kneestingers can't be easily removed if one brings a stone knife or a torch)

Besides, there are Dendorites that are not clerics. Why would you make the Dendor-perk apply to something that only clerics have now? Let us keep the immunity against kneestingers. No reason to rip that out completely. Kneestingers exist on the map.

**Comment by radarseas** [comment]
I think a better idea would be keep the kneestinger spell but rework it so you can cast a growth at a spot instead, with a small windup time and a brief grace period once its placed, so you can still use it for offensive or defensive utility like blocking off an exit, just not for an immedate win stun.

That and cheapen it down to compensate for a nerf, kneestingers should still stay, I hate to say it, they are a staple of fighting dendorites in combat.

**Comment by DorfGuy1** [comment]
I've only ever seen weepvines ONCE. Don't nerf Dendorites for the sins of a few people that should have not been able to play clerics anyway. The Druids especially don't deserve it. If I'm not mistaken they still gain devotion slower from a previous kneestinger nerf.

**Comment by SixplyDev** [comment]
I frankly think this is an incredibly based change and should cut down on Dendor patron abuse. Thank you

**Comment by DorfGuy1** [comment]
Is that charge time in seconds or what, because it's either two or twenty seconds, either way, wtf. If it takes that long it'll barely be usable. Summoning vines to entangle your enemy is a dangerously based idea for a Dendor spell though.

**Comment by CalamaBanana** [comment]
If you rip out the kneestinger spell, there is no reason to remove the immunity alongside it. There are not-Cleric Dendorites playing it for the vibe, no reason to not have them get any benefits from it anymore. 

Kneestingers spawn in the wild, it's a cute little thematic benefit for Dendorites to have a very very subtle advantage when sproinking through the bog. No reason to not have both vine and stinger immunity.

(Once more, unlimited adventurers are the problem tempting to make the game worse for everyone else. The current kneestinger spell would have been perfectly fine if it were druid only.)

**Pull request merged**
