### PR TITLE
Drugs. Salt. Drugs and Salt.

### PR DESCRIPTION
**Pull request by Luctus-Comptus**
made ozium, moondust and salt craft able

### CODE REVIEW

**Comment by burdwatcher** [comment]
Just going to add a side note here that in striving to make this like your average ss13 code base where you can craft everything you also undermine the value of coin, sometimes it's better to have things uncraftable.

**Comment by Moribun** [comment]
> Just going to add a side note here that in striving to make this like your average ss13 code base where you can craft everything you also undermine the value of coin, sometimes it's better to have things uncraftable.

these items are worth 5 mammoms when crafted. the value of what goes in is worth more than what comes out. if ya had looked at the sale value before talking.

**Comment by Gr33d-y** [comment]
holy based. What skill does it take to craft?

**Comment by burdwatcher** [comment]
> > Just going to add a side note here that in striving to make this like your average ss13 code base where you can craft everything you also undermine the value of coin, sometimes it's better to have things uncraftable.
> 
> these items are worth 5 mammoms when crafted. the value of what goes in is worth more than what comes out. if ya had looked at the sale value before talking.

That's not what I'm talking about. What I'm talking about is that in introducing more items to be crafted you're reducing the value of money as people can just work around buying it in the first place. Everyone is already covered in mammom, not everything has to be craftable.

**Comment by Moribun** [comment]
> holy based. What skill does it take to craft?

alch novice for salt, alch journey for drugs.

**Comment by Moribun** [comment]
> > > Just going to add a side note here that in striving to make this like your average ss13 code base where you can craft everything you also undermine the value of coin, sometimes it's better to have things uncraftable.
> > 
> > 
> > these items are worth 5 mammoms when crafted. the value of what goes in is worth more than what comes out. if ya had looked at the sale value before talking.
> 
> That's not what I'm talking about. What I'm talking about is that in introducing more items to be crafted you're reducing the value of money as people can just work around buying it in the first place. Everyone is already covered in mammom, not everything has to be craftable.

Im sorry should I further expand upon the fact this is a precursor to an advancement in alchemy I plan to do in the future when I add an alembic and this is used as base items in crafting new things? or would you rather pay 44 mammons per ozium for crafting an item worth maybe 15? your argument is moot.

**Comment by Wildwestmars** [comment]
Hell yeah! Making alchemists feel more like alchemists, a rare skill that is under-utilized.
I hope you continue to add more crafting recipes like this in the future.

**Pull request merged**
