### PR TITLE
No more bm'able spells

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
Removes purge, due to it being an instant artery
there are some chems that need to be purged to be removed, I couldnt find those chems but they should be called something like "purifying elixir" 
probably missed some other things but this is a slop job to fix something absolutely horrendous to the game

## Why It's Good For The Game
Instant artery spell with no counterplay is coal, thanks mori

### CODE REVIEW

**Comment by Nakalon** [comment]
No SLOOOP.

Can't you just make it not cause an artery rupture?

**Comment by wow50000** [comment]
> No SLOOOP.
> 
> Can't you just make it not cause an artery rupture?

I'm too pissed to fix his mistakes

**Comment by Purpleturtle3** [comment]
People, read:

https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1411

**_*removed artery wound effect from purge. again tired of this shit. this is why you dont get cool things. get a boring ass purge._**

**Comment by john-pawson** [comment]
> People, read:
> 
> #1411
> 
> **_*removed artery wound effect from purge. again tired of this shit. this is why you dont get cool things. get a boring ass purge._**

Well, problem is that that's a straight lie. If you read the code it doesn't remove the artery wound at all, it just removes the 30 dmg it does with it.

These are the patchnotes:
Captura de pantalla 2024-11-07 192344
Top: Artery wound (Untouched)
Red: Changed description
Green: Changed description
Unchanged line
Red: Deleted BRUTE damage

**Pull request closed without merging**
