### PR TITLE
Alternative Latejoin location: The Carriage

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

- Ports https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/598.

Adds a new location for latejoining, the carriage. It is located south west of the town, in that sewer/swamp area previously unused. It's a 50 50 whether you spawn by the boat or here.
image

## Why It's Good For The Game

Flavor

### CODE REVIEW

**Comment by Nakalon** [comment]
Sorry Gyran, not at home, can you show me in the map where this is located?

**Comment by Gyrandola** [comment]
> Sorry Gyran, not at home, can you show me in the map where this is located?

not sure why the map changes didnt push. anyway
image

**Comment by Nakalon** [comment]
> > Sorry Gyran, not at home, can you show me in the map where this is located?
> 
> not sure why the map changes didnt push. anyway
> image
> 

They didn't? I can't see Mapdiff bot on mobile it's a pain... This looks cool!

**Comment by Kepteyn** [comment]
I love how https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1493 made this PR entirely redundant only a week later by moving all latejoins to outside the bog gate, just leaving behind a carriage with fucked up collisions you can walk right through (the collision is marked in red below, with everything else being walkable turf).
Uintitled

**Pull request merged**
