### PR TITLE
The Onager + Multistage crafting system 

### PR DESCRIPTION
**Pull request by Gyrandola**
## Multistage crafting system
A compact system that allows contributors to define new structures that need to be built piece by piece (stage by stage), providing a more interesting and complex crafting experience. The onager is the first example of a multistage structure.

## The Onager

- Add the onager, a refactored version of the catapult from Helmsguard, originally made by Feralape / Gisela.
The refactored version includes new sprites made by SinnerPen, and working ammo overlays.
image
image

### HOW TO CRAFT IT
1) Build the first stage using the normal crafting menu. (Carpentry 2, 10 stones, 10 wood planks)
2) Build the second stage by clicking the unfinished onager with a hammer (Carpentry 3, 5 iron ingots)
3) Build the third stage by clicking the unfinished onager with a hammer (Engineering 3, 7 ropes, 5 bronze gears)
4) Build the ffourth stage by clicking the unfinished onager with a hammer (Blacksmithing 3, 4 steel ingots)

https://github.com/user-attachments/assets/044d2846-32f3-4d3e-8de0-8d1a6d95403f

### Proof of testing

https://github.com/user-attachments/assets/933a8ce8-2c6b-4836-a9aa-200de839b36d

### CODE REVIEW

**Comment by Feralape** [comment]
crying-guy

**Comment by Feralape** [comment]
Screenshot 2024-11-21 214718

twist the knife in my back why dont ya

**Comment by Gyrandola** [comment]
Stop harassing me on every PR. All the credits are here.

**Comment by Feralape** [comment]
Screenshot 2024-11-21 214753
thief

**Comment by Feralape** [comment]
Screenshot 2024-11-21 214718
thief

**Comment by Feralape** [comment]
Screenshot 2024-11-21 214718
shameless, no morals, absolute scum

**Pull request closed without merging**
