### PR TITLE
Prosthetics

### PR DESCRIPTION
**Pull request by OrangeDecay**
Adds several craftable and smithable prosthetic types for both legs and arms.
Adds ability to connect and disconnect them.

### CODE REVIEW

**Comment by SugarBone** [comment]
Get a LIFE(web), bro

**Comment by Gr33d-y** [comment]
what does it take to craft these? I feel like it should be rather difficult honestly.

**Comment by Gr33d-y** [comment]
> > what does it take to craft these? I feel like it should be rather difficult honestly.
> 
> you can already buy prosthetics from the Merchants (they're pretty cheap)

Yes but I mean the limbs that are BETTER THAN FLESH YAWET

**Comment by Frick-Frack** [comment]
> what does it take to craft these? I feel like it should be rather difficult honestly.
A bar of iron or steel depending on the arm and a gear. For the clockwork prosthetic it's a bar of gold and three gears. The base wooden arm for reference requires a small log and a gear.

No need to make them so complicated. They're only meant to be more durable versions of the wooden arm. Only the Clockwork one allows for fine manipulation and it's as fragile as the wooden arm.

**Comment by Gr33d-y** [comment]
> > what does it take to craft these? I feel like it should be rather difficult honestly.
> 
> A bar of iron or steel depending on the arm and a gear on a anvil. For the clockwork prosthetic it's a bar of gold and three gears. The base wooden arm for reference requires a small log and a gear.
> 
> No need to make them so complicated. They're only meant to be more durable versions of the wooden arm. Only the Clockwork one allows for fine manipulation and it's as fragile as the wooden arm. A normal living arm will always be superior to having a prosthetic, so they aren't really meant to be seen as a _upgrade_.

With vices being a lot more impact full, those who take the wood arm vice should not have an easy way out imo. It's likely that the only arm that might need a little extra work to get would be the Clockwork one. Nothing to fancy, just some expensive stuff like gold for internals perhaps?

**Comment by Frick-Frack** [comment]
> > > what does it take to craft these? I feel like it should be rather difficult honestly.
> > 
> > 
> > A bar of iron or steel depending on the arm and a gear on a anvil. For the clockwork prosthetic it's a bar of gold and three gears. The base wooden arm for reference requires a small log and a gear.
> > No need to make them so complicated. They're only meant to be more durable versions of the wooden arm. Only the Clockwork one allows for fine manipulation and it's as fragile as the wooden arm. A normal living arm will always be superior to having a prosthetic, so they aren't really meant to be seen as a _upgrade_.
> 
> With vices being a lot more impact full, those who take the wood arm vice should not have an easy way out imo. It's likely that the only arm that might need a little extra work to get would be the Clockwork one. Nothing to fancy, just some expensive stuff like gold for internals perhaps?

You're really overselling the small benefits that they offer. The normal Iron and steel arms are only slightly better durability wise and you require *expert* engineering for the clockwork. Which is already a investment of it's own. That's not to mention the prosthetic legs which hobble you and slow you down. This was made pre-vices change and it really shouldn't change anything aside from adding roleplay value.

**Comment by Gr33d-y** [comment]
> > > > what does it take to craft these? I feel like it should be rather difficult honestly.
> > > 
> > > 
> > > A bar of iron or steel depending on the arm and a gear on a anvil. For the clockwork prosthetic it's a bar of gold and three gears. The base wooden arm for reference requires a small log and a gear.
> > > No need to make them so complicated. They're only meant to be more durable versions of the wooden arm. Only the Clockwork one allows for fine manipulation and it's as fragile as the wooden arm. A normal living arm will always be superior to having a prosthetic, so they aren't really meant to be seen as a _upgrade_.
> > 
> > 
> > With vices being a lot more impact full, those who take the wood arm vice should not have an easy way out imo. It's likely that the only arm that might need a little extra work to get would be the Clockwork one. Nothing to fancy, just some expensive stuff like gold for internals perhaps?
> 
> You're really overselling the small benefits that they offer. The normal Iron and steel arms are only slightly better durability wise and you require _expert_ engineering for the clockwork. Which is already a investment of it's own. That's not to mention the prosthetic legs which hobble you and slow you down. This was made pre-vices change and it really shouldn't change anything aside from adding roleplay value.

I do love these items and their recipes are pretty much where they should be, a bit sleepy so I did miss the clockwork arm recipe being perfect actually...
This looks great all In all! It always has, I just wanted to stick my head in and ask some stuff.

**Comment by Frick-Frack** [comment]
> > > > > what does it take to craft these? I feel like it should be rather difficult honestly.
> > > > 
> > > > 
> > > > A bar of iron or steel depending on the arm and a gear on a anvil. For the clockwork prosthetic it's a bar of gold and three gears. The base wooden arm for reference requires a small log and a gear.
> > > > No need to make them so complicated. They're only meant to be more durable versions of the wooden arm. Only the Clockwork one allows for fine manipulation and it's as fragile as the wooden arm. A normal living arm will always be superior to having a prosthetic, so they aren't really meant to be seen as a _upgrade_.
> > > 
> > > 
> > > With vices being a lot more impact full, those who take the wood arm vice should not have an easy way out imo. It's likely that the only arm that might need a little extra work to get would be the Clockwork one. Nothing to fancy, just some expensive stuff like gold for internals perhaps?
> > 
> > 
> > You're really overselling the small benefits that they offer. The normal Iron and steel arms are only slightly better durability wise and you require _expert_ engineering for the clockwork. Which is already a investment of it's own. That's not to mention the prosthetic legs which hobble you and slow you down. This was made pre-vices change and it really shouldn't change anything aside from adding roleplay value.
> 
> I do love these items and their recipes are pretty much where they should be, a bit sleepy so I did miss the clockwork arm recipe being perfect actually... This looks great all In all! It always has, I just wanted to stick my head in and ask some stuff.

All good! Glad to get feedback on this.

**Comment by CalamaBanana** [comment]
There is a visual bug with them, it seems. Rolling "Missing Arm (L)" as random flaw, everything worked on the backend, I believe. But visually, I had the wrong arm applied. My good arm (R) was covered up by the prosthetic, and my missing arm (L) was just missing visually.

See also here:
https://github.com/Rotwood-Vale/Ratwood-Keep/issues/828#issue-2478439330

**Comment by OrangeDecay** [comment]
> There is a visual bug with them, it seems. Rolling "Missing Arm (L)" as random flaw, everything worked on the backend, I believe. But visually, I had the wrong arm applied. My good arm (R) was covered up by the prosthetic, and my missing arm (L) was just missing visually.
> 
> See also here: [#828 (comment)](https://github.com/Rotwood-Vale/Ratwood-Keep/issues/828#issue-2478439330)

Only in setup character window or the game itself displayed it incorrectly as well?

**Comment by OrangeDecay** [comment]
Okay so dmi's i was provided with had left prosthetic icons swapped with right ones, notified responsible.

**Comment by Useroth** [comment]
We'll fix it in another PR

**Comment by CalamaBanana** [comment]
The smithy recipes are not craftable either. At least the golden one misses the line about the category.

**Pull request merged**
