### PR TITLE
The long over due spear nerf

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request
Nerfs (standard) iron spear damage by 7,

Drops ap factor from 50 to 30 for iron spear stab (used by lucerne and bardische as well)
increases spear stab charge from 1 to 1.5

## Why It's Good For The Game
Spears are currently the meta weapon for a reason. They're too good. They have great defense, highest damage, 50 AP, 2 tile reach, AND can aim for hands and feet reliably. They also prevent slowdown in rough terrain. It's oppressive, how much better spears are then other options. This PR aims to adjust some of that.

### CODE REVIEW

**Comment by katsukai** [comment]
Isn't that basically any polearm. Minus the AP

**Comment by RadiantFlash7** [comment]
> Isn't that basically any polearm. Minus the AP

Most polearms

> Isn't that basically any polearm. Minus the AP

Spear stab charge increase is for every polearm. The damage and AP reduction changes only affect iron spears.

**Comment by RadiantFlash7** [comment]
> > > Isn't that basically any polearm. Minus the AP
> > 
> > 
> > Spear stab charge increase is for every polearm. The damage and AP reduction changes only affect iron spears.
> 
> Meant your argument about spears hitting feet and hands.

Most polearms are subtypes of spears.

**Comment by zakanater19** [comment]
probably a good idea to remove whatever it is giving the speed buff on rough terrain too from the other polearms, except the wooden staff that some pilgrims/advens spawn with

**Comment by DorfGuy1** [comment]
i'd like to point out that spears are literally THE meta weapon for the vast majority of human history. Also why wouldn't they help with terrain. if this is all for default iron spear thou, fuck it. Just wish steel spear and iron spear didn't look exactly the same last time I checked.

**Pull request merged**
