### PR TITLE
PSYDON IS DEAD, enforces the divine will of the TEN

### PR DESCRIPTION
**Pull request by Dedwolf**
## About The Pull Request

Psydon is long dead, father to the Ten he may be, the creatures made in the image of the pantheon shall take their rightful place as the inheritors of this land.

Removes humans and humanoids from noble roles. Enforces higher roleplay standards. Enables interesting and new interpretations of racism that'll make blackstoners truly understand the meaning of grimdark. 

## Why It's Good For The Game

May the children of Dendor, Noc, Astrata and Xylix reign forevermore.

### CODE REVIEW

**Comment by SayonaraEcho** [comment]
Based.

**Comment by kepesk1** [comment]
Turbo based.

**Comment by radarseas** [comment]
this is so cursed, I love it.

**Comment by MefAnneFeminene** [comment]
FINALLY!

This server is for the FURRIES.

You HUMANS are only here because WE let you be here.

**Comment by ThatReformedEngineer** [comment]
This a terrible and hilarious reversal, but I don't expect it to be merged... Unless like Humens end up becoming a sort of antag which would be equally amusing.

**Comment by Keazra** [comment]
My assumption is that this is a kind of story-based event that may change in the future, yes? If so - this is great and I enjoy it. If it’s meant to enforce furry supremacy in perpetuity, I’m not sure I like it.

**Comment by Coolgat3** [comment]
> I'd like to see it test merged, at least as a social experiment.

gyran said it themselves, speedmerge pls

**Comment by JGlitch** [comment]
Honestly it's always been a constant, human-only servers always exists, but I have never seen furry-only servers... When we do allow humans around, they're very anti-furry. So why not turn the tables? Sure I'm all down for it.

**Comment by SixplyDev** [comment]
Cursed-ass PR. There needs to be a balance, + there's too many furry races rn for it to be defined. Sorry man I'm usually all for more IC racism but not this time. Comes across as more of a salt/retribution PR than one intended for the health of the server

**Comment by SixplyDev** [comment]
> > Cursed-ass PR. There needs to be a balance... [snip]
> 
> I'd like to see a real explanation for why there needs to be a "balance" of this kind on Ratwood of all places, and how having you pick one of the allowed races to be a noble is detrimental to server health. Please, explain.

You people support this but not the other PR that did the exact same thing but for respected races? It's hypocritical to support a PR that changes even more than the one that it's mocking, a PR that made minimal changes that were in-line with fantasy racism. Like Useroth said there, it's not good or healthy for roles to just be removed with no exclusive alternatives for the people being locked out of the roles.

**Comment by MefAnneFeminene** [comment]
> You people support this but not the other PR that did the exact same thing but for respected races? It's hypocritical to support a PR that changes even more than the one that it's mocking, a PR that made minimal changes that were in-line with fantasy racism. Like Useroth said there, it's not good or healthy for roles to just be removed with no exclusive alternatives for the people being locked out of the roles.

Yes, because Ratwood is a furry server. This has always been a furry-friendly and furry-run server, and people who only play Humans have been magically appearing claiming "This isn't a furry server! This is just a server with furries!" and have been using it to justify their irrational malice towards furries.

The original PR wasn't actual fantasy racism, it was just OOC furry-hate. There was no IC aspect to it, because these people hate furries OOCly. I agree that there should be more fantasy IC racism, but I don't think the FURRIES should be the second class citizens in the FURRY server.

It creates a cooler scenario where the Humans are not the ones who are racist, but the furries. Every fantastical setting does racism the same way where it's Humans who are racist, (and parrot many themes of white supremacy but that's a conversation for another day), rather than the Humans being second-class and another race being the culturally "superior" race.

**Comment by pilotmans** [comment]
is this a shitpost of the human only nobles pr?
seriously wtf?
sobachka

**Comment by SixplyDev** [comment]
> > You people support this but not the other PR that did the exact same thing but for respected races? It's hypocritical to support a PR that changes even more than the one that it's mocking, a PR that made minimal changes that were in-line with fantasy racism. Like Useroth said there, it's not good or healthy for roles to just be removed with no exclusive alternatives for the people being locked out of the roles.
> 
> Yes, because Ratwood is a furry server. This has always been a furry-friendly and furry-run server, and people who only play Humans have been magically appearing claiming "This isn't a furry server! This is just a server with furries!" and have been using it to justify their irrational malice towards furries.
> 
> The original PR wasn't actual fantasy racism, it was just OOC furry-hate. There was no IC aspect to it, because these people hate furries OOCly. I agree that there should be more fantasy IC racism, but I don't think the FURRIES should be the second class citizens in the FURRY server.
> 
> It creates a cooler scenario where the Humans are not the ones who are racist, but the furries. Every fantastical setting does racism the same way where it's Humans who are racist, (and parrot many themes of white supremacy but that's a conversation for another day), rather than the Humans being second-class and another race being the culturally "superior" race.

The server isn't furry-run and it's been stated multiple times by the headmins that the server is NOT a furry server. Pictures have been attached below that support these claims as well, people simply aren't entitled to having their furry sparkledog OCs everywhere they want them. If you have any other ideas on how we could actually get some proper xenophobia or IC racism in Ratwood, I'd love to discuss them with you but it feels like a lot of people cheering on this PR are doing so in bad faith.
image_2024-09-15_150843962
image_2024-09-15_150850767
image_2024-09-15_150816371

**Comment by Jovian8991** [comment]
Looks great, can't wait to see it in-game.

**Comment by kokokokokokokokokokokokokokoko** [comment]
finally some good pr here, god bless your soul, buddy.

**Comment by Hmeister-real** [comment]
why is this, not closed. joke PR is living longer than the actual PR before it

**Comment by DorfGuy1** [comment]
Wood elves are the children of Dendor too!

**Comment by kepesk1** [comment]
Still looking forward to this. :)

**Comment by Kepteyn** [comment]
Also looking forward to this.

**Comment by Kepteyn** [comment]
Ratwood truly has fallen.

**Comment by pilotmans** [comment]
Glad to see this shitpost laid to rest, though for people arguing that this was good with sincerity in mind? Kindly get yourself fucking fixed, just cause you've been fucked over doesn't mean you can fuck over others in spite, act mature cause this was dumb from the start.

**Pull request closed without merging**
