### PR TITLE
Fixes Hand allowing shunned races

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

nuf' said. Kobold Hand was fun while it lasted, but man was it stupid

## Why It's Good For The Game

Kobold being royalty is bad for so many reasons, especially one as important and commanding as the Hand

### CODE REVIEW

**Comment by Takoros** [comment]
Kobolds already are restricted by half of the roles, dont take one more.

**Comment by Hmeister-real** [comment]
> Kobolds already are restricted by half of the roles, dont take one more.

sorry Takoros but being a noble is bad... i do like your bog master PR though, hopefully it gets merged with this to balance things out

**Comment by pilotmans** [comment]
Agree with this, I should not be able to either easily kill the hand to steal their keys or deal with the fact that somehow a kobold outranks me, it's fun but also rather annoying to role play with especially if they have the whole (kobolds are stupid) shtick

**Comment by Takoros** [comment]
> sorry Takoros but being a noble is bad... i do like your bog master PR though, hopefully it gets merged with this to balance things out

Well.. If my PR is merged and this one too.. it might.. be okay i guess.. but if only this one, it will be sad.

**Comment by LocalizedDownpour** [comment]
Hand allowing any Race should be allowed as it's basically the Kings chosen friend. The King can 'choose' a shunned person if they want to. Also I don't think the Hand is mechanically a noble.

**Pull request closed without merging**
