### PR TITLE
Adds Lupians as a selectable race

### PR DESCRIPTION
**Pull request by Dedwolf**
## About The Pull Request

This PR adds Lupians as a selectable race and provides some limited lore when selecting them as a species.

## Why It's Good For The Game

Lupians were outlined in the lore draft but weren't present in game. Lupians should be expanded upon further and Ive noticed a few people complaining that furry species don't have funny accents nor much depth like the other races. 

I will be accepting lore feedback and suggestions, and could even expand this PR to give them an accent and additional lore.

They are currently balanced slightly below that of Stagrawl's racial balancing PR which gives most species +2 overall, Lupians currently have a +1 to their stats overall. https://github.com/Rotwood-Vale/Ratwood-Keep/pull/160

### CODE REVIEW

**Comment by Stagrawl** [comment]
I've removed Strongbite from the races that had it as some concerns were raised about the specific of the trait. Nasty-Eater itself should suffice though?

Obviously, don't take my word as final, it isn't.

**Comment by TheRealRatMan** [comment]
ay put messy eater back, and fix the stats. As is this race is the shittiest of all due to the nerf, even half elf is preferable to lupian. and make there stats focus more on physical attributes, lupians should have higher endurance.

**Comment by Wildwestmars** [comment]
This is true! The veteran should have bad stats, but, the Kobold Servant who looked at me and realized they were stronger then me is a *bad* sign.

**Comment by Wildwestmars** [comment]
I do think it's a little odd creatures blessed by Noc have a Pestra-related ability, but, I do think the nerf is too much.

**Comment by JhinHandaGay21** [comment]
@Dedwolf 
specstats = list("strength" = 1, "perception" = -1, "intelligence" = -1, "constitution" = 2, "endurance" = 1 "speed" = -1, "fortune" = 0) 
	specstats_f = list("strength" = 1, "perception" = -2, "intelligence" = -1, "constitution" = 1, "endurance" = 1, "speed" = 1, "fortune" = 0) ??

**Comment by JhinHandaGay21** [comment]
> > @Dedwolf specstats = list("strength" = 1, "perception" = -1, "intelligence" = -1, "constitution" = 2, "endurance" = 1 "speed" = -1, "fortune" = 0) specstats_f = list("strength" = 0, "perception" = -2, "intelligence" = -1, "constitution" = 1, "endurance" = 2, "speed" = 1, "fortune" = 0) ??
> 
> wrong image

It was a suggestion. You're trying to create something based on physical superiority, so I'm offering you these stats.

**Comment by Hmeister-real** [comment]
> they're not based on physical superiority, they merely have different physiology. wolves are intelligent and social animals, they're also great endurance hunters and like all canids have bad eyesight compared to humans so i've reflected that in their stats and their lore.

Stats shouldn't soley be based on sthe IRL characteristics 😞 sure they can be "smart" and social in the wild, but they are still very stupid compared to people, you don't call a Human person smart just for being social and knowing basic maths, you would call them stupid, same goes for volfs that stand up. I suggest you either make them proper volf people, beastish and stupid, or just make them strong and have unchanged intelligence. Personally strong beastpeople + racism (same as kobold and orc) would be good for Lupien, but definitely not both combat + smarts thats just stupid and broken.

**Comment by DeerJesus** [comment]
when you select Lupian the brief lore dump states they specifically view other races as "meat" and tend to kill and eat other races.

This race, under the current lore, needs to be given the verminvolk/horc/kobold treatment of 'shunned' race and given the same job restrictions.

@Useroth

**Comment by DeerJesus** [comment]
> > when you select Lupian the brief lore dump states they specifically view other races as "meat" and tend to kill and eat other races.
> > This race, under the current lore, needs to be given the verminvolk/horc/kobold treatment of 'shunned' race and given the same job restrictions.
> > @Useroth
> 
> What are you talking about? nowhere here does it mention them considering them meat?? genuinely, what made you come to this conclusion? image

okay i guess i was fucking lied to nvm disregard my comment

**Pull request merged**
