### PR TITLE
Lowers the amount of mortician slots to 1 because we don't need three guys running around the map doing the job of 1 man attempting to PQ farm

### PR DESCRIPTION
**Pull request by Slorbin**
Mortician doesn’t really need multiple slots, and suffers from it. Too many cooks spoil the broth and too many morticians result in a much higher chance of one acting catastrophically just as an attempt to PQ farm. By lowering the slots to 1, maybe we’ll restrict the flow and ensure that only people who actually want to roleplay as a Mortician get it as opposed to people who wander around the map looking for dead bodies. 

Lower slots might mean the selected mortician player actually tries for their role when they get it - actually speaking to the dead, actually doing burial rites properly, et cetera.

### CODE REVIEW

**Comment by stutwoby** [comment]
Rage PR, we should be looking at how to give PQ for burying players with their heads chopped off or removing the PQ benefit all together rather than removing the role.

**Comment by DeerJesus** [comment]
> Rage PR, we should be looking at how to give PQ for burying players with their heads chopped off or removing the PQ benefit all together rather than removing the role.

i already removed the PQ benefit and theyre still doing it so i give up

**Comment by stutwoby** [comment]
> > Rage PR, we should be looking at how to give PQ for burying players with their heads chopped off or removing the PQ benefit all together rather than removing the role.
> 
> i already removed the PQ benefit and theyre still doing it so i give up

Still dumb, it's a usefull role which adds value. Rather than deleting the role ask some why's before your mald removes shit. Look at the root problem not the role.

**Comment by DeerJesus** [comment]
> > > Rage PR, we should be looking at how to give PQ for burying players with their heads chopped off or removing the PQ benefit all together rather than removing the role.
> > 
> > 
> > i already removed the PQ benefit and theyre still doing it so i give up
> 
> Still dumb, it's a usefull role which adds value. Rather than deleting the role ask some why's before your mald removes shit. Look at the root problem not the role.

the role adds NOTHING of value. 75 percent of the time burying someone doesn't do SHIT - doesn't skip the underworld or minigame whatsoever. they just walk up, grab your body, bury it, and do nothing. I have seen more morticians beheaded for stealing bodies than I have actual emotes come from these braindead nimrods. They're so mind numbingly stupid that they're still just burying bodies the moment they find them even though it doesn't give PQ anymore.

**Comment by stutwoby** [comment]
> > > > Rage PR, we should be looking at how to give PQ for burying players with their heads chopped off or removing the PQ benefit all together rather than removing the role.
> > > 
> > > 
> > > i already removed the PQ benefit and theyre still doing it so i give up
> > 
> > 
> > Still dumb, it's a usefull role which adds value. Rather than deleting the role ask some why's before your mald removes shit. Look at the root problem not the role.
> 
> the role adds NOTHING of value. 75 percent of the time burying someone doesn't do SHIT - doesn't skip the underworld or minigame whatsoever. they just walk up, grab your body, bury it, and do nothing. I have seen more morticians beheaded for stealing bodies than I have actual emotes come from these braindead nimrods. They're so mind numbingly stupid that they're still just burying bodies the moment they find them even though it doesn't give PQ anymore.

Bodies need to be burried, stop focusing on the afterlife bullshit. You don't want any kind of punishment for deaths, we can't all just run to the priest for revival, it's supposed to be literal magic making people alive again and the fact we're removing literal death punishments is whack. You get killed, the assumption isn't you get revived, it's the exception.

Yes it's shit people get buried when they could be revived but this isn't a state of the art medical bay, it's medival grimdark fantasy land. We should absolutely penalise morticians when they steal bodies about to be revived or healed but if you see a body on the street and it potentially becomes a zombie, you bury it, if a friend is dragging it for healing fine.

We should start giving a carrot in some other way but you got to remember as well looting bodies is another benefit so I'm not surprised they're greedy, they're supposed to be, unless we start admining for looting corpses or burying people, it'll need a culture change or some other incentive to not bury people.

**Comment by DeerJesus** [comment]
> > > > > Rage PR, we should be looking at how to give PQ for burying players with their heads chopped off or removing the PQ benefit all together rather than removing the role.
> 
> > > > 
> 
> > > > 
> 
> > > > i already removed the PQ benefit and theyre still doing it so i give up
> 
> > > 
> 
> > > 
> 
> > > Still dumb, it's a usefull role which adds value. Rather than deleting the role ask some why's before your mald removes shit. Look at the root problem not the role.
> 
> > 
> 
> > the role adds NOTHING of value. 75 percent of the time burying someone doesn't do SHIT - doesn't skip the underworld or minigame whatsoever. they just walk up, grab your body, bury it, and do nothing. I have seen more morticians beheaded for stealing bodies than I have actual emotes come from these braindead nimrods. They're so mind numbingly stupid that they're still just burying bodies the moment they find them even though it doesn't give PQ anymore.
> 
> 
> 
> Bodies need to be burried, stop focusing on the afterlife bullshit. You don't want any kind of punishment for deaths, we can't all just run to the priest for revival, it's supposed to be literal magic making people alive again and the fact we're removing literal death punishments is whack. You get killed, the assumption isn't you get revived, it's the exception.
> 
> 
> 
> Yes it's shit people get buried when they could be revived but this isn't a state of the art medical bay, it's medival grimdark fantasy land. We should absolutely penalise morticians when they steal bodies about to be revived or healed but if you see a body on the street and it potentially becomes a zombie, you bury it, if a friend is dragging it for healing fine.
> 
> 
> 
> We should start giving a carrot in some other way but you got to remember as well looting bodies is another benefit so I'm not surprised they're greedy, they're supposed to be, unless we start admining for looting corpses or burying people, it'll need a culture change or some other incentive to not bury people.

Fine, if we still need people to bury bodies than we only need one person, right? It's the easiest fucking job in the world, and we should be encouraging more people to play other roles that encourage more work instead of having 3 guys wandering around the map in charge of hiding corpses. There should be a guy manning the graveyard and that's it.

**Comment by CVSthePharmacy** [comment]
To quote useroth: Not all PRs that are made, will be merged

This should be a lovely example

**Comment by DeerJesus** [comment]
> To quote useroth: Not all PRs that are made, will be merged
> 
> 
> 
> This should be a lovely example

image

**Comment by X404ErrorX** [comment]
To be honest, I agree with this pr, there have been 3 times that a mortician has taken a body of someone who recently died to bury them and get pq, it's okay if they couldn't be revived but most of the time its possible to revive them, they are just RR shitter in my experience and most of the times THEY DONT COIN the grave, so their work is completely useless.

**Comment by Altangy** [comment]
The point of the mortician is when all else fails, they are the final step in the revival process. Most people would not consider respawning as "revival" but I apparently have to explain what burial even does.

Burying a corpse with a coin is supposed to give the person who died The Toll in the underworld, making it faster for them to respawn. Putting it in their mouth is supposed to flat out hand it to them. The ritual that the followers of Necra get "Burial Rites" sends them right to the main menu skipping the underworld.

I can't speak to people PQ farming, and I have had a few over eager morticians start looting and or dragging corpses I'm working on away, but it turns out yelling at them is more than enough to get them to stop. Failing that, you have fists.

Throwing away or kneecaping an actual way to get people back into the round and playing over some trite shit does not a good PR make.

**Comment by ChungusGamer666** [comment]
>Buries someone so they dont have to go through the underworld
>Retarded motherfucker on github complains about round removal even though they were already dead and should not expect being revived

Are you mentally ill?

**Comment by DeerJesus** [comment]
The underworld bury shit doesn’t fucking work chungusgamer666

**Comment by ChungusGamer666** [comment]
> The underworld bury shit doesn’t fucking work chungusgamer666

Then fucking fix it instead of pushing this under the rug? It is literally an essential game mechanic to bring people back into the fucking round and instead you are being a retard and getting mad that people are using a game mechanic as intended

**Comment by DeerJesus** [comment]
> > The underworld bury shit doesn’t fucking work chungusgamer666
> 
> Then fucking fix it instead of pushing this under the rug? It is literally an essential game mechanic to bring people back into the fucking round and instead you are being a retard and getting mad that people are using a game mechanic as intended
no

**Comment by ChungusGamer666** [comment]
I can see the reasoning for havinb one mortician only, job bloat is bad, but removing the *sole reason* to bury people is simply put a bad call.

**Comment by kepesk1** [comment]
> Buries someone so they dont have to go through the underworld Retarded motherfucker on github complains about round removal even though they were already dead and should not expect being revived
> 
> Are you mentally ill?

You sound really pissed off. Log off buddy, you're in desperate need of a chill pill.

**Comment by kepesk1** [comment]
+1 this PR. Really sick of morticians just burying people who are waiting to be revived. I've literally seen morticians do it time and time again, and notably, one of the morticians I even tried to stop in-game from doing it because I had JUST brought my friend to the church to be revived. An Astrata priest was standing there recharging when the mortician just walks on up and drags them off, wasting a solid five minutes arguing with my character until the body rots. Meanwhile, inside the church, the priest was fully recharged two minutes before the rot. Nice.

Furthermore, the mortician was quite literally speaking in OOC. They did not even remotely sound in-character. They were genuinely angry and speaking with an aggression and writing style that could really only be OOC malice, which became especially true when they dragged the high priest around and lied saying I was "grave robbing" to get me cursed.

Mortician can be a good role, but currently I think more bad than good people play them. They just want to PQ farm by nuking the whole population and burying them. It's poop tier NRP and I'm sick of the poop tier NRP on this server. Get rid of the role or remove its PQ offering.

**Comment by ChungusGamer666** [comment]
> Mortician can be a good role, but currently I think more bad than good people play them. They just want to PQ farm by nuking the whole population and burying them. It's poop tier NRP and I'm sick of the poop tier NRP on this server. Get rid of the role or remove its PQ offering -- and if the PQ offering is gone, just make it the responsibility of the general church to bury people. The faceless morticians burying endless bodies is NRP at its best, nobody even knows who they are because of the hood.

Burying people you killed does not give you PQ, morticians don't go around "nuking" people because it does literally nothing for them. Without the PQ reward, there is no reason to bury people, and hence no one ends up doing it.

**Comment by DeerJesus** [comment]
> morticians don't go around "nuking" people because it does literally nothing for them

you underestimate the stupidity of man

**Comment by Alanii** [comment]
I understand this is just an angry PR.

But when you create a PR at least try to make it more thought out instead of typing out a tirade rant about things.

This is comparable to the "BIG BOOBS" PR in the way everything reads. 

Just edit initial PR comment and be a bit more normal in the reasoning behind your PR instead of ranting and throwing insults and swears.

Also decreasing mortician slot to 1 or even 0 will not prevent burials from happening. Most revivals require both an Acolyte of Pestra and an Acolyta of Astrata. Typically you will always have an Acolyte of Astrata (or just the priest) but you will not always have an Acolyte of Pestra.

Without Acolyte of Pestra revivals are not guarunteed regardless, and body will be taken to the graveyard where a mortician or someone with a shovel will bury the dead.

Also please note, many people are killed by the bog gate and elsewhere, and a lot of people will just bury the people locally than take the body all the way to church.

**Comment by Stagrawl** [comment]
Holy mother of salt cope PRs.

**Comment by DeerJesus** [comment]
> I understand this is just an angry PR.
> 
> 
> 
> But when you create a PR at least try to make it more thought out instead of typing out a tirade rant about things.
> 
> 
> 
> This is comparable to the "BIG BOOBS" PR in the way everything reads. 
> 
> 
> 
> Just edit initial PR comment and be a bit more normal in the reasoning behind your PR instead of ranting and throwing insults and swears.
> 
> 
> 
> Also decreasing mortician slot to 1 or even 0 will not prevent burials from happening. Most revivals require both an Acolyte of Pestra and an Acolyta of Astrata. Typically you will always have an Acolyte of Astrata (or just the priest) but you will not always have an Acolyte of Pestra.
> 
> 
> 
> Without Acolyte of Pestra revivals are not guarunteed regardless, and body will be taken to the graveyard where a mortician or someone with a shovel will bury the dead.
> 
> 
> 
> Also please note, many people are killed by the bog gate and elsewhere, and a lot of people will just bury the people locally than take the body all the way to church.

I don't think it'll prevent the burials from happening if we lower mortician slots to 1, but I think it'll lower the number of people who prioritize burial over the number of people who look at the situation and at least consider revival - the only people playing mortician will be the one who wants to RP it, and perhaps will actually speak to the dead, instead of just wordlessly burying, yeah?

**Comment by CVSthePharmacy** [comment]
I hope useroth closes this PR

**Comment by DeerJesus** [comment]
kinda expected it to be closed sooner

**Pull request closed without merging**
