### PR TITLE
Racial balancing

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Open to feedback!!
The female domestic skills have been removed
**All of the stats have been updated as of 27/07/2024 17:50 GMT**

All males get an extra: +1 CON - 1 INT
All females get an extra: -1 STR +1 SPD
Drows gender modifiers are reversed
Orcs have no gender modifiers
Humen females instead have: -1 STR +1 SPD -1 CON +1 INT

Races:
Axian: -1 INT +1 END +1 SPD
Wildkin: +1 END
Vermin: -2 STR +1 PER +1 INT -1 CON +2 SPD
Halfkin: +1 INT
Drakian: +1 INT +1 CON -1 SPD
Kobold: -2 STR -1 CON +1 END +2 SPD +1 INT
Sissean: +1 STR -1 INT +1 CON -1 SPD +1 END
Lupian: +1 STR -1 PER +1 INT +1 END -1 SPD
Fluvian: -2 STR +1 INT +2 SPD
Tabaxi: -1 CON -1 END +2 SPD +1 PER
Vulpkian: -1 STR +2 PER +1 INT -1 CON
Dwarf: +1 STR -1 PER +2 CON +2 END -3 SPD
Drow: -1 PER +1 END +1 SPD
Wood Elf: -2 STR +1 PER -2 CON +2 SPD +2 INT
Humen: +1 INT 
Aasimar: -1 STR +2 INT -2 CON +1 LCK +1 END
Halfelf: -1 STR +1 PER +1 INT +1 SPD -1 CON
Half Orc: +2 STR -2 INT +2 CON +1 END -2 SPD
Tiefling: +1 PER +2 INT -2 CON +1 END -1 LCK

### CODE REVIEW

**Comment by ddsaw** [comment]
My opening thoughts would be: Atleast we now have an equal statbalance. My second thought would be: but some stats are wildly more useful than others.
Here's my thoughts on the distribution in general:

Axian: Neutral.
Wildkin: I associate Wild creatures with high perception generally (good "senses"). Largely very vanilla as you would expect.
Halfkin: Same as Wildkin. They are supposedly humans with animal features by and large. If you asked me "Does a catgirl have better or worse senses(perception) than a normal person" I would usually say better.
My suggestions: Just reverse these bonuses or something? -Con/End could be taken as the result of being a strange hybrid. Many hybrids that are interspecies actually have acute health problems (usually sterility, but let's not imply that one LMAO).
Vermin: Neutral
Drakian: I like the statline that slightly mirrors sisseans, but their increased intelligence setting them apart.
Lupian: The same statline we have now. The -2PER always felt quite strange for wolves, atleast to me. The 1 INT comes from a connection to Noc I believe. 
My suggestion: No idea. I can't really associate wolves with low per, low con, low end or anything.
Fluvian: I've seen like one moth. Neutral.
Tabaxi: We stole the term from DnD, where Tabaxi are Cheetahs. I strongly associate cheetahs (and cats in general) with speed and agility, but not endurance. By and large cats are all sprinters/ambushers and have terrible endurance.
My suggestion: End 0 or perhaps even -1. Put the point into SPD? Put the second point back into STR or PER (or more SPD if you want it to align with the common tabaxi monk meme)
Vulp: When I think of foxes, I think of cunning. Pull a point somewhere to give them int?
My suggestion: Deduct a point of End, put it into Int.
Dwarf: Slow and steady, as you would expect. 
My suggestion: Maybe even make it SPD -3 to give them a point of Str?
Drow: Haha get nuked. I do not associate elves with low PER however.
My suggestion: Uhh.. -1 End -1Con 2 SPD?
Woodelf: Neutral.
Humen: Just make them +0.
Aasimar: Some people will seethe about LCK. But it's not that good a stat.
Halfelf: Between Human and Elf, As expected.
Half Orc: Oh boy.. +2 Str? It's good they get -2 SPD because that is the only thing making this somewhat sane. But Con and End are the other two good combat stats I think. The array makes thematic sense to me but the gameplay balance is scary. We need somehow punish a low int stat and then this is acceptable I think.
Tiefling: Same as Aasimar, LCK makes some people seethe.

Male vs Female: Acceptable and basically business as usual.
SPD is still a bit worse than STR but overall I think it's almost even now.
Int vs Con is weighted towards Con I believe.

Overall yeah, this has to be done and I am glad that atleast now we have a PR I know won't remain in limbo.

**Comment by katsukai** [comment]
I genuinely wish you keep Verminfolk speed +2.

**Comment by CalamaBanana** [comment]
Elves losing all their INT is a bit sad. Keep their constitution as it was before (-1 for males, - 2 for females), so they are still more fragile than humens, that would free up a point to put back into INT.

**Comment by CalamaBanana** [comment]
I think the domestic skills were a cute little addition, not like they mattered much

**Comment by CalamaBanana** [comment]
> Elves are wood elves, which makes more sense for them to be fast and perceptive, rather than intelligent and we already have a bunch of +1 int races

Bit of my point, so many +int races but elves all of a sudden. It just feels weird to go from the smartest race to being more stupid than half the other races. Especially if most of those races don't really have any justification for it, far less than classical elves at least.

(Or just add a city/high elf race with -3 STR +1 PER +2INT -2 CON +2 SPD)

**Comment by DorfGuy1** [comment]
Don't take elves Int away. I play a lot of non combat roles, and just about the only thing that makes it barely tolerable is having above average int to be able to fudge out some crafting rolls. The trade off is fair, their pretty damn flimsy.

**Comment by EzekyalLegit** [comment]
This is a HUGE push toward equality, remember to factor in gender stats when looking at these and they're all nice and niche. Yes wood elves got fucked a little as far as noncombat but they now have a whopping bonus for archery damage which is very fitting.

**Comment by CalamaBanana** [comment]
> This is a HUGE push toward equality, remember to factor in gender stats when looking at these and they're all nice and niche. Yes wood elves got fucked a little as far as noncombat but they now have a whopping bonus for archery damage which is very fitting.

Which just feels misplaced, considering most elves on the server are far more city elves than wood elves. Forcing the race into a combat niche while taking away what made it great for civilians before is just rough.

**Comment by Jul-Jul** [comment]
Big Brain idea then. Make normal elves the intelligent and soft elves and the dark elves the combat oriented ones. That way normal elf players ain't being fucked over AND you create that separation/differences that you wanted between the two elf types.

**Comment by DorfGuy1** [comment]
Elves are in a good place balance wise. Please don't take the int though. I'm not sure archery damage is even effected by perception. Even if it is, let them keep the int. Humans get a + to int, which, sure, brainy apes, but you see where I'm going with this.

**Comment by EzekyalLegit** [comment]
> Elves are in a good place balance wise. Please don't take the int though. I'm not sure archery damage is even effected by perception. Even if it is, let them keep the int. Humans get a + to int, which, sure, brainy apes, but you see where I'm going with this.

It is very significantly.

**Comment by EzekyalLegit** [comment]
> This is a HUGE push toward equality, remember to factor in gender stats when looking at these and they're all nice and niche. Yes wood elves got fucked a little as far as noncombat but they now have a whopping bonus for archery damage which is very fitting.

Im no longer so jacked about the stats. Humens and half-kin are just the same now which is kinda lame. I liked that half-kin had -1 per like their senses were a bit jumbled from being halfbreed between animal and human instinct. Elves were given +1 int but then it was taken away because being male is now -1 int. Now female half-orcs are gonna only have +1 strength which is aweful....

**Comment by AttackHelicopter6784** [comment]
Any of the races getting perception are being fucked.

Wood Elves getting -3 STR, +2 PER, and losing their INT bonus (effectively -2, and males -3) have been neutered into purely being zape bait, and are now a useless species. Perception is probably the least cared for stat out of the entire list.

**Comment by EzekyalLegit** [comment]
> Any of the races getting perception are being fucked.
> 
> Wood Elves getting -3 STR, +2 PER, and losing their INT bonus (effectively -2, and males -3) have been neutered into purely being zape bait, and are now a useless species. Perception is probably the least cared for stat out of the entire list.

This can be changed, they can make perception stronger when swinging to hit/catch dodges in future or make it help in crafting roles like int does.

**Comment by DavidAreYouSure** [comment]
I don't get how thats a nuke to Drow. You gave them more speed which is arguably a better stat than anything else you could have especially with the recent buff to it.

**Comment by crucialAmnesiac** [comment]
I think that we should get Wildkin origins based on the most common fantasy/furry races which would also affect stats or height.

**Comment by Blankie3563** [comment]
Overall looks kinda cool!
_Outside_ of a couple nitpicky thematic changes, I could see some tweaks to some racial stats.

**Wildkin** being identical to humans is.. kinda sadge? A touch boring, compared to the other races who get their own identities. I know a few who would like it to be different, though seeing the wide variety of species within wildkin, perhaps it's easier said than done. Maybe their crossed genetics could give a semi-random stat-bonus range or something, but that's an ask.

I feel like **Lupians** getting -PER -SPD is a bit odd for a dog.. but it's not a big issue - maybe a +STR +SPD race from them could be cool.

When it comes to **Elves**, (elf main..) I suppose I could hold off on judgement personally, considering there's plans to buff perception. Losing INT focus is tuff though, unless the changes make PER pretty useful. Even if they are _wood elves_, they are the surface only elves we have.

Finally, **Half-orcs** are kinda _massive_. +2 STR +2 CON +1 END are _insane_ combat stats. I'm quite fond of half-orcs myself (getting one commissioned rn even), but I'd probably make their CON and SPD modifiers be +1 and -1, respectively, instead. I can see +2 STR +2 CON being rather frustrating to fight into for non-orcs. +2 STR +1 CON +1 END with -1 SPD -2 INT is still a _stellar_ combat stat-line for them, would _love_ to see that.

Aside from racial stats, there's also something that _could_ be said about the **gendered stats**. I feel Males +1 STR -1 INT and Females -1 CON +1 SPD is an argument one can make for them, but I'm not terribly opposed to it staying as listed. The aforementioned change does fit well thematically for Drow and Half-orcs(assuming a re-enabling of their gendered stats) particularly, I think.

Glad to be seeing more races getting their own defined stats. Well done! :3

**Comment by Gr33d-y** [comment]
> Overall looks kinda cool! _Outside_ of a couple nitpicky thematic changes, I could see some tweaks to some racial stats.
> 
> **Wildkin** being identical to humans is.. kinda sadge? A touch boring, compared to the other races who get their own identities. I know a few who would like it to be different, though seeing the wide variety of species within wildkin, perhaps it's easier said than done. Maybe their crossed genetics could give a semi-random stat-bonus range or something, but that's an ask.
> 
> I feel like **Lupians** getting -PER -SPD is a bit odd for a dog.. but it's not a big issue - maybe a +STR +SPD race from them could be cool.
> 
> When it comes to **Elves**, (elf main..) I suppose I could hold off on judgement personally, considering there's plans to buff perception. Losing INT focus is tuff though, unless the changes make PER pretty useful. Even if they are _wood elves_, they are the only non-drow elves we have.
> 
> Finally, **Half-orcs** are kinda _massive_. +2 STR +2 CON +1 END are _insane_ combat stats. I'm quite fond of half-orcs myself (getting one commissioned rn even), but I'd probably make their CON and SPD modifiers be +1 and -1, respectively, instead. I can see +2 STR +2 CON being rather frustrating to fight into for non-orcs. +2 STR +1 CON +1 END with -1 SPD -2 INT is still a _stellar_ combat stat-line for them, would _love_ to see that.
> 
> Aside from racial stats, there's also something that _could_ be said about the **gendered stats**. I feel Males +1 STR -1 INT and Females -1 CON +1 SPD is an argument one can make for them, but I'm not terribly opposed to it staying as listed. The aforementioned change does fit well thematically for Drow and Half-orcs(assuming a re-enabling of their gendered stats) particularly, I think.
> 
> Glad to be seeing more races getting their own defined stats. Well done! :3

love this feedback!
Half orcs may very well be insane and we can adjust them as needed, but it is also important to remember all the jobs they are locked out of and how the new merc nerf will likely bring them down a peg. That said, we will keep an eye on them if they are to crazy.

as for wildkin, sadly, there's not a ton we can do to make them different as they are a build your own creature sort of deal. Someone could make any number of things with them that any statline could make no sense on.

**Comment by Drayco84** [comment]
>Tabaxi: We stole the term from DnD, where Tabaxi are Cheetahs. I strongly associate cheetahs (and cats in general) with speed and agility, but not endurance. By and large cats are all sprinters/ambushers and have terrible endurance. My suggestion: End 0 or perhaps even -1. Put the point into SPD? Put the second point back into STR or PER (or more SPD if you want it to align with the common tabaxi monk meme)

Tabaxi are supposed to be jaguars according to the D&D wiki, not cheetahs. While cheetahs are famously known for their impressive sprinting speed, jaguars are a terrifyingly good ambush cat with the highest bite strength per weight ratio of all the big cats. (These things typically kill caimans via a bite to the back of the head.)

More importantly, I really wish the racial bonuses all evened out to a higher total of +3 or +4 instead of just +1. That would give more opportunity for races to be more distinct with a greater stat spread for generalist races, or higher focused stats for specialist races.

**Comment by DavidAreYouSure** [comment]
> > I don't get how thats a nuke to Drow. You gave them more speed which is arguably a better stat than anything else you could have especially with the recent buff to it.
> 
> This is not meant to nuke any races

The first comment states about nuking drown stats which I don't understand how that's a nuke.

**Comment by ddsaw** [comment]
> > > I don't get how thats a nuke to Drow. You gave them more speed which is arguably a better stat than anything else you could have especially with the recent buff to it.
> > 
> > 
> > This is not meant to nuke any races
> 
> The first comment states about nuking drown stats which I don't understand how that's a nuke.

The reason for this PR is that stats were NOT handed out evenly before.
Drow used to be at a whopping +4 stat balance. They are now +1. They lost an entire 3 points of stats, that's why I said they got nuked.

**Comment by Teragenic** [comment]
I hope any changes were updated withe edits but I do wonder why the FORTUNE debuff for Half Orcs was removed

**Comment by HissyNays** [comment]
I don't like how it removes difference in woman to man from different races with drow being the only exception.
In general I feel like past stats were better with some exceptions. Playing elf is like a joke now, not that it was much better before, perhaps give them 1 luck to compensate for being absolute weaklings?

Races that have perception as dump stat are basicly winning here, perception is like used for detecting invisible people and mantraps. Or am I missing something? Meanwhile races that are with bonus perception basicly lose. It's just not a useful stat.

**Comment by CalamaBanana** [comment]
I'd really wish you'd reconsider the domestic skill removal as well. They were mostly neat flavor, and I don't think anyone really had an issue with all women knowing how to cook a little. It gave the genders more identity, which grounded the setting just a bit more. (But to be fair, that is already getting softened up so heavily on this server, I am not a biggest fan of all those soldier roles no longer being gender-locked in the first place)

And of course, obligatory: With PER being as useless as it is, why not shift one of those points to INT for elves, to have them back to where they were before? A good civilian race of pushovers.

**Comment by DorfGuy1** [comment]
I agree with adding back the domestic skills for reasons outlined in the other posts. Also please be open to reworking some things, like the wildkin, and maybe the elves again? They were already flimsy, I dread to think how bad it would get otherwise.

**Comment by DorfGuy1** [comment]
> > Overall looks kinda cool! _Outside_ of a couple nitpicky thematic changes, I could see some tweaks to some racial stats.
> > **Wildkin** being identical to humans is.. kinda sadge? A touch boring, compared to the other races who get their own identities. I know a few who would like it to be different, though seeing the wide variety of species within wildkin, perhaps it's easier said than done. Maybe their crossed genetics could give a semi-random stat-bonus range or something, but that's an ask.
> > I feel like **Lupians** getting -PER -SPD is a bit odd for a dog.. but it's not a big issue - maybe a +STR +SPD race from them could be cool.
> > When it comes to **Elves**, (elf main..) I suppose I could hold off on judgement personally, considering there's plans to buff perception. Losing INT focus is tuff though, unless the changes make PER pretty useful. Even if they are _wood elves_, they are the only non-drow elves we have.
> > Finally, **Half-orcs** are kinda _massive_. +2 STR +2 CON +1 END are _insane_ combat stats. I'm quite fond of half-orcs myself (getting one commissioned rn even), but I'd probably make their CON and SPD modifiers be +1 and -1, respectively, instead. I can see +2 STR +2 CON being rather frustrating to fight into for non-orcs. +2 STR +1 CON +1 END with -1 SPD -2 INT is still a _stellar_ combat stat-line for them, would _love_ to see that.
> > Aside from racial stats, there's also something that _could_ be said about the **gendered stats**. I feel Males +1 STR -1 INT and Females -1 CON +1 SPD is an argument one can make for them, but I'm not terribly opposed to it staying as listed. The aforementioned change does fit well thematically for Drow and Half-orcs(assuming a re-enabling of their gendered stats) particularly, I think.
> > Glad to be seeing more races getting their own defined stats. Well done! :3
> 
> love this feedback! Half orcs may very well be insane and we can adjust them as needed, but it is also important to remember all the jobs they are locked out of and how the new merc nerf will likely bring them down a peg. That said, we will keep an eye on them if they are to crazy.
> 
> as for wildkin, sadly, there's not a ton we can do to make them different as they are a build your own creature sort of deal. Someone could make any number of things with them that any statline could make no sense on.

Half orcs are locked out of most of the really good combat rolls, except for mercs, which are catching a nerf. So as a boggard half orc I mostly role around 11-12 in strength, 13 if I'm lucky. That's good and decent, but not too crazy, and their low int means they can't skill up to well, so generally the more elite fighter roles will clap the hell out of them.

**Comment by H0gberg** [comment]
those half orc stats are way too busted, lower the con, endurance and str, even having a bit of any of those is really powerful compared to any other stat.

**Comment by Drayco84** [comment]
@Azarak Which I understand as previously the races ranged from a -stat bonus for some, all the way up to the infamous +4 for female drow. However I really wish they all have a higher +stat bonus to help differentiate the races but I'm not sure how much a one or two point difference in a stat is going to "feel" when playing. However, for a fair number of races, keeping the total +stat bonus at only +1 is a step down from what a large number of them used to have.

And yes, I'm aware that there will eventually be racial quirks (One of which should at least be the ability to see in the dark...) and racial skill bonuses. (IE shark race having innate swimming skills and most animal races getting some form of nightvision like werewolves and vampires, even if they're not as strong.)

**Comment by HissyNays** [comment]
> Half orcs are locked out of most of the really good combat rolls, except for mercs, which are catching a nerf. So as a boggard half orc I mostly role around 11-12 in strength, 13 if I'm lucky. That's good and decent, but not too crazy, and their low int means they can't skill up to well, so generally the more elite fighter roles will clap the hell out of them. The high strenght does not help them hit through parries or dodges. So a clumsy but strong oaf is what most combat halforcs are gonna be, basically.

High strength doesn't let you get through parries? But you know what gets through parries? Grabs. A monk orc has a giant potential to manhandle even a knight. I cannot state enough how op orcs are in right hands. You don't fear a verevulf that bites and claws, you fear a verevulf that grabs and wrestles. Strength is the ultimate combat stat.

But yeah, extra removal of cooking and sewing skills from women is sad. :(
It used to be an ancient meme that all women were able to sew well, so those minor skills really added well to the game.

**Comment by MickDick1** [comment]
> those half orc stats are way too busted, lower the con, endurance and str, even having a bit of any of those is really powerful compared to any other stat.

Since speed stat was made to scale with each point rather than the thresholds that -2 speed stat is pretty brutal, you won't catch people if they simply don't want to be caught. str/con is slooooowly being made less OP compared to other stats. Being slow is hell.

**Comment by wow50000** [comment]
re add the female cooking and sewing please, i really really miss it.

**Comment by wow50000** [comment]
yeah at this point i think it would be better to just use the old system and just nerf the overpowered ones like dark elf female to make em not be able to roll respected or trusted roles rather than just flat nerfing everything

**Comment by Teragenic** [comment]
If people are complaining about Lupians. What about dwarves. Dwarf justice. 

Gwargh. 

But on serious note.

Dwarven females got a decrease in Endurance
While males got Con bonus but speed decrease was nice.

Need my stronk funny charge and targe female dwarf.

**Comment by Drayco84** [comment]
> re add the female cooking and sewing please, i really really miss it. yeah this PR has completely fucked the two things i value about female humen being +2 int and +1 cooking and sewing. This completely fucked my playstyle and i dont really feel like playing until humen females get +1 cooking/sewing and +2 int

Really would like to see racial and gender skills re-added because misogyny FTW! However, they would need to be diversified. Here's some starting ideas...
Human/Elven Male: Woodcutting, maybe some crafting or carpentry. ("If the women don't find you handsome, they should at least find you handy." -Sage advice from Red Green.)
Human/Elven Female: Sewing, cooking.
Lupian: Hunting, butchering or skincraft.
Tabaxi: Climbing, archery or hunting. (What cat CAN'T climb?!)
Axians: SWIMMING, FOR ****'S SAKE!!! And maybe some carpentry because pirate/nomad life. (I know the first one isn't useful, but they're still sharks and it'd be stupid if they couldn't.)
Dwarf Male: Mining, weaponsmithing. (Refine the ores, make the stabby/smashy things.)
Dwarf Female: Sewing/Tailoring, armorsmithing. (Make the things that STOP the stabby/smashy things because I JUST MOPPED AND YOU'RE GETTING BLOOD EVERYWHERE!)

This is obviously just a rough, incomplete list of suggestions as I know the lore is still being worked on. However, this might be a completely different suggestion or thread.
Personally though, as a regular player of a female Drakian, I'm really missing that Int bonus that gave you a SMALL but guaranteed chance of crafting things. REALLY wish we have racial and player quirks already... The ability for somebody to add like a couple guaranteed stats at round start would be rather nice.

**Comment by challade** [comment]
Fluvians with -2 STR and +2 SPE makes no sense. How are they so fast, and why are they as weak as kobolds? If anything they should get a flat +1 PER because they're humans that have big fucking eyes. Or, if you're daring, -2 STR and +3 PER/ -2 STR +1 Int +2 PER.

**Comment by katsukai** [comment]
Think Lupians should have no difference between sexes.

**Comment by Gr33d-y** [comment]
> Think Lupians should have no difference between sexes.

I keep wondering why people are saying this. Wolves are sexually dimorphic in nature so I'm unsure why this would be the case.

**Comment by Gr33d-y** [comment]
> Fluvians with -2 STR and +2 SPE makes no sense. How are they so fast, and why are they as weak as kobolds? If anything they should get a flat +1 PER because they're humans that have big fucking eyes. Or, if you're daring, -2 STR and +3 PER/ -2 STR +1 Int +2 PER.

fluvians are not just humans with big eyes. They are fragile and light insectoids.

**Comment by Gr33d-y** [comment]
> > re add the female cooking and sewing please, i really really miss it. yeah this PR has completely fucked the two things i value about female humen being +2 int and +1 cooking and sewing. This completely fucked my playstyle and i dont really feel like playing until humen females get +1 cooking/sewing and +2 int
> 
> Really would like to see racial and gender skills re-added because misogyny FTW! However, they would need to be diversified. Here's some starting ideas... Human/Elven Male: Woodcutting, maybe some crafting or carpentry. ("If the women don't find you handsome, they should at least find you handy." -Sage advice from Red Green.) Human/Elven Female: Sewing, cooking. Lupian: Hunting, butchering or skincraft. Tabaxi: Climbing, archery or hunting. (What cat CAN'T climb?!) Axians: SWIMMING, FOR ****'S SAKE!!! And maybe some carpentry because pirate/nomad life. (I know the first one isn't useful, but they're still sharks and it'd be stupid if they couldn't.) Dwarf Male: Mining, weaponsmithing. (Refine the ores, make the stabby/smashy things.) Dwarf Female: Sewing/Tailoring, armorsmithing. (Make the things that STOP the stabby/smashy things because I JUST MOPPED AND YOU'RE GETTING BLOOD EVERYWHERE!)
> 
> This is obviously just a rough, incomplete list of suggestions as I know the lore is still being worked on. However, this might be a completely different suggestion or thread. Personally though, as a regular player of a female Drakian, I'm really missing that Int bonus that gave you a SMALL but guaranteed chance of crafting things. REALLY wish we have racial and player quirks already... The ability for somebody to add like a couple guaranteed stats at round start would be rather nice.

things like skills and what not will come when we add skills and traits to every species. This is JUST the stats for the time being.

**Comment by challade** [comment]
> > Fluvians with -2 STR and +2 SPE makes no sense. How are they so fast, and why are they as weak as kobolds? If anything they should get a flat +1 PER because they're humans that have big fucking eyes. Or, if you're daring, -2 STR and +3 PER/ -2 STR +1 Int +2 PER.
> 
> fluvians are not just humans with big eyes. They are fragile and light insectoids.


Somehow, the fox creature, with what we assume has has digitigrade legs (by the way, emphasizing _FOX_ creature); the **crafty**, **speedy** archetype creature has +2 Perception and -1 constitution. No speed. 

Meanwhile, Fluvians, the giant insectoid creature that looks like a moth, a creature archetypically involved with chasing after the light in the darkness to the point of singing themselves in the flame, has the +1 intelligence and +2 speed. Despite having **compound eyes**.

Perception affects your cone of vision, how the race with compound eyes has +2 speed and no bonus to it's field of vision, while the fox, an ambush predator with front facing eyes specifically to ambush creatures has the +2 perception and no speed bonus is wild to me. In fact, it looks like Vulpkians and Fluvian's have swapped stats.

If I gave some random person these two stat spreads and told them to take a guess which of them is a moth man's stat spread and which one is a fox man's stat spread, what do you think they'd say?
???
 -2 STR +1 INT +2 SPD
???
 -1 STR +2 PER +1 INT -1 CON

I don't know bro. I don't know. This makes my right eyebrow go down and my left one go up.

**Pull request merged**
