### PR TITLE
Rebel chance decrease, werevolf infection fix, and minor antag werevolfs

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

Rebels are currently the least fun, least impactful, and most badly played antag currently in play (rebels alone have 5 mentions in the tree of woe in the discord). I decreased the chance for Rebels majorly, i wanted to remove them but need other peoples opinions first because there are so few antags. Also, i made it so bites actually can infect, beforehand only Artery cut bites had a 50% infection chance, and all bites had no chance leading to a werevolf trying to bite someone like 40 times only for them to bleed out and not be infected, that is fixed. Also i added Werevolfs as a minor antag, needs discussion but its good for variaties sake

## Why It's Good For The Game

less shit antags good, werevolfs infecting good

### CODE REVIEW

**Comment by coffeecoffeecoffee** [comment]
I deeply enjoy rebels as an antag and would resent the total removal of them, I would think they should probably be limited to higher PQ people but some of the best roleplay I've had came from a few amazing rebellions.

**Comment by Hmeister-real** [comment]
> if you want to increase infection rate, you MUST nerf the WW stats.

they already get pummelled by crits, and leg attacks. IMO they need a buff but i would rather there just be more of them

**Comment by Hmeister-real** [comment]
> Nothing is broken with the bites, their chance is just low
> 
> You can see all wounds inherit from this image

i am, silly. Il edit the chances there then thanks <3

**Comment by Koteshkin** [comment]
Rebel is a bad mode imo, since bad Kings will be removed by IC reasons without any revolt or just get OOC punishment if they are TOO bad. And with good/neutral Kings you can barely create an actual good reason to rebel to people join you. Its a lose/lose scenario.

I wish rebel mode would give a King an objective to do stupid things on purpose/anything they want without OOC punishment, but then it will give King meta, so probably not the best desicion anyway. Without a change like that rebel has no sense, because as I said with King being actually bad it doesnt need a rebel mode to happen.

**Comment by ChungusGamer666** [comment]
Rebel is a good enough mode and fuck anyone trying to fuck with one of the 4 (!) antagonists that matter, why are people so obsessed with ensuring every round is either bandits or vampyres? ffs

**Comment by Hmeister-real** [comment]
> Rebel is a good enough mode and fuck anyone trying to fuck with one of the 4 (!) antagonists that matter, why are people so obsessed with ensuring every round is either bandits or vampyres? ffs

because rebels are flawed in a HRP environment, either they suck ass and spam "Join" "Join" over and over, or they actually try, and the moment someone declines that person can immediately run to the keep and shout "[PERSON] IS REBEL!!!" and ruin the rebels round.
If rebels were able to forcefully convert, and had the Rebel UI back i could see them being better, but as of now they are flawed and very, very rarely result in interesting or compelling scenarios that don't just devolve to mindless fragging, or literally nothing happening.

**Comment by radarseas** [comment]
the biggest issues as someone that's played rebel head, several times is the following with rebels

1: you're fucked triumph wise if the priest decides to turn against the rebellion/disconnects/kills themselves or dies, they nearly always side with the king anyway. You cannot force-king yourself. (this is a _problem with or without the gamemode honestly._)

2: you have no huds, before you argue talibards, takes too long to make em to know who's who in a fight. Let alone sourcing those 8 fibres, for 4 clothes, times that by 14 or more since you need numbers for a frontal assault, as MAAs and knights have superior fighting stats **_and having them not forget they're rebels._**

3: garrisons/nobles that aren't the king himself being hard-locked out... kinda ruins the RP aspect of optional recruitment. Its also completely incomprehensably fucked in how it works anyway, bog guards are COMPLETELY unable to be revs _but nearly everyone in the keep including the hand can be recruited?_

**Comment by Hmeister-real** [comment]
> we're already messing with the antags and their chances + Vampire and Werewolf rework soon

very out of date anyway

**Pull request closed without merging**
