### PR TITLE
Allows you to be short.

### PR DESCRIPTION
**Pull request by Multigamer99**
## About The Pull Request

_Enable short height to achieve maximum manlet._

So this PR does a few things. Total changelog:
- Renames and moves around the player texture files that are actively in use so that they are consolidated into one place, follow a standard naming scheme, and are a bit more clear in what each texture file actually is.
- Creates textures for muscular short folks.
- Fixes a texture issue on the general anthro short male texture.
- Adds a thing to the character creator menu to toggle being short.
- Altered marking code so that they now obey offsets for height based on the height of the bottom of the torso.
   - This should be changed to be dependent on the exact limb and use the closest offset for that limb but this works for now given that nearly all upper-bodies are the same general shape atm.

Oh, I also ran a quick test on it. Dunno if it works 100% but it probably does, and I squished the bugs I found in my testing.

## Why It's Good For The Game

A visible difference is height is remarkably useful for roleplay. It can get disorienting when a guy is making fun of someone for being short, but the person they are talking to is the same height as them visually. Now we have a general visual distinction between short folk and non-short folk. Additionally, height is a useful tool for social situations: with larger folks generally being more passively threatening while smaller folks are the opposite. This allows a little bit of that passive scene assessment to come into the game without having to slow it down with examine texts or making a me to describe how short you are.

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
I sure do love smaller hitboxes

**Comment by efzapa** [comment]
surely re-adding short sprites not a week after they were removed in relation to concerns regarding pedophilic fetishists abusing it can only go well :)

**Comment by DeerJesus** [comment]
YEAH BABY

**Comment by DeerJesus** [comment]
> surely re-adding short sprites not a week after they were removed in relation to concerns regarding pedophilic fetishists abusing it can only go well :)

you are tripping hard

**Comment by efzapa** [comment]
> > surely re-adding short sprites not a week after they were removed in relation to concerns regarding pedophilic fetishists abusing it can only go well :)
> 
> you are tripping hard

if you wanna promote pedophilic behavior on a server that **_promotes_** rape then that is your prerogative 

just trying to save yall the potential scandal before you turn into Lifeweb v2

**Comment by Gyrandola** [comment]
> > > surely re-adding short sprites not a week after they were removed in relation to concerns regarding pedophilic fetishists abusing it can only go well :)
> > 
> > 
> > you are tripping hard
> 
> if you wanna promote pedophilic behavior on a server that **_already promotes_** rape then that is your prerogative
> 
> just trying to save yall the potential scandal before you turn into Lifeweb v2

I am quite short irl. Do I promote pedophilic behavior?

@Multigamer99 You DEFINITELY need to add a STR debuff. Let's discourage hitbox gamers.

**Comment by CloverIsLucky** [comment]
> > > surely re-adding short sprites not a week after they were removed in relation to concerns regarding pedophilic fetishists abusing it can only go well :)
> > 
> > 
> > you are tripping hard
> 
> if you wanna promote pedophilic behavior on a server that **_already promotes_** rape then that is your prerogative
> 
> just trying to save yall the potential scandal before you turn into Lifeweb v2

@efzapa you should seek for psychological attention if your firsts reactions, comments a thoughts about seeing a manlet/shortstack PR is "pedo" and "rape" in a same comment.

**Comment by ChungusGamer666** [comment]
These are literally renamed kid sprites and you guys are trying to say WELL ERM ACTUALLY... To the guy reasonably pointing out tjat this shit is weird, are you insane?

**Comment by githubuser4141** [comment]
> These are literally renamed kid sprites and you guys are trying to say WELL ERM ACTUALLY... To the guy reasonably pointing out tjat this shit is weird, are you insane?

yea I don't get why we don't just use different sprites, get someone to sprite it properly.

**Comment by DeerJesus** [comment]
> These are literally renamed kid sprites and you guys are trying to say WELL ERM ACTUALLY... To the guy reasonably pointing out tjat this shit is weird, are you insane?

I was informed these were just regular sprites they removed 2 pixels from the legs from? Tf u mean theyre the kid sprites?

**Comment by DeerJesus** [comment]
-1 I looked through it. I was under the impression this is a different PR someone ELSE said theyd make which makes them the size of the recently added kobolds/goblins by removing 2 pixels from the legs. This isn't that PR, apparently this is literally just the teenager sprites.

**Comment by Multigamer99** [comment]
i'll do a str debuff when i go in to fix the build error.

also, fun fact, the old teenager sprites were literally just removing 2 pixels from the leg. that's what it always has been. So this is the one where they are just the normal sprite with pixels in the leg removed.

**Comment by DeerJesus** [comment]
> i'll do a str debuff when i go in to fix the build error.
> 
> also, fun fact, the old teenager sprites were literally just removing 2 pixels from the leg. that's what it always has been. So this is the one where they are just the normal sprite with pixels in the leg removed.

Errr... Then I fell for the reddit drama baby shit, my mistake.

**Comment by Multigamer99** [comment]
Also, i was told by a server admin to not do taller folks. i was originally gonna make it be an offset thing that you could adjust from -2 to +2 pixels in height (dwarves only get -1 to +1 due to constraints). i've been told they won't accept a pr that adds a taller option due to potential clothing conflicts, so yeah.

**Comment by Multigamer99** [comment]
> Errr... Then I fell for the reddit drama baby shit, my mistake.

Happens sometimes.

But yeah no I'm the gal who made the teenager sprites for blackstone back when I played on it because, well, ~~i like being short and getting dunked on by all the taller people~~

the original "teenager" sprites were just the adult sprite with some leg pixels cut out and the body hair set to not render. The latter is the default here now too, since all but dwarves no-longer have body hair, which probably doesn't help public perception even though all it really means is that everyone is shaven except dwarves.

i only re-used the original files because i had made them and knew exactly what they were: shortened full height sprites.

**Comment by Multigamer99** [comment]
> > Also, i was told by a server admin to not do taller folks. i was originally gonna make it be an offset thing that you could adjust from -2 to +2 pixels in height (dwarves only get -1 to +1 due to constraints). i've been told they won't accept a pr that adds a taller option due to potential clothing conflicts, so yeah.
> 
> Coming to think of it, it may be fine but I'd have to check the clothings, and I feel like just a short customization is more than sufficient for now. Tall customization is something that we can think of later in future

Fair enough.

I wasn't gonna bother fighting with it last night so I just did it and went.

**Comment by Multigamer99** [comment]
Alright, -1 strength penalty and compilation error fixed

**Comment by hugmeorelse** [comment]
We're getting our own custom sprites as was originally planned. I don't know why they keep making a big deal out of this, even though I literally told them we weren't going to go ahead with this.

**Comment by Useroth** [comment]
image

**Comment by Multigamer99** [comment]
pffft

**Comment by hugmeorelse** [comment]
> image

Dude has copium on tap. I want what he has.

**Comment by efzapa** [comment]
> image
> 

we are reaching new levels of petty, zamn

**Comment by Multigamer99** [comment]
yeah no idk why they were so pissed the "teenager" sprites are just adult sprites but with pixels from the leg removed and the the rest shifted down to fill the gap

**Comment by Real-MAGNUM** [comment]
> image

Ah yes, the random discord jannie validates a reopening. 🫡

**Pull request closed without merging**
