### PR TITLE
Malum spells Acolytes and Forge clerics

### PR DESCRIPTION
**Pull request by Diltyrr**
## About The Pull Request

Adds Malum Psicross
No specific sprite though. I ain't a spriter.

Adds Malum Spells :

Tier 0
Lesser Miracle (Like everyone else)
 
Tier 1
Vigorous Exchange
Range : 1
Cast time : 2 Seconds
Cooldown : 1 Minute
Effect : Restores 50 Stamina to the caster if self targeted. Drains 100 stamina from the caster but restores 100 to the target if someone else is targeted.

Tier 2
Heat Metal
Range : 15
Cast time : 2 Seconds
Cooldown : 5 Minutes
Effect : Highly target dependant. 
If you target an unequiped smeltable metal item on the floor. It will turns into the result you would have gotten from smelting it.
If you target someone's hand holding an ingot filled tong. It will heat said ingot.
If you target someone's hand holding a smeltable weapon. It will do 10 burn damage to the wielder's hand and make them drop the weapon.
If you target someone's Head/Neck/Arms/Legs/Foot and the target wears a smeltable piece of gear at said location. It will do 20 burn damage to any bodypart covered by said piece of equipement.
If you target someone's Chest and they are wearing a smeltable piece of gear in their armor or shirt slot. It will do either 40 damages if both slots are metal, 20 only the shirt is metal or only the armor is but the target isn't wearing a shirt. 10 if the target wears a metal armor but a non metal shirt.

Tier 3
Hammerfall
Range : 15
Area of effect : 3x3
Cast time : 2 Seconds
Cooldown : 5 Minutes
Effect : Create a 3x3 aoe where you click. After a 2 seconds delay, any structure and walls in the AOE takes 250 damages and any humanoid in the aoe will either have their movement interrupted for 1 second or be knocked down for 1 second. Higher Speed and perception making it easier to resist falling down.

Tier 4
Crafter's Covenant
Range : 1
Cast time : 10 Seconds
Cooldown : 25 Minutes
Effect : Sucks up and destroy any coins, statues or rings present on the tile where the spell was cast. Lets you summon a single item from a choice of smithing recipe, musical instruments or riddle of steel. The price should be around twice the merchant's price if not more though. (I had to extrapolate crafted gear's price from their materials as they don't have a price themselves).

Adds Malum as an allowed patrons for Acolytes and Clerics.

Adds Forge Cleric
An adventurer subclass that is a middle ground between a War cleric and a Blacksmiths. Trading many of the war cleric proficiencies in combat for basic levels of smithing.

## Why It's Good For The Game

It would make sense for players to be allowed to play Acolytes and Clerics (or at least some kind of "holy" role) for all of the ten gods of the humen pantheon. This is my small contribution to that idea.

Disclaimer: First time coding in DM and I'm mostly fuelled by sleep deprivation and caffeine aaaand english isn't my first language. Bonk me on discord if you see anything to fix

## Proof of testing.
Forge Cleric starting Kit
Forge Cleric Traits
Hammerfall
Heat metal armor
Heat metal tongs
Heat metal weapon
Vigorous Exchange effect
Vigorous Exchange On cast
Crafter's covenant
Forge Cleric Select
Forge Cleric Selected
Forge Cleric skills

### CODE REVIEW

**Comment by wow50000** [comment]
you know damn well this is going to replace pilgrim smiths

**Comment by wow50000** [comment]
also you might want to trade some stuff for a +2 str bonus since weaker races and even humen males may get stammed out while smithing

**Comment by babamandaa** [comment]
This would easily be the most powerful cleric and probably the most powerful combat class in the entire game save for like captain or werewolf. The ability to win basically any stamina battle, oneshot anyone you're able to keep in a 3x3 grid for two seconds, and force someone to drop their weapon is insane. Also, heating an ingot on a five minute cooldown is ?????

**Comment by Diltyrr** [comment]
> This would easily be the most powerful cleric and probably the most powerful combat class in the entire game save for like captain or werewolf. The ability to win basically any stamina battle, oneshot anyone you're able to keep in a 3x3 grid for two seconds, and force someone to drop their weapon is insane. Also, heating an ingot on a five minute cooldown is ?????

How would you one shot someone with a spell that only does one thing to characters "roll to check if they fall down" which isn't a guaranteed? 

Also guarantee a win on any stamina battle ? What kind of fight in this game takes long enough for the state of the blue bar to really change anything?

**Comment by katsukai** [comment]
These are really cool, I would reduce heat metal cooldown to maybe 2 or 3 minutes. 5 seems too much.

Effect : Restores 50 Stamina to the caster if self targeted. Drains 100 stamina from the caster but restores 100 to the target if someone else is targeted.

Should turn this into Fatigue instead of stamina, seems absurdly strong in combat.

**Comment by Nakalon** [comment]
> These are really cool, I would reduce heat metal cooldown to maybe 2 or 3 minutes. 5 seems too much.
> 
> Effect : Restores 50 Stamina to the caster if self targeted. Drains 100 stamina from the caster but restores 100 to the target if someone else is targeted.
> 
> Should turn this into Fatigue instead of stamina, seems absurdly strong in combat.

I'm pretty sure Stamina is the Blue bar and fatigue is the green bar

**Comment by katsukai** [comment]
> > These are really cool, I would reduce heat metal cooldown to maybe 2 or 3 minutes. 5 seems too much.
> > Effect : Restores 50 Stamina to the caster if self targeted. Drains 100 stamina from the caster but restores 100 to the target if someone else is targeted.
> > Should turn this into Fatigue instead of stamina, seems absurdly strong in combat.
> 
> I'm pretty sure Stamina is the Blue bar and fatigue is the green bar

Blue bar is what I mean.

**Comment by Diltyrr** [comment]
> > > These are really cool, I would reduce heat metal cooldown to maybe 2 or 3 minutes. 5 seems too much.
> > > Effect : Restores 50 Stamina to the caster if self targeted. Drains 100 stamina from the caster but restores 100 to the target if someone else is targeted.
> > > Should turn this into Fatigue instead of stamina, seems absurdly strong in combat.
> > 
> > 
> > I'm pretty sure Stamina is the Blue bar and fatigue is the green bar
> 
> Blue bar is what I mean.

It's already affecting the blue bar, if that's what you meant?
As for the cooldown on heat metal I could reduce it, My reasoning for the 5 min cd was to avoid it being used multiple time in combat.

**Pull request merged**
