### PR TITLE
Ratwood is dead

### PR DESCRIPTION
**Pull request by ikrarkjr**
Play on Azure Peak

### CODE REVIEW

**Comment by aberrantQuesrist** [comment]
Why...? Shouldn't they be able to write and read for song-making or poetry or whatever?

**Comment by ikrarkjr** [comment]
> Why...? Shouldn't they be able to write and read for song-making or poetry or whatever?

Read the bard skills.

**Comment by aberrantQuesrist** [comment]
Pffft, that's silly. I didn't look far enough down.

**Comment by K4rlox** [comment]
bard are supposed to be able to read song sheets....

**Comment by ikrarkjr** [comment]
Anyone who votes thumbs down or comments clearly doesn't look at what bard's skills are lmao.

**Comment by Elli-Skala** [comment]
It doesn't help it wasn't made clear it's multiple skill adds stacking

**Comment by ikrarkjr** [comment]
> It doesn't help it wasn't made clear it's multiple skill adds stacking

It was a test of basic code literacy.

**Comment by radarseas** [comment]
aww, no more bards that could read so well you'd wonder why _they chose to not become a mage, or a necromancer, or literally anything else_, considering they used to read better than the archivist, **SOMEHOW**.

blessed PR.

**Comment by SixplyDev** [comment]
> bard are supposed to be able to read music sheets....

But bards didn't read music sheets in ye olden days, they sang songs and tales by word of mouth and memory

**Pull request closed without merging**
