### PR TITLE
Create Elfkeep

### PR DESCRIPTION
**Pull request by Murderfoxen**

### CODE REVIEW

**Comment by Murderfoxen** [comment]
This Map is great for the RP community who don't want the immediate Action of the Game. It co-exists as an addition to the main map via travel or Admin Teleportation. (It needs instance access and more help to achieve it's final form!!)

**Comment by Teragenic** [comment]
This is essentially a map to be voted on correct?

**Comment by Murderfoxen** [comment]
> what's next, Space Hotel? Ghost Cafe? LOL

This is arguably space hotel, yes. It COULD become ghost cafe, too. It's very open-ended as to how it can be implemented. That's up to the server owner and those voting. 

It also works well as a stand-alone map. 
I'll be working on it for a while, but I wanted to give it to everyone to see.

**Comment by DeerJesus** [comment]
you can have your dedicated erp hotspot on discord

**Comment by UntoldTactics** [comment]
this is a bad idea, flatout no need to seperate even more of the playerbase, theres a lotta areas already

**Comment by DeerJesus** [comment]
a MUCH better idea that more people might be willing to accept is a few changes to the underworld… like seeing each other’s names and ranks so you can chat, or the ability to go back from the underworld to dead land. Or a ducking dead chat

**Comment by Genevesh** [comment]
I'd say this should be more of a new map than a 'space hotel' alternative.

**Pull request closed without merging**
