### PR TITLE
Fix Bath Swain Latejoining?

### PR DESCRIPTION
**Pull request by Stagrawl**
I'm useful.

### CODE REVIEW

**Comment by coffeecoffeecoffee** [comment]
Maybe now there will actually be swains.

**Comment by CalamaBanana** [comment]
Did this truly fix it? Never been able to latejoin as one today at least, even during lowpop where I was quite certain slots should have been free

**Comment by Stagrawl** [comment]
this should have fixed it, but it's possible it's somehow fucked up elsewhere.

**Comment by CalamaBanana** [comment]
All good, paid attention this round. Seems to work after all.

**Pull request merged**
