### PR TITLE
Shylocks at shops

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Adds shylocks at smithery and merchant so you dont need to run half of town to the closest one
Also moves inn shylock into better position

## Why It's Good For The Game
you dont need to run half of town to the closest shylock to buy shit

### CODE REVIEW

**Comment by Nakalon** [comment]
I don't personally like this. I like how you either keep your money safe in key locations or you bring it with you which adds some vulnerability.

Will ask for other opinions.

**Comment by Heheniy** [comment]
noone takes their money out before going to smith/merchant, because you need first to know the price- how much do you need to withdraw, because putting money back will get you taxed

**Comment by Heheniy** [comment]
weird
image
image

**Comment by Nakalon** [comment]
> noone takes their money out before going to smith/merchant, because you need first to know the price- how much do you need to withdraw, because putting money back will get you taxed

Good this creates conflict.

As it is now you have 2 choices, either go to the shylock before, get more money than you have to spend and get taxed after or go after talking to the shopkeep and have to deal with someone cutting you off in the line.

This way its just. "20 mammons please. Okay. *gulp. There".
Its convinicence for conviniences sake.

**Comment by Heheniy** [comment]
annoying things != good things

**Comment by Heheniy** [comment]
it is not that type of conflict that you want

**Comment by Nakalon** [comment]
Still since I'm against this myself I'll ask for opinions.

**Comment by Nakalon** [comment]
> Pros: • Convenient! • I guess I can mug people at the ATM in more out of the way areas?
> 
> Cons • Slightly immersion breaking to me. Feels exceptionally modern and high-tech; with one or two it feels like some unique invention.. but now that they're everywhere it feels like, okay.. who's **actually** building these highly advanced, technical contraptions? • I kind of agree that I want more traffic from people moving around to get their money. People should get in the habit of carrying around more money, anyways, and this makes it less likely that people will do so.

I agree!
"Given the Opportunity, Players Will Optimize The Fun Out of a Game"

**Comment by Heheniy** [comment]
there is no fun hin running back and forth to shylocks

**Comment by Keazra** [comment]
> there is no fun hin running back and forth to shylocks

It's not that it's "fun", it's that it's immersive and provides opportunities for player encounters. The mere act of creating traffic is a form of engagement that should remain intact, IMO.

**Comment by Heheniy** [comment]
'engagement' should not be created by annoying shit out of players

**Comment by Keazra** [comment]
> 'engagement' should not be created by annoying shit out of players

Why don't most games simply teleport you to where you need to go, then? At some point we are arbitrarily deciding, with every mechanic, on how annoying it is to use or not. Not all mechanics need to be super fun. I just think adding more ATMs stretches immersion, for me, and subtly changes traffick dynamics.

Ultimately I suppose it's not _that_ big of a deal, I'm just providing my input on how I feel.

**Comment by Nakalon** [comment]
After receiving enough feedback confirming my beliefs I have decided to close this.

While we are for QOL things there is a point where we have to discern when something stops being QOL and becomes either too convenient or too efficient.

We want to give players a reason to move around. Shylock and Stockpile scarcity are one way of subtly suggesting this!

Sorry!

**Pull request closed without merging**
