### PR TITLE
Door lock difficulty & lockpicking skill fix

### PR DESCRIPTION
**Pull request by john-pawson**
## About The Pull Request

This PR does two things:
1. Fixes the issue of lockpicking using normal experience instead of sleep experience. No more grinding lockpicking to legendary on the first day of the week.
2. Adds lock difficulty! Now some doors will be more difficult to lockpick than others, this means that such things like the vault and the armory will be harder to lockpick into than some random house on the town. Below i'll leave a list of all the doors that now have a lock difficulty, any that aren't mentioned here haven't been touched. Feel free to remind me of any doors i might've missed:

- Level 1 (Minor security)

Seamster's shop
Center town smithy
All of the street shops
Inn's kitchen doors (Since they lead to where all the keys and ale is)
Mercenary's guild
Church's private area
Solison's entrance
Artificer's

- Level 2 (Medium security)

Merchant's shop
Vanguard's gate
Vanguard's armory
Vanguard's dungeon
Watchouse's cell doors
Keep's cell doors
Keep's bedroom doors

- Level 3 (High security)

Watchouse's entrances
Watchman's armory
Guild smithy's entrances
Court mage's tower

- Level 4 (Very high security)

Keep's armory
Steward's tower 

- Level 5 (Vault)

Vault

(Every level makes it harder by one level, so a **master** lockpicker trying to open the vault will have the same chance of a novice lockpicker trying to open a shop)

## Why It's Good For The Game

Hopefully, this'll make things such as people lockpicking the smithy's backdoor to steal all of the valuables inside (Which has led to most smiths having to wall off those entrances) and people lockpicking straight into the most secure places with little to no skill more rarer. 
No more random refugees breaking into the watchouse to rob the armory with a single ring of lockpicks and 5 minutes of training. 
People like thieves, knaves and the hand that do have some decent lockpicking skill will still be able to pick the locks without much trouble, just taking slightly longer and maybe breaking a lockpick or two if the door is secure.

### CODE REVIEW

**Comment by Gyrandola** [comment]
steward should be very high considering people can drain the treasury.

**Comment by john-pawson** [comment]
Alrighty then.

**Comment by RyszardParys** [comment]
Meh, the sleep leveling up is ass anyway, kinda sad this got ""fixed""

**Comment by john-pawson** [comment]
> Meh, the sleep leveling up is ass anyway, kinda sad this got ""fixed""

Better than letting anyone powergame the skill to legendary by farming for 20 minutes and pick any lock in ~5 seconds. It's even worse since the skill got raised exclusively by pick success, so leveling up got exponentially easier the higher level you were.

**Review by NikolayByondPlayer — APPROVED** [review]

**Review by Gyrandola — APPROVED** [review]

**Review by Gyrandola — APPROVED** [review]

**Comment by DabTheBold** [comment]
I do like that different locks are harder but I just had a round where I got to legendary lockpicking and broke all 3 picks on the vault and only got 1 click. That seems a little too tough to be honest.

**Comment by john-pawson** [comment]
> I do like that different locks are harder but I just had a round where I got to legendary lockpicking and broke all 3 picks on the vault and only got 1 click. That seems a little too tough to be honest.

You should've had an ~50 percent to get a click, and needed to get 7 clicks to unlock it successfully since it's got more health but you have more progress per click. So... it would've been a straight 50-50 chance, the first to 7 clicks or 10 clacks, click and clack having both 50% chance.

So i'll say this confidently: 
Skill issu-
Just joking, it's plain bad luck.

**Pull request merged**
