### PR TITLE
Allows cleaning the coom-decal from floors by biting it.

### PR DESCRIPTION
**Pull request by CalamaBanana**
## About The Pull Request

This PR allows to clean the evidence after the act in a slightly degrading way.
If one is lying down and can use their mouth,  using the "bite" action on a floor with a coom decal on it will start cleaning it.

Small note, cleanables (blood and others as well) do not seem to be targetable directly ingame in this codebase, so I had to sneak it into the floor code instead.

## Why It's Good For The Game

Highly improves the maid gameplay loop.

### CODE REVIEW

**Comment by CalamaBanana** [comment]
That is the same volume you have when drinking from the bog directly. I stole the code there.

**Comment by hivemuscle** [comment]
perish

**Comment by githubuser4141** [comment]
Why only coom and not other cleanables like blood or dirt?

**Comment by CalamaBanana** [comment]
Because other cleanables should have deeper interaction. Slurping up dirt/blood should make one vomit and stuff like that. Would be a bit weird to be able to lick everything clean without consequence.

Right now it's just kink stuff.

**Comment by Gyrandola** [comment]
This is not holy.

**Comment by DeerJesus** [comment]
> Because other cleanables should have deeper interaction. Slurping up dirt/blood should make one vomit and stuff like that. Would be a bit weird to be able to lick everything clean without consequence.
> 
> And mostly, doing it with blood/dirt would just be weird, half the rounds you end up with servants crawling all over the floor to clean instead of grabbing a soap/rug. Right now it's just inconsequential kink stuff,

Week old floor cum would probably make you vomit too

**Pull request merged**
