### PR TITLE
Adventurer Balance Pass

### PR DESCRIPTION
**Pull request by babamandaa**
## About The Pull Request

Doing a quick pass on all of the Adventurer classes to make the underplayed ones (Barbarian and Bard) more interesting while giving volatile or unorthodox classes (Amazon, Monk) more of a general power level. In short;

- Barbarian (Warrior) now starts with an Axe, is open to both genders, and is a bit tankier at a tiny cost to raw power, while Hunter-Killer is mostly untouched.
- Bard (Not Skald) now starts with a Bow at the cost of some speed. (Admittedly huge buff, but the class was already easily the weakest in direct combat)
- Amazon, instead of having a 75% chance to be Journeyman with a sword and a 25% chance to be a master with polearms, instead has a 50% chance to be an Expert with either one. Also buffed unarmed and wrestling, since it's a rarer class.
- Monk now has legendary fist-fighting at the cost of now having Journeyman wrestling in order to make them punchier. Because they relied so heavily on Master grappling, their speed was buffed by 1 point while their strength was nerfed by 1.

## Why It's Good For The Game

Adventurer is the most common job choice for a reason - people like playing as a combat-capable blank slate to hang out in the bog or the town, and that's not inherently a bad thing. However, each of the four classes being adjusted doesn't line up with its traditional archetype.

- Barbarian is locked to men for some reason, and Warrior starts with a sword instead of an axe like they do in most games.
- Bard is almost an entirely non-combat class unless you pick Skald. It's effectively just "Minstrel but it comes up when you pick Adventurer" and it needs a boost.
- Amazon is insanely volatile, either having one of the best starts in the game (Master Polearms and a Spear with excellent stats) or just a mid start  (Journeyman Swordsmanship, nice stats and shitty armor) depending on a dice roll while also being a rare class.
- Monk is literally a grappler at this point - its gameplan is "Grab hand holding weapon, grab torso, tackle, pin, beat in head" when it should be "Dance around your opponent and pepper them with blows until they fall over".

This list of changes will bring what combat classes _should_ be closer to what combat classes _are,_ and will help set them apart from each other more clearly. I tried to keep conscious of each class's power budget, but I am not a coder nor a game designer. If any changes are suggested/needed before (possibly) test merging please make them!

### CODE REVIEW

**Comment by john-pawson** [comment]
Why would a bard, a non-combat class, need a bow to make them better at combat?

Also what's wrong with a monk being a grappler? They've got no armor or weapon skills and right now the only way to beat an armored opponent as a monk would be by wrestling, since punching barely does any damage (even less now that you gave them lower STR) and doesn't give you any kind defense other than maybe dodging unless the other person is also fist-fighting.

Besides, giving them legendary punching would also mean giving them legendary skill on the katar, but i don't know how much that'd end up affecting it.

**Comment by babamandaa** [comment]
> Why would a bard, a non-combat class, need a bow to make them better at combat?

IMO Adventurers are meant to be combat classes and Pilgrims are meant to be non-combat classes. Bard, being under adventurer, should have some combat capability.

> Also what's wrong with a monk being a grappler? 

Literally nothing! Maybe it would make more sense to give them the option between a speedy, skilled but slightly weaker boxer and a stronger grappler type. Still, when you think of monks in fiction you're not thinking "I'm gonna tackle you, rip your helmet off and then pick at your throat with a dagger", you're thinking "Oh, they're the punchy guys." They might be slightly weaker against armor, but having a high attack speed and chance to hit means they can still knock you out very quickly and that's basically a won fight.

**Comment by john-pawson** [comment]
> IMO Adventurers are meant to be combat classes and Pilgrims are meant to be non-combat classes. Bard, being under adventurer, should have some combat capability.

But they are already combat capable? They have high stats, dodging and armor skills, and are trained weapons like knives compared to any other pilgrim class, if anything take it like the life-cleric/war-cleric sublcasses, bard is the life cleric which is less combat centred, skald is the war cleric which is more.

> Literally nothing! Maybe it would make more sense to give them the option between a speedy, skilled but slightly weaker boxer and a stronger grappler type. Still, when you think of monks in fiction you're not thinking "I'm gonna tackle you, rip your helmet off and then pick at your throat with a dagger", you're thinking "Oh, they're the punchy guys."

While i do agree a bit, when i say they're bad against armor, i mean: 
"If the enemy is wearing almost any type of armor makes fist-fighting a bad idea." 
Even if they have the cheapest armor like a leather vest or a slightly thick cap it's going to take in all of the damage from the punch, rendering it useless.
Fist fighting is truly only a viable option when it is on complete equal grounds, unarmored and unarmed man vs unarmored and unarmed man, one of them or both have armor OR weapons? Then fist-fighting becomes a last resort.
It's not that they shouldn't fist-fight or that they should use wrestling more sparringly, it's that fist-fighting is useless in most fights.

> They might be slightly weaker against armor, but having a high attack speed and chance to hit means they can still knock you out very quickly and that's basically a won fight.

Friendly reminder that crits (knocking out people) and damage with fists is directly tied to STR and nothing else, so giving them higher SPD or skill is NOT going to help knocking people out or attack faster, but only on going through parries, parrying (if the other person is ALSO fist-fighting, or you have a katar), and dodging.

**Comment by wow50000** [comment]
not a fan of what you did with barbarians str and end, as well as giving them an axe they can already craft. seems like a nerf to me. as for what you did with amazon, about fucking time.

**Comment by radarseas** [comment]
tbh, monk should have always been a pilgrim class anyway.
sure I guess you can get armor and tacklemax but you're punished heavily for doing so with awful combat stats outside of unarmed, let alone if they just stab you with a polearm and your average bandit/watchman can probably still tackle you down anyway.

honestly, let warriors/amazonians/barbarians just pick what weapon they start with and specialise in.

not sure why bards should use bows, if anything they're an RP class, not a fragger class. maybe some misc talents like fablefield/jester gets. poems, tales, jokes, entertainment sort of.

speaking of warrior, they **need** a buff to seperate them from paladins who are just objectively superior in every shape and form, especally in the long run, like probably better stats in their chosen weapon.

**Comment by katsukai** [comment]
Genuine **** you, if you're changing monk into journeyman wrestling when all garrison and bandits are minimum expert to master wrestlers. Makes the entire class pointless to play because you cannot damage people's armor with your fists and rely on grabs heavily to even stand a chance. And no I am not gonna beg the Smith to make me a Katar.

**Comment by Hmeister-real** [comment]
i HATE the monk changes, undo that shit. they are an awful class for anything but wrestling, removing wrestling makes them useless

**Pull request closed without merging**
