### PR TITLE
Lich Antag

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Ports the Lich antagonist from Azure peak. Coal or gem? We shall see.

> Lich spawns with 3 phylacteries, each of which allow them to live again when they die. You'll be teleported to one after you die, and reform with everything you had on you before you died, so if you lose ur head your helmet and shit is gone etc.
> 
> Those phylaceteries are used up and far as I can tell there's no way to make new ones, so you've got 4 lives, use them well.
> 
> Lich gets
> Bone chill - Channel use spell, acts like a miracle for skeletons and undead, but used on the living, damages and stuns them, akin to how miracle works on vampires.
> 
> Raise greater undead - raises a skeleton, that will be offered to the dead of the underworld, if none are selected it just acts like a lesser undead
> 
> Raise lesser undead - just a skeleton NPC, nothing special
> 
> (Note both of these spawn with skeleton RNG loot kits, so they're an infinite source of free iron and steel, lmao)
> 
> fireball
> 
> blood bolt (the VL spell thats lightning bolt but cool and red basically)
> 
> lightning bolt
> 
> fetch
> 
> secular diagnosis (the doctor examination spell, kinda useful utility)

## Why It's Good For The Game

We need more antags.

### CODE REVIEW

**Comment by Coolgat3** [comment]
Could we get a rundown of how it works instead of having to learn to read code

**Comment by Heheniy** [comment]
skeletons have no skills at all and no intents (strong, fast, aimed and ec)
also skeleton players loosing triumphs when dying (they are literally disposable)

**Comment by Heheniy** [comment]
also let them die without waiting 2 minutes in crit

**Comment by Heheniy** [comment]
spirits of players that accepted to be a skeleton does not dissapear from underworld

**Comment by HissyNays** [comment]
Playing as skeleton is a bit of triumph dump :(
Make it not waste triumphs on death and make it so you're sent to main screen when you die instead of having to find coin.

**Comment by Heheniy** [comment]
also there should be way for skeleton to kill himself or leave body if he fully crippled

**Comment by Heheniy** [comment]
if you move when skeleton spawn proposal pops up- it dissapears

**Comment by ikrarkjr** [comment]
This antag is complete shit. You're just fighting a mage with the ability to stunlock you with zero counterplay. This takes everything people hated about vampires and makes it even worse. Vampire mage dual class + transfix spam.

**Comment by kepesk1** [comment]
transfix should not exist

**Comment by Rayforx** [comment]
> This antag is complete shit. You're just fighting a mage with the ability to stunlock you with zero counterplay. This takes everything people hated about vampires and makes it even worse. Vampire mage dual class + transfix spam.

The antag in itself is fine, but it does need to have some reworks for the bone chill. The idea that classes/abilities can stun-lock a player to have them die without being able to resist, has been a problem I feel.

bonechill: Instead of it being a stun lock, then it would be better if it slows the person, perhaps, with a custom curse that reduces your speed and fortune for 5 minutes

In terms of playing as a skeleton being a triumph dumb, then I do not see a reason why playing as a servant that HELPS makes the round more enjoyable, should not give you triumph in the same way as being a player in the round, so providing a skeleton 2 triumph (1 for when they die, and another 1 to keep) for joining in as the role, could certainly help a long way. If someone abuses it, then the lich can ahelp if someone is farming triumph by suicide.

Skeletons also need some skills, perhaps, a skeleton "job" could work, that is specific for the antag that gives them a bunch of random skills?

Also, I am not sure why we do not give the greater skeleton any gear when they can spam lesser skeletons to kill them for equipment.

**Comment by radarseas** [comment]
Some feedback:

skeletons need more than just being free steel for town to immedately rock up with fullplate against you.

sentient skeletons need far, far more to them than just, skeleton but player controlled, be it fighting classes, smithies for arming your undead army, miners, woodcutters, archers and hunters, etc... actual skills

---
_we already have death knights too to work off of_, it would be interesting if they were rolled into something to do with this, but still in limited moderation like vampire lord.

do they need **TWO** lightning bolt varients? I think blood magic should be more a cultist or vampire thing than an undead, bloodless skeleton necromancer?

They could **probably** use objectives to strive towards, we already suffer the issue that _werewolves_ don't do anything because they have _no obiligations_ than just existing to triumph, _nothing to push for conflict but player side and no reward for it._

If they have diagnosis to heal their minions, they should have a stashed surgery kit and the skills to use it, _like maniac has their surgery kit and knife stashed away._ as well as a welcome prompt like bandits to hint at it.

---
> transfix should not exist

transfix only works for the early stages for vampires, as the hardstun funny hand does blood cult on TG where they need to hit converts dirty to get their early numbers, it sucks en-mass or lategame, but I don't see transfix on lich at all though...?

**Comment by Rayforx** [comment]
I forgot to ask, an examine text like with the werewolves where you can see if someone is a skeleton would be nice

**Comment by ThatReformedEngineer** [comment]
Why were the tongues of the skeletons removed? Was there some issue with skeletons abusing the ability to speak or something else?

**Comment by Rayforx** [comment]
Please make separate skeletons that the lich spawns, outside of the ambushes of what spawns in the wild. Having skeletons spawns that are completely useless to kill, is dumb

**Comment by radarseas** [comment]
Lich definitely needs a way to heal their minions if they will rely on resurrected bodies and a way to work around churn undead in a mob of 7 skeletons instantly sending them into crit.

As much as i know skeles did act a bit silly, they should regain their tongues, their ability to share intel, assist in your plans or relay your orders and convince other skeles to _not run off and murderise everyone is better than what flaws it had._

Lich needs a way to obliterate, stun and punish their minions in case you get that one guy _that tries to instantly kill_ their master, _like vamp lord had as a problem._

---
It would be cool if liches started off resembling a human, hair, skin and all and gradually decayed more to a skeleton form with each phylact in exchange for more benefits and weaknesses of being undead, _with their first death marking them as the monster on examine they truely are, like vampire lords are marked on examine._

It would give them a nice stealth phase, reward them for playing carefully but also open up the risk of using phylacts to become more powerful as a tradeoff before you strike.

**Comment by radarseas** [comment]
I checked the code lately, bone chill massively heals the undead but the description and name of it is so vague, I assumed it an entirely offensive move, it really needs a renaming of that spell to something like "**necrotic restoration**". I had no clue that bone chill even healed a whooping 50 points of damage on skeles until I just checked the code yesterday.

**Pull request closed without merging**
