### PR TITLE
Accents II CORE

### PR DESCRIPTION
**Pull request by Squird5**
#315 Reboot

## About The Pull Request

A little more accent variety among races to make them less homogeneous ((I hated 100% of elves being Russian)). Also tried to make the formatting more consistent between the JSONs.

Also removed the majority of the non-English words from most lists (Except German), making them more oriented around the sounds they make than simply tossing in foreign words.

## Why It's Good For The Game

More variety in speech patterns is always good. Also, all elves speaking demi-Russian would throw me completely out of character every time I saw "Privyet" or "Da" and I would stop thinking of my own character and instead of my friend's Pathfinder character.

## REFERENCE GUIDE

Accents are now broken into four parts: **Full**, **Start**, **End**, and **Syllable**.

**Full** replaces only entire key words with their counterpart. Any additional characters will prevent it from triggering.
`"watch": "look"` will only apply to "**Watch**", changing it to "**Look**", but variants like "**Watch**ed" or "**Watch**es" will **not** change

**Start** will replace words that start with the key word, regardless of the following characters.
`"watch": "look"` will end up allowing **Watch**ing and **Watch**ed to convert to **Look**ing and **Look**ed

**End** is the opposite of Start. It will apply to characters only at the end of a word. Useful for consistently dropping a letter at the end that would be messy if applied as a Syllable.
`"ing": "en'"` will end up allowing Watch**ing** and Slapp**ing** to convert to Watch**en'** and Slapp**en'**

**Syllable** will apply to any instance of the characters in the text, so use it carefully.
`"a": "aye"` would end up being painful, changing "H**a**ve **a** nice d**a**y" to "H**aye**ve **aye** nice d**aye**y"

### Notes
**Do not** use escape characters for things like apostrophes. `\'` It will work in some cases, but not all, resulting in demihuman accents working fine while the exact same accent list on Humans doesn't.

The **order of your replacers matters**. While having them in alphabetical order might look nice, it can result in unwanted outcomes. If a "c" becomes a "k", and a "k" becomes "kh", words like "Change" turn into "Khhange".

**Always test your work.**

## Change List

* REGEX fixed to allow for different types of replacers, while working reliably and multiple times in a line of text.
* Reformatted Universal without changes
* Reformatted German without changes, adding the new regex fields
* Reformatted Anglish without changes, adding the new regex fields
* Reformatted Middlespeak without changes, adding the new regex fields
* Reformatted Dwarf without changes, adding the new regex fields
* Reformatted Proper without changes, adding the new regex fields
* Changed French, removing most of the full word replacements
* Changed Russian, removing the full word replacements and tweaking some of the quirks
* Readded Spanish

### CODE REVIEW

**Comment by CalamaBanana** [comment]
Why those changes to the Elven accent? You turned it from non-intrusive flavor into something quite annoying for no apparent reason. "I" to "EE" is just awful, and will look really bad in every other sentence, as it will replace the pronoun "I". Same with your h to kh. Wkho, wkhile, wkhen. 
Ee brrou'kht you peee, my keen' - That looks just awful. 

Please just leave it as it was, there was nothing wrong with it before.

**Comment by Squird5** [comment]
I really want it gone from most of Elven, but I'm not allowed to do that in one PR

**Comment by CalamaBanana** [comment]
> I really want it gone from most of Elven, but I'm not allowed to do that in one PR

Don't try to achieve it by making Elven annoying as fuck so people argue for it, please. There was nothing wrong with the old syllables.

**Comment by Squird5** [comment]
Idea is more reduce the amount of Russian in use

```/datum/species/elf/wood/get_accent(mob/living/carbon/human/H)
		switch(H.skin_tone)
				if(SKIN_COLOR_DANDELION_CREEK)
						return strings("welsh_replacement.json", "full")
				if(SKIN_COLOR_AZUREGROVE)
						return strings("russian_replacement.json", "full")
				if(SKIN_COLOR_ALMONDVALLE)
						return strings("Anglish.json", "full")
				if(SKIN_COLOR_WALNUT_WOODS)
						return strings("welsh_replacement.json", "full")
				if(SKIN_COLOR_TIMBERBORN)
						return strings("russian_replacement.json", "full")
		return null

**Comment by CalamaBanana** [comment]
> Idea is more reduce the amount of Russian in use
> 
> ```
> 		switch(H.skin_tone)
> 				if(SKIN_COLOR_DANDELION_CREEK)
> 						return strings("welsh_replacement.json", "full")
> 				if(SKIN_COLOR_AZUREGROVE)
> 						return strings("russian_replacement.json", "full")
> 				if(SKIN_COLOR_ALMONDVALLE)
> 						return strings("Anglish.json", "full")
> 				if(SKIN_COLOR_WALNUT_WOODS)
> 						return strings("welsh_replacement.json", "full")
> 				if(SKIN_COLOR_TIMBERBORN)
> 						return strings("russian_replacement.json", "full")
> 		return null
> ```

Thank you for swapping it back, appreciate it. I remember that, was me who begged you to keep it on Azuregrove on the other PR, too.

**Comment by Red-Honk** [comment]
Wanna know what be nice? If the german one changed 'Die' to 'Das' making it neutral making putting more context easier compared to 'Die' which might be confused for that exact thing which is annoying, as well as 'Goblin' going 'Kobold', it made sense back then, but now we got little folk that are just that and it makes null sense, I'd advise changing those two words.

**Comment by Zebraman** [comment]
Can you please just straight out remove the dwarven accent? It's pure nonsensical gibberish that no one fully understand. It was added by a troll who tought it would be funny if dwarfs would sound like inbred Scotish and it just should go, I hate not being able to rp as a dwarf in a fucking rp server.

**Comment by Stokeling9701** [comment]
why does the spanish use weon for 9 words? isnt that kinda redundant?

**Comment by Squird5** [comment]
> why does the spanish use weon for 9 words? isnt that kinda redundant?

Weon can mean lots of different things
Probably one that should be cut down though, maybe to just insulting terms to make it less confusing
Probably readd the Castilian Tiefling Spanish lock instead of having it universal, like before

**Comment by Stokeling9701** [comment]
> > why does the spanish use weon for 9 words? isnt that kinda redundant?
> 
> Weon can mean lots of different things Probably one that should be cut down though, maybe to just insulting terms to make it less confusing Probably readd the Castilian Tiefling Spanish lock instead of having it universal, like before

id like to make a good suggestion to have it borrow from differing latino dialects, such as tonto, huevon, pendejo etc etc. Itd make a interesting and unique form of spanish that has variety and stops people from pinpointing exactly what kind of spanish/latin they are.

**Comment by CalamaBanana** [comment]
Please do get rid of that "Who -> Whom" you want to add to Elves for some reason as well. Whore -> Whomre, Whole -> Whomle. Wholesome -> Whomelsome. That is just weird and out of nowhere. And do not remove "Da" and "Privyet" either. Those are staples of the Elven identity by now. Just leave it as was, please.

**Comment by Cyprex** [comment]
Accents are just bad, quite frankly, to the degree that they are implemented here. Da for Yes is fine but some of the replacements are very non-obvious, and I have to guess what someone is trying to say *way* too often. It kills RP. Like, buddy, I'm not gonna want to hold a long conversation with you when I have to guess what every fourth word is supposed to mean. (Looking at you, dwarves, but this also applies to other accents!).

These should be thin flavor, not make your speech unintelligble 1/3 of the time.
Like, Yes-> Da is fine, I have no idea what Privyet is supposed to be but I think it's just "Thanks" or something. Whatever. Adios and Hola aren't too bad either.

Part of it is that nouns specifying what you are talking about carry a lot of meaning you can't deduce from context. For example if a halforc comes in ordering a horned kenelm I'm like "Sorry bud but that's just not a thing" and you kind of have to know that for some reason helmet->kenelm. Similiarly "The knight killed the hand!!!". The words knight and hand here are critical, and can't really be deduced from context.

I genuinely believe that accents are way overboard in a lot of cases in this game right now, and hinder RP.

**Comment by Gysilian** [comment]
Accents being tied to races is meh. I'd also like a lot to have the option (not) to put up with the fantasies coders have about accents and to just be able to be understood. And not be forced to russian larp as elf or sound like a degenerate as dwarf.

**Comment by Squird5** [comment]
> Accents are just bad, quite frankly, to the degree that they are implemented here. Da for Yes is fine but some of the replacements are very non-obvious, and I have to guess what someone is trying to say _way_ too often. It kills RP. Like, buddy, I'm not gonna want to hold a long conversation with you when I have to guess what every fourth word is supposed to mean. (Looking at you, dwarves, but this also applies to other accents!).
> 
> These should be thin flavor, not make your speech unintelligble 1/3 of the time. Like, Yes-> Da is fine, I have no idea what Privyet is supposed to be but I think it's just "Thanks" or something. Whatever. Adios and Hola aren't too bad either.
> 
> Part of it is that nouns specifying what you are talking about carry a lot of meaning you can't deduce from context. For example if a halforc comes in ordering a horned kenelm I'm like "Sorry bud but that's just not a thing" and you kind of have to know that for some reason helmet->kenelm. Similiarly "The knight killed the hand!!!". The words knight and hand here are critical, and can't really be deduced from context.
> 
> I genuinely believe that accents are way overboard in a lot of cases in this game right now, and hinder RP.

I am not touching the German, Dwarf, Anglish or Middlespeak accents and very much do not want to. If someone else wants to, they very much can.



> If you find accents annoying, then you should simply make accents an optional thing to anyone. For all we know there could be a human raised by drows with a drowish accent, or a drow talking like a grenzelhofter. Maybe restrict them slightly but offer enough variety to let people "annoyed" by it avoid them, but people who fucking love those and use them frequently do so.

This is very much what I would like to do, but when I was trying back in #315 and asked for help, I couldn't find any, and Azarak the head maintainer, and the one I think wrote the code for the character customization, basically told me that was a stupid idea.

What I would very much like is a per race list you can pick from, rather than them being tied to skin tones as they currently are. This PR is effectively just fixing the regex that got changed a month and a half ago with a few minor changes to accents themselves. There will be additional PRs that further expand things, and I hope I can get assistance in making a Accent Selection system one of them.


> Accents being tied to races is meh. I'd also like a lot to have the option (not) to put up with the fantasies coders have about accents and to just be able to be understood. And not be forced to russian larp as elf or sound like a degenerate as dwarf.

Agreed, but I was told to break my PR into a lot of "smaller" PRs. This one is just making things work as they used to and building a foundation for future enhancements.

**Pull request merged**
