### PR TITLE
Boggate Barracks Merge

### PR DESCRIPTION
**Pull request by MickDick1**
## About The Pull Request

Merges bog barracks and gate into one.
Added palisades to the gate facing out toward the Terrorbog.
Removes bog armory and bog barracks keys.
Adds bog master personal office key.
Armory severely reduced.
Prison is now a tower on top of the gate with a single stone window for one of the cells.
Added a little bit of mining weakness to the east side (still have to break the walls)
Moved the barracks shylock to the purity machine on the road.

Visual:

image
image
image

## Why It's Good For The Game

Merging the barracks and bog gate consolidates the boggers that leaves them functional even on lowpop.
No more stealth robbing the armory.
Armory is reduced and thus not a major source of loot/equipment. Besides, the server equivalent of the "Night's Watch" being so insanely oversupplied was stupid.
Bog master getting a personal office just seemed reasonable.
The prison tower is cooler than the generic basement dungeon.
The gate being casually scaled by antags (bandits) every single round was cringe and why wouldn't a fortification like this have the most basic defenses like palisades on the walls facing the threat?

Generally, less round-after-round busy work, more centered organization for boggards, better defenses roundstart, and in exchange they lost most of their armory. I'm hoping this makes bog guards a little more cohesive.

### CODE REVIEW

**Comment by Heheniy** [comment]
why are you adding palisades to second floor if there are stone windows?
all rooms you made are gonna be dark or fully dark
no floor at first level for some reason
also holding cells for some reason at third level???

**Comment by NikolayByondPlayer** [comment]
> why are you adding palisades to second floor if there are stone windows? all rooms you made are gonna be dark or fully dark no floor at first level for some reason also holding cells for some reason at third level???
> 
> ngl your design looks bald and ugly in general

Stone windows are bad idea, palisides can be broken  at least.
Design and decorations can be improved but overall is a good stuff!

**Comment by NikolayByondPlayer** [comment]
I would suggest a decoration pass and add back some items that were in original place, try to use the empty space with either decorations or useful gameplay elements.

**Comment by Nakalon** [comment]
I recommend you maybe ask Nikolay for some direction! But this is a good idea, just needs some polish!

**Comment by radarseas** [comment]
I'd axe the pitchforks and replace em with a spear and maybe a few crudgels _(they only smelt into ash, can't get iron off crudgels)_ instead.

the issue is pitchforks from the bog armory at the moment are only ever stolen by bandits to melt down, the garrison don't use em since everything else is just a better choice

**Comment by Nakalon** [comment]
Please be very careful! We're this to be merged right now other map PRs that got merged (including all the seamster PRs) would he undone!
Please be careful as to how you handle these conflicts! Cheers!

**Comment by NikolayByondPlayer** [comment]
> Please be very careful! We're this to be merged right now other map PRs that got merged (including all the seamster PRs) would he undone! Please be careful as to how you handle these conflicts! Cheers!

Some pipeline of Map PR priorities would be good:
Like maintaner labels map merge order and people can update their pr's after each merge to speed things up. 
Aka first to go seamster - then barracks - then overall updates

I am probably overthinking but it would make things clearer perhaps?

**Comment by Nakalon** [comment]
> > Please be very careful! We're this to be merged right now other map PRs that got merged (including all the seamster PRs) would he undone! Please be careful as to how you handle these conflicts! Cheers!
> 
> Some pipeline of Map PR priorities would be good: Like maintaner labels map merge order and people can update their pr's after each merge to speed things up. Aka first to go seamster - then barracks - then overall updates
> 
> I am probably overthinking but it would make things clearer perhaps?

I'm not sure Nikolay. I don't even know how Map PR conflicts are handled, I've never had to deal with that. But yes we may need a better solution!

**Comment by NikolayByondPlayer** [comment]
> > > Please be very careful! We're this to be merged right now other map PRs that got merged (including all the seamster PRs) would he undone! Please be careful as to how you handle these conflicts! Cheers!
> > 
> > 
> > Some pipeline of Map PR priorities would be good: Like maintaner labels map merge order and people can update their pr's after each merge to speed things up. Aka first to go seamster - then barracks - then overall updates
> > I am probably overthinking but it would make things clearer perhaps?
> 
> I'm not sure Nikolay. I don't even know how Map PR conflicts are handled, I've never had to deal with that. But yes we may need a better solution!

You need to re add changes on your unmerged PR after each map file updates

**Comment by Crowbar764** [comment]
It looks cool, but keep in mind, the more unpleasant you make attacking the bog gate, the more likely those bandits are to just take an alternate path and go frag at the town instead, ignoring the guards they are actually designed to fight.

Fortifying with palisades was optional gameplay content for the guards, they don't have that now.
They will also fight less bandits, if any at all, due to the newly added difficulty to break in.
It also screws over low-pop where there are no bog guards, and vaulting over was the only option for any bog-start players trying to get through.

**Comment by Nakalon** [comment]
> It looks cool, but keep in mind, the more unpleasant you make attacking the bog gate, the more likely those bandits are to just take an alternate path and go frag at the town instead, ignoring the guards they are actually designed to fight.
> 
> Fortifying with palisades was optional gameplay content for the guards, they don't have that now.
> They will also fight less bandits, if any at all, due to the newly added difficulty to break in.
> It also screws over low-pop where there are no bog guards, and vaulting over was the only option for any bog-start players trying to get through.

Extremely valid points here which made me sway out of favor for this PR...

**Comment by Gyrandola** [comment]
life check?

**Comment by MickDick1** [comment]
Yeah it's fine it just needs the decorations and a little looking over. soontm.

**Comment by Gyrandola** [comment]
quite the larger rework in https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1493

**Pull request closed without merging**
