### PR TITLE
Roundend mugshot credits

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

- Ports roundend credits from https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/357.

image

### CODE REVIEW

**Comment by Hmeister-real** [comment]
The text needs a background because sometimes (like with dark purple or yellow) they are really hard to read. But past that I really like it

**Comment by Crowbar764** [comment]
Maybe make it so people with no mugshot get skipped.

**Comment by Nakalon** [comment]
Gyran we should really use this technology for the bandits!!!

**Review by Nakalon — APPROVED** [review]
it just works

**Pull request merged**
