### PR TITLE
Leashes Part 1

### PR DESCRIPTION
**Pull request by Kevak**
## About The Pull Request

Testmerge please, not fullmerge. This isn't ready for full yet.

This adds leashes! And collars! They're craftable! The sprites are shitty codersprites, a spriter is working on better ones and they will be added as soon as feasible.

Wonderful sprites by daemoninsideme

Screenshot 2024-12-17 160513

Oh also I added jingly collars. And the jester's hat jingles now too.

-Rope with needle to craft the currently available leash, more will be added when the sprites are done
-1 Cured hide + needle for leather collar, either hunting or sewing works for it
-1 Cured hide + needle for leather leash. Same as above
-Smith can make chain leashes with 1 iron bar
-Smith can modify chain into chain leashes at a table with their hammer
-Smith can use copper or iron to make cowbells/catbells (Bells are considered either a tool or general, I forget which might be both, gonna move them to general)
-Craft leather collar with cowbell or catbell to get a jingly collar of the cat or cow variety 
-Iron or steel gorget with hammer on table and some blacksmithing skill to add a leashable O-Ring to it
-Can use bell on someone with leather collar to apply bell to them.
-Can have multiple people on different leashes at once, or drag a leashed person while they drag a leashed person while that third person drags a fourth.
-They work up/down zlevels. But not for climbing.
-Activate inhand to yank the pet closer
-Also did a lil QoL tweak to the magetower and mapped leashes/collars into the brothel.

ToDo:

- [x] Leash Trains
- [x] Multi-Leash-Drifting
- [x] Replace The shitty codersprites
- [x] Unfucked Collar Recipes
- [x] Make leather collars able to have bells affixed
- [x] Fix this one weird runtime

## Why It's Good For The Game

Leashes good! Leashes also hot. Gives another option for moving captives about. Also the jester's outfit has bells and should jingle- so I made his hat jingle too. Which is good!

## Proof Of Testing

https://github.com/user-attachments/assets/6aca2c64-d115-4992-8ed2-050012228d95

https://github.com/user-attachments/assets/6c82fca7-3124-4285-89dd-1e2203ae6833

https://github.com/user-attachments/assets/27be853d-40d8-4459-8e6d-303c1338548c

https://github.com/user-attachments/assets/4b428478-27f6-4bb0-94bd-2bbb4bf2258d

### CODE REVIEW

**Comment by Kevak** [comment]
Fixed that conflict

**Comment by Koteshkin** [comment]
How getting out of leash works? Cast time?

**Comment by Kevak** [comment]
Hit x. Resist. It's fast.

**Comment by ophaq** [comment]
I hope you add a cowbell. This game needs more cowbell.

**Comment by Kevak** [comment]
> I hope you add a cowbell. This game needs more cowbell.

A cowbell is in the plans. Thine earlier feedback was taken under advisement

**Comment by Rayforx** [comment]
This recipe have the same name as the leather belt, which makes the recipe break
```
/datum/crafting_recipe/roguetown/sewing/collarleather
	name = "leather belt (leather; APPRENTICE)"
	result = /obj/item/clothing/neck/roguetown/collar/leather
	reqs = list(/obj/item/natural/hide/cured = 1)
	skill_level = 2
```
The hoardmaster seems to be struggling with making collars

**Comment by Githubaccount222** [comment]
I think the code for the recipes for the leather catbell and cowbell collars are formatted wrong. They don't have the number of bells required listed in the recipe.

**Comment by DeerJesus** [comment]
Disable jester's outfit making noises. Shoes only if you do have it. It's really fucking annoying having it doubled up.

**Comment by DeerJesus** [comment]
Why do all the prisoner's collars have jingly cow/catbells on them? This feels like forcing a fetish thing on a role.

**Comment by Kevak** [comment]
> Disable jester's outfit making noises. Shoes only if you do have it. It's really fucking annoying having it doubled up.

I'm thinking the hat. Not the shoes.

**Comment by Kevak** [comment]
> Why do all the prisoner's collars now have jingly cow/catbells on them? This feels like forcing a fetish thing on a role. Leashing and walking people around is already pretty exhibitive sexual play which I think we're trying to discourage here.

Historically people put noisemakers on their prisoners. I will note they already have had permanent collar. I can remove the jingle if people want however.

**Comment by Kevak** [comment]
> I think the code for the recipes for the leather catbell and cowbell collars are formatted wrong. They don't have the number of bells required listed in the recipe.

Yeah I fucked it, fixing it.

**Comment by Kevak** [comment]
> This recipe have the same name as the leather belt, which makes the recipe break
> 
> ```
> /datum/crafting_recipe/roguetown/sewing/collarleather
> 	name = "leather belt (leather; APPRENTICE)"
> 	result = /obj/item/clothing/neck/roguetown/collar/leather
> 	reqs = list(/obj/item/natural/hide/cured = 1)
> 	skill_level = 2
> ```
> 
> The hoardmaster seems to be struggling with making collars

Oh shit, oop, missed that. Fixing. The hoardmaster fix is PRed already and should be live next deployment

**Comment by DeerJesus** [comment]
> people put noisemakers on their prisoners

i do not know where you got this information from but people did not put kinky cat bells on prisoners. most they had was chains on their hands and legs that made noise as a consequence of them being chains

**Comment by ophaq** [comment]
It would be nice if the collar requires novice sewing. Also is there a sound effect for the cowbell yet?

**Comment by Kevak** [comment]
> It would be nice if the collar requires novice sewing. Also is there a sound effect for the cowbell yet?

I reduced the reqs on collarcrafting. As for cowbell sound, nnope! Don't got a cowbell laying around the house to record, unlike my kittycollar. Source me a few cowbell sounds and I'll add em! Until then you get kittybell jingle for it.

**Comment by ophaq** [comment]
> > It would be nice if the collar requires novice sewing. Also is there a sound effect for the cowbell yet?
> 
> I reduced the reqs on collarcrafting. As for cowbell sound, nnope! Don't got a cowbell laying around the house to record, unlike my kittycollar. Source me a few cowbell sounds and I'll add em! Until then you get kittybell jingle for it.

https://www.soundsnap.com/cows_bells_breathing_eating_01

**Comment by Kevak** [comment]
> > > It would be nice if the collar requires novice sewing. Also is there a sound effect for the cowbell yet?
> > 
> > 
> > I reduced the reqs on collarcrafting. As for cowbell sound, nnope! Don't got a cowbell laying around the house to record, unlike my kittycollar. Source me a few cowbell sounds and I'll add em! Until then you get kittybell jingle for it.
> 
> https://www.soundsnap.com/cows_bells_breathing_eating_01
> 
> Found a good one that isn't ear zape. Audio might need to be edited a bit to cut out everything but the first 5 seconds. Some of the chewing sounds though which are not too noticeable come later on, which is why. The sound effect is a bit long anyway.

Ideally we want 3-4 soundfiles so it doesn’t sound horribly repetitive. I’mma take a coding break today cuz I did like two overnighters getting leashcode fully debugged but tomorrow I’ll fiddle with editing this one. If you can find more that would be wonderful (bonus points if you go get a cowbell and record it :3 )

**Comment by Keazra** [comment]
I think leading by chains should be developed before leading by leash. A leash screams of kinkery, which is fine I suppose, but is a smidgen on the immersion breaking side of things. Neat PR tho'.

**Comment by ophaq** [comment]
> > > > It would be nice if the collar requires novice sewing. Also is there a sound effect for the cowbell yet?
> > > 
> > > 
> > > I reduced the reqs on collarcrafting. As for cowbell sound, nnope! Don't got a cowbell laying around the house to record, unlike my kittycollar. Source me a few cowbell sounds and I'll add em! Until then you get kittybell jingle for it.
> > 
> > 
> > https://www.soundsnap.com/cows_bells_breathing_eating_01
> > Found a good one that isn't ear zape. Audio might need to be edited a bit to cut out everything but the first 5 seconds. Some of the chewing sounds though which are not too noticeable come later on, which is why. The sound effect is a bit long anyway.
> 
> Ideally we want 3-4 soundfiles so it doesn’t sound horribly repetitive. I’mma take a coding break today cuz I did like two overnighters getting leashcode fully debugged but tomorrow I’ll fiddle with editing this one. If you can find more that would be wonderful (bonus points if you go get a cowbell and record it :3 )

The website I linked has a few good ones. The file I linked can be split up into different sounds and I think it is free to use.

**Comment by Kevak** [comment]
> Magos Apprentices spawn with collars. Intended behavior?

Yup! If they don't want them the heirs probably do lets be honest, the sluts

**Comment by Alanii** [comment]
what the fuck

**Comment by NikolayByondPlayer** [comment]
Can you make an additional non fetish version for leash on the prisoner's hands-legs like in real life? 
So there would be a non fetish variant

**Comment by DeerJesus** [comment]
> > Magos Apprentices spawn with collars. Intended behavior?
> 
> Yup! If they don't want them the heirs probably do lets be honest, the sluts

please stop giving roles that don't make sense to have fetish gear roundstart have fetish gear roundstart, i beg you

**Comment by Kevak** [comment]
> Can you make an additional non fetish version for leash on the prisoner's hands-legs like in real life? So there would be a non fetish variant

I can give being chained a flag for valid to leash, like a harness effectively

**Comment by Kevak** [comment]
> > > Magos Apprentices spawn with collars. Intended behavior?
> > 
> > 
> > Yup! If they don't want them the heirs probably do lets be honest, the sluts
> 
> please stop giving roles that don't make sense to have fetish gear roundstart have fetish gear roundstart, i beg you

Moved em to a closet. Also mapped some into the brothel

**Review by Gyrandola — APPROVED** [review]

**Comment by ophaq** [comment]
Is there cowbell now?

**Pull request merged**
