### PR TITLE
Changes the lightning smite

### PR DESCRIPTION
**Pull request by ChuChu42**
## About The Pull Request

https://github.com/user-attachments/assets/0291ad24-9f11-4bf5-b368-6a3ff8ee7186

the text that is relayed to chat, and for anyone else to see:
image

75% chance to play funny sound to the player being smited, also the sound clip is timed perfectly

also increases the damage for the smite so it burns at least 2 limbs, it does not kill, however only takes a quarter of the user's health

## Why It's Good For The Game

funny
also lore friendly, its ravox (the judge) 's voice

### CODE REVIEW

**Comment by TuskTusk** [comment]
A divine bolt of thunder hitting you from above is a good signal to everyone in the room that you offended the Ten. 

I approve!

**Comment by Coolgat3** [comment]
As hilarious as this is I dont think it'll get merged specifically because of the audio xddd

**Comment by K4rlox** [comment]
> As hilarious as this is I dont think it'll get merged specifically because of the audio xddd
> 
> Reminds me of abusing people on skyrat with the TG droppod menu that supported sounds

its lore accurate that ravox sounds like low tier god just like how its lore accurate that furries cant play king c:

**Comment by Alanii** [comment]
Too much of a meme

**Pull request closed without merging**
