### PR TITLE
Spells nerf

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request

Cast cost of majority of church spells was increased, as well as cast delay added.
Added sounds to some spell casts.
Fixed ability to cast miracles with blocked mouth.
Spells no longer ignore anti-magic.

## Why It's Good For The Game

Less cancerous instant click-to-heal/click-to-win mechanics.
Also current church healing is just too op. You can cure and heal anything for free.

### CODE REVIEW

**Comment by radarseas** [comment]
any chance of making being roped/chained prevent casting fireballs.

most other magics are fine but fireball can oneshot you at that range, this would not be an issue if it always had an audio que but uhh, right now  people pull the silent casting thing out of the hat and suddenly instantly crit you with minimal warning.

**Comment by DorfGuy1** [comment]
aT SOME point, they just removed fireball from court mage, supposedly there's gonna be a necromancer spell in to replace it, but why take something before you replace it?

**Comment by Polotos** [comment]
Paladin cru 100 max mana

**Comment by DagenbouFree** [comment]
My man, why make churn undead cost 150 when paladin has maximum 100 devotion? It shrimply doesn't make any sense. Thats salt pr if I ever seen one.

**Comment by LeShprotina** [comment]
Psydon, cut off his balls.

_also i hope admins cut off his possibilities to make any pr here, seriosly_

**Comment by pilotmans** [comment]
> My man, why make churn undead cost 150 when paladin has maximum 100 devotion? It shrimply doesn't make any sense. Thats salt pr if I ever seen one.

it's rather clampicated, but seriously there are better ways to go about this.

**Comment by radarseas** [comment]
> My man, why make churn undead cost 150 when paladin has maximum 100 devotion? It shrimply doesn't make any sense. Thats salt pr if I ever seen one.

this I hard agree on too... churn undead fails to churn even obvious undead, due to RNG.

Also fully powered vampire pulls the "fuck you too" card and stuns you if you cast it near them, which can get you absolutely killed.

**Comment by Useroth** [comment]
A rework is needed down the line, but this nerf is not it

**Comment by Polotos** [comment]
@Heheniy 
make a nerf by limiting the prayer that gives devolgen. for example, in the field without a cross it gives 0.5, with a pectoral cross 1, at a large cross but not in the temple 5, in the temple 10

**Pull request closed without merging**
