### PR TITLE
Revert "Remove skeleton organs (#1445)"

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

title.

## Why It's Good For The Game

Skeletons didnt die when decapped

### CODE REVIEW

**Review by Nakalon — APPROVED** [review]
fuck

**Comment by JGlitch** [comment]
> fuck

Testing evidence?

**Comment by Gyrandola** [comment]
> > fuck
> 
> Testing evidence?

https://github.com/user-attachments/assets/0895b4ad-9628-4c36-b7ac-0881a0d08b66

**Comment by JGlitch** [comment]
> > > fuck
> > 
> > 
> > Testing evidence?
> 
>  20241106-0022-30.4226305.mp4

Hahaha I was giving yall shit because of, ya know xDDD Nice testing evidence tho its appreciated.

**Pull request merged**
