### PR TITLE
Fixes kneestinger midcombat power

### PR DESCRIPTION
**Pull request by ikrarkjr**
## About The Pull Request
Fixes kneestingers being the most overpowered combat mechanic in the game.

## Why It's Good For The Game
Kneestingers are blatantly overpowered, they needed a nerf, and everyone knew this.

The enjoyment of the many should not be sacrificed for the fragging of the few.

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Unlisted in the PR body is the changes 
- quadruple the stamina costs 30 -> 12
- requires you to stand still for 20 seconds In order to place with ni interrupts at all
- double the devotion cost 30 -> 60
- forced from a whisper to a shout

**Comment by coffeecoffeecoffee** [comment]
Maybe it shouldn't be nerfed THIS hard? But it definitely needs a nerf like this. I can't help but think it should be viable to use, like, ONCE in combat, as an iconic druid thing?

**Comment by Kepteyn** [comment]
Twenty seconds seems way too long. Even for laying traps down, that seems prohibitively long. I'd reduce that to five seconds maybe, or give it no warmup time and simply give it a 60 second or more cooldown?

**Comment by DorfGuy1** [comment]
Proper druids only use it as an Oh shit button. But if we wanna keep clerics of dendor around druids are gonna have to take the hit too IG.

**Comment by MickDick1** [comment]
> Unlisted in the PR body is the changes
> 
> * quadruple the stamina costs 30 -> 120
> * requires you to stand still for 20 seconds In order to place with no interrupts at all
> * double the devotion cost 30 -> 60
> * forced from a whisper to a shout

it's been a while but I was testing this stuff out a while back and im certain the stamina costs don't even work. Casting doesn't cost anything.

**Comment by ikrarkjr** [comment]
> Unlisted in the PR body is the changes
> 
> * quadruple the stamina costs 30 -> 120
> * requires you to stand still for 20 seconds In order to place with no interrupts at all
> * double the devotion cost 30 -> 60
> * forced from a whisper to a shout

It's not 20 seconds to cast. By that metric according to the code Anastasis (revival) would be 50 seconds to cast. Most definitely not.

**Comment by ikrarkjr** [comment]
> Maybe it shouldn't be nerfed THIS hard? But it definitely needs a nerf like this. I can't help but think it should be viable to use, like, ONCE in combat, as an iconic druid thing?



> Twenty seconds seems way too long. Even for laying traps down, that seems prohibitively long. I'd reduce that to five seconds maybe, or give it no warmup time and simply give it a 60 second or more cooldown?



> Kneestingers do need nerfs, but they don't need to be unusable. 20 seconds of standing still makes them that. They're only used by Druids and Clerics, and only usable defensively unless the person they're used against is terribly unobservant(See: Amulet of Dendor) or just unrobust.
> 
> The rest of the nerfs seem fine. Cast time I could see being 3-5 seconds, otherwise it's just salt PR, I can only imagine.

It's not even remotely 20 seconds, so don't believe that guy. It's less than half the cast time of Anastasis (the revival miracle). This is definitely way more than enough to plant them directly ontop of anyone stunned. It just stops you from planting it directly ontop of prone people, making them GBJ infinitely, which was byond overpowered.

**Comment by ikrarkjr** [comment]
Screenshot 2024-08-01 161245

**Comment by zakanater19** [comment]
> > Unlisted in the PR body is the changes
> > 
> > * quadruple the stamina costs 30 -> 120
> > * requires you to stand still for 20 seconds In order to place with no interrupts at all
> > * double the devotion cost 30 -> 60
> > * forced from a whisper to a shout
> 
> it's been a while but I was testing this stuff out and im certain the stamina costs don't even work. Casting doesn't cost anything.

Casting does cost stamina

**Comment by MickDick1** [comment]
> > > Unlisted in the PR body is the changes
> > > 
> > > * quadruple the stamina costs 30 -> 120
> > > * requires you to stand still for 20 seconds In order to place with no interrupts at all
> > > * double the devotion cost 30 -> 60
> > > * forced from a whisper to a shout
> > 
> > 
> > it's been a while but I was testing this stuff out and im certain the stamina costs don't even work. Casting doesn't cost anything.
> 
> Casting does cost stamina

Took the time to download latest and test it.
No. It doesn't. Only their miracles do.

**Comment by ikrarkjr** [comment]
> > > > Unlisted in the PR body is the changes
> > > > 
> > > > * quadruple the stamina costs 30 -> 120
> > > > * requires you to stand still for 20 seconds In order to place with no interrupts at all
> > > > * double the devotion cost 30 -> 60
> > > > * forced from a whisper to a shout
> > > 
> > > 
> > > it's been a while but I was testing this stuff out and im certain the stamina costs don't even work. Casting doesn't cost anything.
> > 
> > 
> > Casting does cost stamina
> 
> Took the time to download latest and test it. No. It doesn't. Only their miracles do.

It has a variable for it, and it initially was set to a value (before this PR) so it sounds like a bug that slipped through the cracks. In any case, that's not a bug with this PR, it just happens to effect it.

**Comment by radarseas** [comment]
I think the BETTER solution is just make it do a 1x3 wall in FRONT of the user, so you can't just mace them once, stand on them, and permatrap them, but it still keeps its combat utility as a retreat option instead of just encouraging massive obnoxious stunfields and probably make it a loudly worded shout.

**Comment by Teragenic** [comment]
Reading this PR comments is like "When non-coders don't understand code."

However, @ikrarkjr You should definitely update the description of the PR. It blatantly lacks information and other things. 
We should hold a standard to our PR templates.

**Comment by Teragenic** [comment]
> Unlisted in the PR body is the changes
> 
> * quadruple the stamina costs 30 -> 120
> * requires you to stand still for 20 seconds In order to place with no interrupts at all
> * double the devotion cost 30 -> 60
> * forced from a whisper to a shout

This however, should definitely be in the description. It's not 20 seconds though. It's 20 ticks. Less than anastasis.

**Pull request merged**
