### PR TITLE
Changes to pill tin code.

### PR DESCRIPTION
**Pull request by TheFenix323**
## About The Pull Request

Cleans all uneeded procs, and makes the wake and pnk pill tins subtypes of pilltin/, also makes it so all pills can go into the tins with the sprite changing accordingly and now it no longer describes the tin missing a donut.

Empty tin

Example of the sprite changing.
Now has the pill sprite

And you can put pnk pills in wake tins and viceversa.
pnk in wake
Wake in pnk

## Why It's Good For The Game
Fixes some issues with the Pill tins and makes their code more compact.

### CODE REVIEW

**Comment by TheFenix323** [comment]
Love map conflicts.

**Comment by Nakalon** [comment]
Are the pills really named fucking pokeballs

**Comment by TheFenix323** [comment]
> Are the pills really named fucking pokeballs

Yes xD

**Comment by Nakalon** [comment]
> > Are the pills really named fucking pokeballs
> 
> Yes xD

This can't be

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
