### PR TITLE
Armorsmithing and weaponsmithing removal

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Three smithing skills (weaponsmithing, armorsmithing and blacksmithing) is now just one blacksmithing skill
Exp gain for smithing lowered 1.5 times
Armorsmith and weaponsmith roles merged into single two slot guild smith role

## Why It's Good For The Game
Armorsmith always gets x100 more work then weaponsmith
Separating smithing into 3 different branches is stupid in first place. Legendary armorsmith cant make or repair a knife and legendary weaponsmith cant make or repair a simple helmet? Please, no.
this will make everyone's life better

### CODE REVIEW

**Comment by DelineFortune** [comment]
Will kill smiths at all

Why should you even talk with a player if you can simply kill them for tools and do everything you want after one night

**Comment by atomicplan666** [comment]
the problem with this is - people will just learn apprentice smiting and do it themselves. the reason for the separation is to make it more difficult for non-smiths.

**Comment by Nakalon** [comment]
As a weaponsmith main I understand there are issues, but I do believe this is the chickens, easy way, to address them.

My solution would be to instead of removing weaponsmith because he's irrelevant, making him relevant.

Making weaponsmith special, instead of killing it. I have thought of how to do this, but I do not have the knowledge yet to make that happen.

Regarding common blacksmithing why not expand it. Again, making it more relevant. A common blacksmith wouldn't know how to make weapons or armour anyways!
But a common blacksmith would have enough work to be important, in real life. We just gotta make up that work for him.

Hope this feedback is useful.

**Comment by kokokokokokokokokokokokokokoko** [comment]
i like this pr.

i usually don't like PRs that remove mechanics and it will make blacksmithing smoother for the TWO smiths who have to attend to a WHOLE server with more than 80 players. Maybe this can help people get interested in being a smith again.

but it's just my opinion, even so, another idea that may be the middle point is to just give both smiths the skills of weaponsmith and armorsmiths, so that they can attend people easily, without a radical change to the code.

**Comment by MickDick1** [comment]
> Will kill smiths at all
> 
> Why should you even talk with a player if you can simply kill them for tools and do everything you want after one night

You can already do this. The only skill worth learning is armorsmithing so you can repair your own stuff really.

**Comment by Nakalon** [comment]
> > Will kill smiths at all
> > Why should you even talk with a player if you can simply kill them for tools and do everything you want after one night
> 
> You can already do this. The only skill worth learning is armorsmithing so you can repair your own stuff really.

And this would aggravate that issue

**Comment by Rayforx** [comment]
You can merge Weaponsmith and Armorsmith into one role which is the best option, and not have to worry about removing the skills themselves. Then both smiths can specialize if needed, and new (abilities) and whatnot can be added, depending on how leveled their smithing is.

**Comment by Nakalon** [comment]
> You can merge Weaponsmith and Armorsmith into one role which is the best option, and not have to worry about removing the skills themselves. Then both smiths can specialize if needed, and new (abilities) and whatnot can be added, depending on how leveled their smithing is.

I like that much better!!!! Right now smith apprentice is much better at both skills than the proper smiths are hahaha

**Comment by radarseas** [comment]
people here are forgetting the only people that killing/robbing a smith and using their tools to even feasably learn any smithing successfully would be _mages and clerics_ because nobody else has the **int stat for doing it fast enough, under two hours**, even then you'd be **wasting most of the bars** as a clueless person unless _you're tanking a sleep debuff_. to level to apprentice at most.

Clerics are OP anyway so I won't even call them a fair judgement factor, seriously just look at their stats in the code including surgery-capable medicine off the bat on top of T3 (acolyte) miracles, fighting skill and mallie armor **what the fuck?** as for mages, _you'll just tire yourself too much to make stuff even with master skill._


This was already an issue anyway when the dungeons were around and people would just use the smith and tools there to do this. This PR does admitidly make it feasable to do more quicker but it just makes it a more sane system for people that actually play smtih letting them learn engineering and other more fun skills.

We don't have gear quality from this system to worry about anyway. Plus if someone wants to spend half of their round learning smithing, getting the metals for it and having the proper equipment/enough steel over paying 40-60 mammon to have someone make their gear in seconds, _**let em**_.

I know people can DIY smith, you can just say no to giving non-smiths tools, if they break into the smith for em constantly without any good IC reason, let em eat a ban.

**Comment by Heheniy** [comment]
@Moribun fixed

**Pull request merged**
