### PR TITLE
Makes objects more resistant to fire

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
partially reverts the changes to fire and changes the mod from 5x damage to 2x damage
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1126
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1104

## Why It's Good For The Game
Being naked but otherwise fine because your clothes burnt off is bad, I would rather fire only deal a fraction of the health of clothing and it needing repairing rather than having being naked but alive be a high possibility.

### CODE REVIEW

**Comment by Nakalon** [comment]
question is, did you test it? 😳

**Comment by wow50000** [comment]
I'll do it tommorow, playing league rn

**Comment by wow50000** [comment]
ok, tested it. with this sticks have a 10 second burn time and you will burn to death long before your clothes do, just as psydon intended

**Comment by Nakalon** [comment]
> ok, tested it. with this sticks have a 10 second burn time and you will burn to death long before your clothes do, just as psydon intended

YOU SILLY MAN I WANTED TO SEE A PHOTO OF A VIDIEO

**Comment by Nakalon** [comment]
> ok, tested it. with this sticks have a 10 second burn time and you will burn to death long before your clothes do, just as psydon intended

If you die before your clothes do I think you may have went too far tho

**Comment by wow50000** [comment]
Back in my day, the only time you would have all your clothes burn off is if you got greater fireballed and left a flaming pile of meat in the corner.

**Comment by Nakalon** [comment]
He showed this to me in VC after jerking off into a cup, drinking it, jerking off a hobbo, var editing tits into the hobbo, milking the hobbo, drinking the milk and we came to the conclusion that the numbers need to be increased a bit.

**Comment by wow50000** [comment]
> He showed this to me in VC after jerking off into a cup, drinking it, jerking off a hobbo, var editing tits into the hobbo, milking the hobbo, drinking the milk and we came to the conclusion that the numbers need to be increased a bit.

as in reduce clothing fire resistances or ?

**Comment by Nakalon** [comment]
> > He showed this to me in VC after jerking off into a cup, drinking it, jerking off a hobbo, var editing tits into the hobbo, milking the hobbo, drinking the milk and we came to the conclusion that the numbers need to be increased a bit.
> 
> as in reduce clothing fire resistances or ? I think clothing fire damage is fair and lowering stick hp to 1 works until stick hp needs to be used for something else, though a modifier on damage for sticks and wooden items that make it 20x stronger could work

I'd like to see clothes be damaged more by fire yes. I don't know why sticks are included in this but I guess it makes sense.

**Comment by Nakalon** [comment]
You say you don't want to be alive but naked. But that's part of the charm of your clothes burning off. Keep that. These are still taking wayyyyy too long to burn off

**Comment by Squird5** [comment]
> He showed this to me in VC after jerking off into a cup, drinking it, jerking off a hobbo, var editing tits into the hobbo, milking the hobbo, drinking the milk and we came to the conclusion that the numbers need to be increased a bit.

This is, unfortunately, why the numbers were so big. Sticks and bushes finally burn in a reasonable amount of time, but clothing has the unfortunate side effect of just getting deleted. Increasing clothing's fire resistance will just make the mob take less damage as well. Best option may be simply increasing how much integrity clothing items have, or making a new trait for clothing that specifically lets them burn, but at a reduced rate.

**Review by Gyrandola — APPROVED** [review]

**Comment by wow50000** [comment]
> > He showed this to me in VC after jerking off into a cup, drinking it, jerking off a hobbo, var editing tits into the hobbo, milking the hobbo, drinking the milk and we came to the conclusion that the numbers need to be increased a bit.
> 
> This is, unfortunately, why the numbers were so big. Sticks and bushes finally burn in a reasonable amount of time, but clothing has the unfortunate side effect of just getting deleted. Increasing clothing's fire resistance will just make the mob take less damage as well. Best option may be simply increasing how much integrity clothing items have, or making a new trait for clothing that specifically lets them burn, but at a reduced rate.

current numbers work as is, sticks burn eventually but take a while however its piss easy to make a line of code that makes sticks burn faster

**Pull request merged**
