### PR TITLE
Adds options for indicating if you prefer mechanics or emotes when doing Extreme Roleplay.

### PR DESCRIPTION
**Pull request by Kepteyn**
## About The Pull Request

Adds an option in preferences to select if you'd prefer emotes, mechanics or nothing when it comes to doing HRP with an E. This choice is visible to your partner in the sexcon, letting them see what you would prefer in a manner meant to be _immersive™_ (as much as a console filled with buttons and levers so you can have sex can be, anyway). This doesn't limit yours or your partner's ability to do emotes or mechanics, merely communicates preferences that are currently impossible to express outside of discord DMs.

Untitled2
Untitled

## Why It's Good For The Game

Some people would prefer to use emotes or mechanics in their HRP scenes. Currently, outside of using discord messages or subtle-ing to your partner an LOOC that could get you bwoinked by an admin, there is no way to actually express this. Given that LOOC or OOC notes are not viable with the server's aims, this is a non-intrusive way to facilitate this.

### CODE REVIEW

**Comment by Maromar15910** [comment]
A very good step. Aditional bits like actual content preferences would be cool too, but that might require placement somewhere else.

**Comment by Kepteyn** [comment]
> Didn't we all agree that erp with no emotes is sort of shitty rp?
> 
> I might be getting this wrong but is this pr just helping to enable people to mechanic only erp?

The point was moreso to allow people who want _no_ mechanics in their erp to be able to plainly indicate that, as I've found that people typically gravitate to only using mechanics. It includes the option to indicate you'd prefer mechanics or to have no ERP, however, so that those people can also indicate their preferences. Overall, it's just a quality of life thing to help people adjust their method of rp to their partners, or to know if someone isn't a match for them.

> A very good step. Aditional bits like actual content preferences would be cool too, but that might require placement somewhere else.

I'll certainly consider ways to achieve this. A text box that can be opened with a button from sexcon, perhaps, or even an ERP notes option, should such a possibility be permissible with the powers that be. I've certainly had experiences bad enough to nearly quit the server in the past that would have been avoided with this, so I empathise with this want.

**Comment by Cleric2145** [comment]
> Didn't we all agree that erp with no emotes is sort of shitty rp?
> 
> I might be getting this wrong but is this pr just helping to enable people to mechanic only erp?

In general, yes--but personally I personally don't mind if it's somebody/something that's going around quickly raping people like a werevulf or rapist. There's something that's IMO just a little more immersive to have a werevulf rush up, pin the character and unrelenting-brutal fuck the character for a couple rounds before they devour them. Otherwise a horny vulf would get stuff emoting for 20-30 min, leaving them vulnerable and idle.

**Comment by CalamaBanana** [comment]
(Disclaimer, I enjoy both. I am a mayor smut-slut. If I play Shophand, nothing more kinky than quick stints with short emotes and mechanics while the boss and I wait for the balloon to sell things. But if I play bard without responsibilities, I will suckle on that lolipop with lengthy emotes for hours.)

 I am against this kind of windowshopping in general, as it invites and empowers people that are purely looking for smut instead of playing their role and weaving their smut into the gameplay. But if something like this ever gets to be added it needs to be:

- Per character, not account
- Selecting the "lengthy text RP" option should block that character from any role with any hint of relevance to the round
- Indifferent sounds too much like "don't give a shit". Give me a positive sounding option that makes it clear I enjoy both, instead of not caring. Have it say something like "enjoys short stints just as much as lengthy twists."
- Toggleable during a round. If I play maid, and the court actually provides me with proper RP I am only available for short stints. If the court RP level is below even "GIB FOOD PLS", I will sneak off for lengthy sessions
- Using my shophand example, I don't want it to be purely mechanical like your prefs would indicate, but rather "short emotive intercourse". Foreplay, teasing, setting the scene and a little quivering. And speedrunning the plapplaplap so get back into the round quicker. I don't see that covered by your options

**Comment by Kepteyn** [comment]
> (Disclaimer, I enjoy both. I am a mayor smut-slut. If I play Shophand, nothing more kinky than quick stints with short emotes and mechanics while the boss and I wait for the balloon to sell things. But if I play bard without responsibilities, I will suckle on that lolipop with lengthy emotes for hours.)
> 
> I am against this kind of windowshopping in general, as it invites and empowers people that are purely looking for smut instead of playing their role and weaving their smut into the gameplay. But if something like this ever gets to be added it needs to be:
> 
>     * Per character, not account
> 
>     * Selecting the "lengthy text RP" option should block that character from any role with any hint of relevance to the round
> 
>     * Indifferent sounds too much like "don't give a shit". Give me a positive sounding option that makes it clear I enjoy both, instead of not caring. Have it say something like "enjoys short stints just as much as lengthy twists."
> 
>     * Toggleable during a round. If I play maid, and the court actually provides me with proper RP I am only available for short stints. If the court RP level is below even "GIB FOOD PLS", I will sneak off for lengthy sessions. Although this clashes with role-locking...
> 
>     * Using my shophand example, I don't want it to be purely mechanical like your prefs would indicate, but rather "short emotive intercourse". Foreplay, teasing, setting the scene and a little quivering. And speedrunning the plapplaplap to get back into the round quicker. I don't see that covered by your options

Firstly, thank you for commenting your suggestions, I appreciate them!

Regarding windowshopping, you would have to go around and open the sexcon on people in order to see what the prefs indicate, which should make pure windowshopping harder than the character directory system of other servers. Role locking the option that indicates that you'd prefer to use emotes and not mechanical does not seem to me to be beneficial, especially if we consider in-round toggle-ability. I doubt anyone who does not already ignore their job when they're needed so they can erp for hours will suddenly take this preference option as an excuse to do that. I could remove the "long" from the description and leave it as emotive and expressive, though.

As for your other points, I have made the preferences character-specific and not account specific, and I have also added the ability to toggle your preference mid-round through the sexcon (targetting either yourself or someone else). I also see your point regarding the 'indifferent' option and so have changed it to "both short and expressive," to better represent it as the middleground between both options I intended it to be. For your preferred style of erp as you described, this in-between option would be a good fit, I reckon.

**Comment by pilotmans** [comment]
> (Disclaimer, I enjoy both. I am a mayor smut-slut. If I play Shophand, nothing more kinky than quick stints with short emotes and mechanics while the boss and I wait for the balloon to sell things. But if I play bard without responsibilities, I will suckle on that lolipop with lengthy emotes for hours.)
> 
> 
> 
>  I am against this kind of windowshopping in general, as it invites and empowers people that are purely looking for smut instead of playing their role and weaving their smut into the gameplay. But if something like this ever gets to be added it needs to be:
> 
> 
> 
> - Per character, not account
> 
> - Selecting the "lengthy text RP" option should block that character from any role with any hint of relevance to the round
> 
> - Indifferent sounds too much like "don't give a shit". Give me a positive sounding option that makes it clear I enjoy both, instead of not caring. Have it say something like "enjoys short stints just as much as lengthy twists."
> 
> - Toggleable during a round. If I play maid, and the court actually provides me with proper RP I am only available for short stints. If the court RP level is below even "GIB FOOD PLS", I will sneak off for lengthy sessions. Although this clashes with role-locking...
> 
> - Using my shophand example, I don't want it to be purely mechanical like your prefs would indicate, but rather "short emotive intercourse". Foreplay, teasing, setting the scene and a little quivering. And speedrunning the plapplaplap to get back into the round quicker. I don't see that covered by your options

Think Is a good way of going about it

**Comment by DelineFortune** [comment]
Still able to do whatever you want with /me.

**Comment by Coolgat3** [comment]
Why the downvotes??? Isn't this literally just a thing to show people if youre into posts or mechanics??? This literally does nothing wrong to anyone or doesnt ruin anyones experience. Nobody is forcing you to follow it, I personally would not want to post emotes to a person who wants only mechanics, because they will waste my time and bore me, I really dont udnerstand the downvotes.

**Comment by Red-Honk** [comment]
Did you mean superfluous?

**Pull request closed without merging**
