### PR TITLE
The Vanguard: Bog gate & Map rework

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

- The previous bog gate and the surrounding buildings have fallen into ruin, abandoned and sacked. The duke of Rockhill has disbanded the original bog guard and ordered the construction of a bigger and better fortified gate to the north: **The Bastion**, serving as an all-in-one base for the newly established Vanguard, veterans of the disbanded bog guardsmen, captained by a Warden. 

  The new state-of-the-art Bastion provides the garrison with all they need: SCOMM and HERMES, armory, toilets, sleeping quarters, a dungeon, a storage, training room and even brand new stables filled with trained saigas, for the Vanguard are experienced riders who often venture into the bog. The warden even gets a tiny office.

Images below, some minor details like the amount of lightning, roguemachines etc might be slightly outdated.
<details>

image
image
image
image
image
image
image

</details>

- Latejoins will now randomly spawn in the area right infront of the gate, to give the Vanguard some extra rp.
- The Vanguard and Warden have the same skills and stats as the old bogmen, with the addition of expert horse riding.
- The area that previously held the farm fortress and the hobo tent camp has been cut, replaced by a mountain. (Big dungeon incoming)
- That huge empty area on the top right corner of the bog has been cut, for it made no sense at all. I hope you know what location I mean.

### CODE REVIEW

**Review by Nakalon — APPROVED** [review]

**Comment by Gyrandola** [comment]
> Yeah okay but why did they blow up the bridge... haunergeons and chain gaunties in the armory? also needs railings for the stairs. with how many people like setting up in the bog i reckon some tents and signs of camping out would be good, maybe the remnants of a siege that would have ruined the original gate? bit of a waste to just wreck the old area and not do much with it. whats heppening with the fortified farm with the gate to the south west?

the fortified farm was already moved north in another PR. Otherwise all great suggestions. I slaved away all afternoon to get this together but im open to putting more work in it.

**Comment by Gyrandola** [comment]
Gave it one last check and it started runtiming to shit. Untmed before it went live. dont touch.

**Comment by Useroth** [comment]
image

**Comment by Gyrandola** [comment]
Removed some mineable area near the town, added lucratice mining area beyond the Bastion to incentivize traffic.
Added a secondary tunnel that passes through the mountain (still beyond the bastion).
Should have fixed the runtimes

**Comment by Gyrandola** [comment]
Replaced tabards with hooded cloaks for a nightswatch vibe. Removed chain gear from the armory.

**Comment by NikolayByondPlayer** [comment]
Can I do an LA pass on it later to make floors shittier in dungeon area and Warden area to be a bit more posh?

**Comment by Gyrandola** [comment]
> Can I do an LA pass on it later to make floors shittier in dungeon area and Warden area to be a bit more posh?

feel free

**Comment by Gyrandola** [comment]
> Suggestions and some notices:
> 
> You should make these walls into murderholes like previous bog gate
> 
> image
> 
> Also, on the second floor you need grills for shot through above
> 
> image
> 
> These windows will always broken at the roundstart. Somebody throws a rock through the window and that's it.
> 
> image
> 
> I see no spare keys for gatehouse. If there are no additional keys here, it would be worth adding them

Added the grill
The windows might get broken but unlike the old bog gate, you cant just climb up and get in.
Spare keys put in the Warden's office.

**Comment by Crowbar764** [comment]
Can you please at least add sneaky, difficult, alternative ways to get into the town, like the current setup.

As a bandit, I don't want to be forced to assault a fortress just to visit the town. I don't like fragging.

**Comment by Gyrandola** [comment]
> Can you please at least add sneaky, difficult, alternative ways to get into the town, like the current setup.
> 
> As a bandit, I don't want to be forced to assault a fortress just to visit the town. I don't like fragging.

I think the solution to this isnt secret passages that can be memorized and used every single round.
Out of scope for this PR, but not having bandits be immediately recognizable could help.

**Comment by Crowbar764** [comment]
> I think the solution to this isnt secret passages that can be memorized and used every single round. Out of scope for this PR, but not having bandits be immediately recognizable could help.

If you want to add a better alternative then please go ahead.

But just straight up removing the alternate paths and offering no replacement and hoping someone else fixes it for you isn't great and amounts to a flat nerf to an antag that has already been heavily gimped recently.

I suggest adding something similar to what currently exists as to not completely derail the delicate balance, instead of hoping for another PR that will probably never come.

**Comment by zakanater19** [comment]
cool

**Pull request merged**
