### PR TITLE
Terrorbog and river fixes and tweaks

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Fixed few river flow tiles that were pointed into walls
Replaced skeleton remainings at south-west mine with proper decals
Fixed double and tripple trees were they found and trees in murk
Reduced number of placed wolfs, mostly by 1 per 'structure'
Replaced all 'indoors' areas (aside from church at north terrorbog) with 'bog' area as they both have their own mecahnics 
Added possible bandit camp/vl manor spawn at the old merc spawn

### CODE REVIEW

**Comment by Gyrandola** [comment]
> Fixed double and tripple trees were they found and trees in murk

That isnt the tree change the maintainers have asked you multiple times not to do, right??????

> Replaced all 'indoors' areas (aside from church at north terrorbog) with 'bog' area as they both have their own mecahnics 

What indoor areas exactly?

**Comment by Heheniy** [comment]
> That isnt the tree change the maintainers have asked you multiple times not to do, right??????

no

> What indoor areas exactly?

all of inside buildings and tents

**Comment by Gyrandola** [comment]
> > What indoor areas exactly?
> 
> all of inside buildings and tents
> 

In the entire map?

**Comment by Heheniy** [comment]
> In the entire map?

whole terrorbog is now bog area, without any 'indoor' areas, aside of church at the north near the smithery

**Comment by Gyrandola** [comment]
> 
> > In the entire map?
> 
> whole terrorbog is now bog area, without any 'indoor' areas, aside of church at the north near the smithery

Consider how that might affect ambushes, since they are coded per-area

**Comment by Heheniy** [comment]
ambush cant spawn without tree or mushroom-tree in close range

**Comment by Nakalon** [comment]
> > Fixed double and tripple trees were they found and trees in murk
> 
> That isnt the tree change the maintainers have asked you multiple times not to do, right??????

image

Now thats a lotta trees in red, innit...

**Pull request closed without merging**
