### PR TITLE
Adds rune chat emotes

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Now your emotes will also show up on rune chat, with a gray color to distinguish from speech

Emotes can also define `runechat_short_msg` to have it display instead of `message` to shorten down any emotes if they're too long

Edit: Currently only custom emotes make the runechat show it up.

### CODE REVIEW

**Comment by Hmeister-real** [comment]
dont like this, theres a certain charm to not having rune chat emotes.

**Comment by Useroth** [comment]
let's testmerge it like it is for now

**Comment by Hmeister-real** [comment]
only custome emotes pls, at least

**Comment by Jakksergal** [comment]
Only custom emotes or at the very least a reduced font size for normal emotes. With the rate that runechat displays messages I don't wanna wait for speech to show up.

**Comment by zeratino** [comment]
I think that another person made a comment that strongly reflected my feelings, here.

I think this is a little immersion breaking for text to constantly pop up over someone, when nothing else (that isn't TM'd) does that as of now. 

It already plays a sound when an emote is made. I think that is enough.

**Comment by zeratino** [comment]
As a side note, I think that the way this is done is botched at best and immersion breaking at worst. The only way to signify the difference between an emote and speech is through their text color, which most people don't recognize.

image

**Comment by Hmeister-real** [comment]
please un-TM and close. Very emmersion breaking, very unhelpful, and useless for actually seeing emotes, since they are too long and show annoyingly, and stop speaking text from showing up, which is especially awful since people audibly emote when in pain, and when they groan. Maybe rune emotes work on other servers, but not here. Thanks for making this anyway

**Comment by KittyNoodle** [comment]
all emotes are muffled now

**Comment by Useroth** [comment]
> > please un-TM and close. Very emmersion breaking, very unhelpful, and useless for actually seeing emotes, since they are too long and show annoyingly, and stop speaking text from showing up, which is especially awful since people audibly emote when in pain, and when they groan. Maybe rune emotes work on other servers, but not here. Thanks for making this anyway
> 
> Yeah, making only custom emotes use it

My suggestion would be to: let it stay for non-custom emotes, strip punctuation from the edges, wrap them in * so that they differ from spoken text.

**Pull request merged**
