### PR TITLE
House of the Ten rework

### PR DESCRIPTION
**Pull request by AukariBunn**
## About The Pull Request

A lot of players share not so great feelings about the current church. Its too empty and too enormous for its emptiness, it has too little places for proper roleplay. This PR includes almost a full rework of the church, leaving just some spaces untouched.

dreamseeker_6i8pP91liu
dreamseeker_oKgriDvsl2
dreamseeker_ITv5eYEK5R

One of the major changes is replacing the infirmary and barracks, making both more accessable for the players they're designated for.

dreamseeker_hhRp3yUrJD
dreamseeker_APUtdHzjWO
dreamseeker_kgjSgtoiel
dreamseeker_2LYqptXt9O

This update also adds some more content for the inquisitor, adding a proper confession room, a dungeon and some holding cells.

dreamseeker_K1YPRISCMV
dreamseeker_wltR6AVJmX
dreamseeker_Cdn8AVkirJ

The church's basement now also has an armory and some useful baths, the latter can also be accessed from the main entrance.

dreamseeker_w0XHZvraAe
dreamseeker_CAhb6uDXDC
dreamseeker_wOCklsfQVS
dreamseeker_8PIeBwT5FQ
dreamseeker_3Eua2P4VvV
dreamseeker_ZbbyGahSWJ

And the last but not least: the library, which also has a little secret tunnel to the maze.
dreamseeker_FCXEBFY4uh
dreamseeker_bv5a4MpDXP

## Why It's Good For The Game

This PR offers more spaces for roleplaying, as well as expanding some church roles. A proper infirmary, dungeons, lots of social spaces; it all will greatly contribute to the player experience of playing church roles or just visiting the church as any other role.

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
map dif bot is mad
image

**Comment by Nakalon** [comment]
Everything is beautiful but I'm on the fence of the church having a fully kitted out kitchen and stuff like that when there are roles for that...

**Comment by AukariBunn** [comment]
> Everything is beautiful but I'm on the fence of the church having a fully kitted out kitchen and stuff like that when there are roles for that...

I simply copypasted the current kitchen, the only things i added were the bowls and a salt shaker. Kitchen is the thing the church always had and its a necessity for the clergy, beggars, poor adventurers and others. Also thank you for your kind words.

**Comment by AukariBunn** [comment]
I do know some of the decorated walls dont match up (mostly their ends). I will make some fixes in the final commit after I gather enough feedback and the work is greenlighted.

**Comment by NikolayByondPlayer** [comment]
Hello! First of all really great job with adding new beautiful places across the church they add really comfy feeling to the whole place, like level art work on the place also - doubly so for the praying area with water. Also big shoutout for connecting maze area for secret access!

Overall good job but I think the design at the whole can be greatly improved even further if you implement some major and minor things from the list bellow, I will also list some possible things you can do which are mostly nudges in different directions that you can take: 

1) **Major**: I would still encourage you to severely cut the size of the whole church by using z levels. 
_Reasons:_ 
- Right now church is as almost big as the town itself, it is too big
image

- So far we are looking to make a more tow centred gameplay with more condensed spaces but which are more packed together
- It would also possible make the place more architecturaly logical 
_Examples of possible solution:_ 
- You can try to place all the common accessible areas bellow the altar area, deleting the area with water and tree (even if it is so cool I swear I really like it)
- You can also dig in even further by using area bellow the tree place - there is a solid chunk there that can be used for someone like Inquisitor

2) **Major**: I would also encourage you to condense the rooms itself also. Most of them are too big and can be reduced to 50% of their size.
_Reasons_:  
- You will still save the gameplay space but will improve the flow of the place with less time to traverse.
_Examples of possible solution:_ 
- Made it really fast it can be improved to be more visually appealing
image
image


3) **Major**: I think we can cut the spaces that serve double function. Right now we have a lot of double corridors in the church. They make it bigger and don't add anything to the place.
image
image

_Reasons_:  
- Can make space smaller

4) **Major**: Use the empty space that exists now for rooms to reduce the size of the church
_Reasons_:  
- Will help you to reduce the size by using empty space in church, a lot of it in it right now.
- Will also make feel the space more lived in. 
image
image
image

_Examples of possible solution:_ 
In example bellow you can used these places as rooms for healing or room for confessional for example. Also if the entrance is smaller it is easier for church to fight in it's doorsteps.
image

5) **Major**: Cut the altar bellow and reconsider the flow of the place (EVEN THOUGH IT IS A BLAST). How will people come and interact with the clergy? How easy for clergy to keep the place in check and safe? 
_Reasons:_ 
- Right now altar with the tree serves similar function to the altar above and makes it a zone which will be harder for church to control because it is not super comfortable going there as church member. 
- The flow itself is not that good because there are a lot of corridors and doors to get into places. For example in the space bellow it will take going through multiple rooms and mortician's place to get into the interrogation room. We can just move mortician a bit and get rid of some doors to improve it. 
image

Also maybe we can make main altar area more like your variation? With blue colors and water theme instead of generic area.

6) **Minor**: Perhaps we can make the altar smaller and more functional by putting the benches together? And also moving north and south wall closer perhaps? 
image

**Reasons:** 
- Can still serve function but be a lot smaller.

7) **Minor**:  Maybe we can get rid of house that is tucked into the church? Feels weird since it is in church but doesn't belong to it.

8) **Minor**: The secret entrance is real blast and I think you can make it even more cooler by adding a gate there and not closing it with bushes (since you can't jump through them). It can make map knowledge really rewarding.
image

9) **Neatpick**: I just noticed that we have a ship mast inside the walls of church, can we cut it down? 
image


And once again - I really like the direction where this is going I just think we can make it smaller as well as making the rest of town more condensed for best experience! Really like your work and rooms!

**Comment by AukariBunn** [comment]
> * Right now church is as almost big as the town itself, it is too big

StrongDMM_c6MGyLo0HJ
I made it a bit smaller, had a lot of suffering with the left stairs. Now i have to somehow fit the right stairs in. Im not done yet anyways.

**Pull request closed without merging**
