### PR TITLE
Revert "disables pq gain for burial because morticians keep stealing perfectly good bodies to bury for pq, doubles reward for coining"

### PR DESCRIPTION
**Pull request by ChungusGamer666**
Reverts Rotwood-Vale/Ratwood-Keep#232

PR made by a salty retard who literally does not understand how the burial mechanics work.

Burying someone and using rites or a grave marker sends them to the lobby, this is LITERALLY the opposite of round removal, it is round reintegration.

The PQ reward was added because before it was added, *no one did burials, because it gave no benefit to the burier whatsoever.*

"B-but you can do it to living people!"
Burial rites and grave markers do not work on living people, if they did, it would not even reward you with PQ. This gives the burier no benefit whatsoever besides the satisfaction of being an asshole.

"B-but my character!"
Revival is a t3 astrata spell with a large cooldown, large devotion cost, and it should not be common expectation for a priest to revive you as nice as that would be. 
Death happens, don't try to cheapen it's value, some people will die and not be recovered in a round.

"B-but it's bugged!"
I have repeatedly tried to fix burials and as far as I am aware, it works most of the time. If it does NOT work, then it should be fixed ASAP because it is an integral game mechanic and the entire reason the mortician job exists.

### CODE REVIEW

**Comment by DeerJesus** [comment]
That shit doesn’t work EVER. it NEVER skips you no matter how hard you’ve tried to fix it. Coining OCCASSIONALLY works, maybe about 50 percent of the time, but you just simply DO NOT get sent to the menu if buried.

**Comment by ChungusGamer666** [comment]
Fix the god damn bug instead of complaining thaf people are trying to use the feature as it was intended, you low IQ troglodyte. Also, you can bury heads, but apparently you are too retarded to comprehend that.

**Comment by DeerJesus** [comment]
Burying heads doesn't fix it either. 

The purpose of a system is what it does, not what it's supposed to do. Currently, burial seems to exist to be continuously broken over like a fucking McDonald's ice cream machine, with you being the Taylor Co to our proverbial Taylor C602. Since you're the guy who apparently knows how this shit works and has "fixed" it multiple times, YOU fix it.

In a related note, apparently your supposed purpose in the community is to be an excellent coder, but your actual purpose - what you do - is be an abrasive piece of shit that gets banned from every community or chatroom they go to.

**Comment by ChungusGamer666** [comment]
> In a related note, apparently your supposed purpose in the community is to be an excellent coder, but your actual purpose - what you do - is be an abrasive piece of shit that gets banned from every community or chatroom they go to.

Your skin is made of pitch and your brain is made of tripe

**Comment by CVSthePharmacy** [comment]
I gotta agree with Chungus, you really just don't know how burial works. Also deer, you keep trying to move the chat towards them instead of the PR, please stay on topic, or work to better yourself as a person. Thank you 🙏. Btw I don't recommend trying to piss off Chungus, they are a really hard nut to crack, it never works

**Comment by CVSthePharmacy** [comment]
As for the PR, yeah burial rites are a bit bugged sometimes, I haven't checked enough but it usually says I don't have permission to do it. That should be looked into in a separate PR though, for now let's get this merged

**Pull request closed without merging**
