### PR TITLE
Minor nerf Ranger and Sentinel Buff + Silver Knife

### PR DESCRIPTION
**Pull request by Teragenic**
## About The Pull Request

Minor nerf Rangers by reducing Swimming/Climbing and Speed skill(They had +8 Stat Spread), gives Gloom (+1 Str, since they get worse ranged stats and skill. I assumed they were a melee subclass)
Gives sentinel Wrestling, Unarmed, Athletics, Sneaking, Swimming, and Climbing. Minor Skinworking given.
Gives Sentinel a coinpouch. 
Butchering.
Minor Cooking.

Gives their dagger the same effect as WH silver dagger. I don't want to affect the sabre due to LAZY. Enjoy.

## Why It's Good For The Game
Missing Coinpouch for Sents.
Rangers were better than Sents, now it's slightly more balanced.

Silver should affect vamps and werevolfs.

### CODE REVIEW

**Comment by lalaria1** [comment]
I don't think there's a reason to nerf rangers, trying to play this combat centric game as ranger or sentinel is ass and painful.

**Comment by Inveldy** [comment]
Don't nerf the rangers at all. Just make the sentinels buffed to be better than they currently are.

**Comment by TheodoraMoon** [comment]
Rangers doesn't needed to be nerfed

**Comment by Teragenic** [comment]
Climbing skill being reduced doesn't really remove any surfaces from being climbed and only that. Swimming is about the same with speed.

Removing one perception shouldn't be that bad.

**Comment by Teragenic** [comment]
> I don't think there's a reason to nerf rangers, trying to play this combat centric game as ranger or sentinel is ass and painful.

Ranger stats being MORE than Sent is not good.

Rangers get +8 Stats
Sent gets +7 Stats

The Perception nerf makes it +7 +7 for both.

Unless someone gives me a good reason to why I shouldn't nerf

Swimming or Climbing, your opinions are considered and will not make any changes to this PR.

**Comment by JGlitch** [comment]
Well somebody doesnt know how to use a shield haaah

**Comment by Teragenic** [comment]
> Well somebody doesnt know how to use a shield haaah

My PR does not affect shields nor really change much.

Climbing and Swimming does not affect shields. Perception being changed also does not affect shields.

Shields will still block. Your opinion has no argument, because it has no basis with my changes.

**Comment by EzekyalLegit** [comment]
This seems stupid

**Comment by SixplyDev** [comment]
Why would you give sentinels a silver dagger? The whole point of it being given to WH and Inquisitor is they're diehard psydonian dogmatic zealots. Giving it to another class just erodes the purpose of WH and inquisitor. I'm fine with this, just remove the silver effect from the dagger.

**Comment by Teragenic** [comment]
> Why would you give sentinels a silver dagger? The whole point of it being given to WH and Inquisitor is they're diehard psydonian dogmatic zealots. Giving it to another class just erodes the purpose of WH and inquisitor. I'm fine with this, just remove the silver effect from the dagger.

Their Dagger and Sabre is made of silver.
:)

I did not give them one, I just edited the code to make it recognize it's silver.

**Comment by Teragenic** [comment]
Screenshot_2024-08-21-08-16-27-40_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Teragenic** [comment]
"It might be blessed or something."

You can quite literally smelt any silver weapon and make a silver dagger.

**Comment by Teragenic** [comment]
> This seems stupid

Why? Can you tell me why?

**Comment by john-pawson** [comment]
> > I don't think there's a reason to nerf rangers, trying to play this combat centric game as ranger or sentinel is ass and painful.
> 
> Ranger stats being MORE than Sent is not good.
> 
> Rangers get +8 Stats Sent gets +7 Stats
> 
> The Perception nerf makes it +7 +7 for both.
> 
> Unless someone gives me a good reason to why I shouldn't nerf
> 
> Swimming or Climbing, your opinions are considered and will not make any changes to this PR.

While i agree with most of the changes done, i don't see any particular reason of why rangers should be nerfed at all? 
If the problem is that the sentinels get less bonus stats overall compared to ranger, then you could give a well deserved +1 to speed for sentinels, seeing as they are probably considered a lighter/faster role like the rogue or the normal ranger (They even have the dodge expert trait, a mainly SPD based one!)

I just don't see any reason of why nerf rangers when they aren't exactly... in need of a nerf? Their main weapons is a bow and it's only affecting stat is PER, so nerfing it is going to affect this role significantly more than any other. And i think it's fair for them to have a very high PER as it is considered almost completely useless on any other situation.

Same for the recent SPD changes, just buff the sentinel a bit instead of nerfing the ranger if that's the problem, they're now both +8 and have very similar stats, problem fixed!

Anyways, what i want to say is that normally it's better to buff the sentinel than to nerf the ranger, nerfing the ranger makes ranger less fun to play and doesn't change much else, buffing sentinel makes sentinel more fun to play and doesn't change much else.

Also **PLEASE** do not give STR to gloom stalkers, their 3 SPD and 1 END with no STR debuff already makes them strong enough at combat up close comparing them with any other adventurer class, they do not need it. If you **really** want to buff them give them maybe same END as the ranger (making them able to fight up close for longer) or some CON (making them able to *not die* for longer), but i'd suggest you just don't touch it.

Also also, why lower their climbing and swimming skill? The only difference on climbing skill made is when it reaches journeyman (Which then lets you go climb stone walls) and it seems fair since a significant portion of their time is spent probably climbing trees for cover and high ground. And the swimming skill makes sense, looking at how we're at a bog having the ability to swim effectively makes it easier to get out of trouble or effectively fight in the murk (Which also makes a lot of sense for a ranger)

And before you say "What's the problem with lowering climbing skill if it will change nothing?", future changes might be done to climbing or climbing speeds, so it think it's better to just leave it like it is rather than changing it to be just worse for, quite literally, no change whatsoever.

**Comment by DorfGuy1** [comment]
Agree with everyone. Completely uneeded. Also the silver weapons that the elves have, it blocks regen, when you hold it as a vampire.

**Comment by Teragenic** [comment]
> Agree with everyone. Completely uneeded. Also the silver weapons that the elves have, it blocks regen, when you hold it as a vampire.

That last part is just wrong, if you can show me the code of it specifically mentioning the two elven weapons. It does not. 

It only affects items that have a specific attachment code on pickup.

Elven Sabre and Knife don't have that code attached.

**Comment by Teragenic** [comment]
> While i agree with most of the changes done, i don't see any particular reason of why rangers should be nerfed at all? If the problem is that the sentinels get less bonus stats overall compared to ranger, then you could give a well deserved +1 to speed for sentinels, seeing as they are probably considered a lighter/faster role like the rogue or the normal ranger (They even have the dodge expert trait, a mainly SPD based one!)
> 
> I just don't see any reason of why nerf rangers when they aren't exactly... in need of a nerf? Their main weapons is a bow and it's only affecting stat is PER, so nerfing it is going to affect this role significantly more than any other. And i think it's fair for them to have a very high PER as it is considered almost completely useless on any other situation.
> 
> Same for the recent SPD changes, just buff the sentinel a bit instead of nerfing the ranger if that's the problem, they're now both +8 and have very similar stats, problem fixed!
> 
> Anyways, what i want to say is that normally it's better to buff the sentinel than to nerf the ranger, nerfing the ranger makes ranger less fun to play and doesn't change much else, buffing sentinel makes sentinel more fun to play and doesn't change much else.
> 
> Also **PLEASE** do not give STR to gloom stalkers, their 3 SPD and 1 END with no STR debuff already makes them strong enough at combat up close comparing them with any other adventurer class, they do not need it. If you **really** want to buff them give them maybe same END as the ranger (making them able to fight up close for longer) or some CON (making them able to _not die_ for longer), but i'd suggest you just don't touch it.
> 
> Also also, why lower their climbing and swimming skill? The only difference on climbing skill made is when it reaches journeyman (Which then lets you go climb stone walls) and it seems fair since a significant portion of their time is spent probably climbing trees for cover and high ground. And the swimming skill makes sense, looking at how we're at a bog having the ability to swim effectively makes it easier to get out of trouble or effectively fight in the murk (Which also makes a lot of sense for a ranger)
> 
> And before you say "What's the problem with lowering climbing skill if it will change nothing?", future changes might be done to climbing or climbing speeds, so it think it's better to just leave it like it is rather than changing it to be just worse for, quite literally, no change whatsoever.

This is... Actually a good argument and I will be updating the PR or making a new one. If I could get your Discord for more feedback like this, I would appreciate it.

**Pull request closed without merging**
