### PR TITLE
Objects in walls fix

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Fixed all objetcs (torches, candles, paintings etc) in walls i managed to find those
Fixed multiple trees on one tile where i managed to find them
Moved braziers aways from center of roads (3 total), because obstructing roads is bad 
Reset weaponsmith and armorsmith tables and shuttlers names to default as those roles no longer exist

## Why It's Good For The Game
This part is stupid, fixes are good

### CODE REVIEW

**Comment by Nakalon** [comment]
Heney. Did you read the guidelines?
I'm giving you time to do so. I don't have to always come in these and tell you what your PRs are missing.

**Comment by Nakalon** [comment]
Please correct this! 
image

**Comment by Nakalon** [comment]
Other than that it looks good

**Comment by Heheniy** [comment]
> Please correct this! image

what about it

**Comment by Heheniy** [comment]
@Nakalon corrected
also idk why it shows conflict, i literally merged upstream a minute ago

**Comment by Nakalon** [comment]
> @Nakalon corrected also idk why it shows conflict, i literally merged upstream a minute ago

Because there were recent map changes.

You see map changes create conflicts very hard to resolve.

Thats why we have to take these extremely carefully

**Comment by Heheniy** [comment]
map is fucked up now

**Pull request closed without merging**
