### PR TITLE
the dreaded awful pr that even i do not want to make - food that is supposed to rot now rots (read desc before merging)

### PR DESCRIPTION
**Pull request by Slorbin**
pies now rot. sliced bread now rots. cooked fish (not uncooked, uncooked fish still doesnt rot because realistically youd be keeping the fish on a line/net in water to keep it alive)

however, i really do not recommend merging this until there becomes an actual fucking serious to make good foods or anything that isn't salami, jacksberries and crackers

this pr more exists to just 'be ready' when the server can handle actually fixing this bug. i am going to miss pie

### CODE REVIEW

**Comment by DeerJesus** [comment]
if any other food that does not rot that is supposed to rot is in the game lat me know... goodbye my sweet food

**Comment by aberrantQuesrist** [comment]
Maybe the solution should be the other way around, and just make food not rot when on tables or something? It's very sad to have to keep all your food in a chest where no one can see it out of fear that leaving it out too long will cause it to rot. No nice displays, no feasts, just chests and orders.

**Comment by DeerJesus** [comment]
> Maybe the solution should be the other way around, and just make food not rot when on tables or something? It's very sad to have to keep all your food in a chest where no one can see it out of fear that leaving it out too long will cause it to rot. No nice displays, no feasts, just chests and orders. 

I'd like that but I'm kinda getting busy with college so someone else may have to code it

**Comment by CalamaBanana** [comment]
For the love of God, do not merge this. Nearly no one wants to play servant already, having to babysit the freezer chest or recook every five minutes will kill that role.

**Comment by DeerJesus** [comment]
> For the love of God, do not merge this. Nearly no one wants to play servant already, having to babysit the freezer chest or recook every five minutes will kill that role.
> 
> Also, the main reason you see mostly pies being used for feasts as well. You just can't set out other food if it rots before the king finished his speech.
> 
> Honestly, just remove rotting outright, or have it just rot if things are on the floor directly. It adds little to nothing to RP, other than some idiot leaving the freezer open constantly.

I think I will try to add that things don't rot if theyre on a table or in a containre.

**Comment by CalamaBanana** [comment]
> I think I will try to add that things don't rot if theyre on a table or in a containre.

Yes, that would be great.

**Comment by Cyprex** [comment]
Closing this for now- this can be reopened later, potentially! Feel free to ping or DM us about it!

**Comment by Cyprex** [comment]
Actually- I'll leave this open in case you want to add the feature where things only rot on the floor/not on tables or counters/things like that.

**Comment by Keazra** [comment]
For the love of all that is holy don't merge this. Dealing with rotting food is a pain as it is and makes the game less interesting.

**Comment by katsukai** [comment]
> For the love of all that is holy don't merge this. Dealing with rotting food is a pain as it is and makes the game less interesting.

 My opinion having too much food can also take away from the experience.  My opinion there should be like a metallic food lid that you could put on a food item at the table to preserve it and make it available via smithing. So nobles likely have these for their servants and the more wealthy inhabitant of Rockhill could have this if they want to show off their food on a table.
 
image

**Comment by DeerJesus** [comment]
> closing it out since im not sure the PR persons around anymore

I'm still "around" but not gonna work on this since I really didn't like this PR myself, and made it as a begrudging option

**Pull request closed without merging**
