### PR TITLE
Sewing Rework Atomization - Part 1 - Clothing Salvage

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

I have planed to make a rework of the Seamstress and sewing to make it more exciting and fun to play!

The main idea is to make it function similar to Smithing.
This PR fits that purpose by being the Smelting equivalent of Sewing!

### - Introducing: Scissors!

image

Scissors and Needles are to the Seamstress as Tongs and Hammers to the Smith!

Seamsters spawn with an Iron Scissor now instead of a hunting knife!

image

Don't worry, you're not missing anything! The Scissors are actually a subtype of hunting knife.
(Also, if you lose it you can also ask the smiths to make another, Iron or Steel!)

While a Seamstress may use a Needle to repair clothing, they may use their newly discovered scissor technology to salvage materials out of clothing items!

image

This is an example.
You will always either get 1 fiber or no fibers at all depending on the item.
(If its got fibers in its crafting recipe you'll get 1 fiber)

You may or may not be able to salvage base materials (such as cloth and leather) out of a piece of clothing depending on your sewing skill!

image

Yes! It works for leather also!

image

You may be thinking about "what about sleeve tearing? I'm gonna print unlimited cloth!"

NO. NO YOU WONT! STOP IT!

### - Sleeve Tearing improvements

I always thought tearing sleeves was very obscure and not very obvious.

So I changed that! Now you get proper information on examine about the state of the clothing piece!

image
image
image

### Attention: The above typo has been solved. my bad kings and queens.

This means, I also accounted for sleeve tearing when salvaging something with scissors!

The math works!

image

Wow I have no idea what this means!

### - Experience!

~~Now you get sewing experience for sleeve tearing, but get more experience for salvaging the proper way!~~

You only get experience for salvaging now! Oups!

## Why It's Good For The Game

More power to the Seamstress!
Gives one more step of depth to the role, thus hopefully enticing people to play towner!
Also included are some slight coding improvements, which are always good!

## Changelog

Add: Added Iron and Steel Scissors which may be used to salvage articles of clothing
Sprite: Added Sprites for the Iron and Steel Scissors
Tweak: Seamsters now spawn with Iron Scissors instead of a hunting knife
Tweak: You can now tell how many sleeves were torn form a piece of clothing by examining
~~Tweak: You now get sewing experience for sleeve tearing~~
Code: Removed some duplicated vars and commented out code when it presented itself
Code: Improved Sleeve tearing code and gave it some early returns
Code: Changed  the "shiftheld" var to "altheld" in sleeve tearing code to properly mirror what it does

### CODE REVIEW

**Comment by john-pawson** [comment]
Great PR!
Although i'm a bit concerned about the sleeve tearing giving XP, since it means people can farm sewing XP *way* faster by just making pants, tearing them into cloth, and then making pants again. Infinitely. Specially if tearing a sleeve grants about as much as crafting anything with a diff of 1.

Oh and also, the chance to fail tearing a sleeve? the one that goes `if(prob(50 - (skill_level)))` on line 120. You might want to multiply by 10 the skill level, since how it's written it'd end up making someone unexperienced have a 50% chance to fail and a **LEGENDARY** seamstress havea 44% chance. (Skills default value is 0-6, so most check multiply it by 10 or less)

**Comment by Nakalon** [comment]
> Great PR! Although i'm a bit concerned about the sleeve tearing giving XP, since it means people can farm sewing XP _way_ faster by just making pants, tearing them into cloth, and then making pants again. Infinitely. Specially if tearing a sleeve grants about as much as crafting anything with a diff of 1.

I'm not concerned because I don't know how relevant farming the XP is... 

I did think of adding a fail chance for this but it would piss players who always rip their sleeves.

You think I should remove that exp?

> Oh and also, the chance to fail tearing a sleeve? the one that goes `if(prob(50 - (skill_level)))` on line 120. You might want to multiply by 10 the skill level, since how it's written it'd end up making someone unexperienced have a 50% chance to fail and a **LEGENDARY** seamstress havea 44% chance. (Skills default value is 0-6, so most check multiply it by 10 or less)

I sillily droped the multiplication because in testing I cut 20 pieces of clothign and didnt fail once as roundstart seamster

Thanks for letting me know!

**Comment by john-pawson** [comment]
> > Great PR! Although i'm a bit concerned about the sleeve tearing giving XP, since it means people can farm sewing XP _way_ faster by just making pants, tearing them into cloth, and then making pants again. Infinitely. Specially if tearing a sleeve grants about as much as crafting anything with a diff of 1.
> 
> I'm not concerned because I don't know how relevant farming the XP is...
> 
> I did think of adding a fail chance for this but it would piss players who always rip their sleeves.
> 
> You think I should remove that exp?

Personally yes, it becomes a problem when a skill is too easy to learn since people that should be specialized in that specific skill suddenly don't matter. So if leveling up sewing to Apprentice or Journeyman means making 2-3 shirts and ripping their sleeves off instead of having to actually take some time and spend cloth sewing things, it'd make it so a large chunk of people would prefer to just train the skill themselves and craft whatever they need instead of going to the seamster, making the job obsolete or ignored.

>I sillily droped the multiplication because in testing I cut 20 pieces of clothign and didnt fail once as roundstart seamster
>
>Thanks for letting me know!

No problem!

**Comment by Nakalon** [comment]
> > > Great PR! Although i'm a bit concerned about the sleeve tearing giving XP, since it means people can farm sewing XP _way_ faster by just making pants, tearing them into cloth, and then making pants again. Infinitely. Specially if tearing a sleeve grants about as much as crafting anything with a diff of 1.
> > 
> > 
> > I'm not concerned because I don't know how relevant farming the XP is...
> > I did think of adding a fail chance for this but it would piss players who always rip their sleeves.
> > You think I should remove that exp?
> 
> Personally yes, it becomes a problem when a skill is too easy to learn since people that should be specialized in that specific skill suddenly don't matter. So if leveling up sewing to Apprentice or Journeyman means making 2-3 shirts and ripping their sleeves off instead of having to actually take some time and spend cloth sewing things, it'd make it so a large chunk of people would prefer to just train the skill themselves and craft whatever they need instead of going to the seamster, making the job obsolete or ignored.
> 
> > I sillily droped the multiplication because in testing I cut 20 pieces of clothign and didnt fail once as roundstart seamster
> > Thanks for letting me know!
> 
> No problem!

Sorry for not thanking you for the compliments! I had something else on my mind! I commited changes adressing your feedback! Thank you so much for leaving the time to look at my pr!!!
<3

**Comment by katsukai** [comment]
Good job, this one is a really cool change.

**Comment by Nakalon** [comment]
I had no idea this was testmerged... Took the opportunity to try it out for myself. Had a lot of fun as a seamstress!

**Comment by Nakalon** [comment]
decreased salvage amount of stockings from 2 to 1, it was an oversight, im very sorry, its fixed now!

**Pull request merged**
