### PR TITLE
New migrant wave: The Zybantine Slavers (tested and functional)

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

Arriving to the Isles of Enigma, The Zybantine Slavers from western deserts of Zybantine (same place as the Desert Riders). The first light-villain(?) migrant wave, including a Zybantine Slave Master, 4 Zybantynian Mercs (2 with swords, 2 with wips), and an imported Zybantynian slave!

## Why It's Good For The Game

More variety, and also for fun!

Also this is what I based the Zybantine name and lore on
image

image

https://github.com/user-attachments/assets/b3193870-569e-4ad5-a3f2-8ff912044112

### CODE REVIEW

**Comment by MefAnneFeminene** [comment]
When the lore team gets assembled, that map will probably become outdated

**Comment by Hmeister-real** [comment]
> When the lore team gets assembled, that map will probably become outdated

as long as Zybantine remains a desert. it's fine.

**Comment by MickDick1** [comment]
Cool stuff. A shame the million white knights will just lynch them every time. So, with that kind of cultural atmosphere, it's weird a travelling slaver group would even approach rockhill.

At least they're reasonably well equipped, except their feet are totally unarmored (shalal boots have 0 protection values) making them a joke.

**Comment by Heheniy** [comment]
removing slave master in first wave feels like removing heartfelt lord 

also why is it 5 combat roles and only 1 slave

**Comment by MickDick1** [comment]
> removing slave master in first wave feels like removing heartfelt lord
> 
> also why is it 5 combat roles and only 1 slave

That's easy from a quick look. The slave is a bit of jack of all trades + prostitute. Very valuable. And given they're SLAVERS and this server is chock full of fragging white knights the large escort is necessary to dissuade them.

**Comment by Heheniy** [comment]
1 slave is really too low number, make it at elast 3

**Comment by CalamaBanana** [comment]
Small nitpick, your cape and hood does not colour match perfectly:
image

**Comment by Hmeister-real** [comment]
> Small nitpick, your cape and hood does not colour match perfectly: image

fixed
image
image

**Comment by zakanater19** [comment]
Very nice

**Comment by hugmeorelse** [comment]
I feel like unique migrant roles like Heartfelts and this should be forced to trigger early into the round, otherwise they won't get many interested folks and will only make minimal impact.

**Comment by zakanater19** [comment]
> I feel like unique migrant roles like Heartfelts and this should be forced to trigger early into the round, otherwise they won't get many interested folks and will only make minimal impact.

I like the way it currently works, without them all just spawning mish mash at roundstart or being forced

**Comment by hugmeorelse** [comment]
> 1 slave is really too low number, make it at elast 3

I mean, the point is they're there to enslave. If you have three to begin with, what's the point?

**Comment by Coolgat3** [comment]
this is cool lets make more so i can stop looking at fucking pilgrim rolls

**Comment by Genevesh** [comment]
I hate to say it, but the colour you picked for their headdresses and cloaks is just an eyesore. Why must they be PURPLE? You might as well have made them PINK. Make it yellow, dark grey, literally ANY neutral colour or something that befits an actual desert. I know the respective sandie mercenaries have theirs in red, but it looks perfectly fine and isn't biting the eye.

**Comment by Hmeister-real** [comment]
> I hate to say it, but the colour you picked for their headdresses and cloaks is just an eyesore. Why must they be PURPLE? You might as well have made them PINK. Make it yellow, dark grey, literally ANY neutral colour or something that befits an actual desert. I know the respective sandie mercenaries have theirs in red, but it looks perfectly fine and isn't biting the eye.

i chose purple because the Zybantine Kite Shield design is Bright Purple with gold accents, i could have made it even brighter but i chose to make it darker

**Comment by ToothyDeer** [comment]
probably one of my favorite migrant waves, but a few things:
* crossbowman spawns w/ a hauberk, but doesnt have medium armor training. i'd either get rid of easy dodging and give medium armor trait, or get rid of the hauberk and give something light instead

* the keffiyahs are fucking awesome, especially in purple, but everyone gets the closed variant other than the master slaver. do you think it'd be possible to just merge the two variants, and then just have the open and closed toggable via right click? the closed keffiyah looks silly w/ a lot of snouts in the game, but snouts with the open keffiyah look amazing. plus it makes sense to be able to lower it from your nose.


otherwise this is my favorite migrant wave, the rp its given me and the rounds its made have been fucking amazing

**Comment by Hmeister-real** [comment]
> probably one of my favorite migrant waves, but a few things:
> 
> * crossbowman spawns w/ a hauberk, but doesnt have medium armor training. i'd either get rid of easy dodging and give medium armor trait, or get rid of the hauberk and give something light instead
> * the keffiyahs are fucking awesome, especially in purple, but everyone gets the closed variant other than the master slaver. do you think it'd be possible to just merge the two variants, and then just have the open and closed toggable via right click? the closed keffiyah looks silly w/ a lot of snouts in the game, but snouts with the open keffiyah look amazing. plus it makes sense to be able to lower it from your nose.
> 
> otherwise this is my favorite migrant wave, the rp its given me and the rounds its made have been fucking amazing

I meant to give him a Haubergeon, not a hauberk. Whoops.

And sure I can have a go at it

**Comment by ToothyDeer** [comment]
> > probably one of my favorite migrant waves, but a few things:
> > 
> > * crossbowman spawns w/ a hauberk, but doesnt have medium armor training. i'd either get rid of easy dodging and give medium armor trait, or get rid of the hauberk and give something light instead
> > * the keffiyahs are fucking awesome, especially in purple, but everyone gets the closed variant other than the master slaver. do you think it'd be possible to just merge the two variants, and then just have the open and closed toggable via right click? the closed keffiyah looks silly w/ a lot of snouts in the game, but snouts with the open keffiyah look amazing. plus it makes sense to be able to lower it from your nose.
> > 
> > otherwise this is my favorite migrant wave, the rp its given me and the rounds its made have been fucking amazing
> 
> I meant to give him a Haubergeon, not a hauberk. Whoops.
> 
> And sure I can have a go at it
> 
> Both are done 👍

YAAAAAAAAAY!

**Comment by MefAnneFeminene** [comment]
If you'd like my suggestion regarding the pseudo eyesore that is the Zybantine cloaks, you can still have them be purple, just choose a dark / muted purple.
image

Something like this would look really nice.

**Review by Cyprex — APPROVED** [review]

**Pull request merged**
