### PR TITLE
Vampire lord punishment changes

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Subjects will show their real names, not their perceived names (Unknowns)
You can now cancel the punishment
The punishment which ends up dusting the subject has been renamed to DESTROY from Release, to make it more clear, as it's a thing that just dusts you

### CODE REVIEW

**Comment by pismorizzo** [comment]
Thank, once dusted someone assuming the release button had meant cancel.

**Comment by atomicplan666** [comment]
Thank GOD

**Comment by john-pawson** [comment]
> Thank, once dusted someone assuming the release button had meant cancel.

Same, who names the "instantly kill someone" choice Release anyways?
Also love that you can cancel it, hate it when you accidentally click punish and are now FORCED to punish someone.

**Comment by radarseas** [comment]
massively overdue changes, I hate it when you have that, one person whom refuses to be loyal but you can't do anything to them but order your own minions to kill them, because they have a helmet/mask over the face.


That and not being able to cancel on top of the plus that release is... too vague.

Godsend PR.

**Pull request merged**
