### PR TITLE
furry ears can stick out of many more types of helmet armor now

### PR DESCRIPTION
**Pull request by Slorbin**
more helmets can have furry ears sticking out of them. mostly light helmets, heavy helmets don't do that. was going to have it be like a sprite like other servers do on modsuits but azarak suggested this instead.

hidehair no longer hides ears as well. hideears does that.

### CODE REVIEW

**Comment by Moribun** [comment]
Coif's? almost a necessity with neck choppers. and they make you look like someone put a split condom on your head.

**Comment by DeerJesus** [comment]
> Coif's? almost a necessity with neck choppers. and they make you look like someone put a split condom on your head. 

I'll add it to coifs

**Comment by dotCatshark** [comment]
This seems untested/not thought through and lets ears stick out of helmets that make zero sense, like court physician mask or bascinet. Which is of course extremely ugly and makes little sense.

**Comment by Kepteyn** [comment]
Could you do the same for the coif and frills?

**Comment by DeerJesus** [comment]
> yeah it feels like you just turned on the ears enabled for everything that hid ears, including the things that should be hiding ears

no just a few light helmets actually ;) check the code!

**Comment by kepesk1** [comment]
> yeah not for bascinets please, doesn't look good image

looks fine to me. i don't know what kind of bascinet helmet would hide a lupian's tall ears anyways.

**Comment by kepesk1** [comment]
> yeah it feels like you just turned on the ears enabled for everything that hid ears, including the things that should be hiding ears

did you even check the code

although if you genuinely mean it "feels" like it turns on an enable all for ears, i think it's a great addition because we shouldn't be able to hide ears and tails when the helmets are not exactly conforming to the anatomy of the sprite anyways. i'd prefer people make helmets that fit certain races and if they wear one that is misfitting, it's either too large or too small and therefore gives negative effects to you like decreased dex or perception. but i'd like that to come after this PR :)

**Comment by DorfGuy1** [comment]
please add an option to enable or disable this. Elfs look kinda dumb.

**Comment by dotCatshark** [comment]
> > yeah not for bascinets please, doesn't look good image
> 
> looks fine to me. i don't know what kind of bascinet helmet would hide a lupian's tall ears anyways.

bascinet2016a-2572451223

image of a bascinet for reference

**Comment by dotCatshark** [comment]
also, jester's jingly hood not hiding ears because coif doesnt (which also doesnt make sense as its a leather headwrap) makes jester look weird.

**Comment by DeerJesus** [comment]
> also, jester's jingly hood not hiding ears because coif doesnt (which also doesnt make sense as its a leather headwrap) makes jester look weird.

this one is an oversight I'll fix that

**Comment by ThinkArbies** [comment]
If all these "please don't include X item" comments aren't indicative:

This doesn't look good for _any_ fully head-covering item. There's plenty of headwear options for people who want ears visible, but this somehow makes bascinets look even more ridiculous and they already looked stupid enough as is.

**Comment by DeerJesus** [comment]
> If all these "please don't include X item" comments aren't indicative:
> 
> This doesn't look good for _any_ fully head-covering item. There's plenty of headwear options for people who want ears visible, but this somehow makes bascinets look even more ridiculous and they already looked stupid enough as is.
> 
> Ears aren't rigid objects. They can _bend_. You could squeeze them into a helmet or coif. It wouldn't be _comfortable_, but it's possible.

i may reconsider and tryyyy to add 'ear armor', which was my original goal - a little akin to how modsuits automatically apply a layer over your ears, except this will be custom sprited

**Comment by kepesk1** [comment]
> > > yeah not for bascinets please, doesn't look good image
> > 
> > 
> > looks fine to me. i don't know what kind of bascinet helmet would hide a lupian's tall ears anyways.
> 
> bascinet2016a-2572451223
> 
> image of a bascinet for reference

what i mean is i do not know of any bascinet helmet that could be worn with ears that tall. so, better yet, just make them unwearable if you have tall ears since you don't think a bascinet would be made with holes when your ears are several inches long.

**Pull request merged**
