### PR TITLE
Heavily buffs rot timers

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
changes rot from 10 mins to 45, skeletonise from 25 to 90, dust from 35 to 135

## Why It's Good For The Game
Requested in #1766 makes acolytes jobs easier and gives people more time to haul bodies

### CODE REVIEW

**Comment by Gyrandola** [comment]
Rot must remain central to the setting. Upgrading the time it takes for people to zombify to 45 whole minutes would negate its existence.

**Comment by wow50000** [comment]
rot is an unfun mechanic imo but thats fair, the setting requires it

**Comment by wow50000** [comment]
> Considering how rot is supposed to be one of the main threats lore-wise i don't think cuadrupling the rot timer is exactly good since it kind of almost removes it entirely. Not only that but it also makes death, an already pretty easily curable thing, now even more of a non-problem.
> 
> Why not instead make it so there's ways to _slow down_ the rot? Like modifying the winding sheets so they slow down rotting or just adding a drug that delays rotting slightly, instead of making it take so long that it just isn't going to show up anymore if it takes more than half an hour to even appear?

people treat death like nothing because they have 10 backup characters lined up or they want to die IC, not because of rot timers.

**Comment by john-pawson** [comment]
> people treat death like nothing because they have 10 backup characters lined up or they want to die IC, not because of rot timers.

Well i don't see why we should make the problem worse by making rot timers higher.

Also, i'm pretty sure this doesn't exactly apply to everyone. If you die as a knight mid-round there's a pretty big chance you'll not be able to just go in as a backup character again, same goes with about every single role that doesn't have a lot of slots open (Adventurer, Pilgrim, Mercenary, etc.) and for those that do have a lot open, you all lose your gear most of the time. 
Excluding of course the occasional death to spider in the middle of the bog, in which they'll probably just go metagaming and pick up their stuff back.

Also, i never said people treat death like nothing because of rot timers, if anything it's the only thing preventing every single person from getting revived. (Asides from the deliverate decapitations where they hide the head, in which case they, ridiculosly, can still be revived with the head of some other guy or zombie.)

**Comment by john-pawson** [comment]
> > people treat death like nothing because they have 10 backup characters lined up or they want to die IC, not because of rot timers.
> 
> Well i don't see why we should make the problem worse by making rot timers higher.
> 
> Also, i'm pretty sure this doesn't exactly apply to everyone. If you die as a knight mid-round there's a pretty big chance you'll not be able to just go in as a backup character again, same goes with about every single role that doesn't have a lot of slots open (Adventurer, Pilgrim, Mercenary, etc.) and for those that do have a lot open, you lose all your gear most of the time. Excluding of course the occasional death to spider in the middle of the bog, in which they'll probably just go metagaming and pick up their stuff back.
> 
> Also, i never said people treat death like nothing because of rot timers, if anything it's the only thing preventing every single person from getting revived. (Asides from the deliverate decapitations where they hide the head, in which case they, ridiculosly, can still be revived with the head of some other guy or zombie.)

**Pull request closed without merging**
