### PR TITLE
YOU CAN NOW COOK SO MUCH STUFF

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

adds a ton of crops, a ton of things to cook. meatloaf. roast. jade emperor's peking duck. casseroles. stews.

scour through the code until i add all the recipes to the wiki.

it's a lot folks. it's bigly a lot. i am very tired i spent all day on this

i was going to add rockhill mountain oysters but that may be later. but as a consequence all the organs have their correct sprites now. have fun

co-author: LofiOtter (thanks for the pies and some crops!)

sprites shamelessly stolen from tg and one from vg

### CODE REVIEW

**Comment by YennyWR** [comment]
These seeds hould probably also be acquireable through the merchant. The seeds tab on their device barely gets used as is.

**Comment by DeerJesus** [comment]
> this is great, and a tremendous amount of work, fantastic job!
> 
> 
> 
> but, i have to say that i reckon the food with trash items need to have the trash part removed.
> 
> its very silly to have leftover unusable bowls and plates and stuff when you don't use them to make the food.
> 
> 
> 
> it would be so much better in the long run if the food in bowls required a bowl to craft and returned the empty bowl when consumed, the sprites could be standardized too to appear as food like stews or soups of various kinds in wooden bowls.
> 
> 
> 
> perhaps this could be expanded further so you use a pot to craft the uncooked soup, which then gets placed over a hearth or campfire to cook, and once its cooked you can use a bowl on it to get a bowl of soup or stew. 
> 
> 
> 
> obviously the last two are suggestions and are outside the scope of the initial PR but its something to consider

Most soups require a bowl to craft, the only two that didn't are an oversight. Being able to cook soups like you can in tg would be very much desired but I have no idea how to port it.

**Comment by DeerJesus** [comment]
> These seeds hould probably also be acquireable through the merchant. The seeds tab on their device barely gets used as is.

They are! All merchant purchaseable

**Comment by DorfGuy1** [comment]
Based

**Comment by Genevesh** [comment]
YOU CAN COOK SO MUCH
yet you can't...

I made one dish and I reckon most of those don't have sprites, half of the seeds will not be grown outright if they don't already spawn in the farm, and buying them from the merchant is a pain in the ass.

The PR seems to have broken the recipe of a dogroll entirely.

I say you test it some more before releasing

**Comment by DeerJesus** [comment]
> YOU CAN COOK SO MUCH yet you can't...
> 
> I made one dish and I reckon most of those don't have sprites, half of the seeds will not be grown outright if they don't already spawn in the farm, and buying them from the merchant is a pain in the ass.
> 
> The PR seems to have broken the recipe of a dogroll entirely.
> 
> I say you test it some more before releasing

i fixed dogroll :) that was the only one, though plump helmet was misprited

seeds grow if you buy them from the merchant. all of the dishes have sprites. 

it's SUPPOSED to be a guaranteed drop from the merchant loot table HOWEVER merchant code is fucked and instead of giving you each item in the list it selects *random* items from the list. not sure how to fix it but ill work on it

**Comment by Gr33d-y** [comment]
Can we not readd the ability to fry and eat stuff. It's absurdly immersion breaking and gamey.

**Comment by Red-Honk** [comment]
Ears still lack sprites, they're still under the effects of the invisium "spell".

**Comment by hugmeorelse** [comment]
> Ears still lack sprites, they're still under the effects of the invisium "spell".

This might be the wrong PR

**Comment by DavidAreYouSure** [comment]
Do any of these add sugar as a chemical you can grind? If not this alone adds enough chemicals to make a few more interesting things from TG Chem

**Comment by DeerJesus** [comment]
> Can we not readd the ability to fry and eat stuff. It's absurdly immersion breaking and gamey.

This has been disabled as of the time you posted it

**Comment by DeerJesus** [comment]
> Do any of these add sugar as a chemical you can grind? If not this alone adds enough chemicals to make a few more interesting things from TG Chem

This adds sugar. Not sure what interesting tg chem things you mean? Other than caramel, which I'm going to work on soon

**Comment by DeerJesus** [comment]
Sugar comes from grinding beets

**Comment by DeerJesus** [comment]
tomato sprite will be fixed soon along with frying foods. its still broken now. i dont know why. it was supposed to be fix. poopman came

**Comment by Genevesh** [comment]
The most annoying part of this PR is how the seeds are too randomised to reliably get *any* recipe working, with how specific they are. I'd say it would be better to give some of the more basic ones, like radish, poato, and carrot seeds to the farmers roundstart rather than try to gamble them at the merchant's.

**Comment by DeerJesus** [comment]
> The most annoying part of this PR is how the seeds are too randomised to reliably get *any* recipe working, with how specific they are. I'd say it would be better to give some of the more basic ones, like radish, poato, and carrot seeds to the farmers roundstart rather than try to gamble them at the merchant's.

This annoys the shit out of me too and is a big I'm trying to fix. 

I'll also give some of the seeds to them in a separate map PR.

**Comment by DorfGuy1** [comment]
Yo, the tea powder, it does not in fact, seem to make tea when mixed with water, big sad.

**Comment by atomicplan666** [comment]
There's no way to get the red amanita seeds :(

**Comment by DeerJesus** [comment]
> Yo, the tea powder, it does not in fact, seem to make tea when mixed with water, big sad.

Did you heat up the tea powder and water mixture?

**Comment by DeerJesus** [comment]
> There's no way to get the red amanita seeds :(

They can supposedly spawn in caves very rarely, but ATM they're supposed to be exceptionally hard to get.

**Comment by DorfGuy1** [comment]
> > Yo, the tea powder, it does not in fact, seem to make tea when mixed with water, big sad.
> 
> Did you heat up the tea powder and water mixture?

I was looking at the code and it did not seem like I had to, but I will try next time.

**Comment by DeerJesus** [comment]
Oops

**Comment by DavidAreYouSure** [comment]
> > Do any of these add sugar as a chemical you can grind? If not this alone adds enough chemicals to make a few more interesting things from TG Chem
> 
> This adds sugar. Not sure what interesting tg chem things you mean? Other than caramel, which I'm going to work on soon

Sugar means we have carbon which means we have one of the 3 major chemicals needed for TG fuckery. We have a number of chemicals we can add to it, now we just need a source of hydrogen to make alot of chemicals from TG hydrogen carbon and oil makes welding fuel which chains to other chemicals.  sugar is genuinely one of the most important ghetto chem components

**Comment by Useroth** [comment]
We'll have vodka once we have distillation

**Comment by Vanaim** [comment]
Please fix #819

**Comment by Vanaim** [comment]
The pate recipe is still messed up. Of course, I understand that you were working and hiring other PRs at the same time, but it’s still worth fixing just one line in the code. #819 
images

**Pull request merged**
