### PR TITLE
PSYDON added to roles

### PR DESCRIPTION
**Pull request by Jackofashepard**
## About The Pull Request

ALL_DIVINE_PATRONS is applied to Knight, captain, gatemaster and bog master. Now changed to ALL_NON_INHUMEN_PATRONS which just had psydon added.

## Why It's Good For The Game

I think its cool having more roles be able to be psydonites. The king can literally be a psydonite but for some reason a good chunk of his most important retinue cannot. Not to mention the bog and gate masters as well.

### CODE REVIEW

**Comment by john-pawson** [comment]
> As a side note ALL_DIVINE_PATRONS can now basically be deleted since all these other roles with it just force set your patron anyways

Well no, since it still blocks people with characters that have inhumen gods or psydon as a patron from rolling it, so "John the psydonite" or "Bob the graggarite" doesn't roll priest or acolyte.

**Comment by Jackofashepard** [comment]
> > As a side note ALL_DIVINE_PATRONS can now basically be deleted since all these other roles with it just force set your patron anyways
> 
> Well no, since it still blocks people with characters that have inhumen gods or psydon as a patron from rolling it, so "John the psydonite" or "Bob the graggarite" doesn't roll priest or acolyte.

They get forced to x religion anyways. For example they will be forced to astartan anyways

**Comment by Jackofashepard** [comment]
> Leave ALL_DIVINE_PATRONS. It can be useful for other stuff

Fair. Was planning on it. Just added it as a side note for people curious about the DEFS

**Comment by john-pawson** [comment]
> > > As a side note ALL_DIVINE_PATRONS can now basically be deleted since all these other roles with it just force set your patron anyways
> > 
> > 
> > Well no, since it still blocks people with characters that have inhumen gods or psydon as a patron from rolling it, so "John the psydonite" or "Bob the graggarite" doesn't roll priest or acolyte.
> 
> They get forced to x religion anyways. For your example they will be forced to astartan

Captura de pantalla 2024-09-18 123745
Captura de pantalla 2024-09-18 123758
I mean it's used to avoid things like these from happening

**Pull request merged**
