### PR TITLE
Physician can now be a graggarite, similar to town doctor

### PR DESCRIPTION
**Pull request by ChuChu42**
## About The Pull Request
physician can now be a graggarite, because physician is a commoner, theres no real reason a graggarite couldnt pose as a pestran in order to get to a position where they can silently take a bite out of nobles to serve their own desires

## Why It's Good For The Game

physician can now be graggarite, similar to the town doctor

(yumby, human met c: )

### CODE REVIEW

**Comment by Gyrandola** [comment]
Does this account for skeleton limbs being butcherable?
Also, butchering zombies should give rotten or poisoned meat.

**Comment by K4rlox** [comment]
> Does this account for skeleton limbs being butcherable? Also, butchering zombies should give rotten or poisoned meat.

this just adds butcherable to the base limbs, to do the above i need to find every one of the species limbs and add each species the butcher code manually, otherwise i dont know how to make modular code and this is just copy of a butchering code from a diffrent codebase

if you are willing to tell me how, i can, but otherwise i cant

**Comment by Heheniy** [comment]
i know for sure you can already butch heads by MMB with knife, isnt it is same for limbs

**Comment by Xaytan** [comment]
> > Does this account for skeleton limbs being butcherable? Also, butchering zombies should give rotten or poisoned meat.
> 
> this just adds butcherable to the base limbs, to do the above i need to find every one of the species limbs and add each species the butcher code manually, otherwise i dont know how to make modular code and this is just copy of a butchering code from a diffrent codebase
> 
> if you are willing to tell me how, i can, but otherwise i cant

There are two things I would recommend doing.

Add a can_butcher var to the base limb object. Add a check which throws a message to the player and stops the butchering code if the variable is false. Set this on limbs that we don't want players to be able to butcher.

Also, instead of hard-coding in the meat object, add a variable for "butcher_result" and make that the meat object.

This allows limbs to be made unbutcherable if necessary, and also allows for limbs to return something other than ordinary meat if desired.

**Comment by K4rlox** [comment]
> i know for sure you can already butch heads by MMB with knife, isnt it is same for limbs

nope, you cant butcher limbs

**Comment by Gyrandola** [comment]
> i know for sure you can already butch heads by MMB with knife, isnt it is same for limbs

It was added in the lich PR for a while, but I ended up removing it.

**Review by Nakalon — CHANGES_REQUESTED** [review]
Hey! I just had a look on my phone everything seems nice however! Two points!

Please make this happen on MMB click, it's the universal butchering key!

Please add bothering exp to this!

And also, make a var on limbs such as "butcherable" or something and check for that.
That way you can keep the behaviour on the base limb and just need to add a "butcherable = FALSE" on any limbs you don't want to be butchered (like skeletons).

**Comment by K4rlox** [comment]
> Hey! I just had a look on my phone everything seems nice however! Two points!
> 
> Please make this happen on MMB click, it's the universal butchering key!
> 
> Please add bothering exp to this!
> 
> And also, make a var on limbs such as "butcherable" or something and check for that. That way you can keep the behaviour on the base limb and just need to add a "butcherable = FALSE" on any limbs you don't want to be butchered (like skeletons).

i dont know how can i do any of this

**Comment by john-pawson** [comment]
> > i know for sure you can already butch heads by MMB with knife, isnt it is same for limbs
> 
> nope, you cant butcher limbs

I mean... Yes you can? What do you mean? I just launched a test server, cut my own arm off, and successfully butchered it.
Did you test this? I have to say this works with all limbs from what i've tested so far, including skeletonized and rotted ones.
I'll send a video shortly, having trouble with the recording software

**Comment by K4rlox** [comment]
> > > i know for sure you can already butch heads by MMB with knife, isnt it is same for limbs
> > 
> > 
> > nope, you cant butcher limbs
> 
> I mean... Yes you can? What do you mean? I just launched a test server, cut my own arm off, and successfully butchered it. Did you test this? I have to say this works with all limbs from what i've tested so far, including skeletonized and rotted ones. I'll send a video shortly, having trouble with the recording software
> 
> Edit: Code is on _bodyparts.dm, line 179, if you'd like to check yourselves

i completely removed that then

**Comment by Gyrandola** [comment]
Considering you removed all of the controversial content. I'll merge it.

**Pull request merged**
