### PR TITLE
removes sexism from men at arms

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
allows women into the men at arms

## Why It's Good For The Game
There are a stupidly low number of men at arms and giving them the freedom to play female characters with speed and int oriented statblocks over str and con oriented statblock could free up some more men at arms archetypes,

As well as generally nobody really cares about women in combat roles. Nobody is going to stop a female watchman or a female warrior or paladin from fighting so why stop a female from being a man at arms.
image

### CODE REVIEW

**Comment by Heheniy** [comment]
it is not woman at arms

**Comment by K4rlox** [comment]
men at arms translated into women at arms when spawned as female at one point, you should look in history to find the code for that and revert to that

**Review by Nakalon — CHANGES_REQUESTED** [review]
Make the necessary name change take place like @K4rlox mentioned please!

**Comment by Crystal9156** [comment]
Will this also allow female gatemasters?

**Comment by wow50000** [comment]
> men at arms translated into women at arms when spawned as female at one point, you should look in history to find the code for that and revert to that

oh come on, its in the name woMEN at arms

**Comment by wow50000** [comment]
> men at arms translated into women at arms when spawned as female at one point, you should look in history to find the code for that and revert to that

highly doubt that, since I played man at arms as female and didnt notice this, nor is it in any of the older files.

**Comment by wow50000** [comment]
> Will this also allow female gatemasters?

yeah sure fuck it

**Comment by Nakalon** [comment]
> re requesting review because I suspect K4rl is wrong

Well I would prefer if it changed on gender but i guess its okay for it not to

**Review by Nakalon — APPROVED** [review]

**Comment by Nakalon** [comment]
unless you wanna do it 😳

**Pull request merged**
