### PR TITLE
The antag re-enablement

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

- Makes bandits not guaranteed to roll, only 80% chance. They have been dominating the antagonistic landscape and they no longer felt like a minor antag.
- Remove bandit migrant waves, see above.
- Re-enables vampires. Vanguard will have a new class of freaks to fight.
- Re-enables maniac, only 10% chance. EXTREMELY nerfed version made by Carl in https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1673. He is basically just a schizoid serial killer now, not a one man army.

## Why It's Good For The Game

More antag variety, less hordes of annoying bandits, proper serial killer antag akin to Town of salem's one.
Potentially a tiny bit of bog activity due to vamps, although I don't hide the fact I do not care about that.
Generally a breath of fresh air for everyone.

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
Oh, Nice. If theres going to be vampires and maniac...

**Comment by Gyrandola** [comment]
> Oh, Nice. If theres going to be vampires and maniac...
> 
> Though glancing at it. This disabled antag selected bandits, but I don't believe it stops round start opted in ones from the job. If you want them not to be pickable on round start I /believe/ you need to set them to total_positions = 0 spawn_positions = 0

ah, thanks.

**Comment by RadiantFlash7** [comment]
> > Oh, Nice. If theres going to be vampires and maniac...
> > Though glancing at it. This disabled antag selected bandits, but I don't believe it stops round start opted in ones from the job. If you want them not to be pickable on round start I /believe/ you need to set them to total_positions = 0 spawn_positions = 0
> 
> ah, thanks.

I /believe/ based on my code, that setting it to 0 should prevent it from being a selectable job round start, But will allow for late joining if not enough bandits ready up via the antag system. It would need testing, however

**Comment by Crowbar764** [comment]
if(prob(50))
		pick_bandits()

Looks like 50% chance, not 70, unless I am mistaken...

**Comment by Coolgat3** [comment]
Thanks bandit mains suck coc

**Comment by RadiantFlash7** [comment]
So, i've never actually played maniac, nor encountered it before.

I don't particularly like antags that are encouraged to round remove, and from what I can tell looking at the code about maniac.
Their whole shtick is killing people harvesting their organs, and keeping the fact that they're a killer hidden. 

Which- HIGHLY encourages round removal. Atleast with cultist, they're usually able to convert people, and only round remove a noble and a virgin.

**Comment by Koteshkin** [comment]
Any antag is good if you are roleplaying. Any antag is coal if you dont do that. It works from both antag/prey sides and they both needs to RP for antag to become good. Please, dont remove good things because of bad players.

Maniac imo is good from RP side if given to specific people, but honestly needs high PQ restriction. Same as VL.

**Comment by Gyrandola** [comment]
> This somehow seems to be breaking the bandit shop. Can this be un-testmerged until this issue is fixed
> 
> image
> 

I dont see how this would break it.
Going to take a closer look today

**Comment by Crowbar764** [comment]
Also bandit roles are completely broken RN. 4 rounds in a row where no one rolled it. Please untestmerge.

**Comment by Gyrandola** [comment]
> Also bandit roles are completely broken RN. 4 rounds in a row where no one rolled it. Please untestmerge.

just bad luck,

**Comment by Gyrandola** [comment]
Increased bandit roll chances from 70 to 80%

Reduced PQ requirements

- Maniac: 70 -> 50
- Lich: 60 -> 35
- Vampire: 30 -> 20
- Werewolf: 30 -> 20
- Cultist: 30 -> 20
- Bandit: 15 -> 10

**Comment by radarseas** [comment]
vampires were much-much needed, I wish we had mid-round antagonist rolls but that's probably for another time and system. Rounds can get bland _when antagonists are fairly new players/extremely unlucky and get wiped out fast._

not sure how I feel about migrant wave bandits being axed though, I think bandit presence slowly ramping up is fine, it keeps a persistant threat of bandits that scales up as the town does, moreso if they're not dealing with them properly.

**Comment by RadiantFlash7** [comment]
> > I don't particularly like antags that are encouraged to round remove, and from what I can tell looking at the code about maniac. Their whole shtick is killing people harvesting their organs, and keeping the fact that they're a killer hidden. Nevermind that some of the recipes require heads.
> 
> 
> 
> "I dont like antags that round remove" Is such a spineless piss baby thing to say, if you die get your ass revived or go do something else god damn, dying in a videogame is not the be all end all, there are worse things that could happen in your life LMFAO

Again. Round removal. Can't get revived. And yeah, I can go do something else with my life, and I often just play a different game when it happens. That doesn't mean I have to like, nor want or encourage the server to add an antag that has the express purpose of round removing itself targets until it can instantly end the round on success.

**Comment by Gyrandola** [comment]
> > > Also bandit roles are completely broken RN. 4 rounds in a row where no one rolled it. Please untestmerge.
> > 
> > just bad luck,
> 
> No, there's something wrong.
> 
> You can currently latejoin as bandit without using the pilgrim system - I've talked to you about this before, but usually you can get it by spamclicking as other people join the game (for some reason bandit slots are still being auto-opened)...
> 
> This was on a round where bandits didn't naturally spawn (no roundstart bandits) with enough people to roll them, so something is infact broken with how bandits are being done atm.
> 
> It's a minor nitpick as you can get at most 4-5 bandits over a long round with a lot of players, which is way better than the 195195195 billion bandit incidents.

So bandit slots are slowly opening as the round goes on? Sounds really weird. Ill look into it today

**Comment by Crowbar764** [comment]
> > Also bandit roles are completely broken RN. 4 rounds in a row where no one rolled it. Please untestmerge.
> 
> just bad luck,

10 rounds in a row now. It's broken. You literally cannot roll bandit at round start, and please don't say 'bad luck' again. Late-joining is the only work around and you are now trying to remove that.

I'm not sure why such unpopular changes are still being considered at all.

image

**Comment by Gyrandola** [comment]
revert some of the changes to antag roll logic and removed pq requirements. something is not working as intended

**Review by Nakalon — APPROVED** [review]
Bandits are big stinky as everyone knows

**Pull request merged**
