### PR TITLE
Disables another 2 dogshit traits that don't influence the game at all, tweaks roll chances for some

### PR DESCRIPTION
**Pull request by Coolgat3**
## About The Pull Request

As PR title says

## Why It's Good For The Game

All the explaination is in the comments really

### CODE REVIEW

**Comment by zakanater19** [comment]
don't remove specials just because "nobody roleplays" them, also don't nerf how often the negative traits fire

**Comment by Coolgat3** [comment]
> don't remove specials just because "nobody roleplays" them, also don't nerf how often the negative traits fire

negative traits have now in total more weight than they had before by 25 weight.

I am removing specials because they change absolutely fucking nothing just like no pouch did

**Comment by CalamaBanana** [comment]
Do add sewing to the skill special one while you touch it.

**Comment by Hmeister-real** [comment]
So you're against the mood traits, but you made bad week more common? It just doubles mood debuffs, hypocritical much? Shitty salt pr

**Comment by Cyprex** [comment]
No. A handful of these changes I might consider, but most of this is just no.

**Pull request closed without merging**
