### PR TITLE
Lich Antag

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Ports and reworks the original Lich antag from Azure.

Check out the [wiki guide](https://wiki.ratwood.rip/index.php?title=Guide_to_Lich).

### CODE REVIEW

**Comment by ManMadeHorror** [comment]
First thougth so far:
-Lich needs visual differents from it's minions that aren't just clothes
-The Suicide Spell doesn't do jackshit at the moment
-The Lich needs someway to keep it's minions together better or they just gonna run of in every direction and get lost

**Comment by Vultchurr** [comment]
The eyebite spell doesn't seem to be working, there is no audible or visual cue on whether or not it does. Doesn't go on CD either.

**Comment by Gyrandola** [comment]
> brother I cannot be a hypocrit. theres way too many commits on this. revise it please as a separate branch. because if this was from anyone else I would tell them the same.

will do so when its ready to get merged. for now I update as needed while people give feedback from the TM

**Comment by MickDick1** [comment]
Just make sure the skills added on conversion aren't stacking with the original mind or it's vampire bug 2.0 all over again.

**Comment by Gyrandola** [comment]
- Necromancer robes given to the lich to make him more distinguishable
- Suicidebomb spells removed because they are a bit too memey and not conductive to roleplay
- Eyebite fixed
- Skills should no longer stack

**Comment by radarseas** [comment]
personally I'd just keep the suicide spells and make them just, outright _kill you instead of exploding_. In the case you get nuggeted for the rest of the round and/or buried alive instead of properly killed so you can keep playing the game and respawn properly instead of being jailed away from all interaction.

First round I played lich when it was testmerged this happened, _I basically had to be admemed out of the grave, because I couldn't physicially die if I wanted to._

**Pull request merged**
