### PR TITLE
Buffs noble pilgrims, removes sexism

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
Removes sexism from noble code, now both genders get the same skills and stat modifiers, buffed their combat skills to 2(high civilian level) with the exception of polearms IF OLD, which is 3. This is because old man with a staff is cool as fuck. Also they shouldn't be able to hold any of the heavier polearms with old debuffs and -1 str stacked on top of that unless they game it like horc or something. And lastly made it all races because they are a foreign noble. Slopfix for until someone makes a drow noble class or a horc noble class.

## Why It's Good For The Game
Noble was kinda a dogshit class, still should be after these changes with no useful skills and no unique stats (just checked and they get better bows than warriors 50% of the time... oops. Still shouldn't be an issue because warrior is melee coded anyways) other than being a lootbag and having noble blood. Still vastly inferior to other pilgrim classes in terms of combat so shouldn't be an issue.

### CODE REVIEW

**Comment by LeShprotina** [comment]
Finally, good noble.
But what about items and clothing?

**Comment by wow50000** [comment]
> Finally, good noble. But what about items and clothing?

lol
lmao even

**Comment by CalamaBanana** [comment]
Create equality by giving both the domestic skills. 

While you are touching it, do slip in silken stockings for the female one, Black or white ones would me my choice.

**Comment by SixplyDev** [comment]
Not a fan of allowing shunned races to be nobles but other than that,  looks good

**Comment by radarseas** [comment]
not too much a fan of shunned races being nobles. _But, I suppose maybe, as long as people don't game it for horc strength?_

But otherwise needed changes, female nobles weren't able to do anything against tackles from anyone but mages and maybe rogues sometimes. Let alone elf female nobles whom basically lost any fight against you the second you got a grab on them. They still suck but -2 strength on top of racial modifiers is too overkill.

Any chance of giving them value apprasial? _pretty controversal...

But it gives them something in the long run_ to pull their weight with, especally if it comes to trading with the merchant or whatever. It also makes the class more unique than the rest of the pilgrim roles since noble-blooded and fancy gear is all it has going for it at the moment, _not counting the miserable stats and high chance of dying off the bat._

**Comment by Cyprex** [comment]
Sure, whatever.

**Pull request merged**
