### PR TITLE
Adds legendary maid

### PR DESCRIPTION
**Pull request by ikrarkjr**
## About The Pull Request

Every maid has a 1% chance to be a legendary variant.

## Why It's Good For The Game

Like the OG Jester being OP randomly. But because we are ratwood Jester = cringe, maid = based.

### CODE REVIEW

**Comment by radarseas** [comment]
pineapple special already handles whips, we don't need legendary swordsmaster, whipmasters to exist.. really, please, no.

make it for non-combat stats, give them journeyman at most I guess? I don't like the idea of a fragmaster maid existing where they can feasably steal the dungeoneer's whip and get away with it.

remember jester is 1 slot, _sure its a 1% chance_ for these but urm, I'd rather not deal with the rare-as-hell-but-still-feasable absolutely bullshit circumstances that 2-3 of these exist in a round.

_Keep has enough combat-related powercreep._

**Comment by ikrarkjr** [comment]
> pineapple special already handles whips, we don't need legendary swordsmaster, whipmasters to exist.. really, please, no.
> 
> make it for non-combat stats, give them journeyman at most I guess? I don't like the idea of a fragmaster maid existing where they can feasably steal the dungeoneer's whip and get away with it.

What fragmaster plays maid? Lol.
Sleeper OP combat role fr.

**Comment by SixplyDev** [comment]
Based as shit, need me a legendary maid

**Comment by JohnnyJohnJohnson** [comment]
Gimme the Fire Emblem Fates maids that are experts with throwing knives.

**Pull request closed without merging**
