### PR TITLE
Bug fix for Deadite traits not being removed from derotted players

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request
Quick and dirt fix for deadites and rotman.
There are several issues with zombies and rotman in general. However- This PR Aims to resolve the biggest of bugs impacting player gameplay experience.
When a player is de-rotted, Its supposed to remove zombie traits from the player, and re-add Rotman traits. Ever since PR #1054
merged last week, it hasn't been functioning correctly. This is horribly coded, and could be done better, but I've been frustrated with this happening for a week, and someone who cares about rotman can refractor it.

This PR also increases time before rot to 5 minutes, instead of 4, and adds 25% chance of derotting not turning someone into a rotman, lucky you.

**_DO NOT MERGE, THIS PR IS IN PROGRESS_**

## Why It's Good For The Game
Derotting now removes deadite traits from those derotted. Simple bug fix.

### CODE REVIEW

**Comment by Nakalon** [comment]
Turn it into draft if in progress my dear

**Comment by RadiantFlash7** [comment]
> Turn it into draft if in progress my dear

I just need to spend 5 minutes testing it, augh

**Comment by Nakalon** [comment]
> > Turn it into draft if in progress my dear
> 
> I just need to spend 5 minutes testing it, augh

Nuh huh 😤

**Comment by RadiantFlash7** [comment]
This proved a lot more complicated then I anticipated. This fix does not fix the issue 🦊

**Pull request closed without merging**
