### PR TITLE
Prices for all armors and weapons!

### PR DESCRIPTION
**Pull request by john-pawson**
## About The Pull Request

Have you ever noticed how aboslutely none of the fancy armors and weapons on the game have a price? Other than, well, some very specific ones like the decorated ones or swords, because for some reason, swords are the only weapons that deserve a pricetag. I've based off most of the prices depending on the skill needed to make the item and the materials too, considering how a steel bar has a price of 40, most of the prices have been made so if they need a single bar they're usually worth 30, two is 40-50, and so on.
 Now all weapons and armors have a price tag! And here, i've made a list of ***every single price*** that i've changed, so it's not such a pain to search through the code. 

**WEAPON PRICE CHANGES**

**AXES**
- Battle axe = 40
- Axe = 20 (They're common tools, who'd pay much for an *axe*?)
- Hatchet = 20
- Steel axe = 25

**MACES**
- Mace = 20 (Way too many from the skeletons)
- Steel mace = 35
- Warhammer = 20 (Mace copy)
- Steel warhammer = 35 (Mace copy)
- Stunmace = 100 (Wonder of technology)

**WHIPS & FLAILS**
- Flail = 25 (Smaller than other weapons)
- Steel flail = 25
- Repenta En = 50 (It's *the* repenta en)
(Whip didn't need change as they get a price when crafted)

**KNIVES**
- Hunting knife = 15 
- Iron dagger = 15
- Steel dagger = 15
- Combat knife = 25
- Elf dagger = 50 (Also made from silver, like the silver dagger)
- Drow dagger = 60 (Rarer elf dagger)

**POLEARMS**
- Spear = 30
- Halberd = 40
- Bardiche = 40
- Eaglebeak = 40
- Lucerne = 35 (iron)
- Gratsword = 40

**SWORDS**
- Bastard sword = 35
- Scimitar = 35
- Langemesser = 35
- Old sword = 45
- Elvish sabre = 60 (bigger elvish dagger)

**CROSSBOWS**
- Crossbow = 30 

**SHIELDS**
- Tower shield = 30
- Kite shield = 40 
- Buckler shield = 30

**ARMOR PRICE CHANGES**

**CHEST ARMOR**
- Haubergeon = 30
- Chainmaille = 25
- Hauberk = 40
- Cuirass = 50 (Plated will always be more expensive than chain)
- Half-plate = 70 
- Plate armor = 100
- Iron breastplate = 40 (2 iron)
- Scalemail = 30
- Coat of armor (lord) = 100 (Hey it's *THE* lord's armor)
- Coat of armor (hand) = 80 (Carbon copy of the lord's, but without being worn by the lord)
- Brigandine = 50
- Coat of plates = 30
- Light brigandine = 30
- Padded dress = 20 (Seamster's work also has value)
- Gambeson = 20
- Studded leather armor = 35
- Hide armor = 40 (41 if crafted)
- Leather armor = 25 (26 if crafted)
- Grenzelhoft cuirass = 60 (It's blacksteel, of course it's going to be more expensive)

**NON-CHEST ARMOR**

- Plated boots/gauntlets = 20
- Chain gloves = 15
- Noble boots = 15
- Light helmets = 20
- Visored sallet = 30
- Heavy helmets = 30
- Golden spectacles = 50 (Now you have a reason to punch someone wearing glasses. 5 Gold.)
- Steel mask = 20 
- Chain coif = 20
- Iron chain coif = 15
- Bevor = 20
- Gorget = 15
- Chain chausses = 25
- Plated chausses = 50 (Plate)

## Why It's Good For The Game

Hopefully this'll make you able to do things such as selling the weapons to the merchant if the smith decides to get cheap and pay you only a silver for an entire sword, or just make the merchant be able to take in those dozen maces (and maybe resell them, who knows!) that you got from the skeletons when there's no smith around. 

It's also good so you can do things like sell a longsword or plate armor for what it's worth rather than just smelting it for a single bar of iron, i'm sure there's someone out there on the merchant's guild that can repair a ruined plate armor, so it's probably better so they can get sold if broken rather than smelted for a single bar.

### CODE REVIEW

**Comment by Elli-Skala** [comment]
I think giving the old sword a price tag ( a already highly stolen item)  isn't the best idea

**Comment by Cyprex** [comment]
This will encourage looting, not sure I'm a fan of this. Also a silver for a sword at the smith is fine?

**Comment by john-pawson** [comment]
> This will encourage looting, not sure I'm a fan of this. Also a silver for a sword at the smith is fine?

Ah yes, but of course, a sword for the price of an apple.

**Comment by Nakalon** [comment]
I would take the prices the smiths usually do and deduct 5.

From what I've experienced smiths count a steel bar as 25, Iron as 20. And this tends to decrease as the round goes on.

What this means is, I can now go to the smith, buy Haubergeon and go to the merchant to sell it. Make 5 mammons, Merchant makes another 5.

Which MEANS, the smith can just relocate to the merchant and generate wealth like that.

In theory this sounds like a great idea, but would, in practice not work as you expect it to.

Nothing's stopping people from selling weapons to the merchant instead and them reselling as it is now.

Sorry, but I don't see this working out.

**Comment by john-pawson** [comment]
> I would take the prices the smiths usually do and deduct 5.
> 
> From what I've experienced smiths count a steel bar as 25, Iron as 20. And this tends to decrease as the round goes on.
> 
> What this means is, I can now go to the smith, buy Haubergeon and go to the merchant to sell it. Make 5 mammons, Merchant makes another 5.
> 
> Which MEANS, the smith can just relocate to the merchant and generate wealth like that.
> 
> In theory this sounds like a great idea, but would, in practice not work as you expect it to.
> 
> Nothing's stopping people from selling weapons to the merchant instead and them reselling as it is now.
> 
> Sorry, but I don't see this working out.

I don't think you understand, you can already do this with steel statues. Not only that but it'd make you more money to just simply buy the steel bar directly from the smith that's worth 40 mammon and then selling it to the merchant, rather than making a haubergeon from it that's worth 30.
Why are people not doing this? Perhaps because smiths will start to ask you for more mammon when they're running out of steel, or the merchant simply has a 20% tax and can pay you at most 15 mammon and keep 9 for himself making buying from the smith and selling it to the merchant non-profitable for you.
Or perhaps because people are already doing this, that being why you always see the steward hiring some "royal smith" to make 15 statues for them.

You see, this is *already* working out.

This just makes it so smiths buying a steel bar from scraps for stupidly cheap slightly harder, and also gives you the possibility of selling things when the smiths aren't around.

> I think giving the old sword a price tag ( a already highly stolen item) isn't the best idea

The sword (All swords, actually) already had a price before this, i just raised it by 15 since it's an unique item and a longsword, besides, i doubt that people are stealing the old sword to sell it. You can already get some watchmen mad at you if they see you walking around with it. Specially if there's a barkeep.

**Comment by Nakalon** [comment]
> This just makes it so smiths buying a steel bar from scraps for stupidly cheap slightly harder, and also gives you the possibility of selling things when the smiths aren't around.

I honestly don't see the problem with this.

Smiths need more power and say.

**Comment by Nakalon** [comment]
> I don't think you understand, you can already do this with steel statues.

This is also not a good argument in favor of this.

If anything it should be looked into

**Comment by john-pawson** [comment]
> > This just makes it so smiths buying a steel bar from scraps for stupidly cheap slightly harder, and also gives you the possibility of selling things when the smiths aren't around.
> 
> I honestly don't see the problem with this.
> 
> Smiths need more power and say.

I think the smiths being by far the wealthiest people around and usually walking around on full-plate armor because they have more steel that they can use because they buy it for incredibly cheap since you can't sell it anywhere else (a monopoly) isn't exactly good.
I do agree however, that they shouldn't be as easily replaced by wanderers/adventurers/acolytes as they are right now.

>This is also not a good argument in favor of this.
>
>If anything it should be looked into

I mean, i'm not planning on overhauling the economy since that would take a substancial amount of time and also changing a lot of prices, if you turn raw goods into processed goods it should technically raise the value if anything, but i'm lowering it anyways. I made the things that need a steel bar to be made be worth less than a steel bar, you can't make a profit from turning steel bars into armor unless someone else buys them for a higher price than you're getting the steel, in which case sellprice has no effect.

I thought that'd be balanced enough. Didn't want them to be very cheap like 10 mammon since then they'd be about the same as they are right now and the value wouldn't change anything.

**Comment by Cyprex** [comment]
> Which MEANS, the smith can just relocate to the merchant and generate wealth like that.
That is already a thing with statues, and I did that exact thing to make obscene amounts of money: https://i.imgur.com/YoD3ory.png

**Comment by Cyprex** [comment]
I'm on the fence about this, and may well close it- but regardless of that I would only consider this if armory contents were blacklisted from the treasury, we don't want a savvy steward to go put the armory in the treasury, that seems pretty stupid.

**Comment by john-pawson** [comment]
> I'm on the fence about this, and may well close it- but regardless of that I would only consider this if armory contents were blacklisted from the treasury, we don't want a savvy steward to go put the armory in the treasury, that seems pretty stupid.



> I'm on the fence about this, and may well close it- but regardless of that I would only consider this if armory contents were blacklisted from the treasury, we don't want a savvy steward to go put the armory in the treasury, that seems pretty stupid.

I could definitely try and blacklist all weapons and armors from the treasury if that's the issue, i'll see what i can do

**Comment by Heheniy** [comment]
item literally cant cost less then cost of materials put in it

**Comment by john-pawson** [comment]
Alright so, turns out i could manually set the prices of all the armory weapons to 0, which should solve the concern of stewards hauling the armory to the treasury and people raiding the armory to sell all the weapons to the merchant.

Yes, people theoretically *could* replace their swords that do have value with the swords that don't have value, and then sell the sword that does, but at that point it'd be more profitable to steal the 4 value-less swords and selling them to the smith for smelting. Which can already be done.

**Comment by Nakalon** [comment]
I'll let @Cyprex weigh in on this again.

**Comment by john-pawson** [comment]
Fair enough, hopefully it'll get added whenever things are more stabilized at least.
Thanks for letting me know! No need to be sorry

**Pull request closed without merging**
