### PR TITLE
Fixed Guild Smith Spawning

### PR DESCRIPTION
**Pull request by Xaytan**
Two typos were preventing guild smiths from spawning.

## About The Pull Request

Fixes two errors in string capitalization. These were preventing Guild Smith from being selected for late join, as well as banishing them to the bog and other random spawn locations when joining at roundstart.

## Why It's Good For The Game

It's a bug. I fix bug. The town is more likely to have smiths if they spawn correctly in their smithy instead of in a completely random location, or not spawning at all after roundstart.

### CODE REVIEW

**Comment by Nakalon** [comment]
I'll kiss you if you check blame and see who made this mistake for me before I get home. (Just because I'm nosey) 😈😈😈😈😈

**Comment by Xaytan** [comment]
> I'll kiss you if you check blame and see who made this mistake for me before I get home. (Just because I'm nosey) 😈😈😈😈😈

https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1121

This PR right here.

**Comment by Xaytan** [comment]
Conflicts resolved.

**Comment by Nakalon** [comment]
Don't know why the checks are acting up, but wanting to merge this very much!

**Pull request merged**
