### PR TITLE
Updates the Volf Helm to actually be medium armor, adds the vreccale

### PR DESCRIPTION
**Pull request by Dedwolf**
## About The Pull Request

Updates the volf helm to actually be a subtype of the regular helmets, because it is medium armor with a good fov. Adds he vreccale for more merc flavor, the vreccale is identical to the gorget

Sprites commissioned from Cre

## Why It's Good For The Game

Better balance, idk i don't really care honestly

image

image-1

### CODE REVIEW

**Review by Nakalon — CHANGES_REQUESTED** [review]
Very nice all in all but please solve this!

image

**Comment by Nakalon** [comment]
Also, where did you get the sprite? did you make it?

**Comment by Gyrandola** [comment]
I have my doubts about the fov. I will elaborate on them later.

**Comment by Gyrandola** [comment]
> > I have my doubts about the fov. I will elaborate on them later.
> 
> what do you mean

actually its beyond the scope of this PR. I wish to revisit the cones of vision of all helmets later on.

**Review by Gyrandola — APPROVED** [review]

**Review by Nakalon — APPROVED** [review]

**Pull request merged**
