### PR TITLE
Sewing Rework Atomization - Part 4 - Seamstress Emancipation

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

First I want to thank every who has been playing Seamstress since I begun this adventure!
Thanks to you, I think its finally time the Seamstress achieves Emancipation, which was my main goal when I started this.
Know, I'm not yet done, and at least 2 more major parts to this Rework are planned.
However it is time.

### The Seamstress is now a Static role!

image

After Part 1, 2, 3 and Misc of this Rework I have noted seamster has been played more often, however, it's not really a role planned for more than one person.

From now on the Seamstress is her (or his) own, and deserves its static role!

Now you won't have to hope your workshop isn't taken. It belongs to YOU!

image

***However, we're not done...***

### Seelies can now play as Seamster!

image

Yes. Now you HAVE to main it!!!!!

image

Prior to this change Seelies either required a high PQ to be played (Town Seelie), were an horrible experience (Prisoner) or were the jester (no comment).
Whoever wanted to play seelie as a normal member of society couldn't.
Well now they can!

Seelie latejoins as Seamster:
image

### New Seelie spell, just for Seamster seelies, Summon Berry!

Now you can... summon a fucking berry! WOO.
That's all the Seamster Seelies get thought, at least for now!
There's a 50% chance it comes off rotten. Hey, its fallible magic!

image
image
image
image
image

### Your roundstart clothing now doesn't look like utter COW FARTS!!

BEFORE IT WAS UGLY GREEN.
WHYYYYYYYYYYYYYYYYYYYY
NOW ITS BEAUTIFUL AGAIN.
image

ALSO MEN AREN'T FORCED TO WEAR A DRESS ANYMORE
I RESPECT YOUR MANHOOD!!!
image

### Small changes to Seamster Pilgrim

Now spawns with a pretty leather cloak, and its stats are slightly more suitable for combat and life outside of the Town.

Also gave them the more deadly steel scissors for them to survive the bog with!

#### THIS WAS TAKEN BEFORE STEEL SCISSORS WERE ADDED TO THEM, DONT WORRY IT STILL WORKS

image

## Why It's Good For The Game

As it gains gains more relevancy and becomes (hopefully) more enticing to play the seamster role has been more popular.
While this popularity is good, 2 or more players having to share the same role and resources where they are not meant to be shared does not make for the envisioned experience for Seamster. This solves it!

Also, I'm a firm believes Seelies deserve positive opportunities in the game.
I believe the sort of people that would play Seelie seamstress would be the type that would roleplay their race very well and maybe change how the race is portrayed.

The other changes are just to smooth the experience. That green padded dress was disgusting and it made the seamstress look like she didn't know how to dress herself. HER, THE QUEEN OF FASHION!?!?
Makes things professional! That's nice right?

## Changelog

Add: Seamster is now a static role
Add: Seelies are now able to play Seamster
Add: Added the Seelie spell "Summon Berry". Which has a 50% chance of summoning a rotten berry.
Tweak: Male Seamsters have had their dress replaced with an arming jacket. This also applies to Seamster pilgrim which also spawns with a leather coat instead of a fur one.
Tweak: Padded Dress has had it's default color restored to normalcy.
Tweak: Replaced the locks on the Seamster Workshop and the fireplace with an Oven
Tweak: Replaced the shirts on the Seamster Workshop to ones that would spawn without ripped sleeves
Balance: Due to the above change, and since players are already used to the salvaging mechanic, Seamsters no longer spawn with fabric and cloth in their satchel.
Balance: Removed farming skill from Seamstress. Same why I wouldn't want people to do a Seamsters job I don't want Seamsters doing someone elses!
Balance: Changed some Seamster pilgrim skills, mainly reducing sewing by 1 but increasing tanning, crafting, knifes and overall give it stats that are slightly more combat focused. This is barely noticeable however. This was done to make them feel distinct enough to be played outside of the Town reliably.
Code: Removed references to "Tailor" in code. This applies only to strings and defines, not names or descriptions (As well as the Tailor.dm file).
Code: Added a helpful var descriptor to spells.dm

### CODE REVIEW

**Comment by radarseas** [comment]
finally, seamster as it always should have been, an actual seperate job as important as it should be respected and that you can see on the lobby instead of praying some townie goes seamster.

**blessed PR.**

**Comment by Nakalon** [comment]
Oups im fixing pilgrams

**Comment by Simply-Sydney** [comment]
I love everything about this, cant wait to see Seelie seamstresses!

**Comment by Nakalon** [comment]
> im gonna comb it for changes and otherwise I will merge this even tho I dislike anything that is nice to seelies.

Thank you! I'm making some changes to sewing in another PR to make it easier for non seamstress folks, just so you know!

**Comment by Nakalon** [comment]
> code checks from a skim I can merge but. I think it would be funnier that instead of a rotten berry its a poison one. with no chat feedback to tell if it is or isnt. so on round start till ya know which is which is a gamble. both still do dying so. poison or rotten either one tho still fine to do a merge.

So you want, good berry, poison berry. Or rotten berry poison berry?

If the first one i'd have to add something ambiguous to the text so people don't just die by trying to injest it or think the main reason for it is to have food! (The good berry was just a bonus hehe)

**Comment by Nakalon** [comment]
> > thats the point, good berry or poison one RNG, so if they do a dumb and use it for food theres a chance they die.
> 
> fuck didnt mean to edit that ment to respond to it WITH that.

Yeah! I underatand, but I'd change the phrase to be like "summons a berry of dubious quality" or "summons a really funky berry..." or somehting alike in both instances! I don't usually like to add obscure features that don't give players who don't codedive or check wikis any feedback.

Would you be okay with that change?

**Pull request merged**
