### PR TITLE
Reworked guild smith workplace

### PR DESCRIPTION
**Pull request by SayonaraEcho**
## About The Pull Request

Replaced: workstations were moved closer to the counters, reworked some places like old mason room. Deleted some walls.

Replaced: back doors were replaced with reinforced ones

image

image

image

Added leather gloves to smiths. How can they forge if they're holding tongs with their bare hands? :clueless:

## Why It's Good For The Game

Better workstations for blacksmiths, optimization for their work, QoL.
It's a temporary solution for guild smith. There will be new guild smith house soon

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
Oh, a bit too spacious right now 
And I will also rework this area in the town revamp I am just busy with druids right now
But I can give this area for you to revamp if you want, like let's separate the whole thing into different island on the rock with three buidlings on it for smithery, living-meeting area, other guild folk?

**Comment by wow50000** [comment]
image
Could you do it from top to bottom 
water bin
anvil
forge
 ?

**Comment by Elli-Skala** [comment]
You may want to remove the stock pile if you're making it fully private. They already have a vori, and a stock pile makes it redundant.

**Comment by wow50000** [comment]
> > image Could you do it from top to bottom water bin anvil forge ?
> 
> Look at the PR, not comment screens

image

**Comment by wow50000** [comment]
this sort of alleviates the issue of having to walk to another room to get bars but its better at least.

**Comment by Purpleturtle3** [comment]
Can you add a heat treatment furnace to the guild smithy? No one ever makes those, and it makes sense that the guild smithy of all places could have it. (It allows you to "dye" armor).

**Pull request closed without merging**
