### PR TITLE
Proper Race List Refactor

### PR DESCRIPTION
**Pull request by AukariBunn**
## Refactors
* Every race in game was elevated to `RACES_RESPECTED` except humen. 
* Humen was moved to `RACES_VERY_SHUNNED`.

This update encourages actual racism roleplaying which benefits people's experience, as well as the game's immersion.
If you're affected by this update and have humen characters: just play another race idk, its not that much of a big deal. You also have refugees to play.

### CODE REVIEW

**Comment by Githubaccount222** [comment]
catch snowflake humen mains complaining about this
watch this not be merged because a certain coder hates u

**Comment by AukariBunn** [comment]
Returned the shunned and tolerated races list cuz them not existing breaks the game.

**Comment by AukariBunn** [comment]
> catch snowflake humen mains complaining about this watch this not be merged because a certain coder hates u

Yep. I mean there now there's just 1 shunned race out of 20. I admit this needed change would have felt much better or wouldnt have been needed at all if the humen statuses hadnt been sloppified to appease everyones snowflake character.

**Comment by AukariBunn** [comment]
> catch snowflake humen mains complaining about this watch this not be merged because a certain coder hates u

Yep. I mean there now there's just 1 shunned race out of 20. I admit this needed change would have felt much better or wouldnt have been needed at all if the humen statuses hadnt been sloppified to appease everyones snowflake character.

**Comment by Kevak** [comment]
This kitty thinks this is hilarious. +1. Humen snowflake mains can just play another race. Stop self inserting.

**Comment by AukariBunn** [comment]
Five upvotes 18 minutes after the PR was made already
People really like this update
image

**Comment by DelineFortune** [comment]
>  there's just 1 shunned race out of 20.

The best argument i have ever seen 

I love this so much

**Comment by Gyrandola** [comment]
are you looking to get git banned

**Comment by ShiningM00N** [comment]
> are you looking to get git banned

🦐-ply a difference in skill.

**Comment by Kregle** [comment]
Let's do this on tuesdays

**Pull request closed without merging**
