### PR TITLE
Fixes of updated map

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Objects in walls fixed
Missplaced areas fixed (they have their own mechanics, stop placing them in random places)
Mountain filling west of keep and east of church fixed
Reduced amount of SCOMs
Redundant bedrock moved/removed (mostly near side town-bog paths)
Redundant sewer near church reduced
Added borders to lighthouse stairs
Various other small fixes

## Why It's Good For The Game
Trust me bro

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
0) Attach screenshots next time too

1) Bring back SCOMs for private rooms in church and return red glass
2) Leave one  cave with book instead of deleting both, some people use it 
3) Don't close of sewers under church there is a dungeon spawner in there
4) Don't add lights to the tunnel above near graveyard 
5) Don't delete SCOM in merc's quarters
6) Don't close door with the banner in church main area
7) Don't add more palisades to the soilery

**Comment by Heheniy** [comment]
1. red glass will not be returned in is literally mark of zizo
2. there was THREE book spots
image
3. they were reduced with the spawner taken into account
4. what light

**Comment by NikolayByondPlayer** [comment]
> 1. red glass will not be returned in is literally mark of zizo
> 2. there was THREE book spots
>    image
> 3. they were reduced with the spawner taken into account
> 4. what light

1 - It is only in your head and in the name file. It is just red glass. we can make a room with different vibes.
2- Save one of these caves
3 - Okay, let's still leave it as it is one cave
4 - The one that goes down one z level

**Comment by Heheniy** [comment]
you are literally blind if you think they are same
image

**Comment by NikolayByondPlayer** [comment]
> you are literally blind if you think they are same image

Red glass

**Comment by NikolayByondPlayer** [comment]
Besides assets is not used at all - we better use it

**Pull request closed without merging**
