### PR TITLE
Removes maniac roll, doubles bandit roll chance

### PR DESCRIPTION
**Pull request by Useroth**
'nuff said

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
sad day for maniacjaks

**Comment by Hmeister-real** [comment]
every round bandits sounds like Abysmal Dogshit, and Maniac should NOT be removed untill we at the very least get two new antags to fill in, we have so little in the first place

**Comment by MickDick1** [comment]
Personally I think bandits being more prolific is a good thing quite a few reasons.
Maniac being disabled until you guys figure out how to not fuck them over mid game is for the best. Or overhaul them according to how you want them to really play.

**Comment by DorfGuy1** [comment]
i Still have no idea what maniac does, please don't trash can them until I figure it out.

**Comment by kepesk1** [comment]
this PR is horrible. i hate maniac but i hate the theoretical max of 34 bandits even more, it's so hard to play in the bog now

**Pull request merged**
