### PR TITLE
Fixed magemote again (as well as like 20 lighting dependencies)

### PR DESCRIPTION
**Pull request by Kevak**
## About The Pull Request

Fixes magemote and several other lighting and sprite dependencies by partially reverting a file that was deleted in cleanup 3. Why are we deleting so much shit? It doesn't actually impact performance whatsoever. The server load of leaving the unused systems in is negligible and deleting stuff orphans a shitload of dependencies (causing wanton laggy runtimes) and nullsprite icons. SS13code is spaghetti, deleting anything risks fucking up other stuff, just cuz it compiles doesn't mean you didn't break like fifty things. This isn't java where having a large texture repository causes slowdown, this is byond, which has extremely efficient sprite caching. Additionally, why not just comment out undesired things instead of mass-deletions? There is a reason codebases like TG comment out unused shit instead of deletion. Comments are skipped during codeparsing wholecloth, not only is the load negligible, it is _nonexistent._

## Why It's Good For The Game

Fixing shit is good. **Do Not Delete This File Again Please. Several Important Dependencies Rely On It.**

## Proof Of Fix

https://github.com/user-attachments/assets/c44eba06-7ab9-4bba-97ec-551bfe630eb0

### CODE REVIEW

**Comment by Gyrandola** [comment]
Im fairly sure the rest of the lavaland stuff can still be axed

**Comment by Kevak** [comment]
> Im fairly sure the rest of the lavaland stuff can still be axed

Tentative "Maybe." Test before doing. Lavaland touches a lotta stuff in the code.

**Comment by Gyrandola** [comment]
Will merge when you remove the stuff thats not actually needed...

**Comment by Kevak** [comment]
I’ll give it a go-over when I roll outta bed.

**Comment by Kevak** [comment]
Trimmed it down to the bare essentials. No I don't know why TG routed several lighting alpha dependencies through the wisp lantern procset instead of sticking it in the lighting code. No I don't know why moving it to another file makes the code start screaming on compile. It probably needs a proper refactor but that's beyond the purview of this bugfix.

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
