### PR TITLE
Adds Seelie Bathwenches!

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

Allows Seelies to be bathwenches, with their only difference being that they get Breyettes to protect their vulnerable holes.

## Why It's Good For The Game

Fully tested and functional
Capture

image

### CODE REVIEW

**Comment by Gyrandola** [comment]
seelies literally die from sex

**Comment by Hmeister-real** [comment]
> seelies literally die from sex

That's why they get breyettes, so they can't get ass fucked and die. They can still do bodyjobs and other ERP acts though

**Comment by Simply-Sydney** [comment]
Id made a vote on this a while back, there was a lot of people who did not want it. 
Was going to include it with my PR that added Hand and Maid but it didnt seem like a good idea to do so, Im still not sure it is

**Comment by 2PlainGhoul** [comment]
Weird Fetish Add-on

**Comment by Gyrandola** [comment]
Yeah I don't know about this one. I have the feeling it's just a meme pr

**Pull request closed without merging**
