### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Replaced bones at south-west bog mine with proper ones, that can be passed
Fixes double closet at hand's room
Fixed torches inside walls where i managed to find them
Added lights to admin test area
Moved shylock near smiths to be between peddlers
Added shylock near merchant shop
Made merchant's goldface look less out of place
Standartized stone keep walls on 1st floor
Added light to dark areas in town
Added second key chest to steward and separated non-keep keys into it
Fixed some areas and caves (ie replaced all "indoor" areas in terrorbog with just "bog" because of how "indoor" works (blocking sky even withut roof), highground at eastern town near church in not "roofs" but just town "outdoors", fixed mountain areas like on screenshot below, etc)
image

Expanded deepcaves
image

No more easy access to vault from river
image

Farmhouse door starts unlocked (if there any farmers spawned they can lock it, if not- no need to break in to get tools for farming)
Various small tweaks around basin and terrorbog

### CODE REVIEW

**Comment by CalamaBanana** [comment]
You accidentally left the massive tree removal in that no one wanted, you only removed the mention of it in the description of the PR.

**Comment by Heheniy** [comment]
> You accidentally left the massive tree removal in that no one wanted, you only removed the mention of it in the description of the PR.

It was not removal but reshuffle in palces like this where trees were almost fully blocking entrance to the building
image
Same here 
image
Here trees were growing in the road
image
And simmilar things

**Comment by Heheniy** [comment]
@Gyrandola added screenshots

**Comment by CalamaBanana** [comment]
> > You accidentally left the massive tree removal in that no one wanted, you only removed the mention of it in the description of the PR.
> 
> It was not removal but reshuffle in places like this where trees were almost fully blocking entrance to the building

We can see the map changes with the MapDiffBot2 in the checks tab. This is nearly the same Tree-Wall removal PR that was closed shortly before you reopened it here to try to sneak it in without mentioning it.

Diff from old PR: ( https://github.com/Rotwood-Vale/Ratwood-Keep/pull/947#issuecomment-2408934020 )

image


Diff from new PR:

image

**Comment by Heheniy** [comment]
@Moribun fixed

**Pull request closed without merging**
