### PR TITLE
Disables Amazon, allows females to roll Barbarian instead

### PR DESCRIPTION
**Pull request by ddsaw**
## About The Pull Request

This disables the Amazon adventurer class(via CTAG), and instead enables females to become barbarians. 

## Why It's Good For The Game

Amazons were a jank artefact of the genderlocked roles of BlackStone.
They had no notable distinctions from barbarian to justify it's own class and if the Sorceress ought be removed then so should Amazon.
The only notable things about the Amazon was the Chain Bikini (rip truly a sad loss) and the fact that they spawned with 5 polearms sometimes (very unbalanced and not intended behavior and we just didn't fix it till now.)

This improves maintainability and removes an unneeded distinction, and if we truly want what (extremely limited) amazon had we can just make it a barbarian subclass instead.

Pour one out for the chainkini though, I believe it was the only way to get it..

### CODE REVIEW

**Comment by coffeecoffeecoffee** [comment]
...Can we add a way to smith the chain bikini if we're going to be axing the best role from the game?

**Comment by ddsaw** [comment]
> ...Can we add a way to smith the chain bikini if we're going to be axing the best role from the game?

Just play barb? Same stats except when you roll a broken five polearms because somebody messed up the amazon code.

I'm thinking about the chainkini. But it's a bit of a joke armor and this could lead to many wearing it?
I'll get a second opinion from Azerak.

I'd personally make it cost a steel ingot and be low difficulty, as it's statistically a less covering hauberk: steel and only covers chest and groin.

**Comment by zakanater19** [comment]
upvoted for chainkini xD

**Comment by coffeecoffeecoffee** [comment]
> > ...Can we add a way to smith the chain bikini if we're going to be axing the best role from the game?
> 
> Just play barb? Same stats except when you roll a broken five polearms because somebody messed up the amazon code.
> 
> I'm thinking about the chainkini. But it's a bit of a joke armor and this could lead to many wearing it? I'll get a second opinion from Azerak.
> 
> I'd personally make it cost a steel ingot and be low difficulty, as it's statistically a less covering hauberk: steel and only covers chest and groin.
> 
> EDIT: I've added it to Blacksmiths recipes now. Be wary that it is GENDERLOCKED. So I don't know if this is gonna go through as it's a bit sloppy imo.

No I'm JUST talking about the chainkini. That's all I want or care about. I have no problems with amazon being rolled into barbarian, I am only seconding the mourning of the chainkini except I am completely and wholly, utterly unironic about it, as I am also the brayette's only fan. Thank god we finally have a blacksmith option for the chainkini.

**Comment by Hmeister-real** [comment]
i really like amazon, lets me RP as a strong women, barbarian and amazon should be two different classes, just similar. If anything just buff Amazon or make them have something unique that the barbarian doesn't, like maybe whips and flails? -1 from me on this change

**Comment by ddsaw** [comment]
> i really like amazon, lets me RP as a strong women, barbarian and amazon should be two different classes, just similar. If anything just buff Amazon or make them have something unique that the barbarian doesn't, like maybe whips and flails? -1 from me on this change

An amazon is literally just a type of female barbarian. You can now pick a female barbarian instead and presto, you are a strong woman. Infact, you have more strength than before.

**Pull request closed without merging**
