### PR TITLE
strapless dress now covers genitals

### PR DESCRIPTION
**Pull request by Jackofashepard**
## About The Pull Request

The sprite, barely, covers everything it needs to. Now it reflect that in code

## Why It's Good For The Game

Some strapless dress wearers dont like that its somehow see through, this is for them

### CODE REVIEW

**Comment by Keazra** [comment]
Huzzah! I don't feel quite as naked! Honestly you could make it cover just the vageen and it'd be great, but this is good too.

**Comment by Red-Honk** [comment]
Make it right-clickable, like a hood/rain-cloak-visor ect, so, it dictates to expose or not expose the private bits, no doubt swaines and wenches will be happy about it, don't even worry about respiriting it, folk can use their imagination afterall.

**Comment by Jackofashepard** [comment]
> Make it right-clickable, like a hood/rain-cloak-visor ect, so, it dictates to expose or not expose the private bits, no doubt swaines and wenches will be happy about it, don't even worry about respiriting it, folk can use their imagination afterall.

Cool idea but I'd really rather not make it a "imagination" thing. If someone sprites it I'll go for it

**Comment by ikrarkjr** [comment]
This is literally never going to be merged, this is the express reason for strapless dress existing, lol.

**Comment by Cyprex** [comment]
Nah, only as a right-clickable thing

**Comment by Cyprex** [comment]
ping us to reopen if you make it rightclickable

**Pull request closed without merging**
