### PR TITLE
Adds Priest and Templar combat track

### PR DESCRIPTION
**Pull request by ChocoboLord**
## About The Pull Request
Adds a combat track to Priest and Templar - the Pathologic Classic main theme (https://www.youtube.com/watch?v=lieYIg7DCqU)

## Why It's Good For The Game
I know not every class needs their own combat music, but I feel like the clergy at least needs one track to differentiate themselves. I think the theme fits, with the chanting and the organ-esque stings.

### CODE REVIEW

**Comment by radarseas** [comment]
any chance of slapping it onto wandering paladins and battle-clerics? I feel they should get some part in the combat tunes, being battle-clergy of their own gods.

**Comment by ChocoboLord** [comment]
Yeah, sure, I didn't consider that at first :P

**Comment by Frienderanian** [comment]
I know you are probably set on this, but I was at work today and thought that "Holy Orders (Be Just or Be Dead)" from Guilty Gear X2 would be so fucking good as a battle theme for the Priest/Church/Clergy. https://www.youtube.com/watch?v=rGetImTgyFA
You beat me to this by like 3 days 😭

**Comment by Inveldy** [comment]
> I know you are probably set on this, but I was at work today and thought that "Holy Orders (Be Just or Be Dead)" from Guilty Gear X2 would be so fucking good as a battle theme for the Priest/Church/Clergy. https://www.youtube.com/watch?v=rGetImTgyFA You beat me to this by like 3 days 😭

Waaaaaaaaaay too intense. Does not fit the style of tracks that Ratwood uses.

**Comment by Frienderanian** [comment]
> > I know you are probably set on this, but I was at work today and thought that "Holy Orders (Be Just or Be Dead)" from Guilty Gear X2 would be so fucking good as a battle theme for the Priest/Church/Clergy. https://www.youtube.com/watch?v=rGetImTgyFA You beat me to this by like 3 days 😭
> 
> Waaaaaaaaaay too intense. Does not fit the style of tracks that Ratwood uses.

Go listen to the bandit combat music then tell me my choice is way too intense LOL The bandit combat music is INSTANTLY assaulting your fucking ears like you're a raving fucking lunatic sprinting through a crowded subway station killing everyone with a knife.

**Comment by ChocoboLord** [comment]
I think the track I have right now suits it well enough - also, clerics and paladins will now hear the clergy combat track.

**Comment by ChungusGamer666** [comment]
> I know you are probably set on this, but I was at work today and thought that "Holy Orders (Be Just or Be Dead)" from Guilty Gear X2 would be so fucking good as a battle theme for the Priest/Church/Clergy. https://www.youtube.com/watch?v=rGetImTgyFA You beat me to this by like 3 days 😭

This sucks ass I hate weebs so god damn much

**Pull request merged**
