### PR TITLE
Cavemanmax (nudist buff)

### PR DESCRIPTION
**Pull request by usernameasterisk**
## About The Pull Request
Major nudist buff after severe nerfs. Makes nudist barbarian but without weapon skills and ability to wear clothes.
- buff: unarmed skill 4 -> 6;
- buff: wrestling skill 4 -> 5;
- buff: strength stat 2 -> 4;
- buff: constitution stat 1 -> 3;
- buff: athletics skill 0 -> 4;
- buff: farming, cooking, fishing and butchering skills 0 -> 1;
- buff: nudist can't be pain stunned now;
- buff: critical wounds don't apply to nudist, only regular;
- buff: nudist can eat bad berries and drink murky water;

- nerf: crafting skill 4 -> 2;
- nerf: knives skill 2 -> 0.

## Why It's Good For The Game
Yeah, so nudist was broken when it was added to Blackstone due to following reasons:
- Strength was very preferable stat to minmax into. It is still great, but it's damage multiplier was nerfed.
- They were able to wear armor and clothes despite, you know, nudism.
- They were able to easily train their weapons skills from zero to hero, keeping the untrainable unarmed skills and high strength stat. Training was nerfed.
- Wrestling was balanced differently. Now you can't instantly win just because you have high strengh. Also, most combat roles have high wrestling (bog guards and bandits, for example, have their wrestling 4, that's only 1 point lower than nudist's wrestling in this buff pr).
- There was no grab CD.
- You were not able to dodge grabs without CD on defend intent.
- Two simple words "zombie nudist" were able to strike fear even in knight's heart. Zombies are nerfed now.
- Stones (secondary nudist's weapon right after their own fists) were batshit insane with 18 melee (now 10) and 20 throw (now 15) damage.
- Knockouts happening from unarmed strikes were twice as long.

Right now playing nudist feels like this: you are trying to grab/punch a man, man dodges and crits your chest with a hunting knife, 1 minute later you are bled to death, because armor decides a lot of things in this game. Stat and skill wise current nudist can be described as "bog guard but without weapon skills, also braindead (low int) and without ability to wear any clothes and armor". I mean, even a bandit got +3 STR, why must a literal angry caveman be weaker than a bandit?
Also, there are no underwear on this server, so beating the living shit out of a nudist because they are nude can be quite valid reason.

### CODE REVIEW

**Comment by usernameasterisk** [comment]
> You've made them stronger than even the OG blackstone nudists, which were broken beyond belief due to how strong and uncounterable grabs are in this combat system.
> 
> Plus pain resistance and soft crit immunity? You have no idea what you're unleashing on this server.

Already mentioned that grabs were rebalanced, so they are now quite counterable unless you are female elf towner with 6 STR and 2 wrestling standing against bog guard with 12 STR and 4 wrestling. And still, you can dodge without CD at defend intent and just walk away to replenish stamina.
Also TRAIT_NOPAINSTUN does not grant pain resistance. You still can feel pain, you can't be completely stunned by it.
Also TRAIT_CRITICAL_RESISTANCE is not similar to TRAIT_NOSOFTCRIT. It grants you resistance to critical strikes, not to softcrit state.

**Comment by usernameasterisk** [comment]
> > > You've made them stronger than even the OG blackstone nudists, which were broken beyond belief due to how strong and uncounterable grabs are in this combat system.
> > > Plus pain resistance and soft crit immunity? You have no idea what you're unleashing on this server.
> > 
> > 
> > Already mentioned that grabs were rebalanced, so they are now quite counterable unless you are female elf towner with 6 STR and 2 wrestling standing against bog guard with 12 STR and 4 wrestling. And still, you can dodge without CD at defend intent and just walk away to replenish stamina. Said bog guard will counter nudist just by pressing resist couple of times, because he is weaker then nudist only in 1 wrestling skill point and 2 STR stat points. Also TRAIT_NOPAINSTUN does not grant pain resistance. You still can feel pain, you can't be completely stunned by it. Also TRAIT_CRITICAL_RESISTANCE is not similar to TRAIT_NOSOFTCRIT. It grants you resistance to critical strikes, not to softcrit state.
> 
> I guess we will see.

Yeah, I guess it can be TMed to see if it will make shitters numbers raise.

**Comment by pismorizzo** [comment]
Important to remember this is a supposed to be a _challenge_ role offered to every single Pilgrim. Some random common deranged naked man being a master wrestler and stronger than trained mercs is a little insane. I’d say just lower the strength back and just a little less wrestling skill and it won’t be too much.

**Comment by usernameasterisk** [comment]
> Important to remember this is a supposed to be a _challenge_ role offered to every single Pilgrim. Some random common deranged naked man being a master wrestler and stronger than trained mercs is a little insane. I’d say just lower the strength back and just a little less wrestling skill and it won’t be too much.

Trained mercs get weapons skills. You can't just train your weapons skills from zero to absurdly hight levels anymore. Wresling and fist-fist fighting are your only weapons. Also, nudists can't wear armor. By "can't" I mean you just can't put it into a slot. They are probably way too buff to fit into normal clothing.

**Comment by pismorizzo** [comment]
> > Important to remember this is a supposed to be a _challenge_ role offered to every single Pilgrim. Some random common deranged naked man being a master wrestler and stronger than trained mercs is a little insane. I’d say just lower the strength back and just a little less wrestling skill and it won’t be too much.
> 
> Trained mercs get weapons skills. You can't just train your weapons skills from zero to absurdly hight levels anymore. Wresling and fist-fighting are your only weapons. Also, nudists can't wear armor. By "can't" I mean you just can't put it into a slot. They are probably way too buff to fit into normal clothing.

I meant they are stronger than trained mercs as in that they get +4 strength to a mercs 2 or 3. Wrestling is still very strong even after the nerfs, it’s basically just a stat check with no counter play at all once they get you on the ground and give you the resist debuff for being grounded. Master Wrestling and guaranteed +4 strength BEFORE racial stats means a return to random nudist Pilgrim challenge role has a very serious chance to be beating castle guards as in as they just stomp them in a stat check.

If nudist was its own limited slot role I wouldn’t mind, but it isn’t it’s a very common role for infinite slot pilgrims. They don’t need to be master wrestlers in the funny challenge role while no other pilgrim gets much combat skills at all, any jerk can die as it and then respawn in 10 mins to get another go.

**Comment by usernameasterisk** [comment]
> > > Important to remember this is a supposed to be a _challenge_ role offered to every single Pilgrim. Some random common deranged naked man being a master wrestler and stronger than trained mercs is a little insane. I’d say just lower the strength back and just a little less wrestling skill and it won’t be too much.
> > 
> > 
> > Trained mercs get weapons skills. You can't just train your weapons skills from zero to absurdly hight levels anymore. Wresling and fist-fighting are your only weapons. Also, nudists can't wear armor. By "can't" I mean you just can't put it into a slot. They are probably way too buff to fit into normal clothing.
> 
> I meant they are stronger than trained mercs as in that they get +4 strength to a mercs 2 or 3. Wrestling is still very strong even after the nerfs, it’s basically just a stat check with no counter play at all once they get you on the ground and give you the resist debuff for being grounded. Master Wrestling and guaranteed +4 strength BEFORE racial stats means a return to random nudist Pilgrim challenge role has a very serious chance to be beating castle guards as in as they just stomp them in a stat check.
> 
> If nudist was its own limited slot role I wouldn’t mind, but it isn’t it’s a very common role for infinite slot pilgrims. They don’t need to be master wrestlers in the funny challenge role while no other pilgrim gets much combat skills at all, any jerk can die as it and then respawn in 10 mins to get another go.

You should try, like, attacking a nudist. With a weapon. Maybe even on swift intent to leave more bleeding wounds on unarmored body, but it is so advanced play. And you should not try to wrestle them, knowing that they are very good at it. It's simple. I mean, they are nude, so you do know  when a NUDIST tries to assault you. Use your mind and don't try to wrestle down a nudist, strike down a dodging rogue with strong intent or threat a mage in chains, but with open mouth.

**Comment by Useroth** [comment]
Nudist is meant to be a "challenge" class, not something viable.

**Comment by usernameasterisk** [comment]
> Nudist is meant to be a "challenge" class, not something viable.

can i make "caveman" class?

**Pull request closed without merging**
