### PR TITLE
FINALLY, a half orc nerf

### PR DESCRIPTION
**Pull request by GuppyLaxx**
This PR bumps down the ridiculous base stats that Half Orcs have, while still giving them a clear positive.

While this bumps down the difference in half orcs and other races, it's at this point a clear thing that is necessary. Half Orcs are full of shitters and the fact it is OBJECTIVELY THE BEST COMBAT RACE gives a clear reason why. It's awful, and the scales are tipped way too in favor of half orcs 90% of the time.

They've gone from 
+2 STR, + 2 CON, +1 END, -2 INT, -2 SPD
to
+1 STR, +1 CON, +1 END, -1 INT, -1 SPD
with this PR.

### CODE REVIEW

**Comment by wow50000** [comment]
seen half orcs get bodied again and again, play the game nimrod

**Comment by 2PlainGhoul** [comment]
Shitty way to handle the problem

**Comment by radarseas** [comment]
as someone that deals with clerics, mace powergaming and the likes... this is... a non problem, you're slow, you have low int so you get fiented super easy.

You're pretty slow too to boot, you can easily outrun orcs, when your stamina dies, they're also shunned anyway.

**Comment by Genevesh** [comment]
Probably one of the worst salt-prs yet; I've only ever seen orcs win when they had a clear advantage in number, or when it was done as a combat role against a noncombatant.

To top it off, there are plans to punish super low int, and there already are some - namely, vamp's sleep ability that has higher chances the weaker the target's mind is.

In short summary, PLAY THE GAME, NIMROD

**Comment by Takoros** [comment]
How this is test merged so quickly (even with having 7 downvotes) when some PR's that are positive in votes are not test merged since weeks

**Comment by Red-Honk** [comment]
This is a shit PR, you can just outrun the beggas, they sure, hit a tad harder but they also swing slower, have really bad dodge chance, have a funny accent, and folk are usually specist to them, this is a terrible PR overall.

**Comment by Takoros** [comment]
> > How this is test merged so quickly (even with having 7 downvotes) when some PR's that are positive in votes are not test merged since weeks
> 
> I used a favor and phoned in a friend. I will now test merge a PR that makes your PQ -999

Ah i see, and cool, i would be the first ! lol

**Comment by MickDick1** [comment]
It is not objectively the best combat race.
It's just the statline that takes the least amount of effort to be effective with.

Speed users picking roles with dodge expert beat everything else and fully counter the horc statline and classes.

**Comment by zakanater19** [comment]
Screenshot 2024-08-19 145027

**Comment by Mogurk** [comment]
ban this person form ever making a pq

**Comment by pilotmans** [comment]
The issue with orc is that they are not roleplay minded, stunted speech is rather damming to that goal, there are better ways to go about the fact that most orc players are shitters.

**Comment by wow50000** [comment]
may want to re add gender differences for half orcs if you havent already

**Comment by DorfGuy1** [comment]
Half orc village is still pretty good rp though. Good secondary antagonist. Maybe make full orcs, fuck up the speach even more, and make it a wanderer spawn

**Comment by Jackofashepard** [comment]
Great PR, well done

**Comment by Cyprex** [comment]
> Half Orcs are full of shitters 

This is obviously a salt PR, by the authors own admission. See also the screenshots above of them not even playing the game, supposedly- why is this PR being seriously considered?

**Comment by pilotmans** [comment]
> > Half Orcs are full of shitters
> 
> This is obviously a salt PR, by the authors own admission. See also the screenshots above of them not even playing the game, supposedly- why is this PR being seriously considered?

cause orcs do need a nerf, but it's not cause it's the best species, it's because the certain traits of the species helps discourage roleplay such as stunted speech and high strength, whilst i think change should be incurred, i'm not sure this pr is the best way to go about it.

**Comment by HissyNays** [comment]
> > > Half Orcs are full of shitters
> > 
> > 
> > This is obviously a salt PR, by the authors own admission. See also the screenshots above of them not even playing the game, supposedly- why is this PR being seriously considered?
> 
> cause orcs do need a nerf, but it's not cause it's the best species, it's because the certain traits of the species helps discourage roleplay such as stunted speech and high strength, whilst i think change should be incurred, i'm not sure this pr is the best way to go about it.

I've had some of the best roleplay happen with orcs, including because they were intimidating due to being far stronger. Stats or traits cannot discourage roleplay, thats stupid.
Orcs need to stay unnerfed, they have other downsides that keep them in line.

**Comment by pilotmans** [comment]
> > > > Half Orcs are full of shitters
> 
> > > 
> 
> > > 
> 
> > > This is obviously a salt PR, by the authors own admission. See also the screenshots above of them not even playing the game, supposedly- why is this PR being seriously considered?
> 
> > 
> 
> > cause orcs do need a nerf, but it's not cause it's the best species, it's because the certain traits of the species helps discourage roleplay such as stunted speech and high strength, whilst i think change should be incurred, i'm not sure this pr is the best way to go about it.
> 
> 
> 
> I've had some of the best roleplay happen with orcs, including because they were intimidating due to being far stronger. Stats or traits cannot discourage roleplay, thats stupid.
> 
> Orcs need to stay unnerfed, they have other downsides that keep them in line.

The issue comes with orcs
That don't roleplay well at all, which this pr probably wouldn't fix.

**Comment by zakanater19** [comment]
> > > > > Half Orcs are full of shitters
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > This is obviously a salt PR, by the authors own admission. See also the screenshots above of them not even playing the game, supposedly- why is this PR being seriously considered?
> > 
> > 
> > > 
> > 
> > 
> > > cause orcs do need a nerf, but it's not cause it's the best species, it's because the certain traits of the species helps discourage roleplay such as stunted speech and high strength, whilst i think change should be incurred, i'm not sure this pr is the best way to go about it.
> > 
> > 
> > I've had some of the best roleplay happen with orcs, including because they were intimidating due to being far stronger. Stats or traits cannot discourage roleplay, thats stupid.
> > Orcs need to stay unnerfed, they have other downsides that keep them in line.
> 
> The issue comes with orcs That don't roleplay well at all, which this pr probably wouldn't fix.

so why make your first argument

**Comment by pilotmans** [comment]
> > The issue comes with orcs That don't roleplay well at all, which this pr probably wouldn't fix.
> 
> 
> 
> so why make your first argument

Maybe I didn't emphasize it enough but I did say "I think there are better ways to go about this."

I believe something should change I just don't think this is the proper way of doing it.

**Comment by pilotmans** [comment]
> > > The issue comes with orcs That don't roleplay well at all, which this pr probably wouldn't fix.
> > 
> > 
> > 
> > so why make your first argument
> 
> Maybe I didn't emphasize it enough but I did say "I think there are better ways to go about this."
> 
> I believe something should change I just don't think this is the proper way of doing it.

That and the fact that I agree with the reason but not the method, which means I am as close to unbiased to this nerf and if I think it's shit well that probably means it really isn't great even if there is an issue that actually needs to be fixed.

**Comment by lalaria1** [comment]
Can you please change your PR so it's +4 STR, +5 CON, +3 END, -3 INT, -3 SPD

**Pull request closed without merging**
