### PR TITLE
Families

### PR DESCRIPTION
**Pull request by Gyrandola**
family system from penumbra all credits to them.

Family System that allows characters to be part of round-start, randomized families.
A character can select their preferred race for a partner.
Homosexual families cannot happen.
The royal family is always forced.

Heavily WIP, might break or not work as intended etc.

Proof of test:
image

### CODE REVIEW

**Comment by ophaq** [comment]
[https://media2.giphy.com/media/4ZkAeUWFF9ZGRXE7Ud/200.gif?cid=6c09b95225azs3d1zqu7pyhsqlp619672mqmi14pgoo7fl10&ep=v1_gifs_search&rid=200.gif&ct=g](url)

**Comment by Gyrandola** [comment]
> It's about time. :O

its a decent foundation but it doesnt excite me. It lacks the possibility to write your own family name or choose your family members, although the latter could be by design.

**Comment by NikolayByondPlayer** [comment]
DAMN YES

**Comment by NikolayByondPlayer** [comment]
> > It's about time. :O
> 
> its a decent foundation but it doesnt excite me. It lacks the possibility to write your own family name or choose your family members, although the latter could be by design.

Random things are best

**Comment by Purpleturtle3** [comment]
Why did you disable roundstart same sex marriage when it's already a thing in game?

**Comment by Heheniy** [comment]
no roundstart gay marriage is boo

also it fucks up regular marriage

**Comment by radarseas** [comment]
yeah I'd let people pick their prefered partner's gender with randomised families, _save for the royals/court nobles, for immersion sake._ Its already an option ICly.

**Comment by Gyrandola** [comment]
We wont have round start gay marriages I've already discussed it with Useroth as well.
As for mechanically marrying people, it should work for all kinds of couples. If it doesn't ill try to fix it.
As for choosing your spouse? I'm not against it, but I'm also not interested in coding it.

**Comment by Gyrandola** [comment]
image
image

Both straight and gay mid-round marriages seem to be working fine.

**Review by EvenInDeathIStillServe — APPROVED** [review]

**Pull request merged**
