### PR TITLE
Halforc (Appearance) Buff

### PR DESCRIPTION
**Pull request by BladeburstNINJA**
## About The Pull Request

Adds more goblinoid ears and tusks to halforcs, as well as touches up the body sprite so that they're more recognizable as half orcs and not just off-color humans.

## Why It's Good For The Game

Makes half orcs actually distinct in terms of visuals instead of being easily confused for other species.

image

image

image

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
might as well pr upstream even if we dont use half orcs

**Comment by Gyrandola** [comment]
cool stuff

**Comment by BladeburstNINJA** [comment]
> please credit other people's sprites if you're going to use them

Only sprite that's not original is the mt_muscular sprite. Which was kind of just sitting in Stonekeep icon files unused. Everything else I made myself.

**Comment by BladeburstNINJA** [comment]
> Also heads up make branches before working on a PR, dont work off your `main`

Branches are kind of weird to me, but yea, for next time. Should be good to go now?

**Pull request merged**
