### PR TITLE
Tent cost increase

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Increases resource cost of tent wall/door

## Why It's Good For The Game
Considering you neer only 1 lvl of crafting to make this and no climbing skill to climb, it is currently too cheap and often is being used for different cheases

### CODE REVIEW

**Comment by Nakalon** [comment]
heres an idea: add skill level needed to climb?

**Comment by awawaawawaawa** [comment]
> heres an idea: add skill level needed to climb?

You need a low skill level in climbing to climb tentwalls anyway. Its not zero like he's implying.

**Comment by MickDick1** [comment]
Still. Climbing a tent wall shouldn't be possible in the first place.

Make it legendary. Problem solved.

**Comment by Gyrandola** [comment]
Honestly good PRs because how the fuck do you climb a tent, let alone a medieval one

**Pull request closed without merging**
