### PR TITLE
Rebalance Village Elder

### PR DESCRIPTION
**Pull request by ikrarkjr**
## About The Pull Request

Makes the old man wise, and TRULY an old man, easily able to be killed, and the frailest role. Being a bog guard for half a century has maimed his body to hell and back. His speed is now very average, for the sake of the game not being extremely unfun, as very snail walking speed does to players.

## Why It's Good For The Game

Absolutely no one plays the role EVER because it feels so dogshit to play. Now it doesn't. At all.

### CODE REVIEW

**Comment by ikrarkjr** [comment]
> he really doesnt need legendary combat skills, no matter his stats. He's _not_ a veteran.

He's a veteran bog guard.

**Comment by Elli-Skala** [comment]
Honestly making them a vet and giving the bog guard a good reason to go interact with the village is good. How ever I feel like the non combat roles are over tuned as it makes the village elder kind of just a better mason

Also legendary rider is very very strong which not any normal roles have

**Comment by ikrarkjr** [comment]
> Honestly making them a vet and giving the bog guard a good reason to go interact with the village is good. How ever I feel like the non combat roles are over tuned as it makes the village elder kind of just a better mason
> 
> Also legendary rider is very very strong which not any normal roles have

I was told by a coder riding skill only affects mount and dismount speed. Apparently that was blatantly false!

**Comment by MefAnneFeminene** [comment]
Village Elder was fine as he was. He doesn't need rebalancing. His combat ability is already meh. If you're just gonna tank his stats and making him a frail old man, then take away the weapons he starts with or just give him armor or something. The Village Elder does not need these useless changes that's only gonna drive more people away from this criminally underplayed role.

**Comment by ikrarkjr** [comment]
> Village Elder was fine as he was. He doesn't need rebalancing. His combat ability is already meh. If you're just gonna tank his stats and making him a frail old man, then take away the weapons he starts with or just give him armor or something. The Village Elder does not need these useless changes that's only gonna drive more people away from this criminally underplayed role.

You clearly didn't read the rest. Everything on him is buffed except a huge drop in constitution, and one point in strength. His speed, skills, are both vastly buffed. What you say is absolutely not the case at all. No one will play a role just because it's combat ability is lopsided, but everything else is extremely good?

**Comment by Frienderanian** [comment]
I love village elders when I play Soilson! I think a lot of people don't play Village Elder because it requires you to be old and the playerbase wants to play young people who are single and ready to mingle LOL Unsure if any buffing or changing of stats is really gonna fix this. 
I heard suggestions of making the Village Elder a "manor lord" that maybe had an antagonist role vs the Soilsons/owned the land the work on, this would allow younger people to play the role, but it would also be very easy for the soilsons to just overpower him LOL

**Pull request closed without merging**
