### PR TITLE
House of the Ten rework

### PR DESCRIPTION
**Pull request by AukariBunn**
This is the continuation of https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1557
This must be the final major overhaul now, so now we have:

StrongDMM_N5c1KpE3RO
The first floor includes the main room, a confession room, acolytes bedrooms, infirmary, kitchen and some storagerooms.

StrongDMM_svLu54MS5u
The second floor has some training dummies, armory, an open library (design is inspired by the plague tale's cathedral), another acolyte bedroom and the priest's bedroom

StrongDMM_Zx19SIjJVl
The basement has a procession room, a cell room for people who fell from the confession room, morticians room and a whole inquisition area. The inquisition now has a whole unique area in code, also the confession key is changed with the inquisition key. The puritan key is needed to access the inquisitor's room and spare inquisition keys.

image
Also i changed the common graveyard a bit.

### CODE REVIEW

**Comment by Gyrandola** [comment]
@NikolayByondPlayer

**Comment by NikolayByondPlayer** [comment]
> @NikolayByondPlayer

Old feedback still more or less applies: https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1557#issuecomment-2472787296

**Comment by AukariBunn** [comment]
A look from the game
https://discord.com/channels/1240735983276654733/1256033101851656222/1306353507107995780

**Comment by NikolayByondPlayer** [comment]
@Gyrandola You can close this PR since the other PR is based on this one
@AukariBunn Thanks a lot for your work! I either copied some rooms from your work (like library and water altar), translated some ideas into different spaces (like secret entrance) or copied some deko. 
Big thanks for ideas and good stuff, really sorry we couldn't implement it all!

**Comment by AukariBunn** [comment]
> You can close this PR since the other PR is based on this one

We are about to test merge both to see which one would be more liked by the players, right now im working of further overhaul. Also got some inspiration from your work to tweak mine :3

**Comment by AukariBunn** [comment]
dreamseeker_2JmPyuHVB5
dreamseeker_TelVqtyXOA
dreamseeker_VpjXRN0WLw
dreamseeker_wBhAIotVw5
dreamseeker_Ts6yrrhJnz
dreamseeker_24nq8LiIUl
dreamseeker_qGtYfs783k
dreamseeker_t66m69GTja
dreamseeker_1E6B4atIA7
dreamseeker_q3MFFoxnhu
dreamseeker_GpfGEq5ioT
dreamseeker_8PxQ9W9Z2L

**Comment by DelineFortune** [comment]
revert us the pervious version of the church back please

**Comment by AukariBunn** [comment]
The newest version
image
image
image

**Comment by Gyrandola** [comment]
Closing this as per poll results. Hopefully it was a learning experience of some kind to both mappers.

**Pull request closed without merging**
