### PR TITLE
AI NPC FIX - Dungeon Revert

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

I don't know exactly why, but the entire PR breaks the AI completely. I tried ONLY reverting the zmanager changes and the fix was partial. So the entire PR must be reverted and whoever wants to add the Dungeon back must first figure out whats wrong with it.

BEFORE:
https://github.com/user-attachments/assets/7b70e4ba-f711-49fa-8d75-508a5205b72e

AFTER:
https://github.com/user-attachments/assets/56fb447e-3002-4049-a8fb-6396e219c3c6

The PR in question:
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/760

### CODE REVIEW

**Comment by radarseas** [comment]
I have a sneaky suspicion its breaking the AI _just because the place has so many active NPCs at once._

If we left the dungeon without any NPCs, _just as a test_, obviously not great for usual gameplay, I think it might just be that. Worth a testmerge PR over anyway.

If anything it probably needs spawners to place down NPCs as players go through it, _instead of having 40+ skeletons and godknows what else active at once._

**Comment by HissyNays** [comment]
Honestly just remove dungeon. 90% of the time it only serves as a looting stage for bandits. It takes more from games than gives.

**Comment by zakanater19** [comment]
yeah i also can't figure out why it busts the AI, just nuke it

**Comment by radarseas** [comment]
> Honestly just remove dungeon. 90% of the time it only serves as a looting stage for bandits. It takes more from game than gives.

then again, that.

**Pull request merged**
