### PR TITLE
No giant goblins

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Disables giant special for goblins

## Why It's Good For The Game
Stay small

### CODE REVIEW

**Comment by ophaq** [comment]
The goblins have hobgoblins now.

**Comment by NikolayByondPlayer** [comment]
but...giant goblins are cool...

**Comment by Gyrandola** [comment]
you dont even make a case for it other than "I dont like it"

**Comment by Heheniy** [comment]
> you dont even make a case for it other than "I dont like it"

all 'small' races dont have access to it, why goblins, who are 'small' too, have it?

**Pull request closed without merging**
