### PR TITLE
Nerfs the revive spell & cure rot

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Changes the revive & cure rot spells cooldown from 2 to 30 minutes

## Why It's Good For The Game

The church will now have to prioritize which will add conflict into the round

### CODE REVIEW

**Comment by zakanater19** [comment]
I would also like to add this will dramatically change the atmosphere of the game in my belief a positive way

**Comment by TheRealRatMan** [comment]
30 minutes is retarded, rounds will go quiet super fast and this is only going to further stack on the coming nerfs from the ritual update. Please reconsider coding.

**Comment by Hmeister-real** [comment]
i love this, yesterday i was a mortician and was trying to bury a deadlite soul-less kobold and two people that will remain un-named tried to fight me over the corpse, screaming "IT CAN BE REVIVED!!!!!!" and eventually one even ran to the grave, dug it up and pulled the body to the church where the kobold, missing a leg and had /no/ soul was just left to sit there after it had been cure rotted and anastasised, leaving some other actual people who needed it just sitting there dead. im tired of this "revive everyone mindset" and love the idea of death being semi-permanent, only a few people being able to be revived and allowing morticians to do their job

**Comment by Hmeister-real** [comment]
should also make cure rot 30 minutes because if someones becomes a deadlite and gets cure rotted they come back to life without anastasis

**Comment by zakanater19** [comment]
> rounds will go quiet super fast

You realize there is a respawn function right? fuck the static players

**Comment by zakanater19** [comment]
> should also make cure rot 30 minutes because if someones becomes a deadlite and gets cure rotted they come back to life without anastasis

Good point

**Comment by Red-Honk** [comment]
No, just no, shoo with this, it'll lessen roleplay opportunities this isn't good for the game, sure it makes more drama, but it does more bad than good in the big picture.

**Comment by zakanater19** [comment]
> No, just no, shoo with this, it'll lessen roleplay opportunities this isn't good for the game, sure it makes more drama, but it does more bad than good in the big picture.

You shoo me no shoo

**Comment by TheRealRatMan** [comment]
> > rounds will go quiet super fast
> 
> You realize there is a respawn function right? fuck the static players

Are you retarded? The moment a vital role is gone the round will collapse, god forbid a priest dies there is no replacement and everything starts to crumble.

**Comment by zakanater19** [comment]
> > > rounds will go quiet super fast
> > 
> > 
> > You realize there is a respawn function right? fuck the static players
> 
> Are you retarded? The moment a vital role is gone the round will collapse, god forbid a priest dies there is no replacement and everything starts to crumble.

Sounds fun

**Comment by TheRealRatMan** [comment]
> > > > rounds will go quiet super fast
> > > 
> > > 
> > > You realize there is a respawn function right? fuck the static players
> > 
> > 
> > Are you retarded? The moment a vital role is gone the round will collapse, god forbid a priest dies there is no replacement and everything starts to crumble.
> 
> Sounds fun

not when rounds are 3 hours long with no way to end them early currently, it quickly becomes a shitty version of rogue world.

**Comment by zakanater19** [comment]
> > > > > rounds will go quiet super fast
> > > > 
> > > > 
> > > > You realize there is a respawn function right? fuck the static players
> > > 
> > > 
> > > Are you retarded? The moment a vital role is gone the round will collapse, god forbid a priest dies there is no replacement and everything starts to crumble.
> > 
> > 
> > Sounds fun
> 
> not when rounds are 3 hours long with no way to end them early currently, it quickly becomes a shitty version of rogue world.

Don't die then

**Comment by TheRealRatMan** [comment]
> > > > > > rounds will go quiet super fast
> > > > > 
> > > > > 
> > > > > You realize there is a respawn function right? fuck the static players
> > > > 
> > > > 
> > > > Are you retarded? The moment a vital role is gone the round will collapse, god forbid a priest dies there is no replacement and everything starts to crumble.
> > > 
> > > 
> > > Sounds fun
> > 
> > 
> > not when rounds are 3 hours long with no way to end them early currently, it quickly becomes a shitty version of rogue world.
> 
> Don't die then

go host rogue world then.

**Comment by DeerJesus** [comment]
this doesn't add 'conflict into the round' this just deadens the game

Why does every single fucking pr you make sound like a salt pr

**Comment by zakanater19** [comment]
> this doesn't add 'conflict into the round' this just deadens the game
> 
> Why does every single fucking pr you make sound like a salt pr

Don't worry, i speak to the voices before i put PR to paper

**Comment by radarseas** [comment]
I'd keep it at a reasonable 10 minutes or less, remember that spell cooldowns apply if you accidentally MISS the tile, especally if someone keeps pulling the body.

30 minutes is just unfeasable to properly use and it'll result in a lot of interesting revival situations like werewolves, bandit captures, inmates the guard accidentally killed, headrevs pulled away, etc being just thrown to the graveyard and those roles kicked out of the round for good.

It already cuts your speed and strength stats permanently too post-revival.

**Comment by radarseas** [comment]
_plus 10 to 6 minutes even is still long enough to make hoarding bodies unfeasable for revivals unless you want a zombie infestation_, which is arguably tenfold worse than keeping important people during times of strife over random commoners and beggars.

**Comment by zakanater19** [comment]
> It already cuts your speed and strength stats permanently too post-revival.

I didn't know that, alright ill lower the time to 10 instead of 30

**Comment by Altangy** [comment]
I'm already having to deal with a 5% chance for cure rot to work.
I'm already having to deal with 6+ bodies coming in at once
I'm already having to deal with priests that barely understand how miracles work
I'm already having to deal with acolytes wandering off only to show up dead a half hour later

Ya'll need to stop having skill issues and confirm your kills instead of taking to the codebase and salt PRing because suddenly the guard you killed is alive because you left him in the street instead of cleaning up your crime scene.

**Comment by DorfGuy1** [comment]
> I'm already having to deal with a 5% chance for cure rot to work. I'm already having to deal with 6+ bodies coming in at once I'm already having to deal with priests that barely understand how miracles work I'm already having to deal with acolytes wandering off only to show up dead a half hour later
> 
> Ya'll need to stop having skill issues and confirm your kills instead of taking to the codebase and salt PRing because suddenly the guard you killed is alive because you left him in the street instead of cleaning up your crime scene.
I'm with him on this one yall.

**Pull request closed without merging**
