### PR TITLE
Med and doc (1/2 bounty) AKA I SPENT TOO LONG ON THIS

### PR DESCRIPTION
**Pull request by Luctus-Comptus**
so this isnt even going to do it justice the amount of shit in this PR. I have dreaded this moment of documenting this shit for 5 days im gonna say this first this shit is not a final product its a test. there will likely be ALOT of bugs. balance PR's and change PR's will not only be closed but you will be yelled at for not reading. its a bounty, it has specific parameters, bug-fix PR's are fine and welcome tho. 

*craftable rucksack. shitty backpack 10 slots isntead of 14. made from bag and rope

*improvised surgery tools, figure it out its rocks stick and logs. just get a pile I dont remember the numbers.

*death negative removed from revives for church revive, it had to happen because of the shit next, or no one would play them.

*clinic added to the right of keep, temp thing gonna be lore and shit with it

*doctors got a massive buff... ok not a buff an entire fucking rework will but that shit lower

*clinic roles added(under yeomen for now) , clinic doc and clinic guard. 3 each for now. independent dont let a king or priest jerk you around for who you can/cant heal enough of that shit.

*surgeries added heart and liver surgery. required to use revival and de-rot docs have. weakens the heart and gives a debuff of -3s -3c -3s. for. each. so you can get to -6 IF you rot prior to this. BUT the debuff is gone once the heart is removed and a new one put in, see. now you got a reason to do transplants.

*well alembic added compeltely reworked alch system. you now make a mortar and pestel from a log and a stick, and MMD on it with something inside it. some things are juice most are milled similar to flour now. so yes it can mill if the object has a mill result or juice if reagent results. did I mention its one fucking item now and resprited. OH and yea sprites by baron and sinner.... I need a fucking notecard system for all this shit. anyway grind stuff. turns into a powder essence. alot of these do nothing snorted but ya gonna anyway. throw essence into alembic, can do two at a time. they brew into a reagent syrum. all chems and drugs (powders) are now chem reactions. meaty syrum and (alembic'd grinded meat from mortar) and syrum of poison (powdered poison berry ran thru alembic) will make a bottle of red. rest find out on your own. or wait. I dont care. theres a book I made for it in the patch kit and scattered around to help

*town doc renamed to Local Physician and court phsycian is.....court physician I could give a fuck less for keep roles your lucky I gave them doc abbilities -spits- . alchemist and other roles of sub-type removed. they are redundant because....

*alchemy and medicine squashed into one skill. Treatment. and yes alchemy see reagents and shit still happens at level 2.
------------------------------------------------------------------------------------
now some of these fuckign reagents.

most of these are from the purity vendor

detox- purges chems and cures tox.

rejuv- basically super epi, comes in first aid kit you can buy from purity. lowers oxy lose gain, heals a tiny bit of all damage while in crit, restores some fatigue. single dose. restores blood, reduces pain doesnt heal-heal but good for emergencies when you or soemone else are about to drop. will keep you up long enough to treat

pnkballs this comes in the first aid kit nothing special. half a bottle of red in a pill with some iron for blood regain

wake-up bought from purity, baggy of 3 pills. restores a decent bit of fatigue but mostly removes sleep debuff and banks skillpoints for use later. meaning if you dont ahve time to sleep. pop one. you cannot level up that night BUT it banks the points for next night.

-----------------------------------------------------------------------------------------------------------------------

doc abbilities

all of these cost no devotion but are TOUCH targeted, meaning you have to be right next to the person

-rapid mend: reskined standard miricle heal. long 3X cooldown of standard mirical. ike over a mintue I think. good for breaks if you mend all the other shit

-stabalize: that super epi I told ya about as an abbility with a full ox damage reset. this is very important to use for heart transplants or they WILL die when you pull the heart out.

-purge: this is a fully chem and tox purge, slashes an arm artery open (again its a fucking touch attack you will have to grapple them if trying to use this in combat since its the dropdown menu type. so shush.) so reccomended to use after a rapid mend or stabalize. long... logn 5min cooldown. but it will remove instantly EVERY chem good or bad and all tox damage from target even if dead. good for OD revives

-PURITY: seals wounds, no flat out heal but. REMOVES ZOMBIE AND WEREWOLF INFECTION. if caught before it turns you into one. will hurt you does burn damage.

-tissue debridement. requires them to have the liver surgery done AND be on a bed. it will not work if neither of thos conditions are meet, they ahve to ahve the shit liver inside them and be on a bed. de-rots targets

-CPR same as above but for revive and requires shitty heart.

oh and bandages. comes in first aid kit, stacks to 3. 30% better for staunching wounds and applies 30% faster. can be crafted for 3 cloth and 1 ash

personal patch kit. rejuv, detox, pnkballs, needle, bandages, candle. meds are single dose. good for a full reset basically.

surgicaly kit: tools fit in a pouch now for docs so you do not have to carry a shit ton of them now
made cauterizer self heat so it isnt fucking worthless.

there are more im certain I missed. there will be bugs... lots of them I can only test so much.... understand there is alot to this I had to hand implement some medical systems and the alch system do not be a dick and this is a BOUNTY. I get money for this thing whichs means its in beta so dont go making PR's mucking around in the code of it because I will not merge them. bug fix's are more than welcome but this is a test merge to iron out bugs before full release FOR the bounty commisioner.

### CODE REVIEW

**Comment by Squird5** [comment]
>alchemy and medicine squashed into one skill

Why? Firebombs don't make you better at fixing bones

**Comment by Squird5** [comment]
How is alchemy a bloat skill? If you're going to say that then half the fucking weapon skills are bloat skills. You can ADD MORE SHIT to Alchemy instead of just fucking deleting it!

**Comment by K4rlox** [comment]
>clinic with healing spells

im sorry but the entire concept of playing a doctor is not being able to cast miracles, what is the point of being a doctor if you can just click people to heal them?

>keep players -spits-

this line makes me feel like this PR was written and the clinic was written in the way that it is independent because the author hates the keep

that aside, if you change medicine and alchemy, you should really update the kits and gear for the jobs like physician and apotheocatry instead of making them obsolute since theres a clinic now, having a grudge over 1 or 2 king players shouldnt make you not want to update jobs you should be updating


lastly, the independent thing would not work at all

1. taxes, they have to pay them, dont care if its "free" 
2. church, clinic's existence would create conflict with the church since they are stealing their jobs
3. Independancy, theres no real reason clinic guards should have good gear or keep colored tabards at all if they are indepejdant from the keep



last note: author seems to be being a dick to players critisizing this pr with the argument "you play keep"

**Comment by hugmeorelse** [comment]
> honestly yeah alchemy should stay, we'd like to have a proper alchemy system eventually and honestly alchemy should go hand in hand with the clinic.

They're not removing alchemy. They're just having alchemy and medicine be one skill which makes sense. The main people who do alchemy are probably experienced with medicine. There's not really much of a point having it be separate.

**Comment by katsukai** [comment]
Not gonna lie but the purifying blood thing is busted AF. You can run to a knight and just cut their artery and run away, feels way too griefy.

**Pull request closed without merging**
