### PR TITLE
Sewing Rework - Part 5 - Leatherworking and Hunting

### PR DESCRIPTION
**Pull request by Nakalon**
*Before I begin, I must mention, I would rather make Butchering more interesting and important at a later date. I don't want to remove it outright and scrub it from existence. I have an idea of how it could be slightly more interesting and important but its very barebones still, so I didn't include it here.*

## About The Pull Request

Although this is part of the Sewing Rework, it has little to do with sewing directly.

This PR touches however leatherworking and the hunter role.
This PR aims solve the following problems I identified:

1 - Leather is too expensive.
Leather armour is not only weaker than its metal conterparts but also much more expensive.

2 - While the process of hunting and fighting monsters is interesting the way hides are handled could be more interesting.
Right now, hunters kill their prey, drag it into a stockpile, butcher it there, sell.

3 - There is some skill bloat on hunter.
Hunter has a lot of skills, relating to its job, where others have only 1, such as seamstress of guildsmith (now), hunter has 3.
Buthering, Skincrafting and Trap making.

Buthering and Trapmaking are extremely small and matter very little:
Buthering reduces the time it takes to butcher a creature. Only.
Trapmaking allows the player to construct a mantrap and reduce the time it takes for them to handcuff someone. Only.

These skills are used for nothing else.

4 - There was no middle ground between low defense trash basic leather armor and chainmail
Basicly, if you chose to wear leather armor when other choises are aviable you'd be griefing yourself because of how big a difference there was between them

Now, lets talk about whats changing here!

### New: Leather Tanning

Hides aren't used for crafting clothes anymore.
It always bugged me that you were meant to be using a hide which wasn't prepared to be used!

Introducing, CURED LEATHER!

Cured leather can be carried around with ease in a little cute roll!
Just like cloth or stick bundles!
image

image

Now, you'll need to tan Hides to obtain workable Leather!
You'll get a random amount from 1 to your skill level!
So the more skilled you are the more you stand to gain!

https://github.com/user-attachments/assets/663c4da5-3077-4137-b3ab-d5fbc08272ff

As you can see, you place your Hide in the leather rack, and skin it with a hunting knife!
image

You can also use a wooden stake to un-anchor the tanning rack!
image
image

But you can't work on the leather unless its anchored!
(Nevermind this image is old and says "hammer" its wooden stake now)

Also here's a nice surprise! There is a chance based on your skill to get a Masterwork Cured Leather!
(The brightness on this has been toned down to the levels you see in the picture bellow this one)
image

With masterwork leather you can bug a seamstress into upgrading the leather armor you have crafted for yourself!
image

This armor is in general just one tad bit behind chainmail, but has more blunt resistance.

### Hunting skills merged! Into "Hunting"!

image

Hunting is now a skill that's the result of Butchering, and Skincrafting combined!
Trapmaking was just nuked. Trapmaking's bonus on applying restraints was moved to Hunting.
While the mantrap was made available to anyone with the basic crafting skill.

image
image

Hunting will allow you to craft some survival items without the need of a needle, now you'll just need your hunting knife!
Plus a tanning rack isn't required for this type crafting!
(I plan on adding more stuff into this skill or moving, like bait bags and stuff so it can all be organized under this skill)

image

You regain your ability to craft leather armor, as you saw above, and can now upgrade it! All for yourself!
No one can make a masterwork leather armor set without both the hunter and the seamstress (or someone with enough skill in either)

As a Seamstress you will no longer need the tanning rack beside you! That's for the hunter!
(old photo, Basicly, things that are stylish and made out of leather like tricorns and vests can now be made by the seamstress instead)

### New Armor Hardened Leather Armor set

This one is craft able by the seamstress!
You will be able to craft these items with your Sewing skill!

*STAT WISE: This armor is good against blunt and very weak against stabbing, as per recommendation of @Red-Honk*

These sprites were made by the lovely Cynthia!

image
image

Skincrafting, the now called "hunting" was removed from seamstress to account for this thought!

However, a standard white version of the cloak, satchels and bags were given to Sewing too!

### Classes that had either Butchering or Skincrafting now get Hunting!

Since Trapmaking was purged into regular crafting I wanted to replace all instances of it in the different roles with general crafting, but all those that had trapmaking already had general crafting. Huh.

#### You can no longer rip out usable leather from leather clothing.

Sorry guys, I get you needing cloth to bandage your wounds, but unless you have the might of zeus you're not ripping leather with just your own two hands.
It was also creating duplication issues in salvaging.

#### Weaving into Sewing

Fuck Weaving. Like Fuck it in its ass.
It was probably a relic from when weaving was its own skill.
Well I shot that horse in the face, weaving is now a part of Sewing proper and you no longer need the stupid loom.
You need a needle however, just like all other sewing recipes.

#### Leather Belts

You used not to be able to craft Leather Belts.
Sewers and Hunters can now craft it!

#### Some Bug Fixes

Tricorn was unable to be repaired or salvaged, also some other item I can't recall too.
That has been fixed.

## Why It's Good For The Game

I've had my eyes set on hunter for a while and believe these changes will be benefic not only to Hunter but also Seamstress!
Reduces bloat, makes hunting more dynamic and bridges the leather - cloth gap the seamstress suffered from.

## Changelog

**WIP**

add: You can now craft a leather belt with Sewing or Hunting skill
add: Added Cured Leather and Masterwork Cured Leather.
add: Added a Masterwork upgrade to Leather Armor
add: Added the Hardened Leather Armor set
add: Added a leather tanning mechanic to the Tanning Rack
tweak: Reworked the Tanning Rack into a subtype of Machine.
tweak: Gave clothing recipes from tanning to sewing.
tweak: Crafting with leather no longer requires the tanning rack.
tweak: Hunting craft recipes no longer require a needle, they require instead a hunting knife.
tweak: Merged Butchering, Skincrafting and Trapmaking into Hunting
tweak: All roles that had either of the 2 skills mentioned above got Hunting to compensate.
tweak: Making a mantrap now requires general crafting skill instead to craft
tweak: Hide no longer shrinks down when dropped.
balance: All recipes that required hide now required cured leather instead.
balance: Backpacks and Satchels require 1 more cured leather to craft now.
balance: Removed Skincrafting (now Hunting) from Seamstress
fix: Tricorns can now be repaired and salvaged
code: removed some duplicated vars and commented out code when they presented themselves

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
I'll comment briefly on this and say, a lot of the times hunters don't actually deliver to the stockpile right away. They'll sew up some bags, make several baits. Hunt each bait one after another and use the left over bag to pick up the meat/fur/hide.

That said, I dunno how to feel about this PR in truth. It seems more like a nerf to the hunter to reduce what they can make, and now require you to go to the seamster for skincrafting things. 
The seamster already had cloth and silk, adding hide isn't too much of a stretch I suppose.
I just know it's going to be a pita that as a hunter I can't make learher gear for myself anymore.

**Comment by Nakalon** [comment]
> I'll comment briefly on this and say, a lot of the times hunters don't actually deliver to the stockpile right away. They'll sew up some bags, make several baits. Hunt each bait one after another and use the left over bag to pick up the meat/fur/hide.
> 
> That said, I dunno how to feel about this PR in truth. It seems more like a nerf to the hunter to reduce what they can make, and now require you to go to the seamster for skincrafting things. The seamster already had cloth and silk, adding hide isn't too much of a stretch I suppose. I just know it's going to be a pita that as a hunter I can't make learher gear for myself anymore.

I understand this concern! And yes, idealy the idea is you go to the seamstress for armor!
The plan is for people to go to them like they go to smiths!

However! You can still craft pouches with Hunting and I didn't remove the sewing skill form hunter I don't think!
I plan on expanding what Hunters can craft trough the hunting skill!
I just didn't have ideas YET, but I left the cloak, the bags, the water skin, the quiver, and somethings else I can't remember!

My idea for hunter is that it becomes more of a Fletcher/Survivalist. So I plan on adding more content!
How does this make you feel?

**Comment by katsukai** [comment]
Honestly feel a bit same way seamstress kinda taking out all the fun out of other classes seems bit oppressive.

**Comment by Nakalon** [comment]
> Honestly feel a bit same way seamstress kinda taking out all the fun out of other classes seems bit oppressive.

I'm trying to replace the "fun" I'm taking out with something else.

I just know better than to try to do everything all at once, spend 1 month on it and get nowhere because I quit.
So I try to do things in little batches.

Before this PR Hunters got Sewing, and Skincrafting, Seamstresses TOO.

They could ALREADY craft this items, and I'm pretty sure I didn't remove sewing from hunters (althought probably the craft diffs would have to be revised to at least give them a chance maybe)

I plan to give MORE content to hunters instead of taking away from them.

Even giving them the treatment I gave Seamstress and giving their own shop, but thats a ways away still.
Please don't take this PR at face value!

**Comment by Nakalon** [comment]
> If you intend to add more things that the hunter can make, then I'd be fine with it. As it is, if they lose most of their skincrafting stuff, they're left with hunting things and little else after. Which isn't terrible, but doesn't feel particularly good when they had all of leather crafting at their finger tips prior. Especially since seamstera already had a good deal with cloth and silk material
> 
> I will point out, that trap making doesn't really ever get used by hunters. Not much point to it- simple animals can't have broken bones, and iirc, traps require iron, which is expensive or more difficult for hunters to get ahold of.

Say, what about this:

Trap moved into blacksmithing

I go back to draft to add more things to hunter?

But I will need the help of the community to get some ideas!

**Comment by Nakalon** [comment]
I decided to go back to draft and add more things to hunter!

**Comment by Maromar15910** [comment]
> > If you intend to add more things that the hunter can make, then I'd be fine with it. As it is, if they lose most of their skincrafting stuff, they're left with hunting things and little else after. Which isn't terrible, but doesn't feel particularly good when they had all of leather crafting at their finger tips prior. Especially since seamstera already had a good deal with cloth and silk material
> > I will point out, that trap making doesn't really ever get used by hunters. Not much point to it- simple animals can't have broken bones, and iirc, traps require iron, which is expensive or more difficult for hunters to get ahold of.
> 
> Say, what about this:
> 
> Trap moved into blacksmithing
> 
> I go back to draft to add more things to hunter?
> 
> But I will need the help of the community to get some ideas!

Traps should still be under it's own purview I think, or maybe even under engineering with said traps being novice or 0 level creations since a mechanism to close a jaw is 'baby's first simple machine'. 

If it isn't folded into engineering, making things like snare traps that are spooled under trees and hang a target upside down as well as pitfalls and simple rous traps may be interesting. Going into the more exotic directions, one might even edge into arrow casters or things mixed with alchemy. Imagine filling a room with poison gas. 

Maybe trapmaking and engineering should just be folded together after all, with Hunters getting some skill in it.

**Comment by Maromar15910** [comment]
> > > > If you intend to add more things that the hunter can make, then I'd be fine with it. As it is, if they lose most of their skincrafting stuff, they're left with hunting things and little else after. Which isn't terrible, but doesn't feel particularly good when they had all of leather crafting at their finger tips prior. Especially since seamstera already had a good deal with cloth and silk material
> > > > I will point out, that trap making doesn't really ever get used by hunters. Not much point to it- simple animals can't have broken bones, and iirc, traps require iron, which is expensive or more difficult for hunters to get ahold of.
> > > 
> > > 
> > > Say, what about this:
> > > Trap moved into blacksmithing
> > > I go back to draft to add more things to hunter?
> > > But I will need the help of the community to get some ideas!
> > 
> > 
> > Traps should still be under it's own purview I think, or maybe even under engineering with said traps being novice or 0 level creations since a mechanism to close a jaw is 'baby's first simple machine'.
> > If it isn't folded into engineering, making things like snare traps that are spooled under trees and hang a target upside down as well as pitfalls and simple rous traps may be interesting. Going into the more exotic directions, one might even edge into arrow casters or things mixed with alchemy. Imagine filling a room with poison gas.
> > Maybe trapmaking and engineering should just be folded together after all, with Hunters getting some skill in it.
> 
> Engineering exists?!

It does! 
image
It's just very basic. Basic enough to be folded into traps or even just 'device craft' or 'trickery' or something. Maybe just move traps to engineering and give hunter a single level into it.

**Comment by Nakalon** [comment]
> It does! image It's just very basic. Basic enough to be folded into traps or even just 'device craft' or 'trickery' or something. Maybe just move traps to engineering and give hunter a single level in it.

Thank you! I must ponder about this!

**Comment by radarseas** [comment]
blessed PR, finally skincrafting is **ACTUALLY** viable for bandits to learn, finally I can, _make the armor I spawn with almost._


any chance of buffing bandits sewing stat by 1 level, so they can dye stuff and fix their armors without a seamstress they have no plausable way of ever reaching and paying for work.

**Comment by Nakalon** [comment]
Waiting on Sprites and the opinions of my peers.

**Comment by Elli-Skala** [comment]
> They could ALREADY craft this items, and I'm pretty sure I didn't remove sewing from hunters

You did actually

**Comment by Nakalon** [comment]
> > They could ALREADY craft this items, and I'm pretty sure I didn't remove sewing from hunters
> 
> You did actually

Nuh huh!!!

**Comment by NikolayByondPlayer** [comment]
This is the way

**Comment by Nakalon** [comment]
> This is the way

Woo hoo!!

**Comment by Nakalon** [comment]
> > They could ALREADY craft this items, and I'm pretty sure I didn't remove sewing from hunters
> 
> You did actually

I made this comment back before I went back into draft.

I'm unsure you read everything in the PR.

The hunting skill allows the hunters to craft the leather armor.

The lose nothing by losing sewing.
They can still craft what they could craft.
They have no need to repair their weak armor because they can very easily can just craft another, specially since the leather is now more common and cheaper.

Plus this is still a draft. If you're against anything here say so, discuss with me, I've been discussing with other players too in order to make this the best thing it can be.

Just being a naysayer and adding a downvote changes and contributes nothing.

And I'm very prone to be convinced I'm in the wrong.

**Comment by Zelfg** [comment]
After playing a ton of Seamster recently this sounds like a real blessing, I cant really talk about the armor strenght balancing part since I dont really partake in PVP. The Hunter changes seem great! I dont see them losing alot of gameplay or fun at all, they still can do alot if not more then before, and the Hide change is just perfect in my opinion! More money for the Hunter, more leather for the Seamster, its always rather annoying to get hide, you have to pray that there is someone around killing tons of volves and such just so you can make a few overpriced clothing pieces. Adding the little leather treatment steps are cute aswell, no hassel and alot of reward. Removing the need for the loom is also good, helps to make this job more understandble for newer players aswell. Diffrent things for the seamster to sew is always great, variety is fun. being able to make belts is something that everyone is happy about I bet. hmmm I cant think of anything really negetive about this PR as of now. Oh and sorry for the chaotic review hope its all understandable!

**Comment by Nakalon** [comment]
> After playing a ton of Seamster recently this sounds like a real blessing, I cant really talk about the armor strenght balancing part since I dont really partake in PVP. The Hunter changes seem great! I dont see them losing alot of gameplay or fun at all, they still can do alot if not more then before, and the Hide change is just perfect in my opinion! More money for the Hunter, more leather for the Seamster, its always rather annoying to get hide, you have to pray that there is someone around killing tons of volves and such just so you can make a few overpriced clothing pieces. Adding the little leather treatment steps are cute aswell, no hassel and alot of reward. Removing the need for the loom is also good, helps to make this job more understandble for newer players aswell. Diffrent things for the seamster to sew is always great, variety is fun. being able to make belts is something that everyone is happy about I bet. hmmm I cant think of anything really negetive about this PR as of now. Oh and sorry for the chaotic review hope its all understandable!

Thank you! This is really helpful for me!!!
Hopefully the last part of the rework will be the one after this one and then it's done!!

**Comment by Nakalon** [comment]
Currently waiting on sprites for the new armor!

**Comment by Nakalon** [comment]
I let this sit for too long now I have countless conflicts need to be fixed.

**Comment by Nakalon** [comment]
FUKKKKKKKKKKKKKKKKKCK merge conflicts fuckig my ass

**Comment by Nakalon** [comment]
i need to fix this shit

**Review by Gyrandola — APPROVED** [review]

**Comment by LeChatGuid2** [comment]
hya! Good thing i read your cool pr, didn't knew the tailor could still do leatherwork haha. Bracers are apparently still a hunter only thing but maybe that was on purpose! Either way, cool pr, only thing is that it seems that the sprites for the new leather is invisible !
image

**Comment by Nakalon** [comment]
> hya! Good thing i read your cool pr, didn't knew the tailor could still do leatherwork haha. Bracers are apparently still a hunter only thing but maybe that was on purpose! Either way, cool pr, only thing is that it seems that the sprites for the new leather is invisible !
> image
> 

Strange! Sorry about that! I had to solve a lot of merge conflicts like 5 times! it's possible the sprites where dropped by mistake! Will fix!

**Pull request merged**
