### PR TITLE
Re-Flavors most of the Garrison. Bailiff -> Royal Marshal

### PR DESCRIPTION
**Pull request by GuppyLaxx**
This PR gives just about all the jobs in the guard a change up in their text, and changes the Bailiff's title into Royal Marshal.

The Captain of the guard is just a Lieutenant, specifically for the King's retinue, while the Marshal(and in part, their councillors) oversee the whole of the garrison.

The changes in this PR are still subject to change, but for the most part follow this chart I was given by staff :

Hierarchy2

Edit : the PR also adds checking for redundant jobs in savefiles using SSJob.GetJob, and if the job that is in the save file doesn't exist, it's deleted from the list.

### CODE REVIEW

**Comment by DeerJesus** [comment]
thank fucking christ. We also need this chart on a wiki page detailing like, space law or whatever

**Comment by CalamaBanana** [comment]
Poor Veteran forgotten once more. Where would that one fit in?

(Love the chart, though)

**Comment by SixplyDev** [comment]
I also dislike the idea of the knights being under the Bailiff/Royal Marshal. The Knights are under the King since they're his bodyguards

**Comment by SixplyDev** [comment]
> > I also dislike the idea of the knights being under the Bailiff/Royal Marshal. The Knights are under the King since they're his bodyguards
> 
> If you look at the chart, you'll see that nobody actually commands the knight. They are just that low because they are specifically part of the King's retinue(Personal/Manor guards)

Thanks I'm just blind

**Comment by DeerJesus** [comment]
> Poor Veteran forgotten once more. Where would that one fit in?
> 
> (Love the chart, though)

I think royal marshal has direct authority over the veteran, and the captain of the guard has indirect authority over the veteran

**Comment by Keazra** [comment]
I like this a lot. Needs a smidgen more work, like detailing the veteran and figuring out who the knights answer to, but this clarifies so much already.

**Comment by DorfGuy1** [comment]
Big ups for a chart.

**Comment by hugmeorelse** [comment]
Been pushing Useroth to push out the chart for a month now and to make the changes to Bailiff since the beginning of the server, since they were apparently designed to be like this from the start.

**Comment by hugmeorelse** [comment]
Been pushing Useroth to push out the chart for a month now and to make the changes to Bailiff since the beginning of the server. If you look at the code, this is what they were intended to be doing from the start.

**Pull request merged**
