### PR TITLE
Sewing Rework Atomization - Scissor Improvements and Misc Changes

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

Part of the Sewing Rework I'm working on!
While this isn't big enough to warrant calling it a "PART" its still part of the rework!

## Scissors Improvements and Expansion!

image

Scissors now have their own intent for Salvaging called Snip!
(I couldn't fix "Salvage" in the sprite...)

Snip is what will be used for salvaging clothing instead of just attacking normally.
This gives players more control over when they do actually want or not want this function to be enabled.

### New Feature! Web Snipping!

As Requested by LunaBell!
image

You can now snip webs into silk!
image
image

The amount dropped scales with your Sewing skill!
The speed at which you snip scaled also!
And you also get Sewing experience for doing it!

### You can now salvage storages such as bags and cloaks.

Now you will no longer have your scissors fall into your cloaks or satchels when trying to salvage!

https://github.com/user-attachments/assets/1b01466e-1224-41aa-9f74-c5f4e509372d

Also, if the container is holding items, they will now be spat out when salvaging instead of ceasing to exist!

### Sleeve Tearing

Sleeve Tearing now respects the material the article of clothing is made out of!

image
(See webbed shirt)

Sorry guys, now you can't turn silk into cloth by making a silk shirt and ripping its sleeves out!

### Cloth Salvaged with Scissors now respects item colour!

image
(See pants and shirt)

Because it was a feature of sleeve tearing I didn't know how to make work for scissors... but I studied! And got it working!

### Changes to Sewing repairs

Yeah Yeah, I saw some of you fellas abusing the fact they could just fix their stuff up themselves without the need for a seamstress!
Nuh huh!

image

There's now a chance you damage an item if you have little sewing skill, scaling with sewing skill ofc.
The upside is, failing to fix the item now gives you sewing exp! (Yes only failing, no farming grr)

Also Sewing repairs no longer instantly repair an item to max.
Now they work like smith repairs, in that you gotta give the item a couple touch ups to get it to max HP!

image

### Leatherworking

Any instances of recipes that would generate more than 1 no longer do so!

Being able to produce 3 boots out of 1 leather and then salvaging each for 1 leather wasn't... intended...

Adjusted some recipe prices to account for this!

### Small things!

Added Salvage results and Sewn repair variables to items that were otherwise missing it.

Also decreased the price the padded dress recipe to be the same as the arming jacket.

## Why It's Good For The Game

Some of these changes facilitate the Seamstress's job, some serve to difficult those who have no skill in Sewing so they require the Seamstress's services (Like they would a Smith) which puts Seamstress at a healthier place and gives them more costumers.

Other changes here are just all in all better code and fixing some oversights! Polishing the Seamstress Experience!

Fixed a runtime by removing the needle from the seamstress's belt... The item didn't fit there... and that was causing a runtime!
It's fixed now!

## Changelog

Add: Added new intent for Scissors (and a sprite for it), Snip, which should be used to salvage clothes from now on.
Add: Scissors can now make short work out of Webs by using the Snip intent!
Add: Bags such as satchels and Cloaks can now be salvaged.
Fix: Prevents a runtime while trying to spawn the Seamstress by removing the needle form the belt slot
Fix: Fixed a bug where if you did manage to salvage a coat by placing an item inside the item would be deleted.
Fix: Sleeve tearing now properly respects the material the clothing is made out of, no more transmutation of silk into cloth.
Tweak: Salvaged items now inherit the colour of whatever item they were salvaged from, just like sleeve tearing.
Tweak: Repairing a clothing item no longer repairs it automatically to full integrity. Reduced Sewing time a bit to account for this.
Tweak: Removed "leather" from the padded dress description and decreased it's recipe cost.
Tweak: Gave salvaging results to items that were missing still missing them.
Balance: There's now a chance a player with low sewing skill may damage an article of clothing while attempting to repair it. To compensate, failing to repair a clothing item grants the player Sewing Experience.
Balance: Leatherworking Recipes which yielded more than 1 item have add its yield amount decreased to 1 to avoid item duping.
Code: Moved some Sewrepair vars around
Code: Repathed Scissor behavior into the Scissors attack_obj
Code: Moved salvaging vars to obj/item
Code: Added /obj/item/storage/backpack/rogue in order to reduce duplicated vars in its subtypes

### CODE REVIEW

**Comment by Nakalon** [comment]
> silk sales for alot and the items made from said silk. im ok up till this point, please remove the scaling amount from skill for harvesting it and I will merge. this unfortunately could be used to make ALOT of money and have economy impacts.

I decreased it to rand 1 or 2 if thats okay!
I'd like to keep it as a slightly better option than just beating the thing bloody, if thats okay!

**Comment by Koteshkin** [comment]
You can "repair" things with low skill to negative durability, they arent broken after.
image

**Comment by Nakalon** [comment]
> You can "repair" things with low skill to negative durability, they arent broken after. image

Okay now this is GIGA funky!!
Hopefully im fixing this.

**Comment by Nakalon** [comment]
> You can "repair" things with low skill to negative durability, they arent broken after. image

Thank you for reporting this! I was just redoing the repairs and I was gonna miss this yet again, I was gonna test now and discover this and have no idea why it wasnt working, thanks to you I do!

**Pull request merged**
