### PR TITLE
Milk cheese (balanced this time)

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
Makes milking more realistic, the amount of milk produced does not scale with breast size.

Assuming the goal is to produce butter (9 mammons)
You would need to milk
Seelie = 15 times
Pregnant seelie = 5 times
Person = 3 times
Pregnant person = once

For cheese
Seelie = 5 times
Pregnant seelie = 1.67 times
Person = once
Pregnant person = 0.33 times
If this is still busted, I am absolutely toning down the numbers

I also buffed the nutrition and hydration drain from being milked to counteract it.

I removed the time modifier so that you can continuously milk people, this should be counteracted by the drastically lowered numbers.

Proof:
image
image
image
image

Sources:
https://www.thepioneerwoman.com/food-cooking/recipes/a91036/how-to-make-butter/
https://www.healthline.com/health/parenting/breast-feeding/how-much-breast-milk-should-i-be-pumping

## Why It's Good For The Game

Goblins have no cows in the fortress, these changes would allow goblins to produce butter and cheese.

Requested by parts of the player base.
image

The guy who originally worked on it wanted this feature to be more of a meme and thus wanted all balance constraints to be removed, this led to a subpar design as well as upsetting the deviant side of the playerbase.

I am going straight to hell.

### CODE REVIEW

**Comment by Elli-Skala** [comment]
This is why gyran should have banned balance prs

**Comment by ophaq** [comment]
Although I think milk amount should at least very minorly affect milk production for gamer reasons, we don't really have a drawback to breast sizes. Also the current nutrition drain and hydration drain is already pretty significant, I tested it out on a round and was drinking constantly while having to eat at least once or twice between two milking sessions which is about 30oz of milk.

Anyway, excited to see this come if it does get merged.

**Comment by wow50000** [comment]
> Although I think breast size should at least very minorly affect milk production for gamer reasons, we don't really have a drawback to breast sizes. Also the current nutrition drain and hydration drain is already pretty significant, I tested it out on a round and was drinking constantly while having to eat at least once or twice between two milking sessions which is about 30oz of milk.
> 
> Anyway, excited to see this come if it does get merged.

also specifically that we have waaay too many bimbos with humongous boobs

**Comment by ophaq** [comment]
> > Although I think breast size should at least very minorly affect milk production for gamer reasons, we don't really have a drawback to breast sizes. Also the current nutrition drain and hydration drain is already pretty significant, I tested it out on a round and was drinking constantly while having to eat at least once or twice between two milking sessions which is about 30oz of milk.
> > Anyway, excited to see this come if it does get merged.
> 
> also specifically that we have waaay too many bimbos with humongous boobs

Maybe make a drawback to having huge breasts / multiple breasts (multiple breasts should produce more milk, no?) slower move speed / speed stat penalties, but more milk volume?

**Review by Gyrandola — APPROVED** [review]

**Comment by NikolayByondPlayer** [comment]
god...

**Comment by ophaq** [comment]
Pretty good, feels balanced. Could use a little bit more milk, depending if you have multiple breasts. But other than that, it is functioning as intended which is to be somewhat tedious to get enough milk for stuff unless you're pregnant.

**Comment by Faire-Fuzzy** [comment]
Ah yes, who needs the butcher, a role already with little and not much played.

**Pull request merged**
