### PR TITLE
Seelie Diversification

### PR DESCRIPTION
**Pull request by Kevak**
## About The Pull Request

Got the greenlight from Gyran to give seelie much of the customization options of wildkin. More animalistic seelie are now viable, rather than being stuck as tiny men. Can do stuff like weird critters. Tossed in the moth wing sprites for extra funsies. Obviously some sprites won't work well on seelie, as they are tiny little goobers. But I'm sure people will have fun with this.

## Why It's Good For The Game

More customization is good. Also seelie being tiny men is silly, they are spirits of nature and weird little fae things that form from aspected bullshit and whimsy, they should be able to be weird little animals. Also Gyran wanted it.

## Proof Of Testing

Screenshot 2024-12-20 043803

### CODE REVIEW

**Comment by RyszardParys** [comment]
The time for Tiny-Moth™

**Comment by notafurryy** [comment]
> ...now we need bandit seelies...

we already had bandit seelies...

**Comment by TheFenix323** [comment]
Hmm, not sure how I feel on this...

**Comment by Simply-Sydney** [comment]
> Hmm, not sure how I feel on this...

Same, making seelie into tiny wildkin doesnt exactly help make the race distinct or unique... oh well, not our server not our vision.

**Comment by NikolayByondPlayer** [comment]
> > ...now we need bandit seelies...
> 
> we already had bandit seelies...

Was fun though wasn't it? 
I love being robbed by tiny fae!

**Comment by NikolayByondPlayer** [comment]
> > > > ...now we need bandit seelies...
> > > 
> > > 
> > > we already had bandit seelies...
> > 
> > 
> > Was fun though wasn't it? I love being robbed by tiny fae!
> 
> Unable to be clicked. Impossibly strong ability to deal with crowds. Can become impossible to grapple by abusing sitting on your shoulder. Oh yeah. It's frag time.

Funny as hell, yes

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
