### PR TITLE
Grenzel changes

### PR DESCRIPTION
**Pull request by Jackofashepard**
## About The Pull Request

image

Grenzels are now lore accurate in that they are humans and, at worst, demi humans
Grenzels can now choose to be a swordsman or a pikeman (pikeman does the random roll for halbred or billhook)
Grenzels now get a helmet and new mask (the hat is still in the bag)
The grenzel pants are now actually armored like its description says it is! (I stole gambeson stats since its essentially gambeson pants)

EDIT

Changed pants stats to studded leather

## Why It's Good For The Game

I find it strange how grenzels are so underequiped for a supposed highly expensive and sought after merc company and that 9/10 of them are oddly _strength plus one_ I mean not humen races when the lore describes grenzelhoft as being one of the places where humens outnumber everything else 10 to 1. I already really disliked that a merc company that has always only had polearms suddenly got swords for some reason, now its at least a choice. The steel mask is also a nice way to introduce more roles with masks so people dont automatically asume you are a bandit for wearing one, that and it drips hard with the kettle helmet.

### CODE REVIEW

**Comment by DorfGuy1** [comment]
The ploomed hat is such a big loss. Maybe a helmet, something like....[http://www.zbrushcentral.com/t/warhammer-total-war/337666](url)

**Comment by katsukai** [comment]
Pointless powercreep on already powerful role that attracts already the worst in the community.

**Comment by Jackofashepard** [comment]
> The PR fails to mention all the stat buffs to armor and sword skill

you failed to read. it does mention it, the armor that is "The grenzel pants are now actually armored like its description says it is! (I stole gambeson stats since its essentially gambeson pants)" "Grenzels now get a helmet and new mask (the hat is still in the bag)"

Sword skill has been here since the last PR that added zweihanders. if you pick the swordsman class you are better at swords, if you pick pikeman you are better at polearms

**Comment by Jackofashepard** [comment]
> The ploomed hat is such a big loss. Maybe a helmet, something like....[http://www.zbrushcentral.com/t/warhammer-total-war/337666](url)

I have good news! its still in the bag, you can wear it!

**Comment by Jackofashepard** [comment]
> Pointless powercreep on already powerful role that attracts already the worst in the community. Fine with them being Human or Demi only, but may upset few Grenzel mains.

I am sadly aware that some grenzel mains will be upset. In fact some of the few lupian players i like play this role. The "powercreep" is balanced out by the fact that stronger races have been locked out this role entirely

**Comment by Jackofashepard** [comment]
By the way i am open to discussion on two other options for helmets. Namely a visored sallet or a sallet with steel mask

**Comment by Red-Honk** [comment]
1 in 10?; Well, that means a few could be non-humans, meaning the little trickle that comes to Rockhill that aren't human are just a speck, the extreme minority of them, I don't see any lore issues with that at all. (Considering there are only 5 that come in the first place and not like 100)

**Comment by Red-Honk** [comment]
Now for the pants change, don't give them the gambeson stats, give them the studded leather armor ones, those make more sense considering what they are.

**Comment by Jackofashepard** [comment]
> Now for the pants change, don't give them the gambeson stats, give them the studded leather armor ones, those make more sense considering what they are.

good suggestion

**Comment by Jackofashepard** [comment]
I'm more than willing to talk about battle ready. I figured it'd fit battle hardened professionals. Especially ones that actively seek conflict for coins.

**Comment by radarseas** [comment]
I'd not give them steel masks off the bat, a half mask at most? they should still have some weakness on their faces before they get into the town, even riders don't get gear this good.

**Comment by Jackofashepard** [comment]
> I'd not give them steel masks off the bat, a half mask at most? they should still have some weakness on their faces before they get into the town, even riders don't get gear this good. Hell riders _don't even have neck armor_.
> 
> I get you want more classes with steel masks but for a class with battle-ready + expert polearms/swords + steel armor + full body coverage. That has 5 slots?
> 
> _its a little OP having expert-parries without cooldown on your parries and really insanely strong armor for a roundstart spawn in five slots that isn't even the keep's knights._

Man at arms have better armour than this, watchmen have near equivalent armor. Full protection is a stretch, their boots and gloves are still awful. Its 4 slots, not 5. They already had expert polearms/swords. No cooldown parries? I'm not sure what you mean by this as i did not touch parries.

Using desert raiders as a comparison isnt quite fair considering they are a merc band that specializes in cavalry (except they barely ever bother getting any) and have questionable loyalty, their armour is pretty fitting for cavalry units. Grenzels are a expensive highly professional merc company that specializes in foot soldiers. About the only other role on this server on equivalent level is a man at arms i would say which grenzels are now pretty in line with (albeit worse in some respects).

**Comment by Jackofashepard** [comment]
I ask but one favor of any further reviews. Please at the very least do your research on the current role before commenting. I'd like to take these comments seriously but most of the comments have barely read the changes or barely knew the role to begin with. And the new changes too, if you'd please (note i said most, not all)

**Comment by Jackofashepard** [comment]
Battle ready removed

**Comment by pilotmans** [comment]
i like everything about this except for the species locking, does this include axian and wild kin?

**Comment by Cyprex** [comment]
Gyran said I should close this

**Comment by pilotmans** [comment]
> Gyran said I should close this

It's unfortunate cause the kit additions are nice, however the PR no longer aligns with the new Grenzle lore or so I have been told.

**Pull request closed without merging**
