### PR TITLE
Advanced Lockpicking

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

MojaveSun-based lockpicking mechanics.

https://github.com/user-attachments/assets/4971787b-8b08-4663-b6c2-498d1acbabde

## Why It's Good For The Game

It's really cool.

### CODE REVIEW

**Comment by CalamaBanana** [comment]
Disclaimer, I never played MoyaveSun but played more than enough Skyrim. 

I am not the biggest fan of IRL-skillchecks. If lockpicking ever gets added, it should take a serious amount of time based on the quality of the door. Rogue slots should get limited along side it as well, and/or split into a limited thief class with near 0 combat abilities and a knife-fighting cloaked ruffian. 

The map will need serious reworks, too. 

I mean, no one wants to play towner or merchant already. Easy lockpicking for endless self-antags that are more than capable to just murder you instantly when you ask them politely to stop would be the death blow to them.

**Comment by RadiantFlash7** [comment]
I think this is pretty cool. I worry about balance as well, but it'll be interesting to see how the experiment turns out

**Comment by Coolgat3** [comment]
Please explain how it works instead of just referencing a mechanic off another server.. Many of us never touched it and don't know.

**Comment by K4rlox** [comment]
> Please explain how it works instead of just referencing a mechanic off another server.. Many of us never touched it and don't know.

https://github.com/user-attachments/assets/4b6dda3b-1853-4f48-9f10-f88797eda93d

**Comment by Gyrandola** [comment]
Grand reopening

**Pull request closed without merging**
