### PR TITLE
Second floor of towner's smith house

### PR DESCRIPTION
**Pull request by SayonaraEcho**
## About The Pull Request

Re-added: second floor town smith house. Iron bars returned. 
Added: some lights around there

image

image

## Why It's Good For The Game

I still don't know why second floor of towner's smith house was deleted with 3 iron bars. 

There was no light at all.

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
Oh I checked lights they seem to be dim but not too dark, can you delete light post there and place it here please? 
image

And maybe add a wall or a rock so there wouldn't so much empty space at the north. Or maybe like add benches or something? 
image

**Comment by Heheniy** [comment]
why did you place it in literally worst place, pushing it into rock for some reason

**Comment by NikolayByondPlayer** [comment]
> why did you place it in literally worst place, pushing it into rock for some reason

1- getting rid of weird connection to church
2- making a road south 
3- it will be moved anyways

**Comment by Heheniy** [comment]
1- there is nothing weird
2- move a fucking road
3- stop doing shitty temporar 'solutions'

**Comment by NikolayByondPlayer** [comment]
> 1- there is nothing weird 2- move a fucking road 3- stop doing shitty temporar 'solutions'
suffer well
also I forgot 4th one: getting dumb questions from hehenly!

**Comment by NikolayByondPlayer** [comment]
And besides we can do with temp stuff since big one will take sometime

**Pull request closed without merging**
