### PR TITLE
Fixes-the-Benches and Mapping Issues related to the new church

### PR DESCRIPTION
**Pull request by Acantharctia**
## About The Pull Request

It's in the title, minor changes to the church like suggestions and changes that didn't make it before it was merged along with _**hopefully**_ fixing the benches sprites that Xylix made invisible.

## Why It's Good For The Game

Unfucks what has been fucked, fixes what has been broken, generally just improves the church.

### CODE REVIEW

**Comment by Teragenic** [comment]
Please add what this actually changes and what modifications you have added. Also if it has run, if there are any runtimes. Etc. 

Have you tested this? Made sure it actually fixed it?

**Comment by coffeecoffeecoffee** [comment]
> Please add what this actually changes and what modifications you have added. Also if it has run, if there are any runtimes. Etc.
> 
> Have you tested this? Made sure it actually fixed it?

Well for one, it pretty obviously sounds like it FINALLY FIXES ALL THE INVISIBLE PEWS, and that's the main thing as far as I'm concerned, but I'd be curious what other changes there are, yes.

**Comment by Acantharctia** [comment]
> > Please add what this actually changes and what modifications you have added. Also if it has run, if there are any runtimes. Etc.
> > Have you tested this? Made sure it actually fixed it?
> 
> Well for one, it pretty obviously sounds like it FINALLY FIXES ALL THE INVISIBLE PEWS, and that's the main thing as far as I'm concerned, but I'd be curious what other changes there are, yes.

Sorry, didn't see this earlier and GitHub is not giving me notifications.
Problem I've been having is I could not simulate the problem in my end regarding the invisible pews, they were always there and the files were fine too. What I did do was basically export and import than back, which hopefully fixes the issue.

I know saying "PRAY" is not good in coding, but taking what I know of the issue and how to normally fix it, it's the closest and best solution, which should work.

**Comment by Acantharctia** [comment]
> I dont want to merge anything map related until #417 goes through

If I may ask why? You're practically the head maint here, so I won't go against it, but I am curious.

**Comment by Teragenic** [comment]
Please answer the question of:
What are the minor changes to the church. Compared to the other mapping PRs which atleast have pictures of what they have changed.

**Pull request closed without merging**
