### PR TITLE
Cultist Antag

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Ports guts from https://github.com/Darkrp-community/OpenKeep/pull/239.

Ports zizo cult antag from https://github.com/Darkrp-community/OpenKeep/pull/333.

I reccommend checking Stonekeep's [Antag Guide](https://wiki.stonekeep.xyz/index.php/Zizo_Cultist).
Now ported as well: https://wiki.ratwood.rip/index.php/Guide_to_Cultist

TODO: 

- [x] Port following fixes and rebalances
 https://github.com/Darkrp-community/OpenKeep/pull/779.
 https://github.com/Darkrp-community/OpenKeep/pull/551.
 https://github.com/Darkrp-community/OpenKeep/pull/703.
 https://github.com/Darkrp-community/OpenKeep/pull/859.
- [x] Adjust flavor to match our lore and vibe
- [x] Testing

image

image

### CODE REVIEW

**Comment by casualspacestation14enjoyer** [comment]
hello original coder guy for zizoid cult
give credit in PR or i vill RAPE you to DEATH
anyway happy to see my shitcode spreading to other servers like a primordial link between two hiveminds enjoy your future cult orgies

**Comment by katsukai** [comment]
Interesting, does it come with BLOOD cultist sound effect?

**Comment by casualspacestation14enjoyer** [comment]
> Interesting, does it come with BLOOD cultist sound effect?

no it doesnt

**Comment by casualspacestation14enjoyer** [comment]
> > hello original coder guy for zizoid cult give credit in PR or i vill RAPE you to DEATH anyway happy to see my shitcode spreading to other servers like a primordial link between two hiveminds enjoy your future cult orgies
> 
> This is the third-fourth time these people port PRs without crediting, tis bleak.

we should go black to closed source, legal consequences be damned

**Comment by EvenInDeathIStillServe** [comment]
Why even bother crediting if mongrels will come out of the woodworks to accuse you of stealing PRs when the credit is _right there_.

**Comment by casualspacestation14enjoyer** [comment]
> Theres two direct references to your PRs and the commits are co-authored. Are you regarded

oh theyre co authored ok nvm didnt notice that youre good

> Why even bother crediting if mongrels will come out of the woodworks to accuse you of stealing PRs when the credit is _right there_.

ok we will port your codebases PRs without credit if thats what you want

**Comment by EvenInDeathIStillServe** [comment]
> ok we will port your codebases PRs without credit if thats what you want

All your codebases' PRs are credited. Don't be a child.

**Comment by casualspacestation14enjoyer** [comment]
> > ok we will port your codebases PRs without credit if thats what you want
> 
> All your codebases' PRs are credited. Don't be a child.

not if i have anything to do with it

**Comment by Cre77** [comment]
> > > ok we will port your codebases PRs without credit if thats what you want
> > 
> > 
> > All your codebases' PRs are credited. Don't be a child.
> 
> not if i have anything to do with it

big brother you ripped my sprites for homunculus and ascended off a discord image mockup before i got to finish them and left me uncredited
stfu

**Comment by ChocoboLord** [comment]
The praise command isn't logged, apparently. I figured this out trying to find out which LRP buddy was spamming it...

**Comment by ChocoboLord** [comment]
And none of the cultist antags are actually in the traitor panel, that's kind of an issue.

**Pull request merged**
