### PR TITLE
Adds bog armory key to bog guards.

### PR DESCRIPTION
**Pull request by Jackofashepard**
## About The Pull Request

Adds the bog armory key to bog guards keyrings.

## Why It's Good For The Game

To my understanding this change was originally brought on by MAA's raiding the keep armory and smelting everything for full plate. Overall the key changes were good but locking bog guards out of their armory was not needed as there really is nothing of value in there. The change has just made it a hassle for bog guards to get simple items like a replacement gambeson, a stone axe or their iron spear.

### CODE REVIEW

**Comment by SixplyDev** [comment]
There was also a LONG history of Bog Guards raiding the armory to smelt it down to get better equipment. This also _again_ brings the issue of bandits killing 1 bogman to break into the armory and dress like bogmen. There would also be nothing for some rando-ass wanderer to kill a bogman and now enter their relatively well-stocked armory. That whole armory is a treasure hoard for anyone who wants a shit ton of steel just due to the way that smithin works. The key should remain with the Bog Master and nobody else like it is for all other garrisons.

**Comment by Jackofashepard** [comment]
> There was also a LONG history of Bog Guards raiding the armory to smelt it down to get better equipment. This also _again_ brings the issue of bandits killing 1 bogman to break into the armory and dress like bogmen. There would also be nothing for some rando-ass wanderer to kill a bogman and now enter their relatively well-stocked armory. That whole armory is a treasure hoard for anyone who wants a shit ton of steel just due to the way that smithin works. The key should remain with the Bog Master and nobody else like it is for all other garrisons.

Cool story, please, show the steel in the armory. In addition its currently the same except they need to break one door (it takes about a minute at most if you are doing it solo)

**Comment by Jackofashepard** [comment]
image 
image 
image 
image

PERHAPS EVEN 
image

**Comment by Jackofashepard** [comment]
> There was also a LONG history of Bog Guards raiding the armory to smelt it down to get better equipment. This also _again_ brings the issue of bandits killing 1 bogman to break into the armory and dress like bogmen. There would also be nothing for some rando-ass wanderer to kill a bogman and now enter their relatively well-stocked armory. That whole armory is a treasure hoard for anyone who wants a shit ton of steel just due to the way that smithin works. The key should remain with the Bog Master and nobody else like it is for all other garrisons.

You should be comment banned from github, get outa here

**Comment by Jackofashepard** [comment]
As a side not and comparison. The soilsons have more steel in their farming shed and the entire bog armory (it has 0)

**Comment by SixplyDev** [comment]
> > There was also a LONG history of Bog Guards raiding the armory to smelt it down to get better equipment. This also _again_ brings the issue of bandits killing 1 bogman to break into the armory and dress like bogmen. There would also be nothing for some rando-ass wanderer to kill a bogman and now enter their relatively well-stocked armory. That whole armory is a treasure hoard for anyone who wants a shit ton of steel just due to the way that smithin works. The key should remain with the Bog Master and nobody else like it is for all other garrisons.
> 
> Cool story, please, show the steel in the armory. In addition its currently the same except they need to break one door (it takes about a minute at most if you are doing it solo)

Brother, you can literally smelt down ANY iron tools, raw, ingots, etc to get steel. 1 coal or even small log + 3 iron ANYTHING will produce 4 steel. That's why even an iron armory is still a massive mine if  someone wanted to get steel out of it. Please review how smelting works before saying something like that.

**Comment by Jackofashepard** [comment]
> > > There was also a LONG history of Bog Guards raiding the armory to smelt it down to get better equipment. This also _again_ brings the issue of bandits killing 1 bogman to break into the armory and dress like bogmen. There would also be nothing for some rando-ass wanderer to kill a bogman and now enter their relatively well-stocked armory. That whole armory is a treasure hoard for anyone who wants a shit ton of steel just due to the way that smithin works. The key should remain with the Bog Master and nobody else like it is for all other garrisons.
> > 
> > 
> > Cool story, please, show the steel in the armory. In addition its currently the same except they need to break one door (it takes about a minute at most if you are doing it solo)
> 
> Brother, you can literally smelt down ANY iron tools, raw, ingots, etc to get steel. 1 coal or even small log + 3 iron ANYTHING will produce 4 steel. That's why even an iron armory is still a massive mine if someone wanted to get steel out of it. Please review how smelting works before saying something like that.

if someone actually does all the effort to secure an outpost in the bog smith and a smith then by all means. They save about 10 minutes from actual mining. And the town smith will definitely refuse, as far as I can say that's natural player progression and ingenuity which is fine. If it was straight up steel then it'd be a bit much. As a side note i main bog and i have not even once seen someone do it, the only occurrence I heard of was about a bog master doing it which makes the point moot anyways

**Comment by TuskTusk** [comment]
> As a side note and comparison. The soilsons have more steel in their farming shed than the entire bog armory (it has 0)

And this is why they now have a bridge and fancy gate.

**Comment by TuskTusk** [comment]
That aside, good PR?
It's still very easy to break in, but at least it isn't harder for Boggies to arm themselves than it is for outsiders to break in.

**Pull request closed without merging**
