### PR TITLE
Gives Squires the ability to repair. Adds polishing metal tools

### PR DESCRIPTION
**Pull request by GuppyLaxx**
This PR adds the ability to polish anything metallic, giving it a nice shine and some extra durability and the likes. It's some small boons for now, though I will work on the exact perks it provides later on.
To polish something you need cream, and a brush. They can be purchased as a kit from the shop. Squires and smiths get some at the start.
You then put cream, brush it harshly, brush it finely, and then clean it. The effect lasts until the item is damaged.

dreamseeker_niqlbRBPY3

This PR also gives squires a unique trait that lets them do certain smithing related things, primarily, the new polishing and repairing stuff. They can ONLY repair things at an anvil, at a fixed rate.
This trait removes their ability to smith anything, or to properly do anything smithing related, UNLESS they manage to become skilled enough at smithing. In which case their trait becomes moot and they are now a proper smith!

The Squires now get a little room outside the manor, next to the tower and the gatehouse.
image

The whole purpose of this PR is to go with my 2 other Armor PRs nerfing sleeping in armor, and nerfing being able to put on armor on your own. Along with other intended effects that accompany the broader changes like the little extra room and polishing cream.

### CODE REVIEW

**Comment by Heheniy** [comment]
so when keep would manage to get anvil they will have free smiths

**Comment by wow50000** [comment]
I voiced this on discord but I will voice it here, I love everything about this except the repairs. Squires are not blacksmiths they are people kept around to do the bitchwork the knights don't want to do or can't do in hopes that they eventually become a knight themselves. Squires are not the knights personal blacksmith or armour maintainer.

**Comment by CalamaBanana** [comment]
Even if the squires do not get forced into smithing, wherever you put down an anvil will become the new keep smithy area.

**Comment by wow50000** [comment]
voiced on discord but- you know the drill
fuck the cream being 300 mammons

**Comment by Murderfoxen** [comment]
image

I would say, squires should be taking their armor to the smithy to have it repaired or whatnot. The polishing of armor is an amazing feature! I also like the little area for squires.

**Comment by wow50000** [comment]
I mean honestly I would rather you add silver and gold paint that squires can apply than use silver cream for polishing, and let polishing be available to everyone

**Comment by wow50000** [comment]
image
add gold paints like this and have it be scuffed if someone runs into them

**Comment by Cyprex** [comment]
No repairing for squires, the polishing is probably fine

**Comment by Cyprex** [comment]
I don't think you can gain smithing experience if you're guaranteed to fail like this- so that'll need to be tweaked.

**Comment by katsukai** [comment]
Why not? Makes sense for squires to know about armor or weapon maintenence.

**Comment by Nakalon** [comment]
Such a shame we lost this.

**Pull request closed without merging**
