### PR TITLE
[TM] Sleep Advancements & Stress Refactor

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
This PR intends to tackle these issues:
- Grinding encourages bad, antisocial behaviours and often is a problem for balancing (You balance for job skills, and people just mindlessly grind up as various other roles anyway)
- Can't advance your character too much unless you choose to grind
- Grinding creates ugly meta tactics and makes it hard to award XP for various stuff as to not encourage it
- Caring about your character stress is a non-issue
- Being tired and needing to sleep is a trivial thing that can be ignored

Changes:
- Grinding now instead of giving skill XP, grants "sleep XP" of a given skill
- Every time you have a triumph sleep, you'll be awarded with "dream points", which allow you to buy skills which you have unlocked with "sleep XP", you will also get some random choices of novice skills
- You require much less sleep XP than grind XP to advance a skill (which allows players who choose not to grind, but instead cater character needs and roleplay have better advancements than previously)
- Crafting items grants almost double XP as before (With also less XP requirements, you wont have to craft stuff repeatedly to grind it, but instead craft a bunch of things, do other stuff and then advance at night)
- The "dream points" you get are a base number + stress modifier + int modifier (where int plays a smaller role)
- The "dream points" act as a hard cap for advancing skills, allowing more liberal XP awards, as meta tactics for this will always be hard capped
- Stress system has been rewritten, it now is less buggy and most if not all stresses apply correctly (Music, alcohol, food etc.)
- Stresses have been rebalanced so they're no longer wildly out of proportion with eachother
- Stress mattering for skill advancements should encourage people to drink alcohol, smoke weed or ask minstrels to play them tunes, and should care much more about harsher levels of hunger or thrist
- Pickpocketing only grants you XP if you pickpocket other person (not yourself), that is conscious

Specifics:
- On average you receive ~3 dream points
- Crafting skills cost 2/2/3/3/4/5 to advance
- Combat skills cost 3/4/5/6/7/8 to advance
- This means by sleeping 2 triumph nights, you can advance 3 crafting skills to novice
- Or by sleeping 5 nights you can advance a crafting skill to master from nothing (provided you're getting the sleep XP)

These are big changes, and they wont be perfect as you playtest them, I believe this is a great design to get rid of grinding cheese and encourage players to care for their characters more, and interact more for "wants" like alcohol or music, letting players who dont grind too much advance just as well.

If a class does not have the starting skills required to do its role and instead would grind it up, let me know

**While the system is ready, the values are a heavy work in progress, have some patience and do offer feedback**

The system is also prepared to have alternative rewards for dream points instead of skills, that will come soon:tm:
.. oh and uh... people may not like being Paranoid as much as before..

MSeTKoebDR
dreamseeker_DBpthsFaiA
dreamseeker_JuXxddP2Zs

### CODE REVIEW

**Comment by coffeecoffeecoffee** [comment]
Okay-
Can we fucking make it then though so that you don't get drowsy immediately after your last sleep if it happens to become nightfall, since we're making sleep not an ignorable thing any longer?

**Comment by EzekyalLegit** [comment]
really look forward to seeing less massive pits of wooden chests and clubs in the woods where people were skilling. Hope we can have combat damage give good sleep XP so we can do REAL sparring to gain skill and replace the "Stand next to eachother in weak mode offhanding wooden swords and spam click" training method

**Comment by ddsaw** [comment]
A very cool system, most certainly better than the jank that we have now.
The stress rework is also much appreciated but if I had to nitpick, I would have atomized this into two pulls.

As you said the values are heavily in progress, here's my two cents on the value of int before and after this pr.

With the current numbers, this seems an int nerf. From my understanding of the sleep_adv.dm code, atleast. I would claim that int is not considered an amazing stat by most as it stands and after this nerf it's only notable effect would be crafting chance, a system that is ignored by many roles to begin with.
This makes int a stat you can literally dump to 0 with little consequence if the dreampoints are the bottleneck, anod not the sleep exp. 
Priorly, int atleast removed grinding from a bad and horrible system.

I understand that int plays a big role in getting sleep exp, but with sleep exp being supposedly and by design easy to get, this isn't all too desirable. Int's calculation into dreampoints seems to literally be 1% of a dreampoint per int, the exact formula as I saw it being (INT-10)*1 extra "dreamdust" which converts to dreampoints at a rate of literally 1%.

Strength gives you 100% extra damage at 20 str (vs 10str), so I believe it would be appropriate for int to give you 3 extra points at 20 int, on average. This would not even be a 100% bonus, as it can be reasonably assumed people will attempt to get the stress bonuses.
Consider just how overbearing 20 strength is and then consider if you cared at all if somebody had 20 int.

**Comment by ddsaw** [comment]
> > A very cool system, most certainly better than the jank that we have now. The stress rework is also much appreciated but if I had to nitpick, I would have atomized this into two pulls.
> > As you said the values are heavily in progress, here's my two cents on the value of int before and after this pr.
> > With the current numbers, this seems an int nerf. From my understanding of the sleep_adv.dm code, atleast. I would claim that int is not considered an amazing stat by most as it stands and after this nerf it's only notable effect would be crafting chance, a system that is ignored by many roles to begin with. This makes int a stat you can literally dump to 0 with little consequence if the dreampoints are the bottleneck, anod not the sleep exp. Priorly, int atleast removed grinding from a bad and horrible system.
> > I understand that int plays a big role in getting sleep exp, but with sleep exp being supposedly and by design easy to get, this isn't all too desirable. Int's calculation into dreampoints seems to literally be 1% of a dreampoint per int, the exact formula as I saw it being (INT-10)*1 extra "dreamdust" which converts to dreampoints at a rate of literally 1%.
> > Strength gives you 100% extra damage at 20 str (vs 10str), so I believe it would be appropriate for int to give you 3 extra points at 20 int, on average. This would not even be a 100% bonus, as it can be reasonably assumed people will attempt to get the stress bonuses. Consider just how overbearing 20 strength is and then consider if you cared at all if somebody had 20 int.
> 
> My bad, it was meant to be 10% per point of int above 10, not 1% The stress rework got bundled with this because I was to balance some values around stress, which is a broken and half not-working system, or had some wild values here and there, so it had to be tackled
> 
> You're right though, int is not that good, I'll try 20% instead of the intended 10% for now
> 
> _I actually did test it, giving myself 20 INT, and I got the extra dream point, and I was like "huh okay works", so I had to be lucky and get the 10% to roll_

I thought it was something like it being intended to be 10%, yeah.
20% is much better and we'll see how it plays out I suppose. From my gut feeling 20% at a point per point of int is still mediocre but definitely noticeable. It won't make people think int is a good stat, but they will take note of it, hopefully.

Assuming a good and reasonable week a 15 int (very high!! consider a 15str characters combat prowess) character would gain (5*0.2)*5 extra points, amounting to an average of 5 points. That's enough to buy a combat skill from apprentice to journeyman. And remember, this is over the entire week, so you'll have your journeyman swordfighting, if you sleep asap and never miss a sleep, on day 6.

Again, I want somebody who loses 2 points of int to feel as hurt as somebody who lost 2str.
With all the brutal grapplechecks, chargechecks etc. 2str's impact on combat is so heavy that even if int has wide non combat applications it's just incredibly overbearing, not to mention 2str is an immediate gain whilst int would be over the course of week.

Also what is the reasoning behind checking for INT>10 on the points?
You are essentially letting races and classes with -int act like they are perfectly average, in the extreme this even encourages you to dump int as much as you can once it dips below 10.
A half orc should feel his -2 in the tangible reduction of dreampoints, I think.

Another thought: combat skills below 3(journeyman) are essentially noncombat roles. We used to hand out apprentice weapon skills for free via the dummies.
I'd say reduce the combatskill cost for novice and apprentice by one.
The roles who do not already have apprentice in their chosen weapon do not need to be needlessly discouraged from picking up apprentice weapons, imo.
This merely affects things like soilsons learning to swing a sword. Not problematic and even with a reduction still very pricey.

**Comment by coffeecoffeecoffee** [comment]
> Okay- Can we fucking make it then though so that you don't get drowsy immediately after your last sleep if it happens to become nightfall, since we're making sleep not an ignorable thing any longer?

Can somebody explain why this wouldn't be desirable? Who -wants- to go to sleep, wake up, and 5 seconds later after a full rest get hit with 'tired' again for the reason of >oops, the sun went down?

**Comment by coffeecoffeecoffee** [comment]
> > > Okay- Can we fucking make it then though so that you don't get drowsy immediately after your last sleep if it happens to become nightfall, since we're making sleep not an ignorable thing any longer?
> > 
> > 
> > Can somebody explain why this wouldn't be desirable? Who -wants- to go to sleep, wake up, and 5 seconds later after a full rest get hit with 'tired' again for the reason of >oops, the sun went down?
> 
> I want people to fall asleep at night, and if you dont want to get tired again after a moment nothing stops you for waiting for it to become night again

The issue is it happens almost completely unexpectedly, often at the worst of times, and who cares about people falling asleep at night? Why punish people for stalking the streets at night and being ner-do-wells, when the reality of what we're seeing is that everybody simply walks around completely tired?

**Comment by john-pawson** [comment]
> > > > Okay- Can we fucking make it then though so that you don't get drowsy immediately after your last sleep if it happens to become nightfall, since we're making sleep not an ignorable thing any longer?
> > > 
> > > 
> > > Can somebody explain why this wouldn't be desirable? Who -wants- to go to sleep, wake up, and 5 seconds later after a full rest get hit with 'tired' again for the reason of >oops, the sun went down?
> > 
> > 
> > I want people to fall asleep at night, and if you dont want to get tired again after a moment nothing stops you for waiting for it to become night again
> 
> The issue is it happens almost completely unexpectedly, often at the worst of times, and who cares about people falling asleep at night? Why punish people for stalking the streets at night and being ner-do-wells, when the reality of what we're seeing is that everybody simply walks around completely tired?

Well first of all, it'd be nice if most people were falling asleep or trying to fall asleep at night, it would give an opportunnity for ner-do-wells to actually do something while the others are trying to rest, second of all the only reason you get tired after sleeping is because when you DID get tired you decided to wait 23 hours and 59 minutes to go ahead and sleep. In wich case you probably also just slept for 15 minutes since if you did sleep for a bit longer you'd just sleep the next night again. So in some way it makes sense for you to be more tired than normal after an entire day of not sleeping.

**Comment by john-pawson** [comment]
Also, this is more of a general comment, it'd be nice if you could spend triumphs to get a single more point each night, it would finally give them an use and i think it's better to do that since paired with the stress relief that it does right now, it would finally have some kind of use in-game, and i think it wouldn't be that big of a change so people would start powergaming with them.

**Comment by john-pawson** [comment]
> > Also, this is more of a general comment, it'd be nice if you could spend triumphs to get a single more point each night, it would finally give them an use and i think it's better to do that since paired with the stress relief that it does right now, it would finally have some kind of use in-game, and i think it wouldn't be that big of a change so people would start powergaming with them.
> 
> Im afraid to use triumphs for anything significant since people have a TON of them, and they're very easy to get. Especially since that could muddy the general experience, testing and tweaking
> 
> On second though.. hmm.. allowing people to spend 1 for +1 each night, would be kind of neat. It would mean that every night they spent it, they get no net positive triumphs

I was thinking more of like spending 2 - 3 per night, so it's a net negative and people actually SPEND the triumphs instead of not gaining them. Maybe make it exponential? 1 the first night, 2 the second, 4 the fourth...

**Comment by CalamaBanana** [comment]
It would be good if the first level of hungry/thirsty does not add stress. Otherwise it forces you to always carry your lunchbox and fountain dive the second the debuff hits or you miss out on levelups. Basically have the first level as "warning" that one should go drink/eat. And only stress out if one gets hungry, not just a little peckish.

**Comment by Koteshkin** [comment]
Is narcopelsy flaw supposed to dissapear on antags? I started as bandit, got yawning once and then slept manually. Then I got no drowsy feelings at all and when checking my flaw I had none. 
Tapir375-22.58.33

**Pull request merged**
