### PR TITLE
Bog house fix, key work for bogguards and innkeep

### PR DESCRIPTION
**Pull request by NikolayByondPlayer**
## About The Pull Request
Gatehouse fixes, changes for keychains for innkeep, bogguard and warden.

Innkeeper gets keys for all the rooms in his chain.
Boguard get one key for everything in the gatehouse.
Bog Master gets gatehouse key and key from his office.

**Gatehouse**
- Added lights to missing areas
- Everything can be opened with one bog key now
- Warden has his place that can only be opened by his key
- Added names to most doors
- Small fixes

image

## Why It's Good For The Game

QoL mostly, also we had many doors with different locks but if one would kill Bogguard and steal his key chain he would get access to everything anyway

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
Added peddler to cook
image

**Comment by Gyrandola** [comment]
If you are making a key useless, then also remove the key itself.

**Comment by NikolayByondPlayer** [comment]
> If you are making a key useless, then also remove the key itself.

I left it in code but there is no keys on the map

**Comment by NikolayByondPlayer** [comment]
forgot about steward though, deleted just now

**Comment by Gyrandola** [comment]
> > If you are making a key useless, then also remove the key itself.
> 
> I left it in code but there is no keys on the map

Thats what I mean. Dont leave useless assets in the code.

**Comment by NikolayByondPlayer** [comment]
> > > If you are making a key useless, then also remove the key itself.
> > 
> > 
> > I left it in code but there is no keys on the map
> 
> Thats what I mean. Dont leave useless assets in the code.

okay gonna delete now

**Comment by NikolayByondPlayer** [comment]
Deleted them
image

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
