### PR TITLE
Adds bullet pouches and refactored Quiver code.

### PR DESCRIPTION
**Pull request by TheFenix323**
## About The Pull Request
Adds bullet pouches and refactored the quiver code to accept future ammo storage options, so now the Quiver is a subtype of `ammo_storage/`.

**Do note that they are using the pouch sprites and are not craftable.**
pouch_e

https://github.com/user-attachments/assets/267fd60d-685a-4db4-8e97-4b3dca6349ad

## Why It's Good For The Game

Makes carrying ammo for these guns less painful.

### CODE REVIEW

**Comment by Nakalon** [comment]
I fucking hate quiver shitcode!

This is cool I would give it to seamster and artificer to make!

**Comment by Nakalon** [comment]
Did you refractor quiver code???

**Comment by TheFenix323** [comment]
> Did you refractor quiver code???

Yes, wanted to use the quiver code to not just copy and pase the Quiver code for the bullet pouch.

**Review by Nakalon — APPROVED** [review]
awesome!

**Pull request merged**
