### PR TITLE
Makes a new crafting type for traps

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

 Mainly a temptplate for others to make new traps, but also makes the trapping skill have a real use. 
Now tested and fully works in game

## Why It's Good For The Game

unused skill is le bad, is now used

### CODE REVIEW

**Comment by Useroth** [comment]
I wonder if we should change the recipe.... now you can't just go to a smith and buy some of those really.

**Comment by ThatReformedEngineer** [comment]
> I wonder if we should change the recipe.... now you can't just go to a smith and buy some of those really.

I agree with changing up this recipe, mostly because isn't the beartrap just metal in how it operates? I could see it maybe using a cog or gear or something, but thorns just seems arbitrary of an ingredient involved for the damage it causes.

**Comment by Hmeister-real** [comment]
> > I wonder if we should change the recipe.... now you can't just go to a smith and buy some of those really.
> 
> I agree with changing up this recipe, mostly because isn't the beartrap just metal in how it operates? I could see it maybe using a cog or gear or something, but thorns just seems arbitrary of an ingredient involved for the damage it causes.

If it had to be smithed it would result in even less use, it already needs a hammer but if it requires blacksmithing and trapping it would be literally impossible to see outside of the town or in rare cases made by smiths in the bog smithy during high pop

**Comment by Hmeister-real** [comment]
> I think it's bad to just have a skill that only faciliates 1 single recipe.
> 
> What if trapmaking was instead covered by engineering?

true, but then there would be even less people able to make them, and they would essentially never be seen. I want this to remain as a temptplate for more trapping stuff down the line, it's just limited to the mantraps while there aren't any other forms of traps.

**Comment by Useroth** [comment]
We should approach this another time tbh

**Pull request closed without merging**
