### PR TITLE
Grows some balls/ovaries to Cleric and Barbarian class.(Adventurer)

### PR DESCRIPTION
**Pull request by CloverIsLucky**
## About The Pull Request

Steel heartens the clerics and barbarians.

## Why It's Good For The Game

It makes little sense that they accumulate stress and breakdown after seeing dead bodies, they should stress less often when they see a dead body as well as how a paladin and a warrior behave in presence of one.

### CODE REVIEW

**Comment by Nakalon** [comment]
This in theory makes sense, but since it kinda touches balance a little I'll let other people weigh in first.

**Comment by atomicplan666** [comment]
Clerics already have expert in maces and self healing...

**Comment by CloverIsLucky** [comment]
> Clerics already have expert in maces and self healing...

What about barbarians? Is it okay for them to cry like a little girl after witnessing a murder? No, they are fierce warriors which their cries are from warcries.

**Comment by hugmeorelse** [comment]
I'm going to have to say 'no' to this. At a certain point, you're just buffing classes further by doing this when moods play a big part in fortune.

**Comment by CloverIsLucky** [comment]
'ight...

**Pull request closed without merging**
