### PR TITLE
More Artificer Misc Changes

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

- Repathed Cogs, Added Unstable Wooden Cog, renamed Advanced wooden cog to Reliable Wooden Cog

- Special cogs can now be used to stabilize or unstabilize a contraption

image
image
image

- Simplified Cart upgrade code

- Legendary Artificers can now explode themselves again
Now that they can stabilize the contraptions they don't need this free pass

- Solved Essence typo

## Why It's Good For The Game

While in game I noticed Artificer players never sold contraptions because of how they'd only serve them due to skill check.
This will hopefully solve that problem.

### CODE REVIEW

**Comment by Nakalon** [comment]
I FORGOT SOMETHING HERE I THINK DONT MERGE

**Comment by Nakalon** [comment]
Fixed, safe to merge now

**Comment by ThatReformedEngineer** [comment]
Okay my only question is why would an artificer want to make their devices more unstable? Unless there is some mechanic that involves purposefully causing a mishap beyond inflicting danger.

**Comment by Nakalon** [comment]
> Okay my only question is why would an artificer want to make their devices more unstable? Unless there is some mechanic that involves purposefully causing a mishap beyond inflicting danger.

Depends, evil intent probably. The misfiring of the contraptions also has its uses. Purposefully causing them to detonate would at some point be useful (specially if under duress)

**Comment by ThatReformedEngineer** [comment]
> Depends, evil intent probably. The misfiring of the contraptions also has its uses. Purposefully causing them to detonate would at some point be useful (specially if under duress)

Yeah fair enough, it'd make portable smelter (bronze pipebombs) more reliably effective in causing a misfire detonation.

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
