### PR TITLE
New Surgeries and QoL changes for Surgeons Part 1. Azure Port (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by katsukai**
## About The Pull Request
Selective Ports from https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/115

## New Surgeries

- [ ] Curing rot by cauterization
- [ ] Extracting lux matter from the living
- [ ] Infusing the dead with lux to revive them

## QoL Changes

- [ ] Medicine skill on operation chances are more noticeable.
- [ ] New Surgery Bag that goes to the belt slot.
- [ ] New Blacksmithing recipe for Surgery Bag (1 Iron + 1 Hide) Includes set of tools.
- [ ] Revised gear for Court Physician.
- [ ] Revised gear for Barber Surgeon.
- [ ] Revised gear for Sawbones
- [ ] Fixes an issue where applying leeches to people used the medical skill of the target.

## New Reagent

- [ ] Lux or Vitae, the essence of life. Potent hard to obtain drug, effects may be discussed.

## Why It's Good For The Game
More content, surgery been badly neglected here and this is an effort to give a bone. There is still lot of QoL changes for surgery I want to port but better to add them piece meal.

### CODE REVIEW

**Comment by Nakalon** [comment]
I know this is draft but im worried with how this will collide with Moris bounty

**Comment by katsukai** [comment]
> yea no this will shatter it. because guess waht? they ripped off my surgery bag creation method from hearthstone and they ripped off the revival methods from hearthstone

Why not use the surgery bag in your bounty? It is quite nice.

I managed to make the cure rot surgery to work on my local, but suffers the same bugs as the current unrot process due to Rotman changes.

Depending your both decisions or Useroth, I can just implement few bug fixes that isn't merged yet and close this.

**Comment by Cyprex** [comment]
You might be able to PR this to the bounty branch or after the bounty has been merged. Unfortunate timeing for sure.

**Comment by Cyprex** [comment]
Uhhhh, this only changes 12 lines right now, and they're only additions not hooked up to anything as far as I can tell?

**Comment by katsukai** [comment]
> Uhhhh, this only changes 12 lines right now, and they're only additions not hooked up to anything as far as I can tell?

I haven't committed it to the branch. Because I was testing it locally first.
image

**Pull request closed without merging**
