### PR TITLE
Now you can dig up multiple worms/stones in a single tile

### PR DESCRIPTION
**Pull request by Purpleturtle3**
## About The Pull Request

I love saying title in my prs. Title.

## Why It's Good For The Game

Qol of life change, makes digging up rocks and worms less bothersome.
[Proof that it works](
https://imgur.com/Fim4GV8)

### CODE REVIEW

**Comment by ophaq** [comment]
Thank you.

**Comment by Heheniy** [comment]
you already can, just remove old worm/stone from the tile

**Comment by notafurryy** [comment]
> you already can, just remove old worm/stone from the tile

the title doesn't say FROM a single tile but IN a single tile

**Comment by ophaq** [comment]
> you already can, just remove old worm/stone from the tile

This lets them stack on the tile so you can keep digging. Previously, you had to remove them from that tile to spawn another.

**Comment by Purpleturtle3** [comment]
For the love of god just look at the gif I posted as proof to see how it works...

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
