### PR TITLE
Metal uniformity.

### PR DESCRIPTION
**Pull request by AberrantQuerist**
## About The Pull Request
Changes a LOT of iron/steel sprites to have uniform colour schemes as to their metals. Contails a range of edits, from minor to heavy, to enforce this uniformity. Also changes the colour of steel ingots to match the weapons and tools made from them. 

## Why It's Good For The Game
Considering the material a weapon is made of is a determining factor for its quality, this serves as a visual indicator of that. Before the Stonekeep weapon PR, *some* of the older Roguetown sprites followed this philosophy. This is my attempt to return to that, using the better shapes of Stonekeep sprites where they're warranted. 
Screenshot 2024-09-09 201507
Screenshot 2024-09-09 201633
Screenshot 2024-09-09 201650
I may attempt to change the tinting of iron to red in the future, but this contains the green tinted sprites. Uniformity first, palette shift later.

### CODE REVIEW

**Comment by aberrantQuesrist** [comment]
Forgot to mention, this also changes a lot of the hilt sprites to the wood colour. That was changed for a lot in the Stonekeep sprite update, it's been reverted here.

**Comment by Cyprex** [comment]
Second screenshot has several rows- could you label them? Particularly in the iron example with 3 rows it's very unclear what is what!

**Comment by aberrantQuesrist** [comment]
> Second screenshot has several rows- could you label them? Particularly in the iron example with 3 rows it's very unclear what is what!

Redboxed parts are the ones I implemented. I was testing a couple of iron and steel palettes which I might try using in the future, but this one has green iron and blue steel to remain as consistent as possible with everything. The rightmost row is the old Roguetown sprites, second to rightmost is the Stonekeep sprites. They're not really important except to reference what previous iterations of the weapons looked like.

**Comment by aberrantQuesrist** [comment]
> I reckon the hilts should be thicker, for the tang of the blade and for the grip that goes around it. Also the tip on the zwei looks off, like its asymmetrical, and what are the files in 64.dmi named with SK for?

Tip of the Zwei is exactly as it stands right now, I only changed the colour. The _sk is for the Stonekeep sprites in case people want to use them for something else.

**Comment by aberrantQuesrist** [comment]
I will note that I do not enjoy spriting 64x64 weapons and that is why I touched them the least, once the uniformity is through I invite anyone to edit and improve them.

**Comment by Red-Honk** [comment]
Wow, I can tell them apart more easily. (A whole lot more easily)

**Comment by Cyprex** [comment]
Okay so. On one hand as smith I've had to ask myself from time to time if item x would smelt into steel or iron- it wasn't exactly obvious visually. That's bad, and makes this PR good.
On the other hand I'm not sure I like the green tone... but you know what, honestly I don't really mind it! I'm inclined to merge this!

**Comment by aberrantQuesrist** [comment]
> Okay so. On one hand as smith I've had to ask myself from time to time if item x would smelt into steel or iron- it wasn't exactly obvious visually. That's bad, and makes this PR good.
> 
> On the other hand I'm not sure I like the green tone... but you know what, honestly I don't really mind it! I'm inclined to merge this!

Well, the uniformity is the point! As you can see in my sprite sheets, I have plans to alter the iron colour to more of a reddish hue. The green is just the original direction I am begrudgingly following. Hueshift can come later, convenience now!

**Comment by aberrantQuesrist** [comment]
> Okay so. On one hand as smith I've had to ask myself from time to time if item x would smelt into steel or iron- it wasn't exactly obvious visually. That's bad, and makes this PR good. On the other hand I'm not sure I like the green tone... but you know what, honestly I don't really mind it! I'm inclined to merge this!

What more needs to be done prior to merge readiness?

**Pull request merged**
