### PR TITLE
Guildmaster

### PR DESCRIPTION
**Pull request by Teragenic**
## About The Pull Request

Adds Guildmasters. 

Three subclasses.
Quartermaster, a Supporter non-combatant role.
Grenzelhoftian Veteran, Grenzelhoftian Veteran. Big sword.
Desert Rider Veteran, Desert Rider Veteran. More armored, spawns with a horse.

All three are worse stats than their younger counterparts. They make up to it in experience and gear. Give feedback if it's too much.

## Why It's Good For The Game

Someone to tardwrangle the Mercenaries. Please love of God. Also something to build off off if we want to add any mechanics to them being able to punish mercenaries.

### CODE REVIEW

**Comment by Teragenic** [comment]
Please for the love of God, why is this not working 
image

**Comment by Teragenic** [comment]
> What purpose would they serve, ideally, when each mercenary has the free agency to sign on with whoever they wish? What punitive action would a guildmaster be expected to take against an insubordinate mercenary if neither of them are agents of the crown? You can't just give someone a big hat and say that they're the boss with no ability to back it up.

I'm debating either IC or OOC action, currently I've been given feedback to make it IC as possible. It's very much WIP for now. If you have suggestions please.

**Comment by coffeecoffeecoffee** [comment]
I'm very tentative about this given the reasoning given is "Someone to tardwrangle the Mercenaries, please love of God". I'm a mercenary main who tries to maintain roleplaying standards and quality among mercs according to the Grenzel's lore of _being foreign professionals_, and the way I see this going is that all of the worst mercenary players _are going to be attracted to this role,_ and be enabled to make things even worse, but now with some vague authority behind them that seems to have no guidelines or suggestions of limitations. Are mercenaries supposed to register what their job is with this guildmaster? Can the guildmaster demote and disown mercenaries? With questions like these up in the air, I feel like this is kind of a risky one given the issue with mercenaries seems to be player behavior that should be now covered under new policy.

Discord_wLBCZnNcG6

Given that this is a _rule_ now, and _this_ is the _lore in question..._

6DrkOqwncl

Why isn't the solution to this problem "report and ban/jobban more mercenaries"? If this isn't happening, isn't this an issue of policy enforcement?

**Comment by Teragenic** [comment]
I'm still trying to figure out why my code is not working, but my main idea is yes they will be able to demote mercenaries. I want to add a triumph loss if 50% of mercenaries are dead by the end of the round and a triumph gain at the end. 

Someone had a map in mind to help Guildmaster do his job and I'm making this PR in light of that too.

**Pull request closed without merging**
