### PR TITLE
Butchering fur races gives fur

### PR DESCRIPTION
**Pull request by jxanimu**
## About The Pull Request

Lupians, wildkin, tabaxi, and vulpkanin all give fur when butchered now

## Why It's Good For The Game

enhances butchering realism, allows people to profit from skinning.

### CODE REVIEW

**Comment by Foxentail** [comment]
Seems like a new way to RR people

**Comment by john-pawson** [comment]
> Seems like a new way to RR people

This only works on bodyparts, btw. So unless you've already decapitated them and butcher their head (Which you could already do before this) this doesn't add a new way to RR people at all. It just does what the description says.

**Review by Gyrandola — APPROVED** [review]

**Comment by DelineFortune** [comment]
So you say i can literally butch furries to get money? Meat+fur from 1 limbs = 20 coins 

Fucking lmao, its 80 mamms from one player !!

**Comment by john-pawson** [comment]
> So you say i can literally butch furries to get money? Meat+fur from 1 limbs = 20 coins
> 
> Fucking lmao, its 80 mamms from one player !!

Go, make your dream of an org- i mean lupian fur black market come true.

**Pull request merged**
