### PR TITLE
Makes MAA less ugly

### PR DESCRIPTION
**Pull request by Plutolover99**
## About The Pull Request
Changes the spawn-helmet of the Man at Arms class from a Bascinet to the Kettle Helmet.

## Why It's Good For The Game
BECAUSE THE BASCINET IS SO FUCKING UGLY!! NOBODY TAKES MAA SERIOUSLY BECAUSE THEY HAVE THIS STUPID HELMET THAT MAKES THEIR HEAD LOOK LIKE THE TIP OF A PENIS!!

### CODE REVIEW

**Comment by H0gberg** [comment]
god tier pr speed merge plz

**Comment by TheFenix323** [comment]
Like they used to have, nice.

**Comment by pilotmans** [comment]
i used to call them egg-heads, guess this won't work anymore, can't wait to see people enjoy these helms for once.

**Comment by Coolgat3** [comment]
god tier PR speedmerge

**Pull request merged**
