### PR TITLE
Female Barbarians!

### PR DESCRIPTION
**Pull request by babamandaa**
## About The Pull Request

This PR simply lets female characters spawn in as a Barbarian.

## Why It's Good For The Game

There's not really a reason for female barbarians to not be a thing. I don't want to say it's chudcode, but I feel like the archetype of Female Barbarian is different enough in both gameplay and fantasy from Amazon that it warrants a change. Especially since some players (me, admittedly) would like to embody that archetype in a slightly more serious way than a buff girl in a chainmail bikini.

### CODE REVIEW

**Comment by Nakalon** [comment]
I like this! Will let other people weigh in on this tho!

**Comment by wow50000** [comment]
amazon and barbarian are absolutely two different classes, I think they wanted amazon to be its own thing but honestly, I dont even want to touch amazon because it doesnt fit the playstyle I like

**Comment by katsukai** [comment]
Yes please.

**Comment by atomicplan666** [comment]
If this shit is merged Amazonian males better be gettin in

**Comment by Nakalon** [comment]
> If this shit is merged Amazonian males better be gettin in

only if they get to have their cock out

**Comment by Gyrandola** [comment]
Xena the warrior princess.

**Pull request merged**
