### PR TITLE
Keep Remodel

### PR DESCRIPTION
**Pull request by Alanii**
## Keep Remodel

This PR is a comprehensive remodel of the Keep for rockhill.dmm

This PR does the following:
- Moves Steward directly into the Keep
image
image
- Removes the Steward Tower
- Relocates the Wizard (Magician) Tower
image
- Relocates the Keep Dungeon to a new tower
image
- Rearranges some of the tunnels underside of keep
image
- Provides access to the wall interiors (Uses the walls key that is unused)
- Adds new rooms to third floor
   - New Noble Suite
image
   - New Heir room (Seperation of both rooms)
image
image
- Expands some of the access tunnels
- Remodels the kitchen and adds an access service tunnel to the throne
image
- Remodels the Gate-house
- Rearranges the Courtyard and Training Yard
image
- Gives Guard Captain a room
- Provides adequate space for councillors and Bailiff to take petitioners before entering the Court Hall
- Moves Court Hall gate and access door
image

- Adds a vacant stable for saiga

## Why It's Good For The Game

Rearranges a good amount of the Keep and makes the keep more of a Rat-Wood special than Blackstone changes.

This Keep remodel is sadly not as comprehensive as I want it to be. I have to wait for the mythical Harbor Update before I can actually expand the Keep.

### CODE REVIEW

**Comment by SixplyDev** [comment]
Based beyond belief

**Comment by Teragenic** [comment]
Rechecking the designs. I believe the Guard Captain room should be more integrated with the sleeping area and the downstairs. Perhaps a table/bedroom similar to the Stonekeep steward area.  

Add a SCOM into the GC room if you wish to do this so they can atleast relax in there. OR put the GC room by the gate. 

Also I really dislike the layout of the Noble Suite(Guest Room) needs to be rethought.

**Comment by Teragenic** [comment]
keep Dungeon will be horribly underused. I'd also suggest adding a SCOM or something so prisoners can atleast listen in.

Also a SCOM for the Training area so guards can train and still be called is what I'd reccomend.

**Comment by CalamaBanana** [comment]
> Make sure that opening the doors on the wine cellar in the basement does not light the whole thing up, it's where servants can RP

That is actually fixed on the server already, the door is now in the corner where the mugs and table are. Useroth did sneak that in while cleaning up a few other small map oddities.

**Comment by Alanii** [comment]
Pushed to new map

**Pull request closed without merging**
