### PR TITLE
...

### PR DESCRIPTION
**Pull request by Feralape**
Is this a punishment for me not putting in the time as a staff? A punishment for playing only 2 rounds on Ratwood? You punish my fucking burnout by taking my shits and spitting on my face? I got no excuse for not putting in the time as a staff, I'm fucking burnt out from dealing with Harper on Hearthstone, I just wanted to make my own project and be in charge of something for once.

You refuse to properly credit me like you promised, it took someone else to point it out for you to even bother adding my name in the PR title that nobody will see, it shows the lack of sincerity, it shows that you are predatory and would stomp on solo dev like me at the earliest convenience and boy you fucking stomped on me.

You do not see the fucking time I put in making these. I'm a solo fucking dev you fuck, I made these by passion for my project, I don't make money, and I'm a fucking NEET. These are supposed to be my big draws when I launch my project and now I got nothing, my time is wasted.

I was fine with giving you all these until you all fucking stomped on me because I demand proper credits that you're so fucking hesitant to give and would only do the bare fucking minimum by putting it in a PR that nobody would see. Now players will see my work, and they will think of Ratwood, not me, not fucking me.

And you let the players and staffs to insult me, you let them mock me. The fucking staffs of Ratwood fucking ganged on me for trying to demand justice for this act of betrayal. Why the fuck did I defend you guys in Dreamkeep and Hearthstone when they talk shit about you all there, I felt so fucking stupid now, they were right about you guys.

Gyran promised not to take my catapult, and he fucking took it anyway, renaming it to the Onager and letting Sinner doing minor reskin to my sprite. He knows exactly what he's doing, he takes a lot of pleasure stomping on me like this.

Enjoy my work you snakes. Stomp on us solo devs while you can. Choke on my fucking work.

### CODE REVIEW

**Comment by DeerJesus** [comment]
baby

**Comment by Feralape** [comment]
> baby [ baby ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc) [ ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)

really easy to make fun of me from your position

**Comment by DeerJesus** [comment]
> > baby
> >       
> >         [
> >           
> >         
> >             baby
> >           ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> >         
> >        [ baby ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> >       
> >         [
> >           
> >         
> >             baby
> >           ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> 
> really easy to make fun of me from your position

https://www.youtube.com/watch?v=PVD1LNDxOnc

**Comment by Feralape** [comment]
> > > baby
> > >       
> > >         [
> > >           
> > >         
> > >             baby
> > >           ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://private-user-images.githubusercontent.com/11761309/388794418-6d42c71d-c5c6-477f-8669-5380fa655e69.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg0MjgsIm5iZiI6MTczMjI0ODEyOCwicGF0aCI6Ii8xMTc2MTMwOS8zODg3OTQ0MTgtNmQ0MmM3MWQtYzVjNi00NzdmLTg2NjktNTM4MGZhNjU1ZTY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmVkMDkxYTg0OTIzOTUyYTgxNjFiOTQ4Yzc2MTMzMDI4YzQ1NjMzZDVlMzc5NWE0NDkxMGUxZDhhMGM4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AjMUq-RN27RGYOenKGMcDAAYjSQgSU3VzPJ_3z3I2jc)
> > 
> > 
> > really easy to make fun of me from your position
> 
> https://www.youtube.com/watch?v=PVD1LNDxOnc
> 
> https://en.wikipedia.org/wiki/Copyleft

Dangle this shit to tell yourself it's fine to bully solo devs, absolutely no empathy at all

**Comment by NikolayByondPlayer** [comment]
https://www.youtube.com/watch?v=2csS1QfS1n8

**Comment by EvenInDeathIStillServe** [comment]
You will need to remove the relevant items from the `rockhill.dmm` map, too.

**Comment by Feralape** [comment]
> I understand you're upset, but I don't understand your reasoning. You were credited in the event PR, and from the way it appears to me, an outside observer, Gyran simply forgot or didn't think to mention you made the weapons a second time. I don't know what happened with the staff or on discord, but HONESTLY, and I don't mean any offense, if your behavior on github is any indicator it was the right move.
> 
> I have had my work used without credit, look at lupians, hah, does anybody know i even added them and wrote lore for them? No. In fact some codebases outright trash what I wrote for them and add their own. That's fine, they can do what they like because that's the nature of coding for an open source project. That just happens. Your work can and will be used, derived, copied, edited, reworked, tweaked, and even bastardized, all without credit. If you can't accept that you need to understand that your time is better spent working on your own personal projects, not here in ss13.
> 
> Did you know I made the entire NSB Atlas map for Citadel RP? All on my own? I was very proud of it. People have since reworked it, changed it, removed some of my signature layouts and gimmicks for the map, utterly changed it from what it was meant to be. And that's okay. My vision is not perfect, with time and collaboration they've made the project even better than I could have alone, even if I didn't agree with most of the changes or would have been upset if I let myself take it personally. It's an attitude you need to have here. People can take your work, sure, but people can also transform it into something better and work with you to do great things.

People seem to have the impression that I am doing this out of malice or disrespect of the open source license because they do not read what I wrote up there, I am clarifying again for the nth time. So I beg you all please read.

I talked to Gyran before letting him take my stuff, I told him to remember to credit me properly, the credits are important to me because they're meant for my own project that is yet to be made public. I want people to think of me and my project when they use my things, not Ratwood. My project will not be live until next year and now everyone's already associating everything I made with Ratwood. My project now have lost some of its selling points before people even know it exists.

But I would be fine with all these, if we can all be nice. But no, Gyran chose to be spiteful. The moment I asked about my credit in the staff chat, he suddenly somehow remember that I did not put enough time in Ratwood as a staff and promptly had me removed from the staff team, which I say again, I accept the reasoning, but the way it is done shortly after I asked for credits just comes off as a spiteful move to silent me.

I voiced my grief in the general chat, and everybody shit on me, the staffs included. The staff made it sound like me not putting my hours or contributing enough to Ratwood justifies being a total dick to me.

Moving on, prior to this whole shitshow, in the private chat between me and Gyran, I explicitly told him to please not take my catapult as it is one of the hardest equipment i made, and he agreed. And now he blatantly went against his promise. He took my catapult anyway and renamed it the Onager. You can talk about the black and white stuff all you want, open source this that, but this is about a breach of trust, this is just a blatant backstab. How can I even look at Ratwood favorably anymore after what he did. This is the issues of morals.

Now, Gyran banned me from Ratwood's discord because I opened a ticket to call him out. He closed the ticket and banned me without a word. He refuse to engage with me in DM. Now the staffs are all actively make it sound like I deserve this because I did not contribute enough to the server. Which is fucked up.

This is now one of my few last medium to voice my utter disgust.

**Comment by Feralape** [comment]
Once my project is live next year you can take everything, I don't care, you can make a downstream, do whatever. But it's not live now, it's dead before it's even live.

**Comment by Gyrandola** [comment]
I didnt just  take it. I refactored all of it, made the ammo overlays work, replaced the sprites you probably ripped from Age of Empires with ones made by one of our spriters. And still I credited that its from helmsguard. What more you want? I dont know. Its clear the crediting is just a front for your real grieviance, the fact that I ported some of your work.

**Comment by Feralape** [comment]
> I didnt just take it. I refactored all of it, made the ammo overlays work, replaced the sprites you probably ripped from Age of Empires with ones made by one of our spriters. And still I credited that its from helmsguard. What more you want? I dont know. Its clear the crediting is just a front for your real grieviance, the fact that I ported some of your work.

Fucked up dude, you took it after promising not to and now you're discrediting me. How the hell do you sleep at night. Absolutely not an ounce of remorse. 

You are a spiteful person who is willing to step on smaller and weaker people if it benefits you. You only know how to steal or pay others to do the work, and then have the audacity to accuse people that are better than you of stealing/ripping. Take a good look at Age of Empires catapult and compare it to mine before throwing out such vile accusation.

Your spriter also mostly used my elements and only made a cleaner edit. But even a blind person can see it's still based off of mine. 
image
image
image

Taking what I spent weeks making and then making slight changes does not absolve you of this treachery nor does it make you a creator, it makes you a thief who hides behind laws and rules instead of talking to me properly. I also recall how you accused Hearthstone of ripping their minotaur sprite from an old game despite me telling you how it was made by an actual spriter in the server who worked hard making that. 

I can see why many staffs are leaving, I can see why people are saying what they are saying about you. I want all developers to know what sort of person you are, untrustworthy and a bully.

**Comment by Feralape** [comment]
> > > I understand you're upset, but I don't understand your reasoning. You were credited in the event PR
> 
> > cut
> 
> I've read what you posted in your original post, theres no need to repeat it. Just as theres no need to repeat what I said.
> 
> Look, this is how open source projects work. At any time someone could rip the entirety of ratwood or dreamkeep or hearthstone, tweak it, rebrand it, and host it as something entirely different. The same can be done for your work. There is no requirement for anyone to credit you, hundreds of people have contributed to tgstation and rougetown and now ratwood to get us where we are today. How many of them do you remember? Do not do this work for recognition or to get your name out there, that's not why we contribute to open source projects.

The issue is that my project is not live yet. I'm not doing this for fame ffs, I'm doing this because I'm spending money on a serverbox, I'm spending valuable time doing these work, and it will all be for naught by the time it launches because I will likely not have anything new to offer anymore. I want to make my work worth it.

**Comment by Feralape** [comment]
There's no use to ask you to remove my work, I've already made the mistake of showing you my repo because I made the mistake of trusting you, Gyran. Keep it, enjoy my hard work. 
All I ask now is a recognition of your wrongdoings against me personally, you breached my trust, you insulted me, you vilified me and you tried to silence me by banning me from the discord and deleting my comments from your PR. I demand a sincere public apology.

**Comment by Gyrandola** [comment]
> There's no use to ask you to remove my work, I've already made the mistake of showing you my repo because I made the mistake of trusting you, Gyran. Keep it, enjoy my hard work. 
> All I ask now is a recognition of your wrongdoings against me personally, you breached my trust, you insulted me, you vilified me and you tried to silence me by banning me from the discord and deleting my comments from your PR. I demand a sincere public apology.

You left the discord, came back to continue shit stirring in an entry application which I rejected.

**Comment by Feralape** [comment]
> > There's no use to ask you to remove my work, I've already made the mistake of showing you my repo because I made the mistake of trusting you, Gyran. Keep it, enjoy my hard work.
> > All I ask now is a recognition of your wrongdoings against me personally, you breached my trust, you insulted me, you vilified me and you tried to silence me by banning me from the discord and deleting my comments from your PR. I demand a sincere public apology.
> 
> You left the discord, came back to continue shit stirring in an entry application which I rejected.

I did it in a ticket because you won't take my DM. How the hell is calling you out in a ticket shit stirring, it's away from general chat.

**Comment by Leviathan21** [comment]
this shit is retarded

**Comment by James009D** [comment]
> I didnt just take it. I refactored all of it, made the ammo overlays work, replaced the sprites you probably ripped from Age of Empires with ones made by one of our spriters. Im also planning a complex crafting process with one of our maintainers.
> 
> And still, I very explicitly credited that its from helmsguard. What more you want? I dont know. Its clear the crediting is just a front for your real grieviance, the fact that I ported some of your work (legally and ethically).

Why don't you just fully credit him and his work? Seems like you are dismissing his issue/grievance.
This is completely unnecessary drama from a lack of leadership.

**Pull request closed without merging**
