### PR TITLE
The PR Giveth: Added actions for penetrating with tails

### PR DESCRIPTION
**Pull request by Lyroy**
## About The Pull Request

Adds two new interactions using the tail. These can be used even if the giver is fully clothed.
Only works on kobold and lizard tails.
Seelies get destroyed by it, as one would expect.

## Why It's Good For The Game

Tails are pretty phallic, and this translates nicely into the mechanical sex we've got.

### CODE REVIEW

**Comment by Cyprex** [comment]
Looks good to me, can be merged in 23h

**Comment by SayonaraEcho** [comment]
Erm, why only lizards and kobolds though? Tieflings have no tails?

**Comment by Lyroy** [comment]
> Erm, why only lizards and kobolds though? Tieflings have no tails?

I was considering tieflings too but I wasn't 100% certain. It's easy to add them to the list of tails though.

**Comment by aberrantQuesrist** [comment]
Tieflings do indeed have tails.

**Comment by Hmeister-real** [comment]
wildkin tails need this. i would love doing this with a rat tail

**Comment by Maromar15910** [comment]
Floofy tails could be used to tease or rub without penetrative actions. Or their could be a massage tail verb that's indiscriminate.

**Comment by Cyprex** [comment]
I'm just going to merge this- other peeps can add other kinds of tails to this easily enough(I can guide you through it if you'd like!)

**Pull request merged**
