### PR TITLE
Removes No Flaw & Randomizable flaw changes

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Removes No Flaw for 3 triumphs - triumphs are very easy to get and characters should be more unique with a vice or a flaw
Now random flaws use a different pool and cannot pick narcolepsy

### CODE REVIEW

**Comment by Gr33d-y** [comment]
> in a society of 30 drunkers, 30 smokers and 30 crackheads 1 person with no addicktions is not uniquie...

in a strange, hostile place like this, most people would have vices to forget about all the bad shit. Not having a vice is not unique, nor does it drive the story. Needing to pick up some crack so you now charge someone money for that fish and they have to do something to buy that fish that you are now selling them instead of giving them? That there, that pushes the story forward, not having the money to buy crack so you rob someone before the cravings get to bad? That is driving the story.

**Comment by john-pawson** [comment]
> > in a society of 30 drunkers, 30 smokers and 30 crackheads 1 person with no addicktions is not uniquie...
> 
> in a strange, hostile place like this, most people would have vices to forget about all the bad shit. Not having a vice is not unique, nor does it drive the story. Needing to pick up some crack so you now charge someone money for that fish you just fished up to someone and they have to do something to buy that fish that you are now selling them instead of giving them? That there, that pushes the story forward, not having the money to buy crack so you rob someone before the cravings get to bad? That is driving the story.

Well first of all, if everyone does have a vice and/or a flaw, then not having a vice or flaw IS going to be unique.
Second, if someone wants to roleplay as addicted to something or with a vice, they'll just pick up the flaw and roleplay like anyone else creating stories like you said. BUT for those that don't want to have flaws or just don't really care, it's just a minor inconvinence. Forcing people to HAVE to pick a flaw isn't going to force them to roleplay as having said flaw, it's just going to make their playthrough slightly more annoying. Not only that, with the cost being 3 triumphs not only does it make it so not EVERYONE picks no flaws, since they'll eventually run out of them and have to pick up a flaw or chance it with random (Unless they survive and sleep all 5 nights every single round they play on).
But in the end mechanical flaws don't make stories or characters interesting. Character flaws and people that roleplay them do. And you cannot force that with a -1 end and -1 fort debuff.

**Comment by Gr33d-y** [comment]
> > > in a society of 30 drunkers, 30 smokers and 30 crackheads 1 person with no addicktions is not uniquie...
> > 
> > 
> > in a strange, hostile place like this, most people would have vices to forget about all the bad shit. Not having a vice is not unique, nor does it drive the story. Needing to pick up some crack so you now charge someone money for that fish you just fished up to someone and they have to do something to buy that fish that you are now selling them instead of giving them? That there, that pushes the story forward, not having the money to buy crack so you rob someone before the cravings get to bad? That is driving the story.
> 
> Well first of all, if everyone does have a vice and/or a flaw, then not having a vice or flaw IS going to be unique. Second, if someone wants to roleplay as addicted to something or with a vice, they'll just pick up the flaw and roleplay like anyone else creating stories like you said. BUT for those that don't want to have flaws or just don't really care, it's just a minor inconvinence. Forcing people to HAVE to pick a flaw isn't going to force them to roleplay as having said flaw, it's just going to make their playthrough slightly more annoying. Not only that, with the cost being 3 triumphs not only does it make it so not EVERYONE picks no flaws, since they'll eventually run out of them and have to pick up a flaw or chance it with random (Unless they survive and sleep all 5 nights every single round they play on). But in the end mechanical flaws don't make stories or characters interesting. Character flaws and people that roleplay them do. And you cannot force that with a -1 end and -1 fort debuff.

Then they can live with the penalty. Furthermore, where did the argument about vices and being unique come from. I just thought about that. The vice system is not there to make you unique, it's to drive conflict and aid those who are less RP ready to roleplay having a flaw or give them something to work towards in a round.

**Comment by john-pawson** [comment]
>> Furthermore, where did the argument about vices and being unique come from.
> triumphs are very easy to get and characters should be more unique with a vice or a flaw

The argument about vices being used for being unique came from here. From the "About the pull request".

> Then they can live with the penalty.

If the solution you're going for is "just let them have the penalty" i see absolutely no reason why you shouldn't let them just be able to NOT for a couple of rounds here and then? Like i said, it's just an unnecesary inconvinience.

> The vice system is not there to make you unique, it's to drive conflict and aid those who are less RP ready to roleplay having a flaw or give them something to work towards in a round.

Then just let them choose the flaw? Those that are new to RP will probably have a low playtime and triumph count so they won't exactly be choosing no flaw every round, and it can still be a voluntary thing.
Furthermore if the purpose is to drive conflict, then why keep giving flaws for those who you **know** will do nothing about it? It's clear that they don't want a flaw if they're choosing to spend triumphs to not have one, and FORCING them to have one isn't going to suddenly make them act up on it.

**Comment by radarseas** [comment]
you can already bypass cyclops by rolling or seeing a barber surgeon, removing your eye and having it re-implanted as eyes to not have flaws, I see nothing wrong with spending 3 triumphs to not be flawed.

before you axe no flaw, please add more to fill in the void that is flaws at the moment.

**Pull request closed without merging**
