### PR TITLE
Hunter Skill Increases

### PR DESCRIPTION
**Pull request by JohnnyJohnJohnson**
## About The Pull Request

Increases various skills for Hunter, but not to an unbalanced degree.

Knife-Fighting: Apprentice --> Journeyman
Reason: Any experienced Hunter would know how to take down their prey with a knife if they run out of ammo, can't reach their bow, or their prey closes the distance. At apprentice-level knives a Hunter will reliably LOSE a fight with a goat, never mind a saiga or volf... Also Fishermen get this much skill with knives, so should Hunters.

Crossbows: Novice/Apprentice --> Journeyman
Reason: Crossbows were invented to be easier to pick up and learn by an inexperienced soldier than a bow and arrows. Hunters also need to be versatile. If one wants to switch over to one of these, they should already have the skillset to use it properly since they already know marksmanship with a bow.

Cooking: Novice --> Apprentice
Reason: Hunters are survivalists, what survivalist wouldn't know how to cook meat over an open fire? They still can't make anything fancy at this level, but they won't fuck up roasted meat.

Sewing: None --> Apprentice
They need this skill to make sacks for bait. They won't out-compete the town Seamstress with this level of skill, it just keeps them from having to go to the Seamstress and beg her to use all her fabric for burlap sacks.

## Why It's Good For The Game

I believe all these changes are reasonable for the role and help someone understand what kind of persona they should be playing if they select Hunter. They are all things a Hunter would know how to do to survive and maintain their equipment in the wilderness.

### CODE REVIEW

**Comment by john-pawson** [comment]
Alright a little rule of thumb:
Adventurers tend to get maximum Journeyman skills (Excluding things like bows for rangers or wrestling for monks)
Mercs/guards get expert
Veterans/knights get master or higher

So a hunter that'll probably only ever use it's knife for butchering or fend off the one volf that got too close to shoot with a bow EXPERT knives skill is just ridiculous. If you wanna go ahead and talk to the guy that kills his prey with melee weapons regularely, go check out the barbarian.

Oh and the sewing shouldn'd be here since making a bag doesn't need any skill???
image

(Also god damn fishers shouldn't be getting anything even close to expert knives skill, i'll make a PR to fix it in a minue, i guess there just wasn't enough fisher players for anyone to even notice)

The rest of the skills make sense though.

**Comment by Gyrandola** [comment]
I agree, knives 4 is too much.

**Comment by JohnnyJohnJohnson** [comment]
> Alright a little rule of thumb: Adventurers tend to get maximum Journeyman skills (Excluding things like bows for rangers or wrestling for monks) Mercs/guards get expert Veterans/knights get master or higher
> 
> So a hunter that'll probably only ever use it's knife for butchering or fend off the one volf that got too close to shoot with a bow EXPERT knives skill is just ridiculous. If you wanna go ahead and talk to the guy that kills his prey with melee weapons regularely, go check out the barbarian.
> 
> Oh and the sewing shouldn't be here since making a bag doesn't need any skill??? image
> 
> (Also god damn fishers shouldn't be getting anything even close to expert knives skill, i'll make a PR to fix it in a minue, i guess there just wasn't enough fisher players for anyone to even notice)
> 
> The rest of the skills make sense though.

I understand the reason for not wanting sewing skill, but there's a reason Fishers have knives 4, from a PR that was gonna nerf Fisher knife skill until they thought more about it. https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1762/commits/f01fc30a6623dbbf3375be2334eeb550f8137ad3 
"Knives have low defence and fishers dont really have armour proficiencies or dodge skills so IMO let them have this." Hunters have no armor proficiency and their speed increase is rarely enough to reliably dodge assailants too. I can remove sewing and lower knives to 3 since Journeyman should still be good enough to fight off a volf.

**Comment by JohnnyJohnJohnson** [comment]
> I agree, knives 4 is too much.

I've lowered their knives skill to 3, is it balanced enough to get merged with that?

**Comment by john-pawson** [comment]
> "Knives have low defence and fishers dont really have armour proficiencies or dodge skills so IMO let them have this."

You're talking like pilgrims are supposed to be balanced in any way to be combat viable, they don't get defence or armor proficiencies because they're **fishers**. They should be avoiding almost any kind of fight they're not forced to take. And i don't think giving them knife skill (Which isn't knives in general, it's specifically knife fighting) makes sense at all.

**Comment by JohnnyJohnJohnson** [comment]
> > "Knives have low defence and fishers dont really have armour proficiencies or dodge skills so IMO let them have this."
> 
> You're talking like pilgrims are supposed to be balanced in any way to be combat viable, they don't get defence or armor proficiencies because they're **fishers**. They should be avoiding almost any kind of fight they're not forced to take. And i don't think giving them expert knife skill (Which isn't knives in general, it's specifically knife fighting) makes sense at all.

For Fisher I understand, but Hunters aren't exactly completely domestic civilians. They might not be soldiers, but their job still requires them to regularly tangle with animals, many of which can viciously maul them. They would know how to defend themselves competently, so journeyman knife-fighting makes sense for a Hunter when half of his trade relies on the knife.

**Comment by john-pawson** [comment]
> For Fisher I understand, but Hunters aren't exactly completely domestic civilians. They might not be soldiers, but their job still requires them to regularly tangle with animals, many of which can viciously maul them. They would know how to defend themselves competently, so journeyman knife-fighting makes sense for a Hunter when half of his trade relies on the knife.

Oh yeah journeyman knives for hunters makes 100% sense, i was exclusively talking about fishers. Sorry for the confusion.

**Comment by JohnnyJohnJohnson** [comment]
> > For Fisher I understand, but Hunters aren't exactly completely domestic civilians. They might not be soldiers, but their job still requires them to regularly tangle with animals, many of which can viciously maul them. They would know how to defend themselves competently, so journeyman knife-fighting makes sense for a Hunter when half of his trade relies on the knife.
> 
> Oh yeah journeyman knives for hunters makes 100% sense, i was exclusively talking about fishers. Sorry for the confusion.

Ah okay. For Fishers, I'll admit it makes less sense, but admittedly it's likely just there so they have SOME way to defend themselves. They're not meant to look for trouble, but I think the general idea for most pilgrims and towners being semi-competent with at least one weapon is meant to represent that when living in the outskirts of an already dangerous area, the only people that are still alive are the ones that know how to at least keep a monster busy long enough to run away or for help to arrive. Personally I wish they had journeyman polearms to represent being good at spearfishing lol, but that's just a selfish want on my part...

**Comment by john-pawson** [comment]
> They're not meant to look for trouble, but I think the general idea for most pilgrims and towners being semi-competent with at least one weapon is meant to represent that when living in the outskirts of an already dangerous area, the only people that are still alive are the ones that know how to at least keep a monster busy long enough to run away or for help to arrive.

Yeah i think apprentice (What most pilgrims have) is enough to symbolize that, considering how adventurers that probably *live* wandering around the bog and surviving on their own are mostly capped to journeyman, i think that apprentice would be the appropiate inbetween: 
"I have little/no idea how to fight, i'm going to get eaten alive by goblins" (No skill or novice, like a Noble, for example) and 
"I'm trained/experienced on the ways of combat with this weapon, and i can hold myself up against an armed enemy" (Joruneyman skill, like most adventurers)

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
