### PR TITLE
Removes gender locks from captain and royal marshal

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
See title

## Why It's Good For The Game
Gender locks have been removed from every role other than duke by now, including but not limited to:
Knights(the brawliest mfers in ratkeep)
Hand(the second highest position in the game)
Sheriff(another command position)
It's about time we abolished sexism truly and gave women the right to vote.
(obligatory image of lore guy saying he or she wants the change just for shits and giggles)
image
the above image IS A JOKE AND I TAKE FULL RESPONSIBILITY FOR THIS PR

### CODE REVIEW

**Comment by Heheniy** [comment]
we need more sexism and racism

**Comment by Heheniy** [comment]
we need more sexism and racism

**Comment by DelineFortune** [comment]
No, women are weak

**Comment by notafurryy** [comment]
> No, women are weak

so are 90% of marshal players...

**Comment by Gyrandola** [comment]
slippery slope made manifest

**Pull request closed without merging**
