### PR TITLE
Allows you to sever external body parts, adds special biting effects during oral, and allows chained players to do some sex actions.

### PR DESCRIPTION
**Pull request by Multigamer99**
## About The Pull Request

CHANGELOG
- Implements a new "Sever external organs" surgery
  - A surgery that requires far less tools and steps than normal organ removal but leaves the patient heavily wounded on both a success or a failure.
  - To perform, use any tool that can make an incision to make one and then any tool that can remove a limb.
  - Works on eyes, tongues, ears, genitals, and any other part that is externally visible.
  - On a failure, leaves a heavy cut, on a success leaves a heavy cut and a severed vein along with removing the desired organ.
  - Intended to be an option for if you have healers on hand but not surgical tools, or don't care if the "patient" bleeds out.
- Adds special handling for biting when performing oral sex acts.
  - When performing some oral sex acts, bites will be redirected to the appropriate area (namely groin and chest).
  - Biting can be done while chained when performing oral sex acts.
  - Biting gains a damage bonus during oral sex acts.
- Allows some sex acts to be done while chained.
  - This includes most things that don't strictly need your hands, like doing oral or riding.

Bugs noticed during testing that aren't a side effect of this from what I know and that I haven't fixed yet:
- Leg chains do literally nothing.
  - It was never implemented by the looks of it.
- Unchained players in the stockade can do anything but move, including using their arms and sex acts.

Otherwise, this has been tested as much as I reasonably can on my own and should be relatively bug free. Do let me know if there are any changes requested for this.

## Why It's Good For The Game

Requested by a friend who wishes to stay anonymous: "uh players being r*ped constantly threaten to bite back but are literally unable to. the need to do field surgery is constant, be it collecting eyes or punishing criminals, but a doctor isn't always present."

For the surgery changes, it adds an element of realism and adds an easier option for removing body parts with tools players will commonly have on them while having a cost so as to help keep it from being overpowered or even a good idea when proper tools and skills are available.

For the biting changes, it adds an element of realism and risk to some of the sex actions and allows people roleplaying defiance to have a way to follow up on common threats.

For the sex acts while chained up changes, it allows players who are chained to perform certain acts that they would reasonably be able to at least somewhat do with just their hands bound and potentially gives options for fighting back while bound in conjunction with the biting changes by playing along and getting captors into vulnerable positions.

### CODE REVIEW

**Comment by EzekyalLegit** [comment]
Adds the ability to bite back when yoire getting faceraped instead of just being forced to take it. Huge, absolutely needed.

Adds the ability to give footjobs while your arms are tied up. Hilarious, absolutely unneeded but funny.

Adds the ability to actually just grab and cut someones tongue out with a knife. Absolutely metal.

**Comment by Hmeister-real** [comment]
while your messing with bites, could you also make it so getting facefucked gags you so you can't speak?

**Comment by Multigamer99** [comment]
> while your messing with bites, could you also make it so getting facefucked gags you so you can't speak?

Yeah sure. I'll add that tonight.

**Comment by Mogurk** [comment]
can you also add a way for people to scratch someone back during sex like with their claws

**Comment by Multigamer99** [comment]
Uh I believe you can already do that if unchained, or at least you can to
the extent i can test things. Is there some interaction with this that I am
not aware of?

**Comment by Mogurk** [comment]
I dont really know, but thank you appreciate the testing.

**Comment by Multigamer99** [comment]
> while your messing with bites, could you also make it so getting facefucked gags you so you can't speak?

Probably shoulda done it in a different PR given how I ended up doing it but it works from my quick testing, successfully gagging people while their mouth is sufficiently occupied. Do note that not all acts gag this way: licking someone yourself gives you enough room to speak reasonably.

CHANGELOG:
- Updated all sex actions to allow inheritance of start/stop effects
- Added two new parameters to sex actions
  - gags_user - when true, the user is gagged during the action
  - gags_targer - when true, the target is gagged during the action
- Added logic needed to implement parameter functionality into the core sex actions template
  - This lets it be inherited by all current and future (if properly made) sex actions
- Added a variable to mob/living/carbon to track if the mob is gagged via this method and updated the appropriate helper function.

... And while typing this I realized an edge case that would cause someone to ungag if their mouth is somehow in use by multiple people. Is that even possible with the current sex code? If so I can fix that real quick.

**Comment by Red-Honk** [comment]
As hot as it is to be gagged by throat fucking, that would lower the odds of RP by, well, being unable to write in say that sounds like those noises or muffing someone trying to use the emote gag or choke and the like, which would make it a tad less fun.

**Comment by EzekyalLegit** [comment]
> As hot as it is to be gagged by throat fucking, that would lower the odds of RP by, well, being unable to write in say that sounds like those noises or muffing someone trying to use the emote gag or choke and the like, which would make it a tad less fun.

They can still use ME messages to roleplay any of those things. Such as.

Player moans out loud "Mmffhhnngghh....."

**Comment by Multigamer99** [comment]
> As hot as it is to be gagged by throat fucking, that would lower the odds of RP by, well, being unable to write in say that sounds like those noises or muffing someone trying to use the emote gag or choke and the like, which would make it a tad less fun.

Yeah so it turns out gagging and choking work just fine while your mouth is blocked. You can also still me. So it should be fine.

**Comment by Murderfoxen** [comment]
Great PR. Lovely to see. :)

**Pull request merged**
