### PR TITLE
Adds sprites for young adults of all races.

### PR DESCRIPTION
**Pull request by Multigamer99**
## About The Pull Request

Creates .dmi files for all body sprites in use by playable races for their young adult variants, and implements them on each of those species. The sprites are based on the same logic used for the sprites made for blackstone to allow more than human and half elfs.

## Why It's Good For The Game

Gives more visual flavor to young adults, keeps young adult sprites more consistent, and could be used in the future for implementing an option for short characters. I also thought it would be fitting that a redo of one of my first PRs for blackstone would be my first for Ratwood.

My only real concern with this would be the fact that I have yet to test it, although I'll add a comment and any changes I need to make after I test it (sending it up early because I know it takes time to review and stuff and hey, more brains are better than one). That said, given that I did this once before, I'm fairly confident it should be fine.

### CODE REVIEW

**Comment by Multigamer99** [comment]
okay yeah i gotta fix some stuff: mutant parts don't always align for some reason? gonna need to investigate a bit

**Comment by Multigamer99** [comment]
Specifically, tails and outward legs when facing the sides have issues. IDK if outward legs is a side effect of my work though given it affects the adult too.

It tail issue effects:
Axian Men
Drakian Men
Sissean Men
Tabaxi Men
Vulpkian Men

For some reason.

The leg issue seems to be most furry races.

**Comment by BladeburstNINJA** [comment]
The leg issue actually affects every race I'm pretty sure. For males specifically it seems to be the east facing sprite that just has one random thick leg for some reason. For females, usually the rear leg is missing.

**Comment by Multigamer99** [comment]
Okay tail issue was on my end, had a back offset of -11 instead of -1.

As for the leg issue, I'll double check that. I have an idea for what it is.

**Comment by Multigamer99** [comment]
The leg issue affects the outer leg on:
Most Races Males facing right
Most Races Females in both directions
Moths in both directions (?, hard to tell)
Dwarf in both directions
Dark Elves in both directions
Elves in both directions
Half Ork men facing right
Half Ork women are fine

Let me check a few things.

**Comment by Multigamer99** [comment]
It is always the out-most leg, that "thick leg" is the back leg sprite.

It's also not a sprite issus: the outer leg sprites do exist, at least for the OG roguetown races and all but moths. Moths have their outer leg sprite baked into their normal leg spriteset instead of being a seperate thing.

Gonna go check the code for rendering this shit next.

**Comment by Multigamer99** [comment]
Okay so ork women aren't fine and it's a sprite thing there too.

Given elves use feminine sprites for men and dwarves have their own entirely special stuff going on, i'm gonna assume it is 100% related to gender somehow.

More digging to be done.

**Comment by Multigamer99** [comment]
Okay, yeah, I fixed the leg issue. Should be good now.

The female tails bug is not my doing either, although I vaguely know why it happens and I need to test if it is a side effect of hooking into other code or not. For now though, I wanna work on other shit, so that bug fix will be a separate PR. AFAIK, this PR is done.

**Comment by Useroth** [comment]
Currently closing this. Young age is a bit redundant with the direction we're going in and we'll be implementing a separate height choosing system, not dependent on age.

**Pull request closed without merging**
