### PR TITLE
Moves Steward to the town

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Moves the steward office to the town. It is extra reinforced and the doors have 5000 durability  so people cant easily break in to steal the keys, drain the treasury and whatnot.

Steward being in the town allows for a lot more interaction and traffic + removes the huge unused empty space of the old plaza, making everything more compact and claustrophobic.

image

image
image

### CODE REVIEW

**Comment by Vultchurr** [comment]
Not a fan of it. It's excessively cramped, and no that doesn't make it 'good' it just makes it unpleasant to look at or navigate.

**Comment by Heheniy** [comment]
this looks ugly as fuck

**Comment by NeoAurelian420** [comment]
it's just fucking bad man.... like look at it... the roads don't even match any more

**Comment by RadiantFlash7** [comment]
I kind of liked the old town square being open. It was a good spot. This makes the town feel kinda cramped, unessicarily.

PLUS This breaks the town road. The towns main  roads are minimum  3 wide. Thats why this feels so bad to most people is that it's impeding the town road, and constricting traffic. Solidly dislike the change unfortunately.

**Comment by Gyrandola** [comment]
Will rethink the placement together with our maptainer

**Comment by deep-fried-faceplant** [comment]
The other town square with the fountain would be a good location for this. The previous location makes the town center, that has the most foot traffic and is a known spot for people to congregate, feel cramped and worse for large gatherings. The other town center isn't really used for anything and just has a bunch of benches. People don't hang around it, they stay near the gullotine and the public tables instead.

**Pull request closed without merging**
