### PR TITLE
Gives firearm skills to experienced guards + Gives watchman skills to sheriff

### PR DESCRIPTION
**Pull request by john-pawson**
## About The Pull Request

-------------- Gives firearm skills to experienced guards ---------------
Well this should've probably been done on the firearms PR, but oh well. Here's the list of the skill given to the guards that should realistically be trained with firearms, considering their position and why i think that level of skill makes sense:

- Gatemaster: **Master** If anyone's supposed to use firearms it's this guy, considering how 90% of his combat is probably going to be ranged, the gatemaster should be the one most trained to use firearms correctly, for the same reason he's a master with crossbows and bows too. Because when he needs to fight, he *will* do it ranged.

- Veteran: **Expert** Much has to be said? He's a retired warrior that has survived countless battles, it'd make sense for him to remember how to operate a firearm like if it was second nature.

- Captain: **Expert** The captain is supposed to be the best around, he's the one that has to train all the men-at-arms and all! So at the very least he should have an expertise. Doubt it'd be much higher considering how he still uses mainly weapons like swords.

Knights don't get skilled because of the reason gyran stated below.

- Marshal: **Journeyman** He's not good with many weapons, but if someone that does mostly paperwork and laws *had* to choose a weapon to keep with himself, i can assure you it'd be a pistol and decorated sabre. Why? Expensive and powerful. It's about the same reason the duke has a firearm. It'd fit him to know how to use one. (THIS DOESN'T GIVE HIM AN ACTUAL GUN, JUST TRAINING TO BE ABLE TO.)

- Sheriff: **Apprentice** He'd probably be trained with some basic firearm knowledge after being a watchman for so long, he may not be exactly proficient with them, but he'll have some idea on how to use one when it's needed. He's probably seen them used more than any other watchman around either way.
----------- Gives watchman skills to sheriff --------------

You mean to tell me this guy, has been a watchman for longer than any other watchmen, knows the streets of this city so well, has fought crime half of his life, *but* has worse skills than the average watchman? Seriously? This just gives the sheriff the same weapon skills as watchmen, and garaunteed expertise on maces, since he's supposed to be a veteran watchman.

## Why It's Good For The Game

Gives the experienced warriors of the keep the ability to use firearms, considering how they're supposed to be the most capable around, and gives the sheriff the same skills as the role directly below him, the watchmen.

### CODE REVIEW

**Comment by Gyrandola** [comment]
Keep knights with no firearm skills. first of all because they are supposed to remain the chivalrous relic of a dying era.
second because they would rush the armory to steal the 3 arquebus and the MAA would end up with none.

**Comment by zeratino** [comment]
blackpill

**Comment by john-pawson** [comment]
> blackpill

?

**Comment by john-pawson** [comment]
> > How about you add some counter / nerf to guns before rolling them out to almost every guard player on the server.
> > And while you're at it, why don't you give antags guns too, it's only fair right?
> 
> This doesn't give guns to anyone though? Guns are still rare as fuck and only available from the keep armory or if you steal it from the duke. It's just that now the most experienced roles that should realistically know how to use a firearm, can. It doesn't make it ANY easier to get one.

"Almost every guard player on the server"
Every single role here is locked to a *single* person. You'd have at maximum FIVE people that know how to use a firearm, and these five people are *the leaders* of most of the guards.

**Comment by Gyrandola** [comment]
Not sure about gatemaster getting master but its such a hated role, lets roll with it.

**Review by Gyrandola — APPROVED** [review]

**Comment by john-pawson** [comment]
> Not sure about gatemaster getting master but its such a hated role, lets roll with it.

I don't see why the gatemaster of the bog gate should get skill firearm skill but the one of the keep shouldn't.

**Comment by Crowbar764** [comment]
> This doesn't give guns to anyone though? Guns are still rare as fuck and only available from the keep armory or if you steal it from the duke. It's just that now the most experienced roles that should realistically know how to use a firearm, can. It doesn't make it ANY easier to get one.

Called it. Rare my ass.

https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1654

**Comment by john-pawson** [comment]
> > This doesn't give guns to anyone though? Guns are still rare as fuck and only available from the keep armory or if you steal it from the duke. It's just that now the most experienced roles that should realistically know how to use a firearm, can. It doesn't make it ANY easier to get one.
> 
> Called it. Rare my ass.
> 
> #1654

Are you... referencing a PR that hasn't even been merged and has changes requested so guns aren't easy to make? Really? Is that your point? That someone is trying to make guns craftable and was the stopped on the PR itself because the mantainers realized that'd be a problem? The thing isn't even on the game!!

**Pull request merged**
