### PR TITLE
Religious Clothing Adjustment

### PR DESCRIPTION
**Pull request by Alanii**
## About The Pull Request

Removes Eoran Acolyte "alternate" dress.

This is a server that aims for immersion, not promoting ERP to be conducted in the church. 

Acolytes of Eora are not prostitutes or bath wenches, they may have "promiscious" mannerisms but they are not ladies of the night.

The code that allowed it may be preserved in this PR and could perhaps be used on other clothing that is not religious in nature.

Additionally, fixes some minor issue mentioned regarding the Dendor Amulet on Druids. For some reason the Dendor Amulet now uses the psicross onmob. Until someone shows up with a proper Dendor onmob sprite, it has been recolored to match the robes, so as not to look like a "cum stain" on the druid robes.
image

### CODE REVIEW

**Comment by xenotin** [comment]
This is bad. You're making the pantheon a shining beacon of all that's good. You're removing something that can easily be enforceable by the Inquisitor in game.

The dynamic of Baothans and Eorans being very close in means of worship was interesting. How about Inquisitors starting to enforce Eorans to wear their robes modestly? Because at the end of the day, Eoran players are in charge of their own decisions inside the church. Whether they're secretly an agent of Boatha is up to them. Removing the alternative to the dress is just removal without any sort of addition to the game. And removal in itself is bad.

**Comment by Alanii** [comment]
> This is bad. You're making the pantheon a shining beacon of all that's good. You're removing something that can easily be enforceable by the Inquisitor in game.

This is not the intent of this PR. This PR removes the "eora alternate sex dress" as it is not in line with the immersion this server aims to have. This server is not attempting to become a "sexual first" oriented server.

If the Eoran Acolyte character wants to act like a sex pest, they may do so against the updated Eora description. However the codebase should not enable players to act in this manner.

> The dynamic of Baothans and Eorans being very close in means of worship was interesting. How about Inquisitors starting to enforce Eorans to wear their robes modestly? Because at the end of the day, Eoran players are in charge of their own decisions inside the church. Whether they're secretly an agent of Boatha is up to them. Removing the alternative to the dress is just removal without any sort of addition to the game. And removal in itself is bad.
image

Eora's original "lust" nonsense was removed in favor of making it more about love. Whether or not the love is "wholesome" or "family values" is up to the player's interpretation and the Priest of the current round. 

See above response regarding the "sex dress."

> At the end of the day the Pantheon is a PAGAN RELIGION. Why're we forcing values from the modern world onto a Medieval setting?

The only characters in the game that refer to the pantheon as "pagan religion" are those who follow Psydon. As common sense would dictate, the most of this world follows the Pantheon in this region. Thus it is not a pagan religion.

> If you simply don't like the setting you're in. You're free to leave the server. Because I can see you have zero interest in carrying roleplay inside the setting in order to snuff out disordered behavior. You're so worried about whores in the church rather than people who won't roleplay at all.

This is not related to the PR and will be ignored.

**Comment by xenotin** [comment]
> This is not related to the PR and will be ignored.
Yeah, I'm not even going to entertain a response, because I know I can't change your mind. But hopefully anyone reading will see the utter and complete nonsense you've been bringing onto the server.

**Comment by NikolayByondPlayer** [comment]
Less ERP is good

**Comment by NikolayByondPlayer** [comment]
> This is bad. You're making the pantheon a shining beacon of all that's good. You're removing something that can easily be enforceable by the Inquisitor in game.
> 
> The dynamic of Baothans and Eorans being very close in means of worship was interesting. How about Inquisitors starting to enforce Eorans to wear their robes modestly? Because at the end of the day, Eoran players are in charge of their own decisions inside the church. Whether they're secretly an agent of Boatha is up to them. Removing the alternative to the dress is just removal without any sort of addition to the game. And removal in itself is bad.
> 
> At the end of the day the Pantheon is a PAGAN RELIGION. Why're we forcing values from the modern world onto a Medieval setting?
> 
> If you simply don't like the setting you're in. You're free to leave the server. Because I can see you have zero interest in carrying roleplay inside the setting in order to snuff out disordered behavior. You're so worried about whores in the church that you've coded an alternative style of the robes, rather than enforce rules in-character in order to stop that behavior from occurring. Because I promise you, this won't change a thing about Eoran Acolytes.

God no most of templars and acolytes are already galavanting into erping for 3 hours if we have less incentive for them to do that that would be good.

Also Eora and Baotha being close is a bad thing that just makes them too similar, honestly I would just leave one-two main Gods for the humen pantheon but alas.

**Comment by NikolayByondPlayer** [comment]
> I will say as someone who helped with the eoran port that you or anyone else is not forced to do ERP as eoran (yeah, it's more an IC issue). It's already your beliefs, perceptions that eorans shouldn't dress like that, again no one is forcing you. I have yet to see anyone at all walking around in alternate robes in the round or eoran templar fucking with anyone.
> 
> I respect the original code and I don't want that removed just because someone thinks this is wrong.

This PR just deletes ability to open dress for ERP interactions methinks
image

**Comment by Vladmar11** [comment]
Why don't we remove the ability for the acolytes of Eora to take off their clothes altogether? They'll take off their clothes and fuck around. 
No one's forcing them to walk around like that

**Comment by Alanii** [comment]
> I will say as someone who helped with the eoran port that you or anyone else is not forced to do ERP as eoran (yeah, it's more an IC issue). It's already your beliefs, perceptions that eorans shouldn't dress like that, again no one is forcing you. I have yet to see anyone at all walking around in alternate robes in the round or eoran templar fucking with anyone.
> 
> I respect the original code and I don't want that removed just because someone thinks this is wrong.

The only removal is the "eora robe alternate" of which is simply a "strapless dress" that shows genitals along with the "right click" 'feature' that enables you to change the robes to this strapless dress.

Removing the alternate clothing piece removes the unintentional alluding of Eora promoting walking around in the nude and instead should be left to player interpretation if they wish to force it. Something that is currently a gray area when it comes to Dendor and their Druids.

It was already mentioned with Gryan that this should probably not have ever been merged with such a feature as it is "too erp focused."

Leaving the "eora robe alternate" to stay removes the ability for a Priest or any other member of the clergy to argue against some player's interpretations when it comes to nudity for those who follow with Eora without them showing off the "fanatical version" of the Eora robes.

We do not want the Eora Goddess to become some weird "Corruptions of Champions" religion.

**Comment by NikolayByondPlayer** [comment]
> Why don't we remove the ability for the acolytes of Eora to take off their clothes altogether? They'll take off their clothes and fuck around. No one's forcing them to walk around like that

Толсто накинул

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
