### PR TITLE
Places a single purity vendor in the sewers. Remove all others.

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

I don't know who added drugs vending machines all over the place,  but Rockhill is not Amsterdam.
There is now only a single purity machine, and it's in the sewers, where crackheads live.

image

### CODE REVIEW

**Comment by Red-Honk** [comment]
At least add its own room, that risks someone getting ambushed or something, because this just looks lazy and time wasting in my opinion.

**Comment by Red-Honk** [comment]
At least add its own room, that risks someone getting ambushed or something, because this just looks lazy and time wasting in my opinion, like a crack den or the like, a very messy one, places to crash at, relax, so, it's all low tier stuff, but I doubt anyone will notice after the first or second hit.

**Comment by NikolayByondPlayer** [comment]
I have one near bath house, maybe we can just cut others?

**Comment by Nakalon** [comment]
Good! All seems well with the map files too! (seamless wont be flung into the vampire cave again xD)

**Comment by Nakalon** [comment]
> At least add its own room, that risks someone getting ambushed or something, because this just looks lazy and time wasting in my opinion, like a crack den or the like, a very messy one, places to crash at, relax, so, it's all low tier stuff, but I doubt anyone will notice after the first or second hit.

Quick solution: Don't do drugs!

You junkie!

**Pull request closed without merging**
