### PR TITLE
Whips blunt damage and punish damage modifier to 0.5

### PR DESCRIPTION
**Pull request by MickDick1**
## About The Pull Request

Changes all whip intents to blunt damage.
Changes punish intent to halve its damage.

## Why It's Good For The Game

Whips delimbing is whack.
Whips embedding is whack.
Whips being turbo lethal, a melee weapon with 3 range and 40 AP, is whack.
Punish intent no longer defaults to massive hematomas as a result of the base damage being too high on regular whip.

### CODE REVIEW

**Comment by katsukai** [comment]
I think these changes are warranted since it is still quite formidable weapon that hits from far and you cannot dodge or parry the attacks from distance.

**Comment by Keazra** [comment]
To non-robust players like me, someone with a whip is basically unassailable if I'm not covered head to toe in armor. The nerf is needed.

**Comment by radarseas** [comment]
needed honestly, it already still has 40% armor peircing, insane range, decent swing time, in the case of a normal whip it FITS INTO A BACKPACK which is arguably more than it ever should have considering most weaponry stab intents only have 20% armor peircing. _(seriously what the **fuck?**)_


blessed PR.

**Comment by Useroth** [comment]
Could also split whips into its own combat skill rather than shared with flails.
And give it only to the dungeoneer and inquisitor (and the odd migrant/adventurer ones)

**Pull request merged**
