### PR TITLE
Inquisitor New Job Description 

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

Changes the Inquisitor's job description to something that makes sense.

### CODE REVIEW

**Comment by Maromar15910** [comment]
I like it over all, but it feels like it pressures the inquisitor into a personality type. Less 'inquisitors are typically this' and more 'you ARE this', which can limit rp or verbally slap people around for not being the buzz lightyear meme.

**Comment by SixplyDev** [comment]
Frankly, I don't know how to feel about this change. I do think that making the inquisitor's description clearer or more in-line with the current lore that we have is needed, but I also think that this would only make treatment of inquisitors worse than it already is. This implies that it's a religious nutjob that's probably a hermit or some crap, not an educated and powerful man that's there to carry out a noble duty. 

I would much rather see this transformed into implying that the inquisitor is a learned man that's from a much more powerful but mysterious authority. I would also like to see it more imply/say why the inquisitor was hired even though they believe that the church has been taken over by heretical pagans. Overall, I do not think that this change would benefit the inquisitor and I believe that it would in fact harm the inquisitor and how people treat the role.

**Comment by SixplyDev** [comment]
> > **[SixplyDev](/SixplyDev) ** commented [Sep 3, 2024](#issuecomment-2325548551) •
> 
> Pretty much all you wrote is your headcanon

Psydon patron description literally says that you believe the church was taken over by heretical pagans 💀 but I would genuinely like to see something more in line with a man with authority rather than a hermit from a fading cult

**Comment by Cyprex** [comment]
Very mixed feelings on this as well, @GuppyLaxx what do you think?

**Comment by Keyo360** [comment]
As a repeating Inquisitor player, Inquisitors are already looked down upon incredibly in game even if the Kingsfield Queen has sent them for whatever purposes she might have. This change will only amplify that and completely destroy the chance of an Inquisitor to do much any round due to the lack of authority and standing.

**Pull request closed without merging**
