### PR TITLE
Keep tweaks and fix

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
Fixed double hand closet
Separated a mount of steward keys into 2 separate chests
image
Added 2 torches into keep dungeon place where was no light at all
image
Moved street lamps away from roads
image

## Why It's Good For The Game
Dark places in the keep, a mount of keys and lamps in the middle of road is no good

### CODE REVIEW

**Comment by Nakalon** [comment]
image

Mapdiff isnt working for some reason. Can't review without it

**Comment by Nakalon** [comment]
Can you try to do an empty commit to force the checks to re-run please?

**Comment by Heheniy** [comment]
@Nakalon this is super weird

**Comment by Nakalon** [comment]
> @Nakalon this is super weird

Did you kill the snake!?!?

**Comment by Nakalon** [comment]
Mapdiff still bugged...

**Comment by Heheniy** [comment]
fucking diff

**Pull request closed without merging**
