### PR TITLE
Dungeons

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Moves the gateway from inside the gate to the left of the bog village into the bog, it's far away from the bog gate

Currently it loads one of two dungeon map files, but they are the same right now, the loot spawns are randomized but in the same locations, at the end of the dungeon is where the good loot is, and it's full of hostile mobs

## Why It's Good For The Game

Gives something for players to do who want to go fight PVE battles and get loot (adventurer players)

Showing the mobs&drops while aghosting (this was filmed when it wasn't complete)

https://github.com/user-attachments/assets/a1ce3d4d-92a3-4679-b573-b339f6be4ec0

Me getting rekt trying to show off

https://github.com/user-attachments/assets/b1228997-5eb1-4e2d-a77d-83aef76e0e3f

And now showing gate location

Screenshot 2024-08-10 003427

And the dungeon so far, it's pretty basic but mappers and such can build upon it
Screenshot 2024-08-12 100612

### CODE REVIEW

**Comment by zakanater19** [comment]
Also the "dungeons" area that is now loaded is 100x100 and only 1 Z, on local it had next to no impact on startup time

**Comment by zakanater19** [comment]
Changed the lava to deep murk to avoid cheese

**Comment by zakanater19** [comment]
Buffed the mobs slightly

**Comment by dotCatshark** [comment]
This is pretty dope. What about moving the gate out, just so people have more of an incentive to venture out into the bog?

**Comment by zakanater19** [comment]
> This is pretty dope. What about moving the gate out, just so people have more of an incentive to venture out into the bog?

Yeah i could do that, the bog cave entrance area was kinda placeholder anyway

**Comment by zakanater19** [comment]
Moved the gate to deep in the bog

Screenshot 2024-08-10 003427

**Comment by Drayco84** [comment]
Need MULTIPLE dungeons, but this is pretty good as a first step or prototype. Maybe add some loot like a few piles of mammons, gold, potions, and/or rare weapons/armor.

To really make things interesting, need a system that lets the mobs convert failed player corpses into haunts or skeletons.

**Comment by zakanater19** [comment]
> Need MULTIPLE dungeons, but this is pretty good as a first step or prototype. Maybe add some loot like a few piles of mammons, gold, potions, and/or rare weapons/armor.
> 
> To really make things interesting, need a system that lets the mobs convert failed player corpses into haunts or skeletons.

There are already two dungeons, but they are identical because i'm not really a mapper, and there is already loot spawners for the dungeon and i placed some good loot at the last section of the dungeon

And yes maybe, or turning them into the hostile aggro zombie maybe

**Comment by zakanater19** [comment]
Updates from this point are just adding more rooms/details to the dungeon

**Comment by zakanater19** [comment]
Just changes the descriptor text for the dungeons.dm

**Comment by zakanater19** [comment]
Increases hauntpile spawn rate

**Comment by X404ErrorX** [comment]
This is good as fuck, finally dungeons.

**Comment by zakanater19** [comment]
OK that fixed it

**Comment by zakanater19** [comment]
gonna need the funny mapping tool thing

**Comment by zakanater19** [comment]
So this needs more work

**Comment by DavidAreYouSure** [comment]
If you could add something to rotate or respawn maps after they were cleared it'd give adventurers something to do continuously or make it something that occassionally spawns a new gate in the bog SOMEWHERE instead of being a static thing. Like every 30 minutes a new dungeon opens SOMEWHERE

**Comment by Useroth** [comment]
Other changes in a new PR

**Pull request merged**
