### PR TITLE
Stun Mace Return

### PR DESCRIPTION
**Pull request by ProbablyCarl**
Makes stunmaces drain stamina and fatigue. When a target is at no stamina, it acts like it used to, electrocuting and stunning the target. The mace does 6 damage when active, 25 when off.
Also gives the guards gorgets. Because they used to have neck protection.
## Why It's Good For The Game
The mechanic was removed temporarily pending rework. I'd argue this is technically a rework.

### CODE REVIEW

**Comment by Nakalon** [comment]
I'mma wait on Gyrans aproval since they're the one this is being done for 😳

**Review by Gyrandola — DISMISSED** [review]

**Comment by hugmeorelse** [comment]
They should get chain coifs instead of gorgets.

**Comment by ToothyDeer** [comment]
we did it guys. we got ss13 sec in roguetown

**Comment by Heheniy** [comment]
4 hits to win any fight and 7 to leave target completely without stamina

no

**Comment by hugmeorelse** [comment]
Un-TMed.

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
