### PR TITLE
Rebalance betweeen life and war clerics

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

Suggested by @fallenfalse on discord (shout at him not me). Lif eclerics are now non-combat focused, get great intelligence at the cost of losing a lot of their combat/survivability skill along with the heavy armor skill, encouraging them to stick near other people. War clerics on the other hand now get negative int and speed, and less stat boosts then before, at the cost of keeping their heavy armor trait, and weapons skills but losing a lot of their laborer skills and such. go read the code. Also if you want to argue with this further, please explain to me how the blessing spamming/kneestinger spamming, heavy armor and very good stat wise class deserves to have infinite slots.

## Why It's Good For The Game

 Clerics are OP and the most commonly chosen adv class, now they are limited to only 5 slots and not guaranteed (25% chance to show up)

### CODE REVIEW

**Comment by wow50000** [comment]
oh hell no

**Comment by radarseas** [comment]
I think... 3 is far, far, far too few... 6? 10? slots, remember that not every, single cleric makes it alive to the town.


Also unlike paladins who can just strip naked against vampires and STILL miracle (yes templars don't have restricted casting) clerics still need their amulet.

**Comment by Hmeister-real** [comment]
> I think... 3 is far, far, far too few... 6? 10? slots, remember that not every, single cleric makes it alive to the town.
> 
> Also unlike paladins who can just strip naked against vampires and STILL miracle (yes templars don't have restricted casting) clerics still need their amulet.

clerics are spammed out, the whole idea is to limit them since theres max 20 adventurers + random waves of adventurers. and be honest they don't really die...

**Comment by X404ErrorX** [comment]
The only good part of clerics are the spells and the auto heal, in combat skills they are worse than other adventurers, in stats they are mid, in gear they are bad, there is no a real reason to limit them to THREE slots lmao, someone got owned by a cleric and made this salt pr.

**Comment by Hmeister-real** [comment]
> The only good part of clerics are the spells and the auto heal, in combat skills they are worse than other adventurers, in stats they are mid, in gear they are bad, there is no a real reason to limit them to THREE slots lmao, someone got owned by a cleric and made this salt pr.

literally no, clerics have the heavy armor trait, free healing and get very good stats too. i got told to make this PR by someone else anyway, so complain to fallenfalse on discord

**Comment by radarseas** [comment]
I find a \lot\ of undead clerics as a bandit, its usually clerics that do die... weirdly enough. next to pilgrims, they're the most common dead to fauna adventure classes I find.

**Comment by Hmeister-real** [comment]
> I find a _\lot_ of undead clerics as a bandit, its usually clerics that do die... weirdly enough. next to pilgrims, they're the most common dead to fauna adventure classes I find.

probably because maces are genuinely awful against mobs tbf, thats a fair point. But thats why adventurers should stick together

**Comment by ddsaw** [comment]
Instead, just nerf clerics?

**Comment by Elli-Skala** [comment]
This may be redundant when rituals get merged

**Comment by CalamaBanana** [comment]
Cleric is all that is wrong with adventurers. Powerful magic that imbalances half the game modes. Endless respawns of vampire hard counters and endless respawns for kneestinger powergamers. 

They should absolutely be a rare limited class.

**Comment by BladeburstNINJA** [comment]
Remove pickchance, I wouldn't mind raising PQ requirement for it, but making it rng is a no go.

**Comment by Teragenic** [comment]
Update description with pictures and proper images of changes made. There's undocumented changes.

It's far too many for simply 'Balance changes'

**Comment by Altangy** [comment]
"Powerful class". I can understand some people look at the Dendor clerics and go "Oh those knee stingers are strong", but to assume that healing in the middle of swinging is viable is just funny and speaks to how little people actually use them.

Healing drains a not insignificant amount of stamina and even miracle itself wont close wounds.
Others have stated that their combat skills are mid at best.
Everywhere else, the strengths of the clerics only come into play in high attrition battles which sometimes involves bandits who also get clerics joining up with them.
Limiting the cleric slots means that the bandits might get all the clerics or none of the clerics and I can tell you that the big thing I always hear from bandits is that they want a dedicated healer.

**Comment by Hmeister-real** [comment]
> Update description with pictures and proper images of changes made. There's undocumented changes.
> 
> It's far too many for simply 'Balance changes'

sure, can do tomorrow.

**Comment by Hmeister-real** [comment]
> "Powerful class". I can understand some people look at the Dendor clerics and go "Oh those knee stingers are strong", but to assume that healing in the middle of swinging is viable is just funny and speaks to how little people actually use them.
> 
> Healing drains a not insignificant amount of stamina and even miracle itself wont close wounds. Others have stated that their combat skills are mid at best. Everywhere else, the strengths of the clerics only come into play in high attrition battles which sometimes involves bandits who also get clerics joining up with them. Limiting the cleric slots means that the bandits might get all the clerics or none of the clerics and I can tell you that the big thing I always hear from bandits is that they want a dedicated healer.

its op from a non-combative stand point. Blessing completely decimate Vampires, and nullify life threatening injuries. Im too tired to argue this atm but they are OP for the healing they bring to the table and at mass, limiting clerics to less slots allows for more risk to occur since there is less people there to heal you with blessings

**Comment by Alanii** [comment]
Clerics are generally an issue.

The fact they can just replace the church also makes it a bit of a meme. As a suggestion, remove anastasias from astrata cleric perhaps.

**Comment by DorfGuy1** [comment]
> Clerics are generally an issue.
> 
> The fact they can just replace the church also makes it a bit of a meme. As a suggestion, remove anastasias from astrata cleric perhaps.

UGH, I really feel you on this one. Constant wandering clerics, typically just white knights or otherwise stupid, is frustrating. On the otherhand they're a lifeline for bog settlement. They can get some of the benifits of church to those outsider communities. I've seen some real bro clerics. Although, maybe we focus on the issue that if the clerics are round, then the church does not have a monopoly of holy power, which is a challenge to their legitimacy.

**Comment by radarseas** [comment]
better nerf against clerics honestly would be to make it so only PALADIN/TEMPLAR miracle casters can use miracles to 100% on themselves like fixing fractures.

Make it so anyone that isn't those (they only have 100 devotion in comparison) casting miracles on themselves gets only 30% of the healing casting miracles on themselves and fractures, broken ribs or smashed skull/jaw/spine can't be fixed by self-miracling.


before you argue anything against this, they serve the same gods as the church, unless you piss them off they'll fix you anyway without asking much, moreso because you can actually cast miracles to help out.

If you wind up like that, you're as dead as everyone else anyway. Should have ran while you could.

**Comment by EzekyalLegit** [comment]
Anyone here who is trying to argue clerics are not incredibly overpowered has no idea. They're baby knights that can self heal with incredibly valuable mace skill, combat stats, plate training, and miracles. A single cleric can easily kill a group of bandits in the gear they spawn in a 4v1 fight and you see it happen. I've personally wasted entire bandit parties and gone on to be a front liner against the vampires all in one round. I can heal my limbs and instantly crack skulls from the time I spawn in. Choosing classes that aren't cleric feels like intentionally picking a weaker option.

Clerics could be nerfed down to churchlings with a mace, no armor training, and wood shield and leather armor and they would still be a huge value pick being a warrior that can heal and use maces. I would still pick them consistently.

**Comment by Teragenic** [comment]
I mean. You can just make miracle not be able to Self-Heal. It was added from Blackstone but was originally not allowed on OG Roguetown.

**Comment by Teragenic** [comment]
> Anyone here who is trying to argue clerics are not incredibly overpowered has no idea. They're baby knights that can self heal with incredibly valuable mace skill, combat stats, plate training, and miracles. A single cleric can easily kill a group of bandits in the gear they spawn in a 4v1 fight and you see it happen. I've personally wasted entire bandit parties and gone on to be a front liner against the vampires all in one round. I can heal my limbs and instantly crack skulls from the time I spawn in. Choosing classes that aren't cleric feels like intentionally picking a weaker option.
> 
> Clerics could be nerfed down to churchlings with a mace, no armor training, and wood shield and leather armor and they would still be a huge value pick being a warrior that can heal and use maces. I would still pick them consistently.

>incredibly Valuable mace skill. 
Quite literally average mace skill for combat class.

Sounds like we need to remove self-healing like old Roguetown

**Comment by Altangy** [comment]
Most people here are proving they don't understand stamina management and are letting the clerics get away to heal when it's safe then reengage

**Comment by X404ErrorX** [comment]
Every comment about clerics being op just show an massive skill issue.

>"Incredible maces skill", Clerics have maces skill in 3, 2 if life cleric, thats "incredible" for you? lmao

>They have good gear? The only "good" thing they have is the half place that only protect THE UPPER CHEST, how thats op lol
Just attack literaly every other body part.

>Yes they have heavy armor training, but as a lot of other classes they need to get it, and thats not eazy on late game everyone have good armors, not only clerics.

>Lesser miracle dont save you of a critic or instatly heal every part of your body, it heal some points of damage, cut/slash/hit per use, if you have 5 Slash on an limb you need to use miracle 5 times or 6 if you have blood lose, that USE A MASSIVE STAMINE AND DEVOTION and take a lot of time, also in a fight you parry and attack, that also use stamina, lesser miracle dont gonna save you in an fight, you always will need to leave to heal your self.

>Every cleric spell have counters, just dont be dumb and think a bit.

>Their stats and skills are mid, obviusly they dont gonna have the stats of an beggar, they are a combat class, but compared 
to other kinds of adventurers clerics are not that good.

And yes they are good against vampires, thats literaly the point, but a good vampaire can always win an fight 1v1, just dont rush at the damn cleric in malee and use your brain.

Also an vampire lord should always win fight against clerics, if you lose against one you are just bad get robust buddy.

**Comment by Yamitaicho** [comment]
> Anyone here who is trying to argue clerics are not incredibly overpowered has no idea. They're baby knights that can self heal with incredibly valuable mace skill, combat stats, plate training, and miracles. A single cleric can easily kill a group of bandits in the gear they spawn in a 4v1 fight and you see it happen. I've personally wasted entire bandit parties and gone on to be a front liner against the vampires all in one round. I can heal my limbs and instantly crack skulls from the time I spawn in. Choosing classes that aren't cleric feels like intentionally picking a weaker option.
> 
> Clerics could be nerfed down to churchlings with a mace, no armor training, and wood shield and leather armor and they would still be a huge value pick being a warrior that can heal and use maces. I would still pick them consistently.

for someone who wants to defend the class you sure want to sound like the nerfs were needed. Who enjoys getting nerfed?

**Comment by Yamitaicho** [comment]
> I just read undocumented changes. The clerics are nerfed into ground with this nerf. Not only they are rare chance to pick now, they are just pretty much bad idea to pick. Both stats and skills suffered greatly to the point that acolyte is now a stronger combat class than a cleric. Utter nonsense. In a nutshell clerics had a lot of important skills nerfed hard and in trade got a few unimportant skills that they are either never gonna use or they're very easy to learn in game. The wrestling skill being dumped to miserable 1-2 along with strength nerfs is what puts the final nail in clerics combat capability's coffin. This essentially means anyone can manhandle them with ease.
> 
> Life cleric got a buff in maces skill but the other nerfs are so drastic that even if they were expert in maces, they'd still be useless in a direct fight. Half-plate being changed into hauberk was likely meant to be a nerf but it is actually a small buff in terms of gear.
> 
> War clerics got a steel mace which is a pretty considerable gear improvement, but it still absolutely pales in comparison to how much was nerfed.
> 
> Reading through all the unlisted changes ontop of listed ones made me conclude it's not maybe-a-salt pr. It's a straight up rage pr.
> 
> Here is list of changes.
> 
> Life Cleric.
> 
> nerfed skills: crossbows 2 => 0 bows 1 => 0 wresteling 3 => 1 swimming 1 => 0 climbing 2 => 1 knives 3 => 2 (total nerf: 8 skill points)
> 
> buffed skills: sewing 2 => 3 cooking 1 => 2 riding 1 => 2 maces 2 => 3 (total buff: 4 skill points)
> 
> intelligence 2 => 3 strength 1 => 0 constitution 2 => -1 speed 0 => -1 (total nerf: 4 stat points) (total buff: 1 int)
> 
> Half-plate replaced with hauberk.
> 
> War Cleric.
> 
> nerfed skills: crossbows 3 => 0 polearms 2 => 1 bows 1 => 0 wrestling 3 => 2 reading 3 => 1 sewing 2 => 0 medicine 2 => 0 cooking 1 => 0 (total nerf: 13 skill points)
> 
> buffed skills: swimming 1 => 2 athletics 2 => 3 (total buff 2 skill points)
> 
> Intelligence 1 => -1 constitution 2 => 1 speed -1 => -2 (total nerf: 4 stat points)
> 
> Iron mace replaced with steel mace.

Oh wow, that's just bad. Looking at these numbers it looks more like something straight out of a horror movie. I thought Life Cleric was bad enough but looking at War Cleric's numbers, 6x more debuffs. A 2 to 13 ratio is completely insane. The game has a lot of mechanics that are not common knowledge and everything that exists has a proper counter so the fact they want to make it easier to deal with clerics' means probably our dearly antagonists or even just plain powergamers can't manage to find these counters so they turn to the next best thing: getting the entire class nerfed, this was basically nerfing them into the ground in hopes of quelling the complaints that they are too strong. But it's just another change that's going to hit player numbers... Yet again.

**Comment by NikolayByondPlayer** [comment]
Would be cool if adventurers amount would be reduced

**Pull request merged**
