### PR TITLE
Bundle of unpopular changes

### PR DESCRIPTION
**Pull request by Useroth**
- ~~Makes man-eaters a bit harder to get out of alone, much easier if you're pulling somebody out of them~~
- ~~Makes combat mode stronger against vampires' transfix~~ 
- ~~Makes miracles melee-ranged~~ // tests over - the time for those is not yet
- Makes half the fall damage ignore armour
- Makes soap slip only 20% of the time

### CODE REVIEW

**Comment by ThyBaron** [comment]
200w

**Comment by Red-Honk** [comment]
Mircles?; Melee range?; Why not range 2 or 3, why Melee?; They better be at least buffed if they're gonna get nerfed that badly, jeez.

**Comment by Keazra** [comment]
My assumption is to make them more like a Paladin's Lay on Hands.

Why the maneater buff? Truly the worst element of this game.

**Comment by Useroth** [comment]
> My assumption is to make them more like a Paladin's Lay on Hands.
> 
> Why the maneater buff? Truly the worst element of this game.

Because even a weak lone character is about unaffected by them unless someone wounds them and throws them into a man eater while stunned.

**Comment by TheodoraMoon** [comment]
Remove Miracle from templars add them lay on hands or buff acolytes and priest for combat, we cannot even wear armor, don't have stats for it either, and you want us to get frontline to stun them

**Comment by HissyNays** [comment]
> Remove Miracle from templars add them lay on hands or buff acolytes and priest for combat, we cannot even wear armor, don't have stats for it either, and you want us to get frontline where we get a random Artery instantly

I never seen anyone try to send acolytes or priestess into frontline, it's non-combat roles and acolytes are surprisingly capable in combat.

**Comment by HissyNays** [comment]
Miracles being melee only is a cancerous indirect-buff to vampires, I'd understand if it were a 3 tile range at least.

**Comment by radarseas** [comment]
while I absolutely hate the miracle hardstun with all of my will to live, melee range is a _liiiiiiiiiiiiiiiiittle_ tight, that's the range I can spam mace hits over the head on swift intent and break your spine through a heavy helmet in under 3-4 seconds... with my infinite stamina that obliterates your own stamina. at least 1 extra tile away? maybe? 2? perhaps...?

Not sure about maneaters, _bandits/vampires_ don't have any reilable way to deal with limb loss but suicide or basically hoping someone just fixes them out of good will.

God forbid an unlucky vamplord walks into one and gets their leg torn off about 30 minutes into the round, since most people don't know how to pull people out and they can grab you pretty fast after leaving it anyway.

**Comment by X404ErrorX** [comment]
I like mireacle being dangerus and the best weapon against vampires, we would not reward people for get converted into a vampire, i mean, you should always try to avoid get turned into an vampire, if we turn it into an infinite stamina, night vision, stats buff with an magical insta win buttom  without an bad part the game mode loses sense. in the actual way atleast people know if they get converted they are in danger against clerigy.

Also, i think the best way to balance it is make the VL immune to lesser miracle stunt, but only the VL, the thralls should still getting stunned.

**Comment by Lhars** [comment]
Awful. awful PR made to sait the salt of bad vampire players and self antags - Miracles were never an issue to vampires in blackstone, you might want to ask yourself why they seem to be the case here and if it's a skill issue or not.

**Comment by Altangy** [comment]
I love how we keep pandering to vampire fraggers. Does no one remember when vampires were made immune to miracles and they abused their miracle immunity to just slaughter the server with their infinite stamina, double class picks, and self regen?

**Comment by radarseas** [comment]
> Also, i think the best way to balance it is make the VL immune to lesser miracle stut, but only the VL, the thralls should still getting stunned.

this results in vamp lord, going solo with a mace and bat form + mist form, instead of bothering to convert, killing people outright.

This is _about as fun for everyone as you'd guess._

**Comment by DeerJesus** [comment]
Maneater buff is, truly, aids

**Comment by radarseas** [comment]
I will say this about maneaters, vampires have it far, far, far too hard to be enjoyable to come back from losing limbs. Let alone every source of them is likely to miracle you. 

It takes nearly an entire round to get a limb fitted RN, unless a barber doc just randomly stays in bog all round (they won't because werewolves roll)

**Comment by DorfGuy1** [comment]
> while I absolutely hate the miracle stunlock with all of my will to live, melee range is a _little_ tight, that's the range most vlords and their minions will be swinging at with swift-strikes that destroy your stamina, although it'll be interesting to give it a shot I suppose? _Beats being miracle sniped from atop a tree or something off-screen_ and makes stealthpire semi-possible again.
> 
> That and churn undead should _**always**_ work on undisguised vampires because it literally should, its currently uhh, **30 devotion** with a chance to do _**absolutely nothing against a vampire even undisguised**_. Church needs _some_ leeway fighting vampires.
> 
> Vlord can just travel with their army to counter this strat but _honestly with some sane cooldowns to mist+bat form_ to make it less spammable plus probably a limit on the time for mist form. it **should be** counterable by just focusing the lord and churning the rest of their army with magics before they snowball too hard.

There was a round where the vlord spent upwards of an hour as a bat hovering over the fucking river. It was horrible.

**Pull request merged**
