### PR TITLE
De-resourcing of Lumber and Mine in the town (big change)

### PR DESCRIPTION
**Pull request by Hmeister-real**
This is needed for the health of game

## About The Pull Request

Currently the mine is literally just better than the lavaland, and the lumber is plentiful enough to last the entire round and get people rich without having to go far from the town at all. This PR removes a lot of the trees, only leaving the far west of the bog town (past the bridge) as the last remaining forest within the walls, the rest is now just lone trees and stumps. The big change is to the mine, beforehand the entire mine was god awfully strong, literally just better than the lavaland, i have no idea how it has remained like this (check image).

## Why It's Good For The Game

Less resources, more likely people go to the bog for stuff, especially with #754 if that gets mergd too

Before hand: (the yellow is on par with the lavaland, high chance, purple is medium, and green is low)
image
comparison: 
image
Now: 
image

### CODE REVIEW

**Comment by Hmeister-real** [comment]
If this gets merged, i will start working on making manually added dungeon-esque rooms using the unused molerats to the mine that have loot inside. but thats for the future

**Comment by DelineFortune** [comment]
A good idea, honestly. People have no intentions to go into lava mines and deal with antags because they can get same ore drop rate around the castle

**Comment by DorfGuy1** [comment]
We have mines near the castle?

**Comment by MickDick1** [comment]
Finally, someone got around to this. Absolutely necessary.

**Comment by Elli-Skala** [comment]
Another towner L

**Comment by Alanii** [comment]
Good PR.
This PR is necessary for the growth of roleplay outside in the bog.

This will bring more role play to the towners who now have to either get good at fighting or hire mercenaries or bother the keep for soldiers so they may do their job. 

Soon the bog guard and men at arms will form patrols to check the bog and make sure it is safe for towners to venture forth.

This is a good change and will at no way hamper antagonists.

**Comment by zeratino** [comment]
why remove the trees

**Comment by Elli-Skala** [comment]
This PR appears to also make it so the lower levels of the mountain are unmineable for some reason

**Comment by Alanii** [comment]
For a legitimate comment.

Remove the "remove trees" nonsense.

The mine PR itself is fine, but the arbitary removal of trees just seems like a horrible attempt to "stop people from cutting trees around town"

Because you neglected to actually remove every tree within the rockhill, and instead just removed them around the town.

If your intent is to actually force Towner's into the lava mines for actual ore this PR will not do that. It will just push more towners into other roles, and smith will start begging the steward to import materials when miners are not too interested in going to the lava mines when 70% of the rounds are Bandits.

This is just more fun for the combat and antagonists than it is for anyone else.

When submitting such a heavy handed change, you may want to try to look at balancing things instead of outright removing or 'nerfing' things. Elsewise you just end up pushing players to try other roles and abandon roles entirely.

**Comment by Hmeister-real** [comment]
> For a legitimate comment.
> 
> Remove the "remove trees" nonsense.
> 
> The mine PR itself is fine, but the arbitary removal of trees just seems like a horrible attempt to "stop people from cutting trees around town"
> 
> Because you neglected to actually remove every tree within the rockhill, and instead just removed them around the town.
> 
> If your intent is to actually force Towner's into the lava mines for actual ore this PR will not do that. It will just push more towners into other roles, and smith will start begging the steward to import materials when miners are not too interested in going to the lava mines when 70% of the rounds are Bandits.
> 
> This is just more fun for the combat and antagonists than it is for anyone else.
> 
> When submitting such a heavy handed change, you may want to try to look at balancing things instead of outright removing or 'nerfing' things. Elsewise you just end up pushing players to try other roles and abandon roles entirely.

i specifically removed them in places around the town to force people to at least travel further for lumber rather than have all the trees they need directly in the town. I specifically left the forest far west and the few lingering trees so people can still do treehouses and stuff, and very small lumbering for making one or two things, but for entire cottages you now need to actually go somewhere else for lumber. The mining complaint can be true in theory, but i expect for people to continue mining and for there to just be less ore around, encouraging people to go to the lavalands or elsewhere to mine eventually. either way the mine right now in still stupidly too strong and this alleviates that issue

**Comment by Cyprex** [comment]
The lumber: I really like it when people built stuff close to the town, and trees in those spots help that. The ore: Well, Lavamines are rather remote, do people often carry ore from the lavamines to the stockpiles?

**Comment by Cyprex** [comment]
Honestly you can nerf the mines a little if you really wnat but other than that I don't think I like this.

**Comment by Cyprex** [comment]
We've talked about this and we don't really like this. The idea of forcing people out of the town is good, but there's fair worries about pushing towners into other roles(Lumber and iron ore are already often low in stock). That, and bringing ore back from the lavamines is a hassle- I'm not sure it's worth it. That's not to say a less heavy-handed change to ore wouldn't be merged!

**Comment by Hmeister-real** [comment]
> We've talked about this and we don't really like this. The idea of forcing people out of the town is good, but there's fair worries about pushing towners into other roles(Lumber and iron ore are already often low in stock). That, and bringing ore back from the lavamines is a hassle- I'm not sure it's worth it. That's not to say a less heavy-handed change to ore wouldn't be merged!



> We've talked about this and we don't really like this. The idea of forcing people out of the town is good, but there's fair worries about pushing towners into other roles(Lumber and iron ore are already often low in stock). That, and bringing ore back from the lavamines is a hassle- I'm not sure it's worth it. That's not to say a less heavy-handed change to ore wouldn't be merged!

this PR is extremely out of date anyway, so Il remake it when I get the chance

**Pull request closed without merging**
