### PR TITLE
Removes artificer keys from woodcutters

### PR DESCRIPTION
**Pull request by Purpleturtle3**
## About The Pull Request

Tittle

## Why It's Good For The Game

The number of people who have keys for the place is too high, the place has a grand furnace, and artificers are supposed to sleep inside and keep their things, but you can't be safe with so many people who can just walk in. Woodcutters feel entitled to getting wood planks; instead of just dumping the logs in the stockpile they put the planks, I've noticed that a lot of times there are no logs in the stockpile while there are dozens of planks inside.

### CODE REVIEW

**Comment by Nakalon** [comment]
I gave the keys to the woodcutters because they're supposed to work WITH the artificers.

The Artificers have a grinding stone not for THEM but for the woodcutters.

Either roleplay with them or get a lock imprinter contraption and change the lock to something else.

**Comment by Nakalon** [comment]
Also, you're not supposed to be the one cutting the wood into planks, they are...

**Comment by Purpleturtle3** [comment]
> I gave the keys to the woodcutters because they're supposed to work WITH the artificers.
> 
> The Artificers have a grinding stone not for THEM but for the woodcutters.
> 
> Either roleplay with them or get a lock imprinter contraption and change the lock to something else.

I am sorry, but in this pr https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1519 you mentioned that "Engineering skill 5 required (it cannot be made within the first 40 minutes of a round at minimum)" when talking about the imprinter.

You can't work with them when they have the keys for what is functionally your home at all times, what are you supposed to do if you get in trouble with one of them? Beat them up to have the key taken away? Why can an actual pilgrim woodcutter spawn with a key to the artificer building?

**Comment by Elli-Skala** [comment]
> I gave the keys to the woodcutters because they're supposed to work WITH the artificers
Artificers should have spare keys to give out not that every wood cutter should spawn with keys. This is like the balance between miner and smith

**Comment by Nakalon** [comment]
> > I gave the keys to the woodcutters because they're supposed to work WITH the artificers.
> > The Artificers have a grinding stone not for THEM but for the woodcutters.
> > Either roleplay with them or get a lock imprinter contraption and change the lock to something else.
> 
> I am sorry, but in this pr #1519 you mentioned that "Engineering skill 5 required (it cannot be made within the first 40 minutes of a round at minimum)" when talking about the imprinter.
> 
> You can't work with them when they have the keys for what is functionally your home at all times, what are you supposed to do if you get in trouble with one of them? Beat them up to have the key taken away? Why can an actual pilgrim woodcutter spawn with a key to the artificer building?

I'm reducing the craft dif on the imprinter.

Pilgrims can because sadly they share a class type with towner.

> > I gave the keys to the woodcutters because they're supposed to work WITH the artificers
> > Artificers should have spare keys to give out not that every wood cutter should spawn with keys. This is like the balance between miner and smith

I get what you're saying but the woodcutters NEED to enter as this is the only place to make planks, the other one being the smithy.

Ive never had an issue with woodcutters and enjoyed them a lot while playing artificer.
I do not understand this need for self isolation, personaly.

**Comment by Purpleturtle3** [comment]
> > > I gave the keys to the woodcutters because they're supposed to work WITH the artificers.
> > > The Artificers have a grinding stone not for THEM but for the woodcutters.
> > > Either roleplay with them or get a lock imprinter contraption and change the lock to something else.
> > 
> > 
> > I am sorry, but in this pr #1519 you mentioned that "Engineering skill 5 required (it cannot be made within the first 40 minutes of a round at minimum)" when talking about the imprinter.
> > You can't work with them when they have the keys for what is functionally your home at all times, what are you supposed to do if you get in trouble with one of them? Beat them up to have the key taken away? Why can an actual pilgrim woodcutter spawn with a key to the artificer building?
> 
> I'm reducing the craft dif on the imprinter.
> 
> Pilgrims can because sadly they share a class type with towner.
> 
> > > I gave the keys to the woodcutters because they're supposed to work WITH the artificers
> > > Artificers should have spare keys to give out not that every wood cutter should spawn with keys. This is like the balance between miner and smith
> 
> I get what you're saying but the woodcutters NEED to enter as this is the only place to make planks, the other one being the smithy.
> 
> Ive never had an issue with woodcutters and enjoyed them a lot while playing artificer. I do not understand this need for self isolation, personaly.

But it's not self isolation, I just want people not to have unrestricted access to my most valuable asset and sleeping quarters. Artificers ALREADY spawn with 2 keys, they can just share them to the people they like.

**Comment by Rayforx** [comment]
The smith is also supposed to work with the miner, but the miner should not have a key to his shop.

This is the same for the lumberjack with the artificer, there is no reason they should go into his shop WITHOUT permission. But that does not mean that they are not supposed to work together. We will have a problem of people taking the job of the artificer as a lumberjack. That is the same problem that the Smiths had.

**Comment by Nakalon** [comment]
> The smith is also supposed to work with the miner, but the miner should not have a key to his shop.
> 
> This is the same for the lumberjack with the artificer, there is no reason they should go into his shop WITHOUT permission. But that does not mean that they are not supposed to work together. We will have a problem of people taking the job of the artificer as a lumberjack. That is the same problem that the Smiths had, and from what has been observed in rounds, then it has already happened in most rounds because they have a key.

Well as long as the Artificers don't fully close themselves off.

But I'm prone to have my mind changed and you have all raised relevant points.

I will be making first an area for the woodworkers to work in if the Artificer tells them to bugger of.
As such I will be accepting this, just please be kind to your fellow woodworkers!

**Review by Nakalon — APPROVED** [review]
PLEASE BE NICE!!

**Pull request merged**
