### PR TITLE
Fixes Severe Roundstart Delay

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

> so apparently when the lord spawns in, it fucking loops through the ENTIRE WORLD to FIND the LORD and assign them as the LORD for the ROUND.
> 
> tahts stupid as fuck. it assigns the lord directly now

### CODE REVIEW

**Comment by Cyprex** [comment]
testmerged

**Comment by TuskTusk** [comment]
Anything that helps with delays like this is great. My question would be, why did they code it in like that, was it to prevent some rare fringe-scenario?

**Comment by Cyprex** [comment]
Probably because they thought it'd only loop over humans in world instead of everyone. I don't think there's anything smart or deliberate here.

**Comment by BlueMemesauce** [comment]
> Anything that helps with delays like this is great. My question would be, why did they code it in like that, was it to prevent some rare fringe-scenario?

Originally there was a feature that the Queen would become ruler if there was no King at roundstart. I removed that in https://github.com/Blackstone-SS13/BLACKSTONE/pull/689/
image

**Pull request merged**
