### PR TITLE
Gives polearms 2 to every towner role

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
gives polearms 2 to every towner and some yeomen

## Why It's Good For The Game
man(I think its a man anyways) on discord told me to
image
the non joke reason is so that towners can be drafted into peasant armies

### CODE REVIEW

**Comment by challade** [comment]
Seems like powercreep.

**Comment by wow50000** [comment]
its 20 one line meme changes

**Comment by NikolayByondPlayer** [comment]
what

**Comment by NikolayByondPlayer** [comment]
what

**Comment by DorfGuy1** [comment]
Nah nah. Like it was common for people to be made to go out and practice things like that, or archery, in case of needing to be raised as a levy, at least in england. Also can you fix the "master" classes? They almost unversally worse than their normal  pilgrim counterparts, like terribly so, in terms of skills. Miner is the egregious example. No masonry, no and horror of horrors No Athletics.

**Comment by TheFenix323** [comment]
>Also can you fix the "master" classes? They almost unversally worse than their normal pilgrim counterparts, like terribly so, in terms of skills. Miner is the egregious example. No masonry, no and horror of horrors No Athletics.
Seems like #860 is already fixing this

**Pull request closed without merging**
