### PR TITLE
Changes Bogmaster PQ requirement from 8 to 4

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Title

## Why It's Good For The Game

Most rounds bog master is nowhere to be seen, not sure if this is because of the high PQ requirement or what, but it's annoying

### CODE REVIEW

**Comment by Hmeister-real** [comment]
Bogmasters are just Retarded, lower PQ req will make this worse. Just force them to stay in the god damn bog

**Comment by Mogurk** [comment]
never cook again

**Comment by DeerJesus** [comment]
The rounds ALWAYS have a bog master trust me. On one character, I set it to medium right after my high and I never get my high and never get bogman. They’re just fickle beings who don’t really take their job seriously like the cap or sheriff

**Comment by Useroth** [comment]
>8 PQ
>high

**Pull request closed without merging**
