### PR TITLE
Re adds the court physicians coat hiding tails

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
Makes the court physicians coat hide tails.

## Why It's Good For The Game
The robes are meant to cover the full body and historically kept out fleas, there is no reason the tail should poke through it or it defeats the entire point of the coat.

### CODE REVIEW

**Comment by Red-Honk** [comment]
Should just be a toggle via right-clicking the coat in all honesty.

**Comment by Coolgat3** [comment]
bruh it initially didn't hide it and I PRed it in on purpose so it hides it now someone fucking changed it again what? Sorry pink fluffy tail doesn't look good at all on a plague doctor

**Comment by Coolgat3** [comment]
> Should just be a toggle via right-clicking the coat in all honesty.

wyci

**Comment by wow50000** [comment]
> bruh it initially didn't hide it and I PRed it in on purpose so it hides it now someone fucking changed it again what? Sorry pink fluffy tail doesn't look good at all on a plague doctor

https://github.com/Rotwood-Vale/Ratwood-Keep/pull/857

**Pull request merged**
