### PR TITLE
Soilson Semi-Revert

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

- Reverts the mapping changes done in #807, makes some mild defensive improvements and layout changes to the Soilsons.
- Moves their storage space to a basement.
- Gives Butcher a whip.
- Adds a single haunt spawner in the Bog Village.

image

image

## Why It's Good For The Game

- Soilson PR was beautifully mapped, but a massive overcorrection. Moved one of the most boring isolated RP roles even further away from interaction. Gave an overly strong giga-fort to some farming peasants.
- This PR gives Soilson some round start walls to try and make the role less frustrating.
- Kept some sensible stuff like fishing stuff for the Elder in their house and key locked Soilson doors.

This isn't particularly high effort.

### CODE REVIEW

**Comment by Cyprex** [comment]
Isn't the fort necessary for them, unfortunately? They lack the combat skills to actually capitalize on it, really.

**Comment by Jaaackx** [comment]
> Isn't the fort necessary for them, unfortunately? They lack the combat skills to actually capitalize on it, really.

Not really, they got by perfectly fine before. People used to make walls/palisades just so people would stop wandering in and stealing stuff / fail harvesting crops.

Some walls like this will keep most people out, that's all they need. Businesses should generally *be* vulnerable in some ways to being attacked / robbed so there's reason to hire mercs.

**Comment by Keazra** [comment]
> Isn't the fort necessary for them, unfortunately? They lack the combat skills to actually capitalize on it, really.

The main thing that they needed was some better lockable storage, and perhaps the village elder to live closer. An entire fort with walled gates is dramatic overkill for what basically amounts to a patch of soil.

**Comment by Jaaackx** [comment]
changing approach to this

**Comment by BladeburstNINJA** [comment]
Hard to tell from the images here, but the village elder house needs to be much closer. Having the VE be contained with the farming unit is conducive to affirming their role.

**Comment by KKLZ4** [comment]
Here's some issues I see with the map.

PLEASE POST PICTURES OF THE HIGHER Z-LEVELS.

Separate the Saiga pen away from the rest of the animals. Have a solid wall, or an air tile between their pen and everything else. Saigas routinely murder the butcher's entire goat herd, considering they're so janky and so utterly easy to anger (Apparently waving at them can sometimes anger them and cause them to murderize the butcher's goats). In the soilfort, they have their own, completely-separate 'stable'.

The Butcher's house generally needs to be cleaned up. It's got two bedrooms for a one-slot role. It doesn't need a map-spawn hunting knife since Butchers get a hunting knife on them roundstart. In general, it's just a really bizzare design.

Soilsons don't need axes roundstart. Replace them with pitchforks, please. Soilsons barely need to do any woodcutting, and shovels are fine enough for it.

The drying racks need a table beside them. Honestly, the composter also needs a table beside it, but I might just reduce the interaction delay for composters, tbh.

I can't see what the second z-level is, but if you're only making the walls one z-level tall, you have to give the soilsons a way of getting onto the walls for the purpose of reinforcing the higher levels, since soilsons do not spawn with any climbing.

The Village Elder seriously needs to be incorporated into this somehow, please. The role has massively benefitted from having a proper 'soilfort' village area with my map PR, and moving it back into the middle of nowhere turns it back into a vague role without any concrete, easily-identifiable 'things to do' beyond just 'larp as minor nobility'.

Give the farm its own SCOM. It's one of the only major, static work-locations without its own SCOM.

I'd honestly need to take a deeper look into the map changes. I'm a bit too lazy to pull this into strongdmm rn.

My own thoughts, though;

The biggest threat to the farm were adventurers & bogguards. Part of the reason why the farm was placed so far away from the bog-gate and well-defended in my mapping PR was specifically because those two roles were the most likely to murder the entire farm over something as minor as 'Hey, pay for the food you're stealing'.

In general, I don't like this remap, but I'm also heavily biased since it's undoing my own work. Take my Cope & Seething with a grain of salt.

**Comment by Keazra** [comment]
> Separate the Saiga pen away from the rest of the animals. Have a solid wall, or an air tile between their pen and everything else. Saigas routinely murder the butcher's entire goat herd, considering they're so janky and so utterly easy to anger (Apparently waving at them can sometimes anger them and cause them to murderize the butcher's goats). In the soilfort, they have their own, completely-separate 'stable'.
> 
> The Butcher's house generally needs to be cleaned up. It's got two bedrooms for a one-slot role. It doesn't need a map-spawn hunting knife since Butchers get a hunting knife on them roundstart. In general, it's just a really bizzare design.
> 
> Soilsons don't need axes roundstart. Replace them with pitchforks, please. Soilsons barely need to do any woodcutting, and shovels are fine enough for it.
> 
> The drying racks need a table beside them. Honestly, the composter also needs a table beside it, but I might just reduce the interaction delay for composters, tbh.

Reasonable requests imo.

> I can't see what the second z-level is, but if you're only making the walls one z-level tall, you have to give the soilsons a way of getting onto the walls for the purpose of reinforcing the higher levels, since soilsons do not spawn with any climbing.

I hate the soiler MO of going Fortnite defenses over simple farmland, personally, so I'm opposed to any method that would allow them to build up keep-level walls.
 
> The Village Elder seriously needs to be incorporated into this somehow, please. The role has massively benefitted from having a proper 'soilfort' village area with my map PR, and moving it back into the middle of nowhere turns it back into a vague role without any concrete, easily-identifiable 'things to do' beyond just 'larp as minor nobility'.

I've always been of the mind that the Village Elder ought to be a petty nobility role, so that they act more like a role of enforcement to make sure the soilers are doing what they're supposed to, and reaping the lion's share of the rewards for their own use, and the kingdom. This would create some mild antagonism between the two that is more interesting than the VE role, in my opinion.

But.. that's a big ask.
 
> Give the farm its own SCOM. It's one of the only major, static work-locations without its own SCOM.

I agree with this. They are a part of the king's land and hold an important function that should be able to make and receive requests more easily.
 
> The biggest threat to the farm were adventurers & bogguards. Part of the reason why the farm was placed so far away from the bog-gate and well-defended in my mapping PR was specifically because those two roles were the most likely to murder the entire farm over something as minor as 'Hey, pay for the food you're stealing'.

I actually disagree that the biggest threat to the farm are adventurers and boggies, but that's because the boggies are normally keeping the worst of the bog at bay (from a lore perspective); in my opinion, they have the right to demand tribute in the form of food from the soilsons. Taking umbrage with that is also your right - and why mercs can and should be hired, which I rarely saw the soilers do.

I also think the "murder the entire farm" thing really just doesn't happen as often as you fear it does. I never saw it happen once, and if it does happen the odd time that doesn't mean the entire thing is broken from a few bad actors.
 
> In general, I don't like this remap, but I'm also heavily biased since it's undoing my own work. Take my Cope & Seething with a grain of salt.

I used to play the soilsons a lot, until the changes went into effect. They left me feeling isolated - even with others around, I just didn't feel like I was engaging with the server at large, because general foot traffick was dramatically reduced. I don't play the soilsons explicitly just to farm - I do so with the intent of interacting with the rest of the server, and in the interest of community building. I enjoy feeling a little vulnerable against antagonistic forces, because my goal isn't to "win" the round and make sure everyone is fully fed without interruption. People should feel hunger if the soilsons get messed with.

As it is currently, I rarely see any king bother messing with the soilers, because they have such a well defended position that puts their own keep to shame. I don't see any nobility ever approach and demand tribute (I'm sure it does happen but it used to happen far more often). I rarely see people building around the bog gate (though, I'm not there as often as I used to be.. which is a result of the farm changes and its distant location). Overall, the server - to me, I will stress - feels less connected.

I do think they needed upgrades and tweaks, however. But if I'm being brutally honest, if I had my way they wouldn't even have walls..

**Comment by Frienderanian** [comment]
>I actually disagree that the biggest threat to the farm are adventurers and boggies
You have never played soilson, breh 😂 
>I also think the "murder the entire farm" thing really just doesn't happen as often as you fear it does.
okay, now I KNOW you've never played soilson, breh 😂 
>why mercs can and should be hired, which I rarely saw the soilers do.
Because it's fucking BORING defending a farm? Mercs want to go out and kill people. I genuinely paid mercs 200+ mammons to follow me around and punch anyone in the face I didn't like and have had them walk off after 30 minutes because "bored lmao". 
I love being able to play the videogame and not Tower Defense where I have to stop 99999 adventurers and bog guards from killing me and stealing my shit over nothing while also playing Farmville. I get that the gate might have been overkill, but now I see people consistently playing Soilson when I didn't before. 
I know you worked hard on this, but I would just let the guy who did the original changes to the Soilsons make adjustments to what is already in the game instead of radically changing it again.

**Comment by Keazra** [comment]
> You have never played soilson, breh 😂

I am speaking from the perspective of the lore, and justification - that the terrors of the bog is being held back by the bogguard gate. Doing that grants them some measure of justification to demand stipends. I am not stupid; of course random adventurers and bog guards are "threats" to the farm. But honestly all I've seen them do is just take some apples.

> okay, now I KNOW you've never played soilson, breh 😂

I just never saw it happen at all, sorry. I was not a soilmain, but I played a decent share of soil rounds. I experienced a few incidents, such as Kron and co going on a wife-hunt, tax demands, blatant thievery and the like, but nothing that I'd call straight-up fragging - except once when bandits roamed through, but they spent a lot of time setting things up and we didn't cede to their demands.

> I love being able to play the videogame and not Tower Defense where I have to stop 99999 adventurers and bog guards from killing me and stealing my shit over nothing

This is some mad hyperbole. When people asked me I'd just point at the apples and give a big ol' thumbs up of approval. I'd occasionally give a hoe away if it was just me as the only soilbride. I literally never died from fragging, ever, whenever I played soilbride.

**Comment by Jaaackx** [comment]
> > I actually disagree that the biggest threat to the farm are adventurers and boggies
> 
> You have never played soilson, breh 😂 
> 
> > I also think the "murder the entire farm" thing really just doesn't happen as often as you fear it does.
> 
> okay, now I KNOW you've never played soilson, breh 😂 
> 
> > why mercs can and should be hired, which I rarely saw the soilers do.
> 
> Because it's fucking BORING defending a farm? Mercs want to go out and kill people. I genuinely paid mercs 200+ mammons to follow me around and punch anyone in the face I didn't like and have had them walk off after 30 minutes because "bored lmao". 
> I love being able to play the videogame and not Tower Defense where I have to stop 99999 adventurers and bog guards from killing me and stealing my shit over nothing while also playing Farmville. I get that the gate might have been overkill, but now I see people consistently playing Soilson when I didn't before. 
> I know you worked hard on this, but I would just let the guy who did the original changes to the Soilsons make adjustments to what is already in the game instead of radically changing it again.

I most definitely did not work hard on this. This was a 10 minute change.

The developer of the remap is busy and unable to work on changes.

I am uninterested in changes to their existing fort. It's too far away and it's shoved a boring role into a forgotten corner even moreso than it used to be.

I'll have a read through and make some *minor* tweaks but ultimately, this is a revert with some incredibly basic aesthetic tweaks and nothing more.

**Comment by SixplyDev** [comment]
I think this is a great PR but I also think giving the Bog Master and only the Bog Master a key to he farm would be the only thing I'd add. This is the man in charge of their protection and so it doesn't really make sense for him to be locked out of it when he's literally next door. The rest of the bogmen? No, nope, 100% hell no, they can't be trusted for shit with it.

**Pull request closed without merging**
