### PR TITLE
Small soilery fixes 

### PR DESCRIPTION
**Pull request by NikolayByondPlayer**
## About The Pull Request

1)Changed bookcases from religion to random
image

2) Changed turf to prevent tree spawns
image
image

3) Moved candles from village armory's window
image

4) Made soiler's basement have stone walls
image

5) Added a copy of velder key, butcher key to village elder's house
image

6) Added chairs to village elder, closed of windows
image

7) Added door to butcher, changed butcher's door id 
image

8) Added a few windows to second floor

## Why It's Good For The Game

Small wee QoL things

### CODE REVIEW

**Comment by Nakalon** [comment]
Niko, I have to wait untill my Artificer thing is done with because I've had to solve merge conflicts 3 times on map 😭

**Comment by Nakalon** [comment]
This is not getting conflicts? Blessed by Malum I guess

**Review by Nakalon — APPROVED** [review]
looks fine and cute

**Comment by Nakalon** [comment]
im gonna run the checks just in case

**Comment by Nakalon** [comment]
They refuse to listen to me, I'll kill them

**Comment by Frienderanian** [comment]
Can you make sure that late join Soilers (both women and men) spawn with a farm key?

**Pull request merged**
