### PR TITLE
Remove old cooking code

### LINKED ISSUE #1477: [BUG] Cheesecake platter sprite issue + some other cooking issues.
## Describe the bug

When I put a cooked cheesecake slice on a platter, the sprite disappears! It still exists and is edible, but it just disappears. I'm unsure if this happens for other items or just the cheesecake.

## Round ID:

image

## Steps to Reproduce:

As described already!

### PR DESCRIPTION
**Pull request by TheFenix323**
## About The Pull Request
Removes leftover code from the old cooking system, was making conflict with the new cooking system.
This will also make it so the new sprites will be used.

## Why It's Good For The Game
Will fix #1477 as it was caused by the wrong cheese cake being called.
image

Also cleans up a lot of commented out code.

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
Are you also deleting crackers? I thought they are used in game?

**Comment by TheFenix323** [comment]
> Are you also deleting crackers? I thought they are used in game?

They are replaced by Hardtracks, which are the same thing just under a different name

**Comment by NikolayByondPlayer** [comment]
> > Are you also deleting crackers? I thought they are used in game?
> 
> They are replaced by Hardtracks, which are the same thing just under a different name

Ah, thank you!

**Comment by Simply-Sydney** [comment]
Good work, speed merge?

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
