### PR TITLE
Tavern and baths revamp, minor map fixes

### PR DESCRIPTION
**Pull request by NikolayByondPlayer**
Tavern and baths remake, minor fixes across the map.

## About The Pull Request
With this PR I split Bath House and Tavern (though they are still connected by small bridge across the sewers). 

In addition I move mining area a bit more west to make way for the new Bath House, I also move one of sewer generators further east to make way for expanded tavern. I've cut down tavern's width and placed some houses there for people to dwell in.

With minor changes I delete unused assets near church and delete invisible milestone.

## Why It's Good For The Game
In short I try to give more RP space, cut the unnecessary width and length of the buildings while using z levels to still give enough space for mechanics and RP and I also try to use some visual cues to make buildings seem more memorable.

## Bath House: 
Bath House is a manor-like building with roof, and multiple z levels. It is now west from the Inn and connected with it by small bridge. I tried to Bath House both fun for ERPers and dark and moody in some areas.
Bath House has multiple different styled rooms for different kinks and preferences.
Bath house also now features a place of rest for Bath swains (though it is not as pretty as the rest of the building).

Снимок экрана 2024-09-13 164857
Снимок экрана 2024-09-13 164904
Снимок экрана 2024-09-13 164913
Снимок экрана 2024-09-13 164921

## The Inn: 
The Inn is now less wide but has more z levels. 
The First floor is now mostly made from non-wood tiles in order to make the ground floor still functional in case of major fire (Thanks Neon for suggestion). In case if we need to make the place more burnable it will be always possible to add more wood.
In addition to that the main bar area is now on the first floor, instead of the second one as it was (I made it so Inn wouldn't be too tall and match the height of mage tower).
Снимок экрана 2024-09-13 161937

The second floor is pretty much an area for 3 fancy rooms, restroom and stairs leading to the roof.
Снимок экрана 2024-09-13 162017

The -1 floor is a place with usual rooms, dim atmosphere and a secret for those who always wanted to dwell in the HUNT room. 
The cook's main work area is also positioned there.
Снимок экрана 2024-09-13 161948
In addition Inn also has some opportunities for parkour right now, some of which might get expanded in the future.

## Other big changes 
Had to move the mining area and sewer part to accommodate new stuff.

Снимок экрана 2024-09-13 165617
Снимок экрана 2024-09-13 175304

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
Forgot to mention that I've place a few keys for the HUNT room if you won't but it from the inn keeper

**Comment by DorfGuy1** [comment]
Azure peaks has some really, really sick music for their bathouse. Its atmospheric as shit. Also, what even is the hunt room.

**Comment by NikolayByondPlayer** [comment]
> Azure peaks has some really, really sick music for their bathouse. Its atmospheric as shit. Also, what even is the hunt room.

There was useless key and I made a weird room for that key, a few of these keys are scattered around the map

**Comment by CalamaBanana** [comment]
I like it, the addition of a shady unlit alleyway to linger in is a neat touch. The separate bathhouse will have a lot of good RP potential, not just for smut. Can already see slavers being allowed to use it as their base of operation from time to time.

**Comment by Frienderanian** [comment]
I know you worked hard on this, but as someone who plays Barkeep, the Tavern is just too fucking big. We need to think practically and design the game based around how the game currently functions and not mystical realism about how we WANT it to function or how it would function REALISTICALLY. There's rarely ever a Tavern/Cook player and there aren't any "waitress" roles, so, if I (as the barkeep) can't see the entire Tavern, people could be destroying shit, stealing shit, breaking shit and I would have no idea. The current tavern is already too huge. And why are the rooms in the basement? Being able to look up from the bar and see the second floor and it's rooms is way better than whatever the fuck is happening here. 

If we're going to rework the tavern why not also rework how the Peddler works and how room keys work? Now that Adventurers can't claim Towner Homes it's CRITICAL that the inn be able to supply people with rooms and the current system does not work. Someone can walk in and buy a key for 10 mammon and hold it the entire week, or, if the Barkeep is in, they can quickly try to reprice the keys so that they're 50 because there's no way in hell they're going to be able to track down players and make them pay nightly. 

I like that the Tavern and Bath House were connected, if they're disconnected like this then any amount of looting or crimes could be happening and I can't do anything about it. 

Also, start the tavern with a LOT more supplies. Like food already made or enough ingredients to make food that will last the first fourty minutes of the round until the Soilsons get up and running. Or, rework food so that it isn't expensive and completely inefficient to make anything that isn't apple pie.

**Comment by SixplyDev** [comment]
Does this PR also add a separate role for the Nightmaster or does it allow the Barkeep to roundstart spawn with a Nightmaster key? My only concern is nobody being in charge of the bath swains/wenches and as a result, them not really having an employer to tend to their needs.

**Comment by Coolgat3** [comment]
Doesn't this also make the good ore in rockhill mountains inaccessible or much harder to access? The vast sea of high tier rocks was created so rockhill has an upper hand vs the outside.

Unsure cant check cuz on phone

**Comment by NikolayUshakovLD** [comment]
> Doesn't this also make the good ore in rockhill mountains inaccessible or much harder to access? The vast sea of high tier rocks was created so rockhill has an upper hand vs the outside.
> 
> Unsure cant check cuz on phone

It was moved a bit west and takes a bit longer to reach

**Comment by NikolayUshakovLD** [comment]
> Does this PR also add a separate role for the Nightmaster or does it allow the Barkeep to roundstart spawn with a Nightmaster key? My only concern is nobody being in charge of the bath swains/wenches and as a result, them not really having an employer to tend to their needs.

Nope, didn't add the master role - just map stuff, also didn't want to add nightmares key to innkeeper since they are separate entities which have to work together. But adding someone who can be a head of bath is a good idea I think

**Comment by NikolayUshakovLD** [comment]
> I know you worked hard on this, but as someone who plays Barkeep, the Tavern is just too fucking big. We need to think practically and design the game based around how the game currently functions and not mystical realism about how we WANT it to function or how it would function REALISTICALLY. There's rarely ever a Tavern/Cook player and there aren't any "waitress" roles, so, if I (as the barkeep) can't see the entire Tavern, people could be destroying shit, stealing shit, breaking shit and I would have no idea. The current tavern is already too huge. And why are the rooms in the basement? Being able to look up from the bar and see the second floor and it's rooms is way better than whatever the fuck is happening here.
> 
> If we're going to rework the tavern why not also rework how the Peddler works and how room keys work? Now that Adventurers can't claim Towner Homes it's CRITICAL that the inn be able to supply people with rooms and the current system does not work. Someone can walk in and buy a key for 10 mammon and hold it the entire week, or, if the Barkeep is in, they can quickly try to reprice the keys so that they're 50 because there's no way in hell they're going to be able to track down players and make them pay nightly.
> 
> I like that the Tavern and Bath House were connected, if they're disconnected like this then any amount of looting or crimes could be happening and I can't do anything about it.
> 
> Also, start the tavern with a LOT more supplies. Like food already made or enough ingredients to make food that will last the first fourty minutes of the round until the Soilsons get up and running. Or, rework food so that it isn't expensive and completely inefficient to make anything that isn't apple pie.

Thanks for addressing your concerns and I agree on some points.

Firstly perhaps some tavern size and room amounts can be reduced, though it would be hard to make a space from which you can look up. But overall looking for size reduction is a good thing, though the inn was partly made with idea that someplace might be broke into by rogues.

Peddler also is a bit of crutch right now in case that innkeeper is not here, I also tend to unlock it and change price roundstart or take the keys away. Not sure what to do here - maybe increase price?

Also supplies were moved from the baths cellar and some were cut though I was indeed thinking there are a lot of some of them indeed. Perhaps I will cut down some of them, though again before that half of these supplies were just a but further in the baths cellar.

**Comment by NikolayByondPlayer** [comment]
> I know you worked hard on this, but as someone who plays Barkeep, the Tavern is just too fucking big. We need to think practically and design the game based around how the game currently functions and not mystical realism about how we WANT it to function or how it would function REALISTICALLY. There's rarely ever a Tavern/Cook player and there aren't any "waitress" roles, so, if I (as the barkeep) can't see the entire Tavern, people could be destroying shit, stealing shit, breaking shit and I would have no idea. The current tavern is already too huge. And why are the rooms in the basement? Being able to look up from the bar and see the second floor and it's rooms is way better than whatever the fuck is happening here.
> 
> If we're going to rework the tavern why not also rework how the Peddler works and how room keys work? Now that Adventurers can't claim Towner Homes it's CRITICAL that the inn be able to supply people with rooms and the current system does not work. Someone can walk in and buy a key for 10 mammon and hold it the entire week, or, if the Barkeep is in, they can quickly try to reprice the keys so that they're 50 because there's no way in hell they're going to be able to track down players and make them pay nightly.
> 
> I like that the Tavern and Bath House were connected, if they're disconnected like this then any amount of looting or crimes could be happening and I can't do anything about it.
> 
> Also, start the tavern with a LOT more supplies. Like food already made or enough ingredients to make food that will last the first fourty minutes of the round until the Soilsons get up and running. Or, rework food so that it isn't expensive and completely inefficient to make anything that isn't apple pie.

Thanks for addressing your concerns and I agree on some points.

Firstly perhaps some tavern size and room amounts can be reduced, though it would be hard to make a space from which you can look up. But overall looking for size reduction is a good thing, though the inn was partly made with idea that someplace might be broke into by rogues.

Peddler also is a bit of crutch right now in case that innkeeper is not here, I also tend to unlock it and change price roundstart or take the keys away. Not sure what to do here - maybe increase price?

I feel like there is good enough supplies as it is - barkeeper needs to use autmats for food buying and talk to soilers - otherwise he is stacked too much and too well. Also supplies were moved from the baths cellar and some were cut.

**Comment by NikolayByondPlayer** [comment]
> Does this PR also add a separate role for the Nightmaster or does it allow the Barkeep to roundstart spawn with a Nightmaster key? My only concern is nobody being in charge of the bath swains/wenches and as a result, them not really having an employer to tend to their needs.

It was moved a bit west and takes a bit longer to reach

**Comment by NikolayByondPlayer** [comment]
> Doesn't this also make the good ore in rockhill mountains inaccessible or much harder to access? The vast sea of high tier rocks was created so rockhill has an upper hand vs the outside.
> 
> Unsure cant check cuz on phone

Nope, didn't add the master role - just map stuff, also didn't want to add nightmares key to innkeeper since they are separate entities which have to work together. But adding someone who can be a head of bath is a good idea I think

**Comment by Quink-Fix** [comment]
Glad to see the slave-breaking chamber in. I'd suggest however doing away with the candles/iron bars in the cell and just making that wooden door into a dungeon door. That way it's always dark in there (sensory isolation) and people can look in from the outside. Also, get some chains in the cell too. Sometimes even the freedom of being able to lay down is too much.

**Comment by Red-Honk** [comment]
Actually, there is a role that is disabled by default called the Nightmaster probably changes name to Nightmistress if it's the other gender, regardless, if one would make a room for them, they possible could be enabled to join in the fun of the round, they're basically the head of the wenchs/swaines and what used to be called the pimp, think of it as a head butler/maid.

**Comment by NikolayByondPlayer** [comment]
> Actually, there is a role that is disabled by default called the Nightmaster probably changes name to Nightmistress if it's the other gender, regardless, if one would make a room for them, they possible could be enabled to join in the fun of the round, they're basically the head of the wenchs/swaines and what used to be called the pimp, think of it as a head butler/maid.

Good call - I will make a room when/if she will be added though and will keep that stuff in mind

**Comment by NikolayByondPlayer** [comment]
> Glad to see the slave-breaking chamber in. I'd suggest however doing away with the candles/iron bars in the cell and just making that wooden door into a dungeon door. That way it's always dark in there (sensory isolation) and people can look in from the outside. Also, get some chains in the cell too. Sometimes even the freedom of being able to lay down is too much.

Thanks for suggestions! Also the door is already dungeon door there. I will add a bit of chains there, not sure about the lighs, maybe will cut them down a bit.

**Comment by Quink-Fix** [comment]
I'm referring specifically to the door facing the cell.

**Comment by Keazra** [comment]
This looks dope, but this resembles more of a high-class brothel you'd find in a large city, instead of the stinkin' barony of Rockhill.

**Comment by Quink-Fix** [comment]
> I'm referring specifically to the door facing the cell.

As in, there should be two dungeon doors total, not just one. If that makes sense?

**Comment by NikolayByondPlayer** [comment]
> > I'm referring specifically to the door facing the cell.
> 
> As in, there should be two dungeon doors total, not just one. If that makes sense?

Wait, don't really follow...

**Comment by NikolayByondPlayer** [comment]
> This looks dope, but this resembles more of a high-class brothel you'd find in a large city, instead of the stinkin' barony of Rockhill.

Agreed, but Rockhill was and is a good trading spot still. 
I think I might do an overall "gloomy" pass on the town some time later to make some places more decayed since lore wise I think the place used to be better some time ago.

**Review by Jaaackx — CHANGES_REQUESTED** [review]
Hello, Maptainer here.

Lovely mapping work. Couple of changes requested:

- Couple of bloat sections I'd like to see axed/changed. Not a fan of the bushy cabin outside or how large the dungeon section is.
image
image

- Nitpick but this room is weird and could do with a redesign.
image

- I agree with the comments regarding moving the bedrooms back upstairs and giving some visibility on them via the bar by looking up. I think a redesign of the top floor and shrinking the basement would be sensible.

Massive fan of the look of the new tavern overall, really nicely done.

Mild concern that the Brothel might steal people away from the Tavern and make that role even more dull, but we can see when it's in.

**Comment by Jaaackx** [comment]
> > Hello, Maptainer here.
> > 
> > Lovely mapping work. Couple of changes requested:
> > 
> > * Couple of bloat sections I'd like to see axed/changed. Not a fan of the bushy cabin outside or how large the dungeon section is.
> >   image
> >   image
> > * Nitpick but this room is weird and could do with a redesign.
> >   image
> > * I agree with the comments regarding moving the bedrooms back upstairs and giving some visibility on them via the bar by looking up. I think a redesign of the top floor and shrinking the basement would be sensible.
> > 
> > Massive fan of the look of the new tavern overall, really nicely done.
> > 
> > Mild concern that the Brothel might steal people away from the Tavern and make that role even more dull, but we can see when it's in.
> 
> Hello! Working on changes now, do you mind if there will be only one fancy room since there is not much space for 9 rooms? 
> 

Heya.

That works, or I'd honestly recommend using the roof area a bit if you're struggling for space.

Could just leave half roofed and a smaller section at the top, or something. I'm okay with the tavern being biiig.

**Comment by CalamaBanana** [comment]
>     * Couple of bloat sections I'd like to see axed/changed. Not a fan of the bushy cabin outside or how large the dungeon section is.

I did assume that part of the "dungeon" is the private quarters of the bathhouse staff, the bathers need a private area to hide in sometimes, too.

**Comment by NikolayByondPlayer** [comment]
> > Couple of bloat sections I'd like to see axed/changed. Not a fan of the bushy cabin outside or how large the dungeon section is.
> 
> I did assume that part of the "dungeon" is the private quarters of the bathhouse staff, the bathers need a private area to hide in sometimes, too.

Yes, it did

**Comment by NikolayByondPlayer** [comment]
> Hello, Maptainer here.
> 
> Lovely mapping work. Couple of changes requested:
> 
> * Couple of bloat sections I'd like to see axed/changed. Not a fan of the bushy cabin outside or how large the dungeon section is.
>   image
>   image
> * Nitpick but this room is weird and could do with a redesign.
>   image
> * I agree with the comments regarding moving the bedrooms back upstairs and giving some visibility on them via the bar by looking up. I think a redesign of the top floor and shrinking the basement would be sensible.
> 
> Massive fan of the look of the new tavern overall, really nicely done.
> 
> Mild concern that the Brothel might steal people away from the Tavern and make that role even more dull, but we can see when it's in.

Hello! I've pushed an update, check it out, please!
Can you also send your discord account contacts? 

Снимок экрана 2024-09-20 212806
Снимок экрана 2024-09-20 212739
Снимок экрана 2024-09-20 212732
Снимок экрана 2024-09-20 212721
Снимок экрана 2024-09-20 212303
Снимок экрана 2024-09-20 212247

**Comment by NikolayByondPlayer** [comment]
Made some various fixes, now can look

**Comment by Jaaackx** [comment]
Looks good, thank you.

**Comment by NikolayByondPlayer** [comment]
Added some balconies for fancy rooms (ONE CAN ALWAYS HAVE MORE BALCONIES)
Снимок экрана 2024-09-21 075525

**Review by Jaaackx — APPROVED** [review]

**Comment by Cyprex** [comment]
Good to merge once conflicts are resolved, ping me on Discord please!

**Comment by NikolayByondPlayer** [comment]
Updated PR and new version was merged

**Pull request closed without merging**
