### PR TITLE
Small Surgery Buff

### PR DESCRIPTION
**Pull request by notafurryy**
## About The Pull Request

Gives a small buff to surgery success chance so that being a physician isn't a pain in the ass with constant step repeating from shitty rng

## Why It's Good For The Game

Save surgeon players a headache and makes them slightly better and suck slightly less compared to acolytes that get guaranteed success chances and massive healing potential.

### CODE REVIEW

**Comment by DelineFortune** [comment]
You can become legendary surgeon in 10 minutes..........

**Comment by DelineFortune** [comment]
Cannot become a good surgeon without spending some efforts to get education 
Its 9 points = 2-3 nights (half of the round) for you to become a professional surgeon

**Comment by notafurryy** [comment]
> > Self healing abuse? Acolytes can almost insta mend fractures with no effort without having to rely on rng and having to pull out tools and repeating steps over and over, also surgeons are supposed to be PROFESSIONSALS not some random bums off the street with tools, also surgeons get next to no combat skills anymore, level 2 knives
> 
> they dont know scalpel scales with knife + surgical skill giving surgeons near-100% crit chance on aimed, poor soul.
> 
> 

I dont see anything in the code suggesting that

**Comment by ophaq** [comment]
When you compare surgeons to acolytes, the argument that they can abuse self healing isn't really viable. Acolytes can instantly heal themselves over a period of time and even fix broken bones. Surgeons have to go through all the steps to heal themselves by putting their tools in themselves, stripping their clothing, etc. Potentially it could be slightly faster at mending damage since there isn't a cooldown like the acolyte spell but the surgeon has to consider the place where they're doing it and also blood loss. Not to mention they need to tear their tools out after they're done.

**Comment by Gyrandola** [comment]
TG surgery is good and the mori spells are bad

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
