### PR TITLE
Disables sorceress, makes mage accessible to both males and females.

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

Only men can be mages, and only females can be sorceresses. This would be fine if sorceress wasn't grossly weaker than mage for chuddie reasons.

It's one of the only 'two classes for two genders' types of adventurer classes, and unlike amazon and barbarian where amazon gets some things barbarian doesn't, sorceress is just a DIRECT downgrade from mage.

Sorceress is worse than mage in every way. Mage has, in comparison to sorceress:

BETTER magic skill
The ability for regular adults to play mages (only old and middle aged can play sorceress)
Flat better stats
The skills:
polearms
bows
wrestling
unarmed
swimming
Climbing
athletics
swords
knives
crafting

Sorceress has nothing added in comparison to mage - NADA.

It's a byproduct of ChuddieCode.

This PR just lets females play mages and makes sorceress, which is now a redundant class, unavailable.
## Why It's Good For The Game

Removes ChuddieCode and lets females play magic users - we have female court magicians, why not female mages that are actually... useful?

### CODE REVIEW

**Comment by kepesk1** [comment]
Good, ChuddieCode begone

**Comment by Hmeister-real** [comment]
In my Alchemy PR on blackstone, i de-chudded the sorcerres already, basicly making her remain physically weaker, but more proficient than a mage in magic. So this may conflict with that PR if Ratwood Syncs Blackstone, which it is soon

**Comment by DeerJesus** [comment]
> In my Alchemy PR on blackstone, i de-chudded the sorcerres already, basicly making her remain physically weaker, but more proficient than a mage in magic. So this may conflict with that PR if Ratwood Syncs Blackstone, which it is soon

Your PR on blackstone still has the sorceress unable to be played by regular adults and they’re still worse magic users than the Mage, just slightly. I still think it’d be better if they’re gone altogether.

**Comment by Hmeister-real** [comment]
> > In my Alchemy PR on blackstone, i de-chudded the sorcerres already, basicly making her remain physically weaker, but more proficient than a mage in magic. So this may conflict with that PR if Ratwood Syncs Blackstone, which it is soon
> 
> Your PR on blackstone still has the sorceress unable to be played by regular adults and they’re still worse magic users than the Mage, just slightly. I still think it’d be better if they’re gone altogether.

Oh wait are you removing them as a middle-old job? Do not do that. The reasons they are older is because it took them long to study, they are better like that. Also as Adults they get way better stats, but still have the Mage skills which is unbalanced, so if you do that at least nerf the jobs skills

**Comment by DeerJesus** [comment]
> > > In my Alchemy PR on blackstone, i de-chudded the sorcerres already, basicly making her remain physically weaker, but more proficient than a mage in magic. So this may conflict with that PR if Ratwood Syncs Blackstone, which it is soon
> > 
> > 
> > Your PR on blackstone still has the sorceress unable to be played by regular adults and they’re still worse magic users than the Mage, just slightly. I still think it’d be better if they’re gone altogether.
> 
> Oh wait are you removing them as a middle-old job? Do not do that. The reasons they are older is because it took them long to study, they are better like that. Also as Adults they get way better stats, but still have the Mage skills which is unbalanced, so if you do that at least nerf the jobs skills

But in that case, regular adult females can’t play magic casters but regular adult males can. I’m removing them altogether, because two very similar magic casters for one gender seems silly.

**Comment by Hmeister-real** [comment]
> > > > In my Alchemy PR on blackstone, i de-chudded the sorcerres already, basicly making her remain physically weaker, but more proficient than a mage in magic. So this may conflict with that PR if Ratwood Syncs Blackstone, which it is soon
> > > 
> > > 
> > > Your PR on blackstone still has the sorceress unable to be played by regular adults and they’re still worse magic users than the Mage, just slightly. I still think it’d be better if they’re gone altogether.
> > 
> > 
> > Oh wait are you removing them as a middle-old job? Do not do that. The reasons they are older is because it took them long to study, they are better like that. Also as Adults they get way better stats, but still have the Mage skills which is unbalanced, so if you do that at least nerf the jobs skills
> 
> But in that case, regular adult females can’t play magic casters but regular adult males can. I’m disabling them altogether, because two very similar magic casters for one gender seems silly.

ok thats fine then, just make sure to check compatibility when blackstone syncs correctly

**Comment by DeerJesus** [comment]
> > > > > In my Alchemy PR on blackstone, i de-chudded the sorcerres already, basicly making her remain physically weaker, but more proficient than a mage in magic. So this may conflict with that PR if Ratwood Syncs Blackstone, which it is soon
> > > > 
> > > > 
> > > > Your PR on blackstone still has the sorceress unable to be played by regular adults and they’re still worse magic users than the Mage, just slightly. I still think it’d be better if they’re gone altogether.
> > > 
> > > 
> > > Oh wait are you removing them as a middle-old job? Do not do that. The reasons they are older is because it took them long to study, they are better like that. Also as Adults they get way better stats, but still have the Mage skills which is unbalanced, so if you do that at least nerf the jobs skills
> > 
> > 
> > But in that case, regular adult females can’t play magic casters but regular adult males can. I’m disabling them altogether, because two very similar magic casters for one gender seems silly.
> 
> ok thats fine then, just make sure to check compatibility when blackstone syncs correctly

We should be fine  after blackstone syncs correctly - it just removes Sorceress’ file from “include when loading” because the way sorceress works I’d either have to comment it out entirely, delete the file or just do this. I don’t want to delete the file in case someone wants to rework it and add a proper “sorcerer” counterpart class, so, just disabling it from loading works.

**Comment by ChungusGamer666** [comment]
I don't want chuddiecode in my chuddiecodebase!!!! This is bad and the game needs more DEI!!!

**Comment by DeerJesus** [comment]
> I don't want chuddiecode in my chuddiecodebase!!!! This is bad and the game needs more DEI!!!

Thanks for understanding ChungusGamer666 the blackstone maintainer <3 we here at Meet n Fuck Kingdom desire to create an equal environment for all races unlike #BLACKEDstone! #pridemonth

**Comment by DeerJesus** [comment]
I fucked up the entire github somehow so i'm just going to remake this pr

**Pull request closed without merging**
