### PR TITLE
Church Changes + Confessor and High Templar

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

Code:
- (re)Added Confessor using existing code. 1 slot, support to Inquisitor. Inquisitor needs friends. Basic skills and equipment, forced Psydon worship. Shepherd role renamed to Confessor throughout code.
- Altered Inquisitor description to make it clear that they're hired by the Priest(ess) rather than the Keep. No confusion needed. Raised Inquisitor PQ requirement to 8 to align with Priest.
- Addition of High Templar (name open to suggestion) role. 1 slot. Plate armour, grand mace and a fancy helmet, more weapons skill, ability to hire new Templars. Someone to keep them wrangled. Comparable to a Knight but just a bit worse overall stats/skills wise.
- Added said fancy helm to code.
- Removal of 1 Templar slot to account for High Templar. Limited to 2 now.
- Removal of Churchling miracles.
- Gives Priest graveyard keys.

I want to mess about with Acolyte / potentially a lead Medical role, but there's a PR up messing with anastasis and I want to see what happens there first.

Map:
- Slightly shrunk the space of the Chapel, Kitchen and dining area. General aesthetic changes. Removal of the psycrosses at the altar.
- Moved healing off to a small clinic on the side, moved Acolyte quarters upstairs and shrunk (in place of Inquisitor quarters).
- Moved the equipment room around. Added a small, Priest-locked armoury with a very limited supply of haubergeon, gambeson, steel swords and a mace.
- Added a tunnel connecting the Church to the Crypt underneath.
- Moved the Inquisitor down a level. Proper torture basement with cells, Inquisitor's quarters, Confessor dorm. Small tunnel to the river.
- Made the Priest quarters a little bigger. Added an actual bedroom and bath away from the 'office'.

Z2:
image

Z3: 
image

Z4:
image

Z5:
image

## Why It's Good For The Game

- Confessor -Inquisitor needs friends to help. Make it a bit more of a social role. Arguably role bloat and up for debate.
- High Templar - Sorely needed. Priest is too busy to continually wrangle the Templar to do their jobs, and this just adds another leadership position to the Church. Arguably role bloat and up for debate.
- Inquisitor - Falling in as part of the Church hierarchy makes sense. No interesting conflict comes from them being a Keep hire, most act as part of the Church anyway. Just the sneakier, nastier part of the Church without any more easy 'oh I don't hire them, I can't stop them torturing you' excuses.
- Churchling - Pushes Churchling into the support cooking/cleaning role rather than just being Aco-lite.
- Map changes - Sanity, increased vibes and atmosphere. Sex bath for the Priest. Church needed some form of armoury for ages.

### CODE REVIEW

**Comment by Jaaackx** [comment]
https://discord.com/channels/1240735983276654733/1248017174489075806/1272030293821489253

Walkaround of map changes.

**Comment by Alanii** [comment]
So you will remove the psycrosses, but not think of adding the Astrata statue back in the church?

Weird flex, clearly a worshipper of inhumen pantheon.

**Comment by Jaaackx** [comment]
> So you will remove the psycrosses, but not think of adding the Astrata statue back in the church?
> 
> Weird flex, clearly a worshipper of inhumen pantheon.

(Praise Zizo). Honestly, I tried fitting one in the Chapel and it looked silly in most places tbh. Sprite can't be rotated.

I did put one in though! There's one in the little prayer room with the amulets and the blue lighting just off the corridor.

**Comment by Rayforx** [comment]
I am curious if you could also fix the mortician lacking access to their storage room(next to the stairs)/basic access to the church in this PR.
They currently only have access to the crypt, which is miserable for them to be able to do anything involving the church.

**Comment by Jaaackx** [comment]
> I am curious if you could also fix the mortician lacking access to their storage room(next to the stairs)/basic access to the church in this PR.
> They currently only have access to the crypt, which is miserable for them to be able to do anything involving the church.

You mean the actual Church storage room with the needles, cloth, sun hoods/robes and stuff?

I'm iffy on that personally. I like that Mortician's a hooded weirdo role with limited Church access myself. Maybe if others want it.

**Comment by Rayforx** [comment]
> You mean the actual Church storage room with the needles, cloth, sun hoods/robes and stuff?
> 
> I'm iffy on that personally. I like that Mortician's a hooded weirdo role with limited Church access myself. Maybe if others want it.

image

I am mostly talking about this room here, which is next to the crypt.

**Comment by Jaaackx** [comment]
> 
> > You mean the actual Church storage room with the needles, cloth, sun hoods/robes and stuff?
> > 
> > I'm iffy on that personally. I like that Mortician's a hooded weirdo role with limited Church access myself. Maybe if others want it.
> 
> image
> 
> I am mostly talking about this room here, which is next to the crypt.

Oh, that's weird. I assumed they had access. I'll fix that.

**Comment by Jaaackx** [comment]
commit fixes the above + some other oversights with door locks. polished now.

**Comment by Matrimy** [comment]
As a frequent priest player, a few things.

Inquisitor isn't hired by the keep either in the lore of other servers. Given our server doesn't really HAVE lore, it's hard to say for certain. But generally the Inquisitor is treated as an outside agent not beholden to keep or church, but an inquisition from a foreign country. I like that. The inquisitor is a Psydonian and Psydon is not the primary god of the church. It does not make sense that the church of the ten would hire a Psydonian inquisitor. Useroth has suggested removing Psydon from the lore, so that may handle that.

There should be at LEAST one psycross in the main temple area, still. That's all to really say about that.

**Comment by SixplyDev** [comment]
The Inquisitor is hired by Kingsfield, not the Church or Keep. I feel like making it more specific that he's employed by Queen Samantha or the Inquisition (as an independent entity) is essential due to the amount of times priest(esse)s get upset at their inquisitor for doing something they dislike. This would mean the Inquisitor keeps their free agent status to effectively perform their duty but also show that they're not exactly "one of us" to everyone else.

**Comment by Jaaackx** [comment]
> As a frequent priest player, a few things.
> 
> Inquisitor isn't hired by the keep either in the lore of other servers. Given our server doesn't really HAVE lore, it's hard to say for certain. But generally the Inquisitor is treated as an outside agent not beholden to keep or church, but an inquisition from a foreign country. I like that. The inquisitor is a Psydonian and Psydon is not the primary god of the church. It does not make sense that the church of the ten would hire a Psydonian inquisitor. Useroth has suggested removing Psydon from the lore, so that may handle that.
> 
> There should be at LEAST one psycross in the main temple area, still. That's all to really say about that.

Most people I've personally seen IC have the view that the Queen / Keep have hired the Inquisitor. The tutorial text currently says _"As an Inquisitor, the Queen has emboldened your radical sect...-"_. A lot of people take this to mean the Queen in-round rather than 'Queen Samantha'. Personal experiences may very but I've seen this come up a lot, and the Inquisitor has keys to the Manor to back it up.

I'm open to changing it if people want it, but I personally prefer the Inquisitor being a Church hire. I think it _does_ make sense that the Inquisition are quietly hired by the Church, who don't want their own hands/religion stained with torture. Off-loading the nasty work onto a couple of pseudo-heretics and making their work more valid in the eyes of the Crown. There's some actual interesting conflict there if the Inquisitor is too brash/public with their kidnappings and torture.

What I don't think makes a lick of sense is the King / citizens accepting this independent group of people who don't follow Rockhill's primary religion, who's primary role is going around torturing people for being heretics (whilst being 'heretics' in and of themselves). I think they at least need backing from the Church in some sense to really have this work. In the mind of most players, 'Kingsfield' is just where people spawn in from and I don't think I've ever seen a reference to Queen Samantha IC.

Generally, I think this is the best bet for now until we get some actual lore. I'm willing to argue the change but, as said, if consensus is that people want them to remain more independent then we can do that.

**Comment by DeerJesus** [comment]
Churchling gets 1 fucking miracle just let them have it  tbh.

**Comment by Jaaackx** [comment]
taking this down and making a new PR, fucked the map file

**Pull request closed without merging**
