### PR TITLE
Changes Spice High music

### PR DESCRIPTION
**Pull request by Plutolover99**
## About The Pull Request
Changes the spice high song from spice.ogg to Hishmaliin.

## Why It's Good For The Game
Because we love our funny lifeweb references, and for an LSD-esque drug, it makes sense for the high music to be cheery and weird.

The song for reference: https://www.youtube.com/watch?v=7J5JMJ0JHx4

### CODE REVIEW

**Comment by NikolayByondPlayer** [comment]
God, yes

**Comment by Coolgat3** [comment]
we love our funny lifeweb but maniac was disabled

**Comment by aberrantQuesrist** [comment]
I think this would be best fitting for something else. Spice's sound effect has always been perfectly fitting for the ethereal experience of seeing stars and having the world warped and colours shifted. I find it incredibly immersive as-is. Hell, I play without music usually as the keep track gets repetitive, but always turn my music back on for doing spice. It's such an integral part of the experience in my opinion.

**Comment by MefAnneFeminene** [comment]
> I think this would be best fitting for something else. Spice's sound effect has always been perfectly fitting for the ethereal experience of seeing stars and having the world warped and colours shifted. I find it incredibly immersive as-is. Hell, I play without music usually as the keep track gets repetitive, but always turn my music back on for doing spice. It's such an integral part of the experience in my opinion.

I was actually contacted by someone who wanted to use this for their current idea to add shrooms. I'm gonna close this and send them the file, so he can add the new drug and use this song, and spice uses the spice song for it.

**Pull request closed without merging**
