### PR TITLE
[PORT] Magic mastery

### PR DESCRIPTION
**Pull request by Rayforx**
## About The Pull Request
**All the stats are subject to change depending on how they feel in the game.**

**Adventure mages will temporarily have a limit of 6 + 2 from Bladesinger. This is made, so we do not see 20 mages around and should be changed to normal with adventure mages specifically, after the TM. - Maintainers**

Ports: https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/196
Magic-wielding roles now get Spellpoints when they join based on their Arcane skill (1 level, 1 point) and any job or age related spellpoint bonuses which they can use to customize their spell loadout, also adds various new spells and a loot item that can be placed in dungeons to grant spellpoints.

A few different spells now give XP based on their fatigue cost, so one could level up their Arcane skill mid-game but it is quite slow, spamming trying to spam spells non-stop while using mana potions and sleeping usually took around 20 minutes in local tests for a Mage Adventurer.

> All the ranged spells will move slower, depending on how large they are, with the greater fireball being the slowest

FORCEWALL:
Puts up a 3x1 magical wall that the caster can pass through, centered on their position when cast. Not very durable, (a MAA with a cudgel broke a wall in three hits) and lasts 20 seconds.

> The sprites for the walls are temporary, they are ugly, and we know it. 

ENSNARE:
A 3x3 square of warning tendrils spawns on the targeted location, and after a brief delay it immobilizes anyone caught inside for a short time.

Spitfire:
Shoot out a low-powered ball of fire (20 burn damage) that shines brightly on impact, blinding a target.

MESSAGE:
Send out a message to anyone whom you know the name of, the target cannot answer back without casting their own Message spell.

REPULSE:
Throws everything including people in a 3x3 area around the caster, turning them prone and making them drop held items, watch for your allies.

BLADE BURST:
A 1x1 square spawns on the targeted tile, and after a short delay it deals 45 damage to whomever is still standing on that tile.

NONDETECTION:
Blow a handful of ash onto a target to render them immune to scrying abilities for an hour.

HASTE:
Enhance a target with +3 Speed for 1 minute.

FEATHERFALL:
Imbue yourself and all adjacent creatures with 1 minute of fall damage resistance. You can only fall safely from one Z-level

DARKVISION:
Touch a target to grant them enhanced vision in darkness for 10 minutes, 2 minute cooldown.

Prestidigitation:
Light up a light with a spark, make a wisp above your head, or clean that dirty floor with a flick of your hand. The most basic of spells, or party trick. Depending on who you ask.

Arcane Bolt
Shoot your favorite magic missile at people, it does 30 brute damage but gets stopped by armor.  Very good for long-range assaults, or accidentally shooting a towner and getting killed.

A new rare class was added called "Bladesinger" that gets access to basic magic and basic skills as a warrior, will you suck at both or become a hero in one field in time?

- Apprentice: 8
- Mage: 10
- Court magician: 12 + greater fireball and prestidigitation
- Heartfelt mago: 12 + greater fireball and prestidigitation
- Bladesinger: 4

<html><body>
<p dir="auto">SPELL CATALOG:</p>
<markdown-accessiblity-table data-catalyst="">

SPELL | COST
-- | --
Fireball | 4
Bolt of Lightning | 3
Spitfire | 3
Forcewall | 3
Ensnare | 3
Repulse | 3
Haste | 3
Fetch | 2
Message | 2
Blade Burst | 2
Darkvision | 2
Arcane Bolt | 2
Nondetection | 1
prestidigitation | 1
Featherfall | 1

</markdown-accessiblity-table>
</body>
</html>

### CODE REVIEW

**Comment by Rayforx** [comment]
The PR should be ready with the testing I have done, but please, make sure to write me on discord BEFORE you TM' it

**Comment by Inveldy** [comment]
I feel like Fetch, specifically, should be a zero cost spell, if that is workable.

**Comment by Squird5** [comment]
Needs more fire spells, for reasons

**Comment by Rayforx** [comment]
Removes the extra spell points for old court magician and heartfelt mago (2)
Remove a spell point for adventures (1)

**Comment by Rayforx** [comment]
Increased the damage of blade burst to 80
Added XP gain to prestidigitation
Added the spell books as a random spawn in chest (5)

**Comment by Rayforx** [comment]
> probably a massive ask, butIt would be cool to add a prestidigitation spell book for crazy expensive to the merchant to give people a chance to try and level spells as a non-mage. Especially if it takes like 20 mins of constant casting and stuff to actually level.

It would not make much sense to add it to be something you can buy with Zenarii, even if it costs a lot. 
Both from the fact that being a mage means that you have either studied hard or been blessed by Noc, and it will be a struggle to balance if a knight gets it.

**Comment by Genevesh** [comment]
Featherfall should be buffed in duration and turned up to (2) cost, while fetch should become (1) instead.

Featherfall gives INFINITELY MORE value from it to someone who is a capable climber, or just goes to higher Z-levels with available ledges; Duration should be buffed to make it reasonably useful as a support spell for your allies, rather than yourself.

Fetch is just pretty niche - unless you learn to do some fuckery by angling it right and throwing people against walls, or off the ledges; Some other codes made fetch let you automatically catch whatever you're fetching, so until we steal that idea it's pretty useless.

**Comment by RadiantFlash7** [comment]
> Changed the damage of blade burst back to 45, new spell (magic missile) for 2 spell points, spam able, changed the various spells to have speed, so you can dodge them, spitfire cooldown changed, added anti-magic effect for some of the spells

I will be honest. I'm somewhat skeptical of reducing spell speeds, and spammable spells. It will need testing, of course, but my first  impression on hearing it, is that it may prove problematic. Magic spells are balanced by mages being weaklings in combat, and anyone who closes the distance can almost always crit them with a single hit. Combine that with spells taking fatigue, and you have a limited amount of casting you can do. If spells are easily dodgeable, it may make them effectively worthless unless you plan on pointblanking people.

Of course, thats subject to actual testing. Maybe I'm just doomsaying and the balance change is fine. Hard to know without having people dart back and forth.

**Comment by Rayforx** [comment]
What to be tested in the TM
Magic missile as a new spell!
Spitfire cooldown
The speed of Greater fireball, fireball, spitfire, and magic missile
XP for prestidigitation
spell books as a random spawn in the chest - Sell it to the local merchant so that he can sell it to a merchant

**Comment by radarseas** [comment]
first impression on learning skill in further magic, _it takes, waaaaaaaaaaaay too much spamming spells_ to the point it detracts from doing anything but casting as much as possible while laying on the floor to regen the blue bar.

Maybe make it a dimishing returns where _you're rewarded decently fast but not enough to become a legendary in one day_ and punished for overdoing it but also enough so you can still do it in two hours with a decent bit of practice like 14-ish casts per day plus make it require sleep learning.

Fetch costs far too much to even be worth picking, unless you autocatch items and can move containers and that.

You can spam Prestidigitation shove(snap) before the cooldown and lose stamina, whoops.

**Comment by annikaRU** [comment]
This is personal experience, 

Fireballs are way too slow, I was able to watch a fireball come right at me, walk one tile before it hit and shrug it off speed those up

Fetch should be reduced for points, it costs too much

Magic missile should be buffed to be on par with a regular fireball, speed increased as well

Spitfire cooldown is fine, speed should be increased

XP is fine as is, no need to change

Nullring is fine

Spell Books should be more common in the bog dungeon specifically, maybe give them to the court magician inside his tower to 'teach' their apprentices

**Comment by CalamaBanana** [comment]
You should be using the sleep-to-learn-skills system for this, too. No reason to have arcane level ups be instantly and outside that system. People should have to buy their level ups like any other skill.

Besides that, it would be neat to have a different sound for harmful and helpful spells. People always look at you as if you are about to fireball the king if you are just sending a sneaky message off.

**Comment by HissyNays** [comment]
Finally a PR that isn't removing or nerfing to death feature or class. This looks incredibly fun and well done. 

However. Spellblade is absolutely crippled class and I can see that from stats alone.
Effectively you can just go hit training dummy a bunch as adventurer mage and you will become better version of spellblade in under 10 minutes.
The only thing spellblade has going for it is 2 in wrestling, wrestling just happens to be mage's worst enemy and that solves that somewhat.
Spellblade absolutely needs 3 at least in swords and some other weapon skills like polearms, maces.
The endurance minus effectively makes it not a fighting class and needs to be changed to +1 to actually make you be able to hold ground in melee.
Intellect could use another +1 too since it's a class that is seemingly created to rely on learning.

**Comment by Genevesh** [comment]
> Besides that, it would be neat to have a different sound for harmful and helpful spells. People always look at you as if you are about to fireball the king if you are just sending a sneaky message off.

I think that was an intentional thing; It's probably better it stays that way. It's funny to see people switch their focus to you in a big group fight just because you're trying to buff your allies.

**Comment by HissyNays** [comment]
Spitfire spell is so bad it wouldn't be worth getting even for 1 spellpoint.

**Comment by HissyNays** [comment]
> Arcane Bolt only does damage with 0% chance to cripple/break bones, I believe. At least against NPC goblins, all I ended up doing was stacking damage. This was bad, because you need cripples to win fights. (After stacking damage on its limbs with Arcane Bolt for ages, I used my staff against it and instantly broke all bones I touched)

Arcane bolt is decent but it trully needs ability to break bones and pierce skin. Same with bladeburst given how hard it can be to land.

**Comment by HissyNays** [comment]
It feels impossible to up your arcane skill. At least I haven't managed to do it thus far.
Perhaps adjusting exp gain from spells individually per cast is better than for stamina. Some spells do not waste stamina or waste so little of it that it's unnoticeable. 

Ensnare feels overpriced too. It doesn't really do much and mostly only serves as set up for hitting other spells

**Comment by DeerJesus** [comment]
'cancel' does not cancel learning the spell

**Comment by Squird5** [comment]
If you try to purchase Fireball and have Greater Fireball, it will cost your skill points but not give you the spell.

**Pull request merged**
