### PR TITLE
DYEING CLOTHES!

### PR DESCRIPTION
**Pull request by Slorbin**
You can now dye a select few types of clothes, with the possibility of more clothes in the future if people see it fit..!

No longer will we have six different ways to craft a colored robe - no longer will you have to suffer with a horrible mismatch of colors as a mage - no longer will you have to wear BROWN PEASANT PANTS as a noble - now you can be STYLISH with just a bit of effort!

image

Basically ported colormate from desertrose and made it into a 'dyeing station'. No good at spriting so the sprite is just a stone bin.

https://github.com/Rotwood-Vale/Ratwood-Keep/assets/11761309/a34da65a-1b11-40a1-a341-4f766ce2e5ac

Also comes with the squashing of all robe craftable color subtypes into one AND dr2's rgb matrices helpers

### CODE REVIEW

**Comment by DeerJesus** [comment]
hm that should fix a merge conflict

**Comment by coffeecoffeecoffee** [comment]
What does this mean for the cloaks?

**Comment by DeerJesus** [comment]
> What does this mean for the cloaks?

Not all items can be dyed. Depends on the cloak. Some cloaks naturally support colorization in the code - I've just added them now. Tabbards and such, no. Half-cloaks and raincloaks, yes!

**Comment by DeerJesus** [comment]
I've finished making a complete list of the items that can be dyed. These are:

shortshirts
undershirts
simple shoes
tights
raincloaks
halfcloaks
a few capes
gambeson
robes
dresses (including chemise)
hoods
headbands
caps
rope belts and cloth belts
chaperons (not very pretty but you can do it)

**Comment by kepesk1** [comment]
Awesome update, really looking forward to it so I can finally have robes that aren't shit brown. Boring as hell when I'm playing mage or monk and I get an unlucky brown ass ugly ass robe. Plus I've multiple times gone to seamstress and pay them and they can't figure out how to color either, sooo..

**Comment by DiscordWizard** [comment]
Great updated, I really didn't like how all clothing you can wear is either random or some flavor of shit brown. It's forcing grimdark on a setting that by all accounts should have dyes, both historically and for a fantasy setting. Hell, prehistoric people had dyes, there's no reason for us to not have this.

**Comment by DeerJesus** [comment]
> Great update, I really didn't like how all clothing you can wear is either random or some flavor of shit brown. It's forcing grimdark on a setting that by all accounts should have dyes, both historically and for a fantasy setting. Hell, prehistoric people had dyes, there's no reason for us to not have this.

It's not even forcing grimdark, it's forcing History Channel documentary vibes on this to limit dyeing... do people forget that the biggest and FIRST grimdark setting is made by a paint company and the main characters of it are literally named after a blue paint???

**Comment by DeerJesus** [comment]
right, i ripped out the matrix paint option (because thats dumb) and slid in the option for the hosts to make a maximum saturation limit... reason i didn't set one is because 
image 
our eyes work in mysterious ways - this is max saturation, but this is a very acceptable color. the same is true of most reds. but greens? try even 50 percent saturation with a green and it'll look neon. it's not worth it.
 
 
limiting the players to just a 'set list of colors' is uberlame too and undermines the entire pr

**Comment by DeerJesus** [comment]
Gonna try and limit it to a LARGE selection of curated colors.

**Comment by DeerJesus** [comment]
been completely redone, with a new video added.

**Comment by Jakksergal** [comment]
Nice!! Glad someone got to this before me. I was going to expanding on this concept to add a whole dyer role that was responsible for growing flowers for dyes and doing the blending with dyes of different intensity. Maybe just make it part of an apothecary role to craft the dyes..

**Comment by DeerJesus** [comment]
> I would not want this to be merged without the limit for a set of reasonable colors

But it has that. Look at the video.

**Comment by pilotmans** [comment]
Brigidine cannot be dyed

**Pull request merged**
