### PR TITLE
Better crafting naming 2

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request
"I sew a cloth (2 fibers; NONE)!" -> "I sew a cloth!" (now list() friendly)

### CODE REVIEW

**Comment by Nakalon** [comment]
Remember how I asked how it behaved with multiple result recipes?

Wouldn't have to bother doing this now.

**Comment by Nakalon** [comment]
Test evidence, pretty please.

**Comment by Heheniy** [comment]
it works

**Comment by Nakalon** [comment]
> it works

That doesn't qualify as test evidence. Post a screenshot ._.

**Comment by Heheniy** [comment]
image

**Pull request merged**
