### PR TITLE
Ports Sleeping bags and Sleeping cloths

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

 Stonekeeps PR. original authors words "Sleepcloths! You can now sew bedsheets and sleepcloths. A sleepcloth is basically a sleeping bag which you can roll up to carry around with you. For the added convenience it's also very uncomfortable to sleep on, causing you to get a mood debuff. An even bigger one if you're of noble blood."
https://github.com/Darkrp-community/OpenKeep/pull/96

## Why It's Good For The Game

 "Convenience! And a better camping experience."

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Sleeping without a bed already takes a ton more time draining your mood irl I don't think it needs to be hammered even more
I feel like it should be a mood buff for using a bed instead

**Comment by lalaria1** [comment]
Please remove the mood debuff for rangers/hunters/sentinels and people who are meant to be campers and love sleeping bags.

**Comment by Hmeister-real** [comment]
> Please remove the mood debuff, at the very least, remove it for rangers/hunters/sentinels and people who are meant to be campers and love sleeping bags.

it's only a debuff if you sleep on the actual ground, doubley so as a noble. On a sleeping bag theres no debuff

**Comment by Quink-Fix** [comment]
That doesn't appear to be what the PR text implies?

**Pull request merged**
