### PR TITLE
Weight Class added to various armors, and Pouch Max carry weight class reduced to Small.

### PR DESCRIPTION
**Pull request by UnexceptionalFox**
## About The Pull Request

Added WEIGHT_CLASS_BULKY and WEIGHT_CLASS_NORMAL to many armor items, and shield. Changed the Pouch to only hold WEIGHT_CLASS_SMALL items. Some items may still left without a defined weight class, but I've attempted to put the major offenders here. 

## Why It's Good For The Game

Stops people from loading up a billion pouches with a bunch of armor then stuffing them into satchels. The affected armor WEIGHT_CLASS_NORMAL armor, and other WEIGHT_CLASS_NORMAL items in the games should no longer be put into pouches.
WEIGHT_CLASS_NORMAL armor such as helmets and chainmail can still be put into satchels and backpacks. WEIGHT_CLASS_BULKY armor can no longer be put into backpacks or satchels. They must be transported by other means.

### CODE REVIEW

**Comment by coffeecoffeecoffee** [comment]
I very much agree with the idea of pouches not being able to hold bulkier armors, particularly plate, but I really, really really REALLY think it's going to be an incredibly painful and bad move to reduce the max carrying size of pouches given how many other things they're used for and how limited our inventory options and their storage space already is. Please, god, I do not want handcarts to become mandatory just to play the game. Why on earth is the chainkini "bulky"? Why wouldn't a pouch be able to hold a set of brayettes, they're literally booty shorts? Chainmail, "bulky"?

**Comment by TheFenix323** [comment]
Charging pouches to only allow to carry small objects may be a bit too much, you won't be able to carry bottles in them anymore.

**Comment by UnexceptionalFox** [comment]
> Charging pouches to only allow to carry small objects may be a bit too much, you won't be able to carry bottles in them anymore.

Made commit that adjusted some items from normal to small, so they can still fit in pouches, such as waterskins, bottles, and bottle bombs

**Comment by UnexceptionalFox** [comment]
> I very much agree with the idea of pouches not being able to hold bulkier armors, particularly plate, but I really, really really REALLY think it's going to be an incredibly painful and bad move to reduce the max carrying size of pouches given how many other things they're used for and how limited our inventory options and their storage space already is. Please, god, I do not want handcarts to become mandatory just to play the game. Why on earth is the chainkini "bulky"? Why wouldn't a pouch be able to hold a set of brayettes, they're literally booty shorts? Chainmail, "bulky"?
> 
> You say "they must be transported by other means", without giving us any other means. Our other options as it stands are "satchel" (literally the same item for 2 different body slots - did you change this as well, or why is it different?) - "backpack" (utterly impractical in most situatioins with a very useful niche) - and literal draggable structures. Or the one-slot cloaks, I guess.

Adjusted Chainkini and Brayette to weightclass small. Kept chainmail shirt and pants on Weight class normal, meaning they can be stored in satchels and backpacks. Handcarts should be used more often, and so should Backpacks. They are not mandatory, just don't carry 9 sets of armor on you like some gaming warlord.

Pouches should not be used like bags of holding for armor. The idea that someone can put 3 pairs of chainmail shirts into a pouch which can then be put in their neck slot is dumb.

**Comment by Cyprex** [comment]
Nah, inventory space is already limited enough I feel.

**Comment by Cyprex** [comment]
Reopened after discussion with @GuppyLaxx

**Comment by Cyprex** [comment]
No I won't in fact

**Pull request merged**
