### PR TITLE
Makes Rockhill Great Again!

### PR DESCRIPTION
**Pull request by Alanii**
## Why It's Good For The Game

Players have begun to make pickaxes and other crude items to bypass the Bog-Gate entirely by simply building around it. This alleviates the issue by forcing players to either confront the Bog-Guard when attempting to bypass the gate, or use a more undetectable method.

Effectively just makes it so when players want to bypass the Gate, they will do so in an obvious manner through mining directly to the left of the Bog Gate, mining to the rooftops of the Bog Gate house, or actually take effort as they need to utilize the bog mines that are under the bog to completely bypass the Gate undetected.

Additionally pulls PR #997

### CODE REVIEW

**Comment by radarseas** [comment]
also if you have decent swimming stat, just swim up the river, there's absolutely nothing they can do about it.

**Comment by SixplyDev** [comment]
This PR should hopefully encourage more people to play Bog Guard and reinforce the security of the gate. As it stands, the gate is far too easy to break into/bypass its current state and this should hopefully fix that.

**Comment by DorfGuy1** [comment]
Whenever i dig under there, I dig like, a huge twenty five block long autism tunnel. Nobody's ever noticed it when I did do it either.

**Comment by DorfGuy1** [comment]
Though, make it more difficult, because when I play boggard recently, I basically never see the bandits until they've already dug into town.

**Comment by Alanii** [comment]
> Whenever i dig under there, I dig like, a huge twenty five block long autism tunnel. Nobody's ever noticed it when I did do it either.

The idea is to incentivise people to cross the underground river and dig through the under-mines that are under the bog. 

Elsewise, they'll be digging the usualy place going to the roof of gatehouse or directly to the left of the gate house.

This PR is mostly to prevent the meme of "bandits sneaking into town by just digging around the gate" and the adventurers who fire ball the bog guard for demanding tolls and breaking in through the windows or digging a hole around like a gremlin.

People who want to bypass the Bog-Gate should do so in a more hidden method or very loud method. Not autism tunnel build on the Z levels directly right of the Bog-Gate.

It may seem "dumb" or "bad idea" but most players are unable to think methodically and just go "unga tunnel" because they pulled the map up on SDMM and know the optimal route of bypassing the gate.

**Pull request merged**
