### PR TITLE
Yet another gooner PR

### PR DESCRIPTION
**Pull request by wow50000**
## About The Pull Request
Ports https://github.com/Tree445/Hearthstone/pull/159/files with balance changes.

List of stolen code:
Breasts now store milk starting empty and a maximum of 30u
Breasts generate milk when not hungry or starving and pregnant.
Sucking breasts and forcing people to suck your breasts is now a sex action possible
Sucking breasts only transfers milk when milk is available and otherwise only causes orgasms.
Milking was moved to using any reagent container on a person with breasts.
Seelies cannot produce milk for obvious reasons

Code has been tested and only errors were from mapping changes.
{152C0282-81FB-4826-B1B0-2B4E82D73690}

## Why It's Good For The Game
Realism and more breast milking nerfs while also making it not goofy(reports of characters going from normal to starving after one milking session)

### CODE REVIEW

**Comment by Gyrandola** [comment]
frankly im about to remove human milking altogether since nobody lactates for no reason

**Comment by ophaq** [comment]
This PR is awesome. I really like the current milking mechanics because it lets me play milkable cow girl... Maybe move being able to be milked as a pregnant-only feature for humens and for wildkin/beast races the current way it is.

**Comment by wow50000** [comment]
> frankly im about to remove arbitrary human milking altogether since nobody lactates for no reason. It should only be possible if the woman is pregnant. Pure fetish content that doesnt belong here.

I

**Comment by wow50000** [comment]
> frankly im about to remove arbitrary human milking altogether since nobody lactates for no reason. It should only be possible if the woman is pregnant. Pure fetish content that doesnt belong here.

I could add a check that checks for pregnancy and spawns everyone at 0

**Comment by wow50000** [comment]
> frankly im about to remove arbitrary human milking altogether since nobody lactates for no reason. It should only be possible if the woman is pregnant. Pure fetish content that doesnt belong here.

Made it so the toggle both has to be active and the character has to be pregnant.

**Comment by Gyrandola** [comment]
> > frankly im about to remove arbitrary human milking altogether since nobody lactates for no reason. It should only be possible if the woman is pregnant. Pure fetish content that doesnt belong here.
> 
> Made it so the toggle both has to be active and the character has to be pregnant.

remove the toggle because its an unnecessary preference, make it so the character has to be pregnant to lactate.

**Comment by wow50000** [comment]
> remove the toggle because its an unnecessary preference, make it so the character has to be pregnant to lactate.
Removed the toggle, tested both sex actions and tested the code using view variables. Milk will not be produced unless pregnant and all pregnant characters with breasts will produce milk.

Milk is not transferred with either suck action unless the person with breasts is producing milk(pregnant)

Added a unique warning for when someone is not pregnant, do not merge until I fix the code issues.

**Comment by wow50000** [comment]
Right, thoroughly tested it and I am satisfied with the rates, this PR also makes pregnant women need food as soon as they get pregnant due to the high nutritional demands of milk.

**Review by Gyrandola — APPROVED** [review]

**Pull request merged**
