### PR TITLE
Bandit buff

### PR DESCRIPTION
**Pull request by Heheniy**
## About The Pull Request

Boosts all combat skills of bandits by 1 point (to level 4 (crossbows to 3))
Also boosts athletics by 1 point (level 3)
Bandit knight gets level 5 or, less often, 6 level sword skill.

## Why It's Good For The Game

Bandits have literally awful combat skills as for one of main antags. Even peasants with pitchforks can fight them off, and they supposed to fight whole ass guard regiment + church.
They are getting beaten VERY often.

### CODE REVIEW

**Comment by X404ErrorX** [comment]
As an constant bandit player i can tell you bandits dont need a buff, their skills are good and they can get the matthios necklase to get an gigabuff on their stats, play bandit It's just a matter of being smart and not fighting fights that can't be won until you have some decent gear from the idol.

**Comment by Erdrom** [comment]
Bandits do need a buff. I think their nerf dates all the way back to emoney dying to them

**Comment by radarseas** [comment]
Personally, as a person that plays bandit, the biggest issue is there's little point dragging your injured off because by the time you do and are suturing, they're dead as dead. Unless like you've got a health potion, even then, if someone broke their neck with a mace they're pretty much a goner unless you can somehow convince someone to help a super obvious heretic..

Giving them an empty bottle would be a nice low-level on the fly anti-bloodloss measure, better than trying to craft up a bucket, run to the river and try not to die while being chased by 8+ people that just killed everyone that rushed bog gate.

Your leg armor is god awful and should be iron chassuses at minimal, you have absolutely no twist/stab resistance with leather trousers, the two most likely injuries from a tackler-build skillset. Especally a floored pilgrim/adventurer with no other options tackled down on the floor is them trying to bite/stab your legs or counterattack with a grab-twist.


I don't think bandits need expert in ALL weaponry skills, either give them an option to specialise and knock all the others down by 1 or keep them the perfect but average jack of all trades.

Honestly, maybe but extremely risky balance wise, give em fast reflexes? since bandits start in light armor it gives them something for fast hit and runs and getaways.

**Comment by wow50000** [comment]
bandits having 3 in everything is good enough, powercreep pr "Even peasants with pitchforks can fight them off" no they cannot, peasant gets polearms 1 and shitass stats and skills bandits arent supposed to be a sieging force or as trained as men at arms

**Comment by SixplyDev** [comment]
This PR reads like someone got robusted by peasants as a bandit and immediately thought that they should buff themselves. Bandits easily wipe out the averagely-staffed Bog Garrison (some 2-3 people now, at most 4) as long as they actually play smart and work together

**Comment by radarseas** [comment]
I've played bandit a lot lately since my last comment, the lack of leg armor is namely what gets you.

You're pretty powerful if you play smart, but massive bandit hordes usually die to leg injuries.

---

Otherwise, they really don't need a buff, _trust me, they don't_, at least from a non-mapper's side, their camp definitely needs improvements but there's a PR for that.

Once you get a dragonscale necklace, you can just meme on knights by dragging them to the floor, all you need is a smith to make statues/get gold from the lava mines and gems. Or just steal like 20 steel bars and run off with them. 1000 mammon comes easy when you melt stuff down.

---

_**HOWEVER**_, I will say this, please, **PLEASE**, give them skincrafting, you can't currently make anything out of leather, despite having it as your armor and probably one extra level in sewing so you can make gambesons without grinding by making 20 peices of cloth.

**Pull request closed without merging**
