### PR TITLE
Sheathes and genital descriptors

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Adds sheaths and genital descriptors, describing intimate parts if they're exposed
All animalistic penises now have sheathes, which they'll be hidden inside if they're not erect
And some tweaks to arousal and scon

Customizers for penises have changes, and **people will need to adjust their savefiles!!!**

### CODE REVIEW

**Comment by Hmeister-real** [comment]
merge NOW

**Comment by coffeecoffeecoffee** [comment]
Finally, people can tease me about the small dicks I set on all of my characters.

**Comment by Kepteyn** [comment]
A good addition, but not a massive fan of the arousal system. It would be nice to have a way to manually toggle it for those who prefer to use emotes as opposed to mechanics.

**Comment by ToothyDeer** [comment]
could kobolds have more variety with genitals? like the rest wild-kin have, w/ knots and sheaths. kobolds w/ sheaths are hip and cool

**Pull request merged**
