### PR TITLE
Pixel Shifting - The HRP Aid.

### PR DESCRIPTION
**Pull request by Kepteyn**
## About The Pull Request

This PR adds pixel shifting, hotkeyed by default to Ctrl+Shift+movement keys, and can be remapped (Note, old players will need to reset your keybinds for the default hotkeys to be selected). The pixel shift is limited to 16 pixels and resets to normal after moving. Pixel shifting while wallpressed is disabled, as is pixel-shifting and then wall-leaning. In order to share a turf with someone, have the person in on the desired turf lie down and stand ontop of them, then you can both pixel shifted into the desired positions.

## Why It's Good For The Game

Pixel shifting has been a wanted feature from the start, and this adds it. Pixel shifting helps with HRP and especially while HRPing the holding of hands.

### CODE REVIEW

**Comment by coffeecoffeecoffee** [comment]
You could make it so being pixel shifted enough allows others to move past you, as this is one of the most immersive everyday things I used to see on traditional Space for making way for people and little gestures like leaning over people (and for pushing people up against walls)

**Comment by Kepteyn** [comment]
> You could make it so being pixel shifted enough allows others to move past you, as this is one of the most immersive everyday things I used to see on traditional Space for making way for people and little gestures like leaning over people (and for pushing people up against walls)

That would be feasible, although Useroth didn't seem too sure about that so I left it out, at least for now. Leaning against walls is still fully possible via the click and drag method, though.

**Comment by Kepteyn** [comment]
> I really dont want people to just wiggle around with pixel shifting

It has been on the to-do list for quite a long time.

**Comment by Kepteyn** [comment]
> > > I really dont want people to just wiggle around with pixel shifting
> > 
> > 
> > It has been on the to-do list for quite a long time.
> 
> Since that was posted the person suggesting it is no longer staff and I became a maintainer
> 
> My opinion still stands and unless Useroth wishes otherwise I will be closing this
> 
> Im sorry you were mislead by the todo channel, we dont have enough time to keep track and update everything
> 
> We already have issues with headshots and id hate to see people wiggle around with this

Given that I worked quite closely with Useroth on this and took his suggestions into account, I would hope he would be interested in this PR.

**Comment by Gr33d-y** [comment]
There seems to be a rather bad bug involving standing on a table and pixel shifting upwards to fly off the screen.

**Comment by Kepteyn** [comment]
> There seems to be a rather bad bug involving standing on a table and pixel shifting upwards to fly off the screen.

Ah, thanks for finding this. Time to figure it out...

**Comment by Kepteyn** [comment]
There, that should fix the bug. It was funny while it lasted.

**Pull request merged**
